<?php

declare(strict_types=1);

namespace App\Support\Postman;

use Illuminate\Filesystem\Filesystem;

final class PostmanCollectionWriter
{
    private const SCHEMA = 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json';

    public function __construct(private readonly Filesystem $files) {}

    /**
     * @param  array<string, array{realm: string, module: string, folder: string, items: list<array<string, mixed>>}>  $groups
     */
    public function writeAll(string $basePath, array $groups): void
    {
        $this->files->ensureDirectoryExists($basePath);

        $adminFolders = [];
        $appFolders = [];
        $infrastructureItems = [];

        ksort($groups);

        foreach ($groups as $group) {
            $realm = $group['realm'];
            $module = $group['module'];
            $items = $group['items'];

            if ($realm === 'infrastructure') {
                $infrastructureItems = $items;

                continue;
            }

            $modulePath = $basePath . '/' . $realm . '/' . $module;
            $this->files->ensureDirectoryExists($modulePath);

            $title =
                'Community Connect API - ' . ucfirst($realm) . ' - ' . str_replace('-', ' ', ucwords($module, '-'));

            $this->writeJson(
                $modulePath . '/' . $module . '.postman_collection.json',
                $this->collection($title, $items, $this->collectionAuth($realm))
            );

            $folder = [
                'name' => str_replace('-', ' ', ucwords($module, '-')),
                'item' => $items,
                'auth' => $this->collectionAuth($realm),
            ];

            if ($realm === 'admin') {
                $adminFolders[] = $folder;
            } else {
                $appFolders[] = $folder;
            }
        }

        usort($adminFolders, static fn(array $a, array $b): int => $a['name'] <=> $b['name']);
        usort($appFolders, static fn(array $a, array $b): int => $a['name'] <=> $b['name']);

        $masterItem = [];

        if ($adminFolders !== []) {
            $masterItem[] = ['name' => 'Admin', 'item' => $adminFolders];
        }

        if ($appFolders !== []) {
            $masterItem[] = ['name' => 'App', 'item' => $appFolders];
        }

        if ($infrastructureItems !== []) {
            $masterItem[] = ['name' => 'Infrastructure', 'item' => $infrastructureItems];
        }

        $master = $this->collection('Community Connect API', $masterItem, null);
        $this->writeJson($basePath . '/Community-Connect-API.postman_collection.json', $master);
        $this->writeEnvironment($basePath . '/Community-Connect-API.postman_environment.json');
    }

    /**
     * @param  list<array<string, mixed>>  $items
     *
     * @return array<string, mixed>
     */
    private function collection(string $name, array $items, ?array $auth): array
    {
        $collection = [
            'info' => [
                '_postman_id' => (string) str()->uuid(),
                'name' => $name,
                'description' => 'Generated by `php artisan postman:generate`. Do not edit by hand; regenerate after route changes.',
                'schema' => self::SCHEMA,
            ],
            'item' => $items,
        ];

        if ($auth !== null) {
            $collection['auth'] = $auth;
        }

        return $collection;
    }

    /**
     * @return array<string, mixed>|null
     */
    private function collectionAuth(string $realm): ?array
    {
        if ($realm === 'infrastructure') {
            return null;
        }

        $token = $realm === 'admin' ? '{{admin_token}}' : '{{app_token}}';

        return [
            'type' => 'bearer',
            'bearer' => [['key' => 'token', 'value' => $token, 'type' => 'string']],
        ];
    }

    private function writeEnvironment(string $path): void
    {
        $environment = [
            'id' => (string) str()->uuid(),
            'name' => 'Community Connect API',
            'values' => [
                ['key' => 'base_url', 'value' => 'http://localhost:8000', 'enabled' => true],
                ['key' => 'admin_token', 'value' => '', 'enabled' => true],
                ['key' => 'app_token', 'value' => '', 'enabled' => true],
                ['key' => 'session_token_hash', 'value' => '', 'enabled' => true],
                ['key' => 'candidate_uuid', 'value' => '', 'enabled' => true],
                ['key' => 'package_uuid', 'value' => '', 'enabled' => true],
                ['key' => 'payment_uuid', 'value' => '', 'enabled' => true],
                ['key' => 'import_batch_id', 'value' => '', 'enabled' => true],
                ['key' => 'document_uuid', 'value' => '', 'enabled' => true],
                ['key' => 'role_uuid', 'value' => '', 'enabled' => true],
                ['key' => 'notification_id', 'value' => '', 'enabled' => true],
                ['key' => 'image_uuid', 'value' => '', 'enabled' => true],
                ['key' => 'contact_request_uuid', 'value' => '', 'enabled' => true],
                ['key' => 'razorpay_webhook_signature', 'value' => '', 'enabled' => true],
            ],
            '_postman_variable_scope' => 'environment',
            '_postman_exported_at' => now()->toIso8601String(),
            '_postman_exported_using' => 'Community Connect API Generator',
        ];

        $this->writeJson($path, $environment);
    }

    /**
     * @param  array<string, mixed>  $data
     */
    private function writeJson(string $path, array $data): void
    {
        $json = json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR);
        $this->files->put($path, $json . "\n");
    }
}
