<?php

declare(strict_types=1);

namespace App\Support\Postman;

use Illuminate\Filesystem\Filesystem;

final class PostmanCollectionWriter
{
    private const SCHEMA = 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json';

    public function __construct(private readonly Filesystem $files) {}

    /**
     * @param  array<string, array{realm: string, module: string, folder: string, items: list<array<string, mixed>>}>  $groups
     */
    public function writeAll(string $basePath, array $groups): void
    {
        $this->files->ensureDirectoryExists($basePath);

        $adminFolders = [];
        $appFolders = [];
        $sharedFolders = [];
        $infrastructureItems = [];

        ksort($groups);

        foreach ($groups as $group) {
            $realm = $group['realm'];
            $module = $group['module'];
            $items = $group['items'];

            if ($realm === 'infrastructure') {
                $infrastructureItems = $items;

                continue;
            }

            $modulePath = $basePath . '/' . $realm . '/' . $module;
            $this->files->ensureDirectoryExists($modulePath);

            $title =
                'Community Connect API - ' . ucfirst($realm) . ' - ' . str_replace('-', ' ', ucwords($module, '-'));

            $this->writeJson(
                $modulePath . '/' . $module . '.postman_collection.json',
                $this->collection($title, $items, $this->collectionAuth($realm))
            );

            $folder = [
                'name' => str_replace('-', ' ', ucwords($module, '-')),
                'item' => $items,
                'auth' => $this->collectionAuth($realm),
            ];

            if ($realm === 'admin') {
                $adminFolders[] = $folder;
            } elseif ($realm === 'shared') {
                $sharedFolders[] = $folder;
            } else {
                $appFolders[] = $folder;
            }
        }

        usort($adminFolders, static fn(array $a, array $b): int => $a['name'] <=> $b['name']);
        usort($appFolders, static fn(array $a, array $b): int => $a['name'] <=> $b['name']);
        usort($sharedFolders, static fn(array $a, array $b): int => $a['name'] <=> $b['name']);

        $masterItem = [];

        if ($sharedFolders !== []) {
            $masterItem[] = ['name' => 'Shared', 'item' => $sharedFolders];
        }

        if ($adminFolders !== []) {
            $masterItem[] = ['name' => 'Admin', 'item' => $adminFolders];
        }

        if ($appFolders !== []) {
            $masterItem[] = ['name' => 'App', 'item' => $appFolders];
        }

        if ($infrastructureItems !== []) {
            $masterItem[] = ['name' => 'Infrastructure', 'item' => $infrastructureItems];
        }

        $master = $this->collection('Community Connect API', $masterItem, null, $this->masterCollectionDescription());
        $this->writeJson($basePath . '/Community-Connect-API.postman_collection.json', $master);
        $this->writeEnvironment($basePath . '/Community-Connect-API.postman_environment.json');
    }

    /**
     * @param  list<array<string, mixed>>  $items
     *
     * @return array<string, mixed>
     */
    private function collection(string $name, array $items, ?array $auth, ?string $description = null): array
    {
        $collection = [
            'info' => [
                '_postman_id' => (string) str()->uuid(),
                'name' => $name,
                'description' => $description ??
                    'Generated by `php artisan postman:generate`. Do not edit by hand; regenerate after route changes.',
                'schema' => self::SCHEMA,
            ],
            'item' => $items,
        ];

        if ($auth !== null) {
            $collection['auth'] = $auth;
        }

        return $collection;
    }

    private function masterCollectionDescription(): string
    {
        return <<<'MD'
# Community Connect API

Postman collection for the **Community Connect** matrimonial platform API (Laravel 11, API v1). Use it to explore and test admin back-office workflows and candidate-facing app flows against a running instance.

Import **`Community-Connect-API.postman_environment.json`** alongside this collection. `BASE_URL` and demo login credentials are filled from your `.env` `APP_URL` and `config/postman.php` when you run `php artisan postman:generate`.

## Realms

| Folder | Base path | Audience |
|--------|-----------|----------|
| **Admin** | `/api/v1/admin/*` | Staff with Spatie permissions (candidates, packages, payments, reports, settings, team users, RBAC) |
| **App** | `/api/v1/app/*` | Candidates and members (registration, profile, discovery, contact requests, KYC, notifications, Razorpay) |
| **Infrastructure** | `/api`, `/api/health*` | Health checks and API metadata (no auth) |

## API standards

- **Versioning:** All product routes live under `/api/v1/`.
- **Response envelope:** `{ success, statusCode, message, data, error, meta }` on every JSON response.
- **Validation:** Request bodies mirror Laravel Form Request rules; 422 responses use structured `error` objects.
- **Auth:** Laravel Sanctum Bearer tokens. Protected routes use **Bearer Token** with `{{AUTH_TOKEN}}`.
- **Sessions:** Many routes use tracked sessions; expired sessions return `403` with `error.code` `SESSION_INVALID`.
- **Admin RBAC:** Admin endpoints declare required permissions in each request description (e.g. `permission:admin.packages.view`).

## Authentication workflow

1. Set `BASE_URL`, `ADMIN_USERNAME` / `ADMIN_PASSWORD`, and `CANDIDATE_USERNAME` / `CANDIDATE_PASSWORD` in the environment (pre-filled on generate).
2. Run **Admin → Auth → POST auth/login** or **App → Auth → POST auth/login** (bodies use those variables).
3. On `200`/`201`, the login/register/refresh **Tests** script saves `data.token` to `AUTH_TOKEN` (and `session_token_hash` / `candidate_uuid` when returned).
4. All other protected requests inherit Bearer auth automatically.

Public routes (login, register, forgot-password, featured profiles, webhooks) use **No Auth** so they do not send a stale token.

## What is included

- One request per registered route, grouped by module (auth, candidates, packages, settings, discovery, webhooks, etc.).
- Example bodies derived from Form Request validation rules.
- Saved example responses for common status codes (200/201, 400, 401, 403, 404, 422, 429, 500).
- Controller, permission, and Form Request notes in request descriptions.

## Key app features (candidate)

- Multi-step profile (basics, photos, partner preferences, KYC documents).
- Profile discovery/search, favorites, matches, contact requests.
- Membership packages, Razorpay registration/checkout, webhooks.
- Notifications and account/me endpoints.

## Key admin features

- Candidate CRUD, import/export, KYC review.
- Packages, subscriptions, payments.
- Reports and dashboard metrics.
- Site, SEO, social login, payment gateway, notifications, storage, search, Redis, and legal page settings.
- Team users and roles/permissions management.

## Regenerate

This file is generated — do not edit by hand:

```bash
php artisan postman:generate
```

See `docs/postman/README.md` in the repository for the full variable list and module layout.
MD;
    }

    /**
     * @return array<string, mixed>|null
     */
    private function collectionAuth(string $realm): ?array
    {
        if ($realm === 'infrastructure') {
            return null;
        }

        return [
            'type' => 'bearer',
            'bearer' => [
                [
                    'key' => 'token',
                    'value' => '{{' . PostmanRequestBuilder::AUTH_TOKEN_VARIABLE . '}}',
                    'type' => 'string',
                ],
            ],
        ];
    }

    private function writeEnvironment(string $path): void
    {
        $environment = [
            'id' => (string) str()->uuid(),
            'name' => 'Community Connect API',
            'values' => [
                ['key' => 'BASE_URL', 'value' => $this->resolveBaseUrl(), 'enabled' => true],
                [
                    'key' => 'ADMIN_USERNAME',
                    'value' => (string) config('postman.admin_username'),
                    'enabled' => true,
                ],
                [
                    'key' => 'ADMIN_PASSWORD',
                    'value' => (string) config('postman.admin_password'),
                    'enabled' => true,
                ],
                [
                    'key' => 'CANDIDATE_USERNAME',
                    'value' => (string) config('postman.candidate_username'),
                    'enabled' => true,
                ],
                [
                    'key' => 'CANDIDATE_PASSWORD',
                    'value' => (string) config('postman.candidate_password'),
                    'enabled' => true,
                ],
                ['key' => PostmanRequestBuilder::AUTH_TOKEN_VARIABLE, 'value' => '', 'enabled' => true],
                ['key' => 'session_token_hash', 'value' => '', 'enabled' => true],
                ['key' => 'candidate_uuid', 'value' => '', 'enabled' => true],
                ['key' => 'package_uuid', 'value' => '', 'enabled' => true],
                ['key' => 'payment_uuid', 'value' => '', 'enabled' => true],
                ['key' => 'import_batch_id', 'value' => '', 'enabled' => true],
                ['key' => 'document_uuid', 'value' => '', 'enabled' => true],
                ['key' => 'role_uuid', 'value' => '', 'enabled' => true],
                ['key' => 'notification_id', 'value' => '', 'enabled' => true],
                ['key' => 'image_uuid', 'value' => '', 'enabled' => true],
                ['key' => 'contact_request_uuid', 'value' => '', 'enabled' => true],
                ['key' => 'razorpay_webhook_signature', 'value' => '', 'enabled' => true],
            ],
            '_postman_variable_scope' => 'environment',
            '_postman_exported_at' => now()->toIso8601String(),
            '_postman_exported_using' => 'Community Connect API Generator',
        ];

        $this->writeJson($path, $environment);
    }

    private function resolveBaseUrl(): string
    {
        $configured = config('postman.base_url');

        if (is_string($configured) && $configured !== '') {
            return rtrim($configured, '/');
        }

        $appUrl = rtrim((string) config('app.url'), '/');
        $parts = parse_url($appUrl);

        if (is_array($parts) && isset($parts['host'])) {
            $scheme = $parts['scheme'] ?? 'http';
            $host = $parts['host'];
            $port = isset($parts['port']) ? ':' . $parts['port'] : '';

            return $scheme . '://' . $host . $port;
        }

        return 'http://localhost:8000';
    }

    /**
     * @param  array<string, mixed>  $data
     */
    private function writeJson(string $path, array $data): void
    {
        $json = json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR);
        $this->files->put($path, $json . "\n");
    }
}
