<?php

namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CafeAccessSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables --limit=500
         */
        $dataTables = [
            [
                'id' => 1,
                'cafe_id' => 8,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 3,
                'cafe_id' => 4,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 5,
                'cafe_id' => 7,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 6,
                'cafe_id' => 9,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 7,
                'cafe_id' => 5,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 8,
                'cafe_id' => 11,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 9,
                'cafe_id' => 3,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 10,
                'cafe_id' => 24,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 11,
                'cafe_id' => 25,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 13,
                'cafe_id' => 22,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 14,
                'cafe_id' => 26,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 15,
                'cafe_id' => 27,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 16,
                'cafe_id' => 30,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 17,
                'cafe_id' => 36,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 19,
                'cafe_id' => 33,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 20,
                'cafe_id' => 35,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 21,
                'cafe_id' => 37,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 22,
                'cafe_id' => 38,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 23,
                'cafe_id' => 29,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 24,
                'cafe_id' => 31,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 25,
                'cafe_id' => 39,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 26,
                'cafe_id' => 13,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 28,
                'cafe_id' => 28,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 29,
                'cafe_id' => 34,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 30,
                'cafe_id' => 14,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 31,
                'cafe_id' => 20,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 32,
                'cafe_id' => 21,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 33,
                'cafe_id' => 17,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 36,
                'cafe_id' => 4,
                'alonti_user_id' => 4,
                'route' => 0,
            ],
            [
                'id' => 39,
                'cafe_id' => 9,
                'alonti_user_id' => 4,
                'route' => 0,
            ],
            [
                'id' => 41,
                'cafe_id' => 11,
                'alonti_user_id' => 4,
                'route' => 0,
            ],
            [
                'id' => 64,
                'cafe_id' => 20,
                'alonti_user_id' => 4,
                'route' => 0,
            ],
            [
                'id' => 65,
                'cafe_id' => 21,
                'alonti_user_id' => 4,
                'route' => 0,
            ],
            [
                'id' => 77,
                'cafe_id' => 24,
                'alonti_user_id' => 34,
                'route' => 0,
            ],
            [
                'id' => 78,
                'cafe_id' => 25,
                'alonti_user_id' => 34,
                'route' => 0,
            ],
            [
                'id' => 101,
                'cafe_id' => 4,
                'alonti_user_id' => 6374,
                'route' => 0,
            ],
            [
                'id' => 107,
                'cafe_id' => 11,
                'alonti_user_id' => 6395,
                'route' => 0,
            ],
            [
                'id' => 110,
                'cafe_id' => 3,
                'alonti_user_id' => 6376,
                'route' => 1,
            ],
            [
                'id' => 113,
                'cafe_id' => 24,
                'alonti_user_id' => 6401,
                'route' => 1,
            ],
            [
                'id' => 115,
                'cafe_id' => 26,
                'alonti_user_id' => 6389,
                'route' => 1,
            ],
            [
                'id' => 116,
                'cafe_id' => 27,
                'alonti_user_id' => 6402,
                'route' => 0,
            ],
            [
                'id' => 122,
                'cafe_id' => 30,
                'alonti_user_id' => 6380,
                'route' => 0,
            ],
            [
                'id' => 126,
                'cafe_id' => 34,
                'alonti_user_id' => 6390,
                'route' => 0,
            ],
            [
                'id' => 127,
                'cafe_id' => 35,
                'alonti_user_id' => 6392,
                'route' => 0,
            ],
            [
                'id' => 130,
                'cafe_id' => 38,
                'alonti_user_id' => 6398,
                'route' => 0,
            ],
            [
                'id' => 133,
                'cafe_id' => 4,
                'alonti_user_id' => 4618,
                'route' => 0,
            ],
            [
                'id' => 141,
                'cafe_id' => 9,
                'alonti_user_id' => 4618,
                'route' => 0,
            ],
            [
                'id' => 145,
                'cafe_id' => 11,
                'alonti_user_id' => 4618,
                'route' => 0,
            ],
            [
                'id' => 195,
                'cafe_id' => 20,
                'alonti_user_id' => 4618,
                'route' => 0,
            ],
            [
                'id' => 197,
                'cafe_id' => 21,
                'alonti_user_id' => 4618,
                'route' => 0,
            ],
            [
                'id' => 217,
                'cafe_id' => 22,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 221,
                'cafe_id' => 24,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 223,
                'cafe_id' => 25,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 229,
                'cafe_id' => 4,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 230,
                'cafe_id' => 5,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 233,
                'cafe_id' => 7,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 234,
                'cafe_id' => 8,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 237,
                'cafe_id' => 9,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 240,
                'cafe_id' => 11,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 242,
                'cafe_id' => 17,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 246,
                'cafe_id' => 20,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 248,
                'cafe_id' => 21,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 250,
                'cafe_id' => 4,
                'alonti_user_id' => 6503,
                'route' => 0,
            ],
            [
                'id' => 251,
                'cafe_id' => 13,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 256,
                'cafe_id' => 30,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 257,
                'cafe_id' => 31,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 259,
                'cafe_id' => 33,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 262,
                'cafe_id' => 36,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 263,
                'cafe_id' => 37,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 264,
                'cafe_id' => 38,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 265,
                'cafe_id' => 39,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 269,
                'cafe_id' => 9,
                'alonti_user_id' => 6503,
                'route' => 0,
            ],
            [
                'id' => 271,
                'cafe_id' => 11,
                'alonti_user_id' => 6503,
                'route' => 0,
            ],
            [
                'id' => 289,
                'cafe_id' => 3,
                'alonti_user_id' => 6369,
                'route' => 1,
            ],
            [
                'id' => 292,
                'cafe_id' => 24,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 293,
                'cafe_id' => 25,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 296,
                'cafe_id' => 26,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 297,
                'cafe_id' => 27,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 308,
                'cafe_id' => 15,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 311,
                'cafe_id' => 4,
                'alonti_user_id' => 6371,
                'route' => 0,
            ],
            [
                'id' => 315,
                'cafe_id' => 9,
                'alonti_user_id' => 6371,
                'route' => 0,
            ],
            [
                'id' => 317,
                'cafe_id' => 11,
                'alonti_user_id' => 6371,
                'route' => 0,
            ],
            [
                'id' => 352,
                'cafe_id' => 4,
                'alonti_user_id' => 6370,
                'route' => 0,
            ],
            [
                'id' => 356,
                'cafe_id' => 9,
                'alonti_user_id' => 6370,
                'route' => 1,
            ],
            [
                'id' => 358,
                'cafe_id' => 11,
                'alonti_user_id' => 6370,
                'route' => 1,
            ],
            [
                'id' => 361,
                'cafe_id' => 20,
                'alonti_user_id' => 6370,
                'route' => 0,
            ],
            [
                'id' => 362,
                'cafe_id' => 21,
                'alonti_user_id' => 6370,
                'route' => 0,
            ],
            [
                'id' => 387,
                'cafe_id' => 20,
                'alonti_user_id' => 9542,
                'route' => 0,
            ],
            [
                'id' => 390,
                'cafe_id' => 4,
                'alonti_user_id' => 9736,
                'route' => 0,
            ],
            [
                'id' => 394,
                'cafe_id' => 9,
                'alonti_user_id' => 9736,
                'route' => 0,
            ],
            [
                'id' => 396,
                'cafe_id' => 11,
                'alonti_user_id' => 9736,
                'route' => 0,
            ],
            [
                'id' => 418,
                'cafe_id' => 5,
                'alonti_user_id' => 6381,
                'route' => 1,
            ],
            [
                'id' => 459,
                'cafe_id' => 11,
                'alonti_user_id' => 11186,
                'route' => 0,
            ],
            [
                'id' => 462,
                'cafe_id' => 9,
                'alonti_user_id' => 11448,
                'route' => 0,
            ],
            [
                'id' => 470,
                'cafe_id' => 31,
                'alonti_user_id' => 6383,
                'route' => 0,
            ],
            [
                'id' => 504,
                'cafe_id' => 20,
                'alonti_user_id' => 6371,
                'route' => 0,
            ],
            [
                'id' => 505,
                'cafe_id' => 21,
                'alonti_user_id' => 6371,
                'route' => 0,
            ],
            [
                'id' => 520,
                'cafe_id' => 31,
                'alonti_user_id' => 12258,
                'route' => 0,
            ],
            [
                'id' => 525,
                'cafe_id' => 35,
                'alonti_user_id' => 12845,
                'route' => 0,
            ],
            [
                'id' => 538,
                'cafe_id' => 11,
                'alonti_user_id' => 13735,
                'route' => 0,
            ],
            [
                'id' => 541,
                'cafe_id' => 4,
                'alonti_user_id' => 13735,
                'route' => 0,
            ],
            [
                'id' => 542,
                'cafe_id' => 20,
                'alonti_user_id' => 6394,
                'route' => 0,
            ],
            [
                'id' => 553,
                'cafe_id' => 21,
                'alonti_user_id' => 11854,
                'route' => 0,
            ],
            [
                'id' => 561,
                'cafe_id' => 4,
                'alonti_user_id' => 11854,
                'route' => 0,
            ],
            [
                'id' => 565,
                'cafe_id' => 9,
                'alonti_user_id' => 11854,
                'route' => 0,
            ],
            [
                'id' => 567,
                'cafe_id' => 11,
                'alonti_user_id' => 11854,
                'route' => 0,
            ],
            [
                'id' => 571,
                'cafe_id' => 11,
                'alonti_user_id' => 14964,
                'route' => 0,
            ],
            [
                'id' => 572,
                'cafe_id' => 9,
                'alonti_user_id' => 14965,
                'route' => 0,
            ],
            [
                'id' => 584,
                'cafe_id' => 9,
                'alonti_user_id' => 16009,
                'route' => 0,
            ],
            [
                'id' => 585,
                'cafe_id' => 9,
                'alonti_user_id' => 16010,
                'route' => 0,
            ],
            [
                'id' => 588,
                'cafe_id' => 11,
                'alonti_user_id' => 16009,
                'route' => 0,
            ],
            [
                'id' => 589,
                'cafe_id' => 11,
                'alonti_user_id' => 16010,
                'route' => 0,
            ],
            [
                'id' => 664,
                'cafe_id' => 26,
                'alonti_user_id' => 18957,
                'route' => 0,
            ],
            [
                'id' => 700,
                'cafe_id' => 39,
                'alonti_user_id' => 6396,
                'route' => 0,
            ],
            [
                'id' => 709,
                'cafe_id' => 41,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 734,
                'cafe_id' => 11,
                'alonti_user_id' => 22738,
                'route' => 0,
            ],
            [
                'id' => 735,
                'cafe_id' => 9,
                'alonti_user_id' => 22738,
                'route' => 0,
            ],
            [
                'id' => 736,
                'cafe_id' => 4,
                'alonti_user_id' => 22738,
                'route' => 0,
            ],
            [
                'id' => 766,
                'cafe_id' => 39,
                'alonti_user_id' => 23263,
                'route' => 0,
            ],
            [
                'id' => 797,
                'cafe_id' => 22,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 799,
                'cafe_id' => 24,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 800,
                'cafe_id' => 27,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 801,
                'cafe_id' => 25,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 802,
                'cafe_id' => 5,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 803,
                'cafe_id' => 7,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 804,
                'cafe_id' => 8,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 805,
                'cafe_id' => 17,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 809,
                'cafe_id' => 31,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 811,
                'cafe_id' => 37,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 813,
                'cafe_id' => 13,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 816,
                'cafe_id' => 30,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 818,
                'cafe_id' => 33,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 819,
                'cafe_id' => 36,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 820,
                'cafe_id' => 38,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 821,
                'cafe_id' => 39,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 852,
                'cafe_id' => 13,
                'alonti_user_id' => 25248,
                'route' => 0,
            ],
            [
                'id' => 854,
                'cafe_id' => 29,
                'alonti_user_id' => 25248,
                'route' => 0,
            ],
            [
                'id' => 855,
                'cafe_id' => 30,
                'alonti_user_id' => 25248,
                'route' => 0,
            ],
            [
                'id' => 860,
                'cafe_id' => 39,
                'alonti_user_id' => 25248,
                'route' => 0,
            ],
            [
                'id' => 861,
                'cafe_id' => 3,
                'alonti_user_id' => 25248,
                'route' => 0,
            ],
            [
                'id' => 862,
                'cafe_id' => 22,
                'alonti_user_id' => 25248,
                'route' => 0,
            ],
            [
                'id' => 863,
                'cafe_id' => 26,
                'alonti_user_id' => 25248,
                'route' => 0,
            ],
            [
                'id' => 864,
                'cafe_id' => 24,
                'alonti_user_id' => 25248,
                'route' => 0,
            ],
            [
                'id' => 866,
                'cafe_id' => 25,
                'alonti_user_id' => 25248,
                'route' => 0,
            ],
            [
                'id' => 876,
                'cafe_id' => 8,
                'alonti_user_id' => 25248,
                'route' => 0,
            ],
            [
                'id' => 880,
                'cafe_id' => 13,
                'alonti_user_id' => 24277,
                'route' => 0,
            ],
            [
                'id' => 884,
                'cafe_id' => 41,
                'alonti_user_id' => 26436,
                'route' => 0,
            ],
            [
                'id' => 887,
                'cafe_id' => 36,
                'alonti_user_id' => 26161,
                'route' => 0,
            ],
            [
                'id' => 902,
                'cafe_id' => 42,
                'alonti_user_id' => 6369,
                'route' => 1,
            ],
            [
                'id' => 903,
                'cafe_id' => 42,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 905,
                'cafe_id' => 42,
                'alonti_user_id' => 25248,
                'route' => 0,
            ],
            [
                'id' => 907,
                'cafe_id' => 42,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 908,
                'cafe_id' => 42,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 913,
                'cafe_id' => 7,
                'alonti_user_id' => 28621,
                'route' => 0,
            ],
            [
                'id' => 922,
                'cafe_id' => 37,
                'alonti_user_id' => 6397,
                'route' => 0,
            ],
            [
                'id' => 928,
                'cafe_id' => 43,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 929,
                'cafe_id' => 43,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 946,
                'cafe_id' => 43,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 951,
                'cafe_id' => 17,
                'alonti_user_id' => 29720,
                'route' => 0,
            ],
            [
                'id' => 983,
                'cafe_id' => 5,
                'alonti_user_id' => 30750,
                'route' => 0,
            ],
            [
                'id' => 985,
                'cafe_id' => 8,
                'alonti_user_id' => 30750,
                'route' => 0,
            ],
            [
                'id' => 987,
                'cafe_id' => 17,
                'alonti_user_id' => 30750,
                'route' => 0,
            ],
            [
                'id' => 989,
                'cafe_id' => 3,
                'alonti_user_id' => 30750,
                'route' => 0,
            ],
            [
                'id' => 992,
                'cafe_id' => 26,
                'alonti_user_id' => 30750,
                'route' => 0,
            ],
            [
                'id' => 993,
                'cafe_id' => 24,
                'alonti_user_id' => 30750,
                'route' => 1,
            ],
            [
                'id' => 995,
                'cafe_id' => 25,
                'alonti_user_id' => 30750,
                'route' => 0,
            ],
            [
                'id' => 996,
                'cafe_id' => 42,
                'alonti_user_id' => 30750,
                'route' => 0,
            ],
            [
                'id' => 998,
                'cafe_id' => 28,
                'alonti_user_id' => 30750,
                'route' => 0,
            ],
            [
                'id' => 1004,
                'cafe_id' => 13,
                'alonti_user_id' => 30750,
                'route' => 0,
            ],
            [
                'id' => 1006,
                'cafe_id' => 29,
                'alonti_user_id' => 30750,
                'route' => 0,
            ],
            [
                'id' => 1013,
                'cafe_id' => 39,
                'alonti_user_id' => 29121,
                'route' => 0,
            ],
            [
                'id' => 1030,
                'cafe_id' => 17,
                'alonti_user_id' => 34005,
                'route' => 0,
            ],
            [
                'id' => 1031,
                'cafe_id' => 3,
                'alonti_user_id' => 34005,
                'route' => 0,
            ],
            [
                'id' => 1032,
                'cafe_id' => 22,
                'alonti_user_id' => 34005,
                'route' => 0,
            ],
            [
                'id' => 1033,
                'cafe_id' => 26,
                'alonti_user_id' => 34005,
                'route' => 0,
            ],
            [
                'id' => 1034,
                'cafe_id' => 24,
                'alonti_user_id' => 34005,
                'route' => 0,
            ],
            [
                'id' => 1036,
                'cafe_id' => 25,
                'alonti_user_id' => 34005,
                'route' => 0,
            ],
            [
                'id' => 1037,
                'cafe_id' => 42,
                'alonti_user_id' => 34005,
                'route' => 0,
            ],
            [
                'id' => 1039,
                'cafe_id' => 28,
                'alonti_user_id' => 34005,
                'route' => 0,
            ],
            [
                'id' => 1044,
                'cafe_id' => 13,
                'alonti_user_id' => 34005,
                'route' => 0,
            ],
            [
                'id' => 1046,
                'cafe_id' => 29,
                'alonti_user_id' => 34005,
                'route' => 0,
            ],
            [
                'id' => 1051,
                'cafe_id' => 39,
                'alonti_user_id' => 34005,
                'route' => 0,
            ],
            [
                'id' => 1055,
                'cafe_id' => 43,
                'alonti_user_id' => 12469,
                'route' => 0,
            ],
            [
                'id' => 1064,
                'cafe_id' => 39,
                'alonti_user_id' => 26897,
                'route' => 0,
            ],
            [
                'id' => 1074,
                'cafe_id' => 39,
                'alonti_user_id' => 23285,
                'route' => 0,
            ],
            [
                'id' => 1084,
                'cafe_id' => 8,
                'alonti_user_id' => 38590,
                'route' => 0,
            ],
            [
                'id' => 1085,
                'cafe_id' => 29,
                'alonti_user_id' => 38785,
                'route' => 0,
            ],
            [
                'id' => 1090,
                'cafe_id' => 28,
                'alonti_user_id' => 39291,
                'route' => 0,
            ],
            [
                'id' => 1091,
                'cafe_id' => 3,
                'alonti_user_id' => 39292,
                'route' => 0,
            ],
            [
                'id' => 1092,
                'cafe_id' => 31,
                'alonti_user_id' => 39293,
                'route' => 0,
            ],
            [
                'id' => 1100,
                'cafe_id' => 44,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 1101,
                'cafe_id' => 44,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 1102,
                'cafe_id' => 44,
                'alonti_user_id' => 30750,
                'route' => 0,
            ],
            [
                'id' => 1120,
                'cafe_id' => 39,
                'alonti_user_id' => 8958,
                'route' => 0,
            ],
            [
                'id' => 1144,
                'cafe_id' => 45,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 1152,
                'cafe_id' => 45,
                'alonti_user_id' => 25248,
                'route' => 0,
            ],
            [
                'id' => 1153,
                'cafe_id' => 45,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 1154,
                'cafe_id' => 43,
                'alonti_user_id' => 41702,
                'route' => 0,
            ],
            [
                'id' => 1156,
                'cafe_id' => 46,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1158,
                'cafe_id' => 47,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1159,
                'cafe_id' => 46,
                'alonti_user_id' => 41888,
                'route' => 0,
            ],
            [
                'id' => 1164,
                'cafe_id' => 46,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 1165,
                'cafe_id' => 46,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 1167,
                'cafe_id' => 47,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 1168,
                'cafe_id' => 47,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 1169,
                'cafe_id' => 46,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 1170,
                'cafe_id' => 47,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 1171,
                'cafe_id' => 46,
                'alonti_user_id' => 30750,
                'route' => 0,
            ],
            [
                'id' => 1172,
                'cafe_id' => 47,
                'alonti_user_id' => 30750,
                'route' => 0,
            ],
            [
                'id' => 1179,
                'cafe_id' => 8,
                'alonti_user_id' => 43140,
                'route' => 0,
            ],
            [
                'id' => 1182,
                'cafe_id' => 44,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 1194,
                'cafe_id' => 8,
                'alonti_user_id' => 44255,
                'route' => 0,
            ],
            [
                'id' => 1198,
                'cafe_id' => 3,
                'alonti_user_id' => 44255,
                'route' => 0,
            ],
            [
                'id' => 1201,
                'cafe_id' => 24,
                'alonti_user_id' => 44255,
                'route' => 0,
            ],
            [
                'id' => 1203,
                'cafe_id' => 25,
                'alonti_user_id' => 44255,
                'route' => 0,
            ],
            [
                'id' => 1212,
                'cafe_id' => 45,
                'alonti_user_id' => 44255,
                'route' => 0,
            ],
            [
                'id' => 1220,
                'cafe_id' => 39,
                'alonti_user_id' => 44255,
                'route' => 0,
            ],
            [
                'id' => 1232,
                'cafe_id' => 51,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 1233,
                'cafe_id' => 51,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 1234,
                'cafe_id' => 51,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 1235,
                'cafe_id' => 51,
                'alonti_user_id' => 22348,
                'route' => 0,
            ],
            [
                'id' => 1236,
                'cafe_id' => 51,
                'alonti_user_id' => 25248,
                'route' => 0,
            ],
            [
                'id' => 1237,
                'cafe_id' => 51,
                'alonti_user_id' => 30750,
                'route' => 0,
            ],
            [
                'id' => 1240,
                'cafe_id' => 46,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1241,
                'cafe_id' => 47,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1242,
                'cafe_id' => 5,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1243,
                'cafe_id' => 7,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1244,
                'cafe_id' => 8,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1245,
                'cafe_id' => 17,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1247,
                'cafe_id' => 44,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1248,
                'cafe_id' => 3,
                'alonti_user_id' => 46072,
                'route' => 1,
            ],
            [
                'id' => 1249,
                'cafe_id' => 22,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1250,
                'cafe_id' => 26,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1251,
                'cafe_id' => 24,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1253,
                'cafe_id' => 42,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1254,
                'cafe_id' => 14,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1255,
                'cafe_id' => 28,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1256,
                'cafe_id' => 31,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1257,
                'cafe_id' => 34,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1258,
                'cafe_id' => 37,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1259,
                'cafe_id' => 41,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1260,
                'cafe_id' => 35,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1261,
                'cafe_id' => 45,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1262,
                'cafe_id' => 51,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1263,
                'cafe_id' => 13,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1264,
                'cafe_id' => 15,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1265,
                'cafe_id' => 29,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1266,
                'cafe_id' => 30,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1268,
                'cafe_id' => 36,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1269,
                'cafe_id' => 38,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1270,
                'cafe_id' => 39,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1271,
                'cafe_id' => 43,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1272,
                'cafe_id' => 25,
                'alonti_user_id' => 6401,
                'route' => 0,
            ],
            [
                'id' => 1273,
                'cafe_id' => 39,
                'alonti_user_id' => 24397,
                'route' => 0,
            ],
            [
                'id' => 1282,
                'cafe_id' => 46,
                'alonti_user_id' => 48765,
                'route' => 0,
            ],
            [
                'id' => 1287,
                'cafe_id' => 8,
                'alonti_user_id' => 48899,
                'route' => 0,
            ],
            [
                'id' => 1290,
                'cafe_id' => 52,
                'alonti_user_id' => 49082,
                'route' => 0,
            ],
            [
                'id' => 1291,
                'cafe_id' => 47,
                'alonti_user_id' => 41887,
                'route' => 0,
            ],
            [
                'id' => 1293,
                'cafe_id' => 47,
                'alonti_user_id' => 49083,
                'route' => 0,
            ],
            [
                'id' => 1294,
                'cafe_id' => 52,
                'alonti_user_id' => 49083,
                'route' => 0,
            ],
            [
                'id' => 1295,
                'cafe_id' => 52,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1297,
                'cafe_id' => 52,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 1298,
                'cafe_id' => 52,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 1301,
                'cafe_id' => 52,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1303,
                'cafe_id' => 52,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 1322,
                'cafe_id' => 53,
                'alonti_user_id' => 49083,
                'route' => 0,
            ],
            [
                'id' => 1323,
                'cafe_id' => 53,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1325,
                'cafe_id' => 53,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 1326,
                'cafe_id' => 53,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 1329,
                'cafe_id' => 53,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1331,
                'cafe_id' => 53,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 1361,
                'cafe_id' => 39,
                'alonti_user_id' => 50378,
                'route' => 0,
            ],
            [
                'id' => 1365,
                'cafe_id' => 52,
                'alonti_user_id' => 44255,
                'route' => 0,
            ],
            [
                'id' => 1369,
                'cafe_id' => 53,
                'alonti_user_id' => 50910,
                'route' => 0,
            ],
            [
                'id' => 1393,
                'cafe_id' => 39,
                'alonti_user_id' => 48899,
                'route' => 0,
            ],
            [
                'id' => 1399,
                'cafe_id' => 8,
                'alonti_user_id' => 51490,
                'route' => 0,
            ],
            [
                'id' => 1409,
                'cafe_id' => 25,
                'alonti_user_id' => 51490,
                'route' => 0,
            ],
            [
                'id' => 1427,
                'cafe_id' => 39,
                'alonti_user_id' => 51490,
                'route' => 0,
            ],
            [
                'id' => 1435,
                'cafe_id' => 28,
                'alonti_user_id' => 54547,
                'route' => 1,
            ],
            [
                'id' => 1449,
                'cafe_id' => 46,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1450,
                'cafe_id' => 47,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1451,
                'cafe_id' => 5,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1452,
                'cafe_id' => 7,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1453,
                'cafe_id' => 8,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1454,
                'cafe_id' => 17,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1456,
                'cafe_id' => 44,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1457,
                'cafe_id' => 3,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1458,
                'cafe_id' => 22,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1459,
                'cafe_id' => 26,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1460,
                'cafe_id' => 24,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1461,
                'cafe_id' => 27,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1462,
                'cafe_id' => 25,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1463,
                'cafe_id' => 42,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1464,
                'cafe_id' => 14,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1465,
                'cafe_id' => 28,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1466,
                'cafe_id' => 31,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1467,
                'cafe_id' => 34,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1468,
                'cafe_id' => 35,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1469,
                'cafe_id' => 37,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1470,
                'cafe_id' => 41,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1471,
                'cafe_id' => 45,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1472,
                'cafe_id' => 51,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1473,
                'cafe_id' => 13,
                'alonti_user_id' => 57087,
                'route' => 0,
            ],
            [
                'id' => 1474,
                'cafe_id' => 15,
                'alonti_user_id' => 57087,
                'route' => 0,
            ],
            [
                'id' => 1475,
                'cafe_id' => 29,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1476,
                'cafe_id' => 30,
                'alonti_user_id' => 57087,
                'route' => 0,
            ],
            [
                'id' => 1478,
                'cafe_id' => 36,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1479,
                'cafe_id' => 38,
                'alonti_user_id' => 57087,
                'route' => 0,
            ],
            [
                'id' => 1480,
                'cafe_id' => 43,
                'alonti_user_id' => 57087,
                'route' => 0,
            ],
            [
                'id' => 1481,
                'cafe_id' => 52,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1483,
                'cafe_id' => 53,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1495,
                'cafe_id' => 54,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 1498,
                'cafe_id' => 54,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1499,
                'cafe_id' => 54,
                'alonti_user_id' => 57087,
                'route' => 0,
            ],
            [
                'id' => 1500,
                'cafe_id' => 54,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 1503,
                'cafe_id' => 54,
                'alonti_user_id' => 11129,
                'route' => 1,
            ],
            [
                'id' => 1530,
                'cafe_id' => 44,
                'alonti_user_id' => 59071,
                'route' => 1,
            ],
            [
                'id' => 1532,
                'cafe_id' => 38,
                'alonti_user_id' => 59294,
                'route' => 1,
            ],
            [
                'id' => 1534,
                'cafe_id' => 55,
                'alonti_user_id' => 2,
                'route' => 1,
            ],
            [
                'id' => 1536,
                'cafe_id' => 55,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 1538,
                'cafe_id' => 55,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1539,
                'cafe_id' => 55,
                'alonti_user_id' => 57087,
                'route' => 0,
            ],
            [
                'id' => 1541,
                'cafe_id' => 55,
                'alonti_user_id' => 8509,
                'route' => 0,
            ],
            [
                'id' => 1550,
                'cafe_id' => 3,
                'alonti_user_id' => 60497,
                'route' => 0,
            ],
            [
                'id' => 1560,
                'cafe_id' => 24,
                'alonti_user_id' => 57639,
                'route' => 1,
            ],
            [
                'id' => 1581,
                'cafe_id' => 56,
                'alonti_user_id' => 2,
                'route' => 1,
            ],
            [
                'id' => 1583,
                'cafe_id' => 56,
                'alonti_user_id' => 28373,
                'route' => 1,
            ],
            [
                'id' => 1584,
                'cafe_id' => 56,
                'alonti_user_id' => 30750,
                'route' => 1,
            ],
            [
                'id' => 1585,
                'cafe_id' => 56,
                'alonti_user_id' => 4819,
                'route' => 1,
            ],
            [
                'id' => 1586,
                'cafe_id' => 56,
                'alonti_user_id' => 11129,
                'route' => 1,
            ],
            [
                'id' => 1587,
                'cafe_id' => 56,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1588,
                'cafe_id' => 56,
                'alonti_user_id' => 6369,
                'route' => 1,
            ],
            [
                'id' => 1589,
                'cafe_id' => 56,
                'alonti_user_id' => 46072,
                'route' => 1,
            ],
            [
                'id' => 1607,
                'cafe_id' => 28,
                'alonti_user_id' => 65369,
                'route' => 1,
            ],
            [
                'id' => 1608,
                'cafe_id' => 31,
                'alonti_user_id' => 65369,
                'route' => 1,
            ],
            [
                'id' => 1611,
                'cafe_id' => 37,
                'alonti_user_id' => 65369,
                'route' => 1,
            ],
            [
                'id' => 1613,
                'cafe_id' => 45,
                'alonti_user_id' => 65369,
                'route' => 1,
            ],
            [
                'id' => 1614,
                'cafe_id' => 51,
                'alonti_user_id' => 65369,
                'route' => 1,
            ],
            [
                'id' => 1626,
                'cafe_id' => 57,
                'alonti_user_id' => 46072,
                'route' => 1,
            ],
            [
                'id' => 1627,
                'cafe_id' => 57,
                'alonti_user_id' => 2,
                'route' => 1,
            ],
            [
                'id' => 1628,
                'cafe_id' => 57,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1630,
                'cafe_id' => 57,
                'alonti_user_id' => 6369,
                'route' => 1,
            ],
            [
                'id' => 1631,
                'cafe_id' => 57,
                'alonti_user_id' => 4819,
                'route' => 1,
            ],
            [
                'id' => 1633,
                'cafe_id' => 58,
                'alonti_user_id' => 46072,
                'route' => 1,
            ],
            [
                'id' => 1634,
                'cafe_id' => 58,
                'alonti_user_id' => 6369,
                'route' => 1,
            ],
            [
                'id' => 1635,
                'cafe_id' => 58,
                'alonti_user_id' => 2,
                'route' => 1,
            ],
            [
                'id' => 1637,
                'cafe_id' => 58,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1639,
                'cafe_id' => 58,
                'alonti_user_id' => 4819,
                'route' => 1,
            ],
            [
                'id' => 1640,
                'cafe_id' => 59,
                'alonti_user_id' => 46072,
                'route' => 1,
            ],
            [
                'id' => 1641,
                'cafe_id' => 59,
                'alonti_user_id' => 6369,
                'route' => 1,
            ],
            [
                'id' => 1644,
                'cafe_id' => 59,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1645,
                'cafe_id' => 59,
                'alonti_user_id' => 2,
                'route' => 1,
            ],
            [
                'id' => 1646,
                'cafe_id' => 59,
                'alonti_user_id' => 4819,
                'route' => 1,
            ],
            [
                'id' => 1657,
                'cafe_id' => 54,
                'alonti_user_id' => 67150,
                'route' => 1,
            ],
            [
                'id' => 1661,
                'cafe_id' => 42,
                'alonti_user_id' => 66814,
                'route' => 1,
            ],
            [
                'id' => 1664,
                'cafe_id' => 46,
                'alonti_user_id' => 70399,
                'route' => 1,
            ],
            [
                'id' => 1665,
                'cafe_id' => 47,
                'alonti_user_id' => 70399,
                'route' => 1,
            ],
            [
                'id' => 1666,
                'cafe_id' => 52,
                'alonti_user_id' => 70399,
                'route' => 1,
            ],
            [
                'id' => 1667,
                'cafe_id' => 53,
                'alonti_user_id' => 70399,
                'route' => 1,
            ],
            [
                'id' => 1668,
                'cafe_id' => 3,
                'alonti_user_id' => 70399,
                'route' => 1,
            ],
            [
                'id' => 1669,
                'cafe_id' => 26,
                'alonti_user_id' => 70399,
                'route' => 1,
            ],
            [
                'id' => 1671,
                'cafe_id' => 24,
                'alonti_user_id' => 70399,
                'route' => 1,
            ],
            [
                'id' => 1673,
                'cafe_id' => 42,
                'alonti_user_id' => 70399,
                'route' => 1,
            ],
            [
                'id' => 1674,
                'cafe_id' => 56,
                'alonti_user_id' => 70399,
                'route' => 1,
            ],
            [
                'id' => 1692,
                'cafe_id' => 60,
                'alonti_user_id' => 46072,
                'route' => 1,
            ],
            [
                'id' => 1695,
                'cafe_id' => 60,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1698,
                'cafe_id' => 60,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 1703,
                'cafe_id' => 26,
                'alonti_user_id' => 71536,
                'route' => 1,
            ],
            [
                'id' => 1704,
                'cafe_id' => 5,
                'alonti_user_id' => 6369,
                'route' => 1,
            ],
            [
                'id' => 1705,
                'cafe_id' => 7,
                'alonti_user_id' => 6369,
                'route' => 1,
            ],
            [
                'id' => 1706,
                'cafe_id' => 8,
                'alonti_user_id' => 6369,
                'route' => 1,
            ],
            [
                'id' => 1707,
                'cafe_id' => 17,
                'alonti_user_id' => 6369,
                'route' => 1,
            ],
            [
                'id' => 1709,
                'cafe_id' => 44,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1710,
                'cafe_id' => 55,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1711,
                'cafe_id' => 14,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1712,
                'cafe_id' => 28,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1713,
                'cafe_id' => 31,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1714,
                'cafe_id' => 34,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1715,
                'cafe_id' => 35,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1716,
                'cafe_id' => 37,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1717,
                'cafe_id' => 41,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1718,
                'cafe_id' => 45,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1719,
                'cafe_id' => 51,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1720,
                'cafe_id' => 13,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1721,
                'cafe_id' => 15,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1722,
                'cafe_id' => 29,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1723,
                'cafe_id' => 30,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1725,
                'cafe_id' => 36,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1726,
                'cafe_id' => 38,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1727,
                'cafe_id' => 43,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1728,
                'cafe_id' => 54,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1733,
                'cafe_id' => 33,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1734,
                'cafe_id' => 42,
                'alonti_user_id' => 24127,
                'route' => 0,
            ],
            [
                'id' => 1738,
                'cafe_id' => 30,
                'alonti_user_id' => 74125,
                'route' => 0,
            ],
            [
                'id' => 1754,
                'cafe_id' => 57,
                'alonti_user_id' => 57657,
                'route' => 1,
            ],
            [
                'id' => 1755,
                'cafe_id' => 58,
                'alonti_user_id' => 57657,
                'route' => 1,
            ],
            [
                'id' => 1756,
                'cafe_id' => 59,
                'alonti_user_id' => 57657,
                'route' => 1,
            ],
            [
                'id' => 1767,
                'cafe_id' => 62,
                'alonti_user_id' => 46072,
                'route' => 1,
            ],
            [
                'id' => 1768,
                'cafe_id' => 62,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1769,
                'cafe_id' => 62,
                'alonti_user_id' => 6369,
                'route' => 1,
            ],
            [
                'id' => 1770,
                'cafe_id' => 62,
                'alonti_user_id' => 30750,
                'route' => 0,
            ],
            [
                'id' => 1774,
                'cafe_id' => 62,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 1777,
                'cafe_id' => 62,
                'alonti_user_id' => 4819,
                'route' => 1,
            ],
            [
                'id' => 1778,
                'cafe_id' => 62,
                'alonti_user_id' => 11129,
                'route' => 1,
            ],
            [
                'id' => 1779,
                'cafe_id' => 62,
                'alonti_user_id' => 59071,
                'route' => 1,
            ],
            [
                'id' => 1783,
                'cafe_id' => 61,
                'alonti_user_id' => 4819,
                'route' => 1,
            ],
            [
                'id' => 1784,
                'cafe_id' => 61,
                'alonti_user_id' => 11129,
                'route' => 1,
            ],
            [
                'id' => 1785,
                'cafe_id' => 61,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 1786,
                'cafe_id' => 61,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1789,
                'cafe_id' => 61,
                'alonti_user_id' => 45466,
                'route' => 0,
            ],
            [
                'id' => 1794,
                'cafe_id' => 61,
                'alonti_user_id' => 57087,
                'route' => 0,
            ],
            [
                'id' => 1795,
                'cafe_id' => 61,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1805,
                'cafe_id' => 26,
                'alonti_user_id' => 46275,
                'route' => 1,
            ],
            [
                'id' => 1826,
                'cafe_id' => 63,
                'alonti_user_id' => 46072,
                'route' => 1,
            ],
            [
                'id' => 1831,
                'cafe_id' => 63,
                'alonti_user_id' => 57087,
                'route' => 1,
            ],
            [
                'id' => 1833,
                'cafe_id' => 63,
                'alonti_user_id' => 2,
                'route' => 1,
            ],
            [
                'id' => 1841,
                'cafe_id' => 63,
                'alonti_user_id' => 6369,
                'route' => 1,
            ],
            [
                'id' => 1845,
                'cafe_id' => 65,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1846,
                'cafe_id' => 65,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1848,
                'cafe_id' => 65,
                'alonti_user_id' => 57087,
                'route' => 0,
            ],
            [
                'id' => 1850,
                'cafe_id' => 65,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 1851,
                'cafe_id' => 65,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 1852,
                'cafe_id' => 65,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 1853,
                'cafe_id' => 65,
                'alonti_user_id' => 57657,
                'route' => 1,
            ],
            [
                'id' => 1855,
                'cafe_id' => 57,
                'alonti_user_id' => 88405,
                'route' => 1,
            ],
            [
                'id' => 1872,
                'cafe_id' => 42,
                'alonti_user_id' => 89891,
                'route' => 0,
            ],
            [
                'id' => 1876,
                'cafe_id' => 46,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1877,
                'cafe_id' => 47,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1878,
                'cafe_id' => 5,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1879,
                'cafe_id' => 7,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1880,
                'cafe_id' => 8,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1882,
                'cafe_id' => 17,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1884,
                'cafe_id' => 44,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1885,
                'cafe_id' => 55,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1886,
                'cafe_id' => 61,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1887,
                'cafe_id' => 62,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1888,
                'cafe_id' => 3,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1889,
                'cafe_id' => 22,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1891,
                'cafe_id' => 26,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1892,
                'cafe_id' => 24,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1893,
                'cafe_id' => 27,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1898,
                'cafe_id' => 28,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1899,
                'cafe_id' => 31,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1902,
                'cafe_id' => 37,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1904,
                'cafe_id' => 45,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1905,
                'cafe_id' => 51,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1907,
                'cafe_id' => 13,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1909,
                'cafe_id' => 29,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1910,
                'cafe_id' => 30,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1912,
                'cafe_id' => 33,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1913,
                'cafe_id' => 36,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1914,
                'cafe_id' => 38,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1915,
                'cafe_id' => 43,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1916,
                'cafe_id' => 54,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1917,
                'cafe_id' => 58,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1918,
                'cafe_id' => 57,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1919,
                'cafe_id' => 59,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1920,
                'cafe_id' => 65,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1921,
                'cafe_id' => 52,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1922,
                'cafe_id' => 53,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1930,
                'cafe_id' => 66,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1932,
                'cafe_id' => 66,
                'alonti_user_id' => 57087,
                'route' => 0,
            ],
            [
                'id' => 1933,
                'cafe_id' => 66,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1935,
                'cafe_id' => 66,
                'alonti_user_id' => 57657,
                'route' => 0,
            ],
            [
                'id' => 1936,
                'cafe_id' => 66,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 1937,
                'cafe_id' => 66,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 1938,
                'cafe_id' => 66,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 1939,
                'cafe_id' => 66,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1940,
                'cafe_id' => 66,
                'alonti_user_id' => 22348,
                'route' => 0,
            ],
            [
                'id' => 1942,
                'cafe_id' => 67,
                'alonti_user_id' => 57657,
                'route' => 0,
            ],
            [
                'id' => 1943,
                'cafe_id' => 67,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 1945,
                'cafe_id' => 67,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 1946,
                'cafe_id' => 67,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 1947,
                'cafe_id' => 67,
                'alonti_user_id' => 11129,
                'route' => 0,
            ],
            [
                'id' => 1950,
                'cafe_id' => 67,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 1951,
                'cafe_id' => 67,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 1952,
                'cafe_id' => 67,
                'alonti_user_id' => 57087,
                'route' => 0,
            ],
            [
                'id' => 1958,
                'cafe_id' => 53,
                'alonti_user_id' => 94200,
                'route' => 0,
            ],
            [
                'id' => 1965,
                'cafe_id' => 65,
                'alonti_user_id' => 95021,
                'route' => 0,
            ],
            [
                'id' => 1971,
                'cafe_id' => 60,
                'alonti_user_id' => 95446,
                'route' => 1,
            ],
            [
                'id' => 1990,
                'cafe_id' => 52,
                'alonti_user_id' => 94200,
                'route' => 0,
            ],
            [
                'id' => 1992,
                'cafe_id' => 66,
                'alonti_user_id' => 44255,
                'route' => 1,
            ],
            [
                'id' => 1995,
                'cafe_id' => 52,
                'alonti_user_id' => 98738,
                'route' => 0,
            ],
            [
                'id' => 1996,
                'cafe_id' => 53,
                'alonti_user_id' => 53769,
                'route' => 0,
            ],
            [
                'id' => 2000,
                'cafe_id' => 68,
                'alonti_user_id' => 51490,
                'route' => 0,
            ],
            [
                'id' => 2001,
                'cafe_id' => 68,
                'alonti_user_id' => 2,
                'route' => 0,
            ],
            [
                'id' => 2002,
                'cafe_id' => 68,
                'alonti_user_id' => 6369,
                'route' => 0,
            ],
            [
                'id' => 2003,
                'cafe_id' => 68,
                'alonti_user_id' => 4819,
                'route' => 0,
            ],
            [
                'id' => 2004,
                'cafe_id' => 68,
                'alonti_user_id' => 91651,
                'route' => 0,
            ],
            [
                'id' => 2005,
                'cafe_id' => 68,
                'alonti_user_id' => 46072,
                'route' => 0,
            ],
            [
                'id' => 2006,
                'cafe_id' => 68,
                'alonti_user_id' => 57087,
                'route' => 0,
            ],
            [
                'id' => 2007,
                'cafe_id' => 68,
                'alonti_user_id' => 97569,
                'route' => 0,
            ],
            [
                'id' => 2008,
                'cafe_id' => 68,
                'alonti_user_id' => 44255,
                'route' => 0,
            ],
            [
                'id' => 2015,
                'cafe_id' => 67,
                'alonti_user_id' => 57640,
                'route' => 0,
            ],
            [
                'id' => 2027,
                'cafe_id' => 68,
                'alonti_user_id' => 103408,
                'route' => 0,
            ],
            [
                'id' => 2052,
                'cafe_id' => 44,
                'alonti_user_id' => 109272,
                'route' => 0,
            ],
            [
                'id' => 2058,
                'cafe_id' => 45,
                'alonti_user_id' => 109911,
                'route' => 0,
            ],
            [
                'id' => 2059,
                'cafe_id' => 3,
                'alonti_user_id' => 110081,
                'route' => 0,
            ],
            [
                'id' => 2063,
                'cafe_id' => 42,
                'alonti_user_id' => 110081,
                'route' => 0,
            ],
            [
                'id' => 2071,
                'cafe_id' => 7,
                'alonti_user_id' => 110085,
                'route' => 0,
            ],
        ];

        DB::table('cafe_access')->insert($dataTables);
    }
}
