<?php

namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CafegoalsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables --limit=500
         */
        $dataTables = [
            [
                'CafeGoalsID' => 1,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 13,
                'Goal' => 1973,
            ],
            [
                'CafeGoalsID' => 2,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 13,
                'Goal' => 1901,
            ],
            [
                'CafeGoalsID' => 3,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 13,
                'Goal' => 1581,
            ],
            [
                'CafeGoalsID' => 4,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 13,
                'Goal' => 1711,
            ],
            [
                'CafeGoalsID' => 5,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 13,
                'Goal' => 1724,
            ],
            [
                'CafeGoalsID' => 6,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 13,
                'Goal' => 1607,
            ],
            [
                'CafeGoalsID' => 7,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 13,
                'Goal' => 1675,
            ],
            [
                'CafeGoalsID' => 8,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 13,
                'Goal' => 1487,
            ],
            [
                'CafeGoalsID' => 9,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 13,
                'Goal' => 1798,
            ],
            [
                'CafeGoalsID' => 10,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 13,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 11,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 13,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 12,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 13,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 13,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 14,
                'Goal' => 2301,
            ],
            [
                'CafeGoalsID' => 14,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 14,
                'Goal' => 2697,
            ],
            [
                'CafeGoalsID' => 15,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 14,
                'Goal' => 2538,
            ],
            [
                'CafeGoalsID' => 16,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 14,
                'Goal' => 2277,
            ],
            [
                'CafeGoalsID' => 17,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 14,
                'Goal' => 2729,
            ],
            [
                'CafeGoalsID' => 18,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 14,
                'Goal' => 2362,
            ],
            [
                'CafeGoalsID' => 19,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 14,
                'Goal' => 1976,
            ],
            [
                'CafeGoalsID' => 20,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 14,
                'Goal' => 2312,
            ],
            [
                'CafeGoalsID' => 21,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 14,
                'Goal' => 3059,
            ],
            [
                'CafeGoalsID' => 22,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 14,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 23,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 14,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 24,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 14,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 25,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 15,
                'Goal' => 4141,
            ],
            [
                'CafeGoalsID' => 26,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 15,
                'Goal' => 3349,
            ],
            [
                'CafeGoalsID' => 27,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 15,
                'Goal' => 2713,
            ],
            [
                'CafeGoalsID' => 28,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 15,
                'Goal' => 3110,
            ],
            [
                'CafeGoalsID' => 29,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 15,
                'Goal' => 3067,
            ],
            [
                'CafeGoalsID' => 30,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 15,
                'Goal' => 3078,
            ],
            [
                'CafeGoalsID' => 31,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 15,
                'Goal' => 2752,
            ],
            [
                'CafeGoalsID' => 32,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 15,
                'Goal' => 3275,
            ],
            [
                'CafeGoalsID' => 33,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 15,
                'Goal' => 2910,
            ],
            [
                'CafeGoalsID' => 34,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 15,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 35,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 15,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 36,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 15,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 37,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 3,
                'Goal' => 3576,
            ],
            [
                'CafeGoalsID' => 38,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 3,
                'Goal' => 3683,
            ],
            [
                'CafeGoalsID' => 39,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 3,
                'Goal' => 3808,
            ],
            [
                'CafeGoalsID' => 40,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 3,
                'Goal' => 2507,
            ],
            [
                'CafeGoalsID' => 41,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 3,
                'Goal' => 2374,
            ],
            [
                'CafeGoalsID' => 42,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 3,
                'Goal' => 2674,
            ],
            [
                'CafeGoalsID' => 43,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 3,
                'Goal' => 2108,
            ],
            [
                'CafeGoalsID' => 44,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 3,
                'Goal' => 5765,
            ],
            [
                'CafeGoalsID' => 45,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 3,
                'Goal' => 4004,
            ],
            [
                'CafeGoalsID' => 46,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 3,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 47,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 3,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 48,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 3,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 49,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 28,
                'Goal' => 2095,
            ],
            [
                'CafeGoalsID' => 50,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 28,
                'Goal' => 2063,
            ],
            [
                'CafeGoalsID' => 51,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 28,
                'Goal' => 1886,
            ],
            [
                'CafeGoalsID' => 52,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 28,
                'Goal' => 1904,
            ],
            [
                'CafeGoalsID' => 53,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 28,
                'Goal' => 2061,
            ],
            [
                'CafeGoalsID' => 54,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 28,
                'Goal' => 2414,
            ],
            [
                'CafeGoalsID' => 55,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 28,
                'Goal' => 1923,
            ],
            [
                'CafeGoalsID' => 56,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 28,
                'Goal' => 2095,
            ],
            [
                'CafeGoalsID' => 57,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 28,
                'Goal' => 2548,
            ],
            [
                'CafeGoalsID' => 58,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 28,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 59,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 28,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 60,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 28,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 61,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 29,
                'Goal' => 693,
            ],
            [
                'CafeGoalsID' => 62,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 29,
                'Goal' => 687,
            ],
            [
                'CafeGoalsID' => 63,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 29,
                'Goal' => 640,
            ],
            [
                'CafeGoalsID' => 64,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 29,
                'Goal' => 653,
            ],
            [
                'CafeGoalsID' => 65,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 29,
                'Goal' => 576,
            ],
            [
                'CafeGoalsID' => 66,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 29,
                'Goal' => 894,
            ],
            [
                'CafeGoalsID' => 67,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 29,
                'Goal' => 631,
            ],
            [
                'CafeGoalsID' => 68,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 29,
                'Goal' => 776,
            ],
            [
                'CafeGoalsID' => 69,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 29,
                'Goal' => 543,
            ],
            [
                'CafeGoalsID' => 70,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 29,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 71,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 29,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 72,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 29,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 73,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 22,
                'Goal' => 42,
            ],
            [
                'CafeGoalsID' => 74,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 22,
                'Goal' => 40,
            ],
            [
                'CafeGoalsID' => 75,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 22,
                'Goal' => 32,
            ],
            [
                'CafeGoalsID' => 76,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 22,
                'Goal' => 42,
            ],
            [
                'CafeGoalsID' => 77,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 22,
                'Goal' => 22,
            ],
            [
                'CafeGoalsID' => 78,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 22,
                'Goal' => 31,
            ],
            [
                'CafeGoalsID' => 79,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 22,
                'Goal' => 37,
            ],
            [
                'CafeGoalsID' => 80,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 22,
                'Goal' => 42,
            ],
            [
                'CafeGoalsID' => 81,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 22,
                'Goal' => 47,
            ],
            [
                'CafeGoalsID' => 82,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 22,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 83,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 22,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 84,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 22,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 85,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 30,
                'Goal' => 3953,
            ],
            [
                'CafeGoalsID' => 86,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 30,
                'Goal' => 3946,
            ],
            [
                'CafeGoalsID' => 87,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 30,
                'Goal' => 3227,
            ],
            [
                'CafeGoalsID' => 88,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 30,
                'Goal' => 3839,
            ],
            [
                'CafeGoalsID' => 89,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 30,
                'Goal' => 3467,
            ],
            [
                'CafeGoalsID' => 90,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 30,
                'Goal' => 4043,
            ],
            [
                'CafeGoalsID' => 91,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 30,
                'Goal' => 3412,
            ],
            [
                'CafeGoalsID' => 92,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 30,
                'Goal' => 4336,
            ],
            [
                'CafeGoalsID' => 93,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 30,
                'Goal' => 4381,
            ],
            [
                'CafeGoalsID' => 94,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 30,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 95,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 30,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 96,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 30,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 97,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 5,
                'Goal' => 1885,
            ],
            [
                'CafeGoalsID' => 98,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 5,
                'Goal' => 1917,
            ],
            [
                'CafeGoalsID' => 99,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 5,
                'Goal' => 1780,
            ],
            [
                'CafeGoalsID' => 100,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 5,
                'Goal' => 2113,
            ],
            [
                'CafeGoalsID' => 101,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 5,
                'Goal' => 3096,
            ],
            [
                'CafeGoalsID' => 102,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 5,
                'Goal' => 3362,
            ],
            [
                'CafeGoalsID' => 103,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 5,
                'Goal' => 2557,
            ],
            [
                'CafeGoalsID' => 104,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 5,
                'Goal' => 3083,
            ],
            [
                'CafeGoalsID' => 105,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 5,
                'Goal' => 2998,
            ],
            [
                'CafeGoalsID' => 106,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 5,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 107,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 5,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 108,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 5,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 109,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 31,
                'Goal' => 2006,
            ],
            [
                'CafeGoalsID' => 110,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 31,
                'Goal' => 1931,
            ],
            [
                'CafeGoalsID' => 111,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 31,
                'Goal' => 2033,
            ],
            [
                'CafeGoalsID' => 112,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 31,
                'Goal' => 1576,
            ],
            [
                'CafeGoalsID' => 113,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 31,
                'Goal' => 1246,
            ],
            [
                'CafeGoalsID' => 114,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 31,
                'Goal' => 1769,
            ],
            [
                'CafeGoalsID' => 115,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 31,
                'Goal' => 1807,
            ],
            [
                'CafeGoalsID' => 116,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 31,
                'Goal' => 2331,
            ],
            [
                'CafeGoalsID' => 117,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 31,
                'Goal' => 1885,
            ],
            [
                'CafeGoalsID' => 118,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 31,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 119,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 31,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 120,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 31,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 121,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 7,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 122,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 7,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 123,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 7,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 124,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 7,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 125,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 7,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 126,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 7,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 127,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 7,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 128,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 7,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 129,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 7,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 130,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 7,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 131,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 7,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 132,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 7,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 133,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 8,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 134,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 8,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 135,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 8,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 136,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 8,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 137,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 8,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 138,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 8,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 139,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 8,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 140,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 8,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 141,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 8,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 142,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 8,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 143,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 8,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 144,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 8,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 145,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 33,
                'Goal' => 1682,
            ],
            [
                'CafeGoalsID' => 146,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 33,
                'Goal' => 1474,
            ],
            [
                'CafeGoalsID' => 147,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 33,
                'Goal' => 1619,
            ],
            [
                'CafeGoalsID' => 148,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 33,
                'Goal' => 1590,
            ],
            [
                'CafeGoalsID' => 149,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 33,
                'Goal' => 1443,
            ],
            [
                'CafeGoalsID' => 150,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 33,
                'Goal' => 1042,
            ],
            [
                'CafeGoalsID' => 151,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 33,
                'Goal' => 1121,
            ],
            [
                'CafeGoalsID' => 152,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 33,
                'Goal' => 1813,
            ],
            [
                'CafeGoalsID' => 153,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 33,
                'Goal' => 1309,
            ],
            [
                'CafeGoalsID' => 154,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 33,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 155,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 33,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 156,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 33,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 157,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 26,
                'Goal' => 2455,
            ],
            [
                'CafeGoalsID' => 158,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 26,
                'Goal' => 3047,
            ],
            [
                'CafeGoalsID' => 159,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 26,
                'Goal' => 2704,
            ],
            [
                'CafeGoalsID' => 160,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 26,
                'Goal' => 3217,
            ],
            [
                'CafeGoalsID' => 161,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 26,
                'Goal' => 2718,
            ],
            [
                'CafeGoalsID' => 162,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 26,
                'Goal' => 3055,
            ],
            [
                'CafeGoalsID' => 163,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 26,
                'Goal' => 2473,
            ],
            [
                'CafeGoalsID' => 164,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 26,
                'Goal' => 3069,
            ],
            [
                'CafeGoalsID' => 165,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 26,
                'Goal' => 3781,
            ],
            [
                'CafeGoalsID' => 166,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 26,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 167,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 26,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 168,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 26,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 169,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 34,
                'Goal' => 523,
            ],
            [
                'CafeGoalsID' => 170,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 34,
                'Goal' => 488,
            ],
            [
                'CafeGoalsID' => 171,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 34,
                'Goal' => 247,
            ],
            [
                'CafeGoalsID' => 172,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 34,
                'Goal' => 402,
            ],
            [
                'CafeGoalsID' => 173,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 34,
                'Goal' => 485,
            ],
            [
                'CafeGoalsID' => 174,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 34,
                'Goal' => 270,
            ],
            [
                'CafeGoalsID' => 175,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 34,
                'Goal' => 314,
            ],
            [
                'CafeGoalsID' => 176,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 34,
                'Goal' => 342,
            ],
            [
                'CafeGoalsID' => 177,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 34,
                'Goal' => 271,
            ],
            [
                'CafeGoalsID' => 178,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 34,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 179,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 34,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 180,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 34,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 181,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 35,
                'Goal' => 1775,
            ],
            [
                'CafeGoalsID' => 182,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 35,
                'Goal' => 1836,
            ],
            [
                'CafeGoalsID' => 183,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 35,
                'Goal' => 1706,
            ],
            [
                'CafeGoalsID' => 184,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 35,
                'Goal' => 1771,
            ],
            [
                'CafeGoalsID' => 185,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 35,
                'Goal' => 2338,
            ],
            [
                'CafeGoalsID' => 186,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 35,
                'Goal' => 2672,
            ],
            [
                'CafeGoalsID' => 187,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 35,
                'Goal' => 1894,
            ],
            [
                'CafeGoalsID' => 188,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 35,
                'Goal' => 2415,
            ],
            [
                'CafeGoalsID' => 189,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 35,
                'Goal' => 2131,
            ],
            [
                'CafeGoalsID' => 190,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 35,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 191,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 35,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 192,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 35,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 193,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 36,
                'Goal' => 1234,
            ],
            [
                'CafeGoalsID' => 194,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 36,
                'Goal' => 1945,
            ],
            [
                'CafeGoalsID' => 195,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 36,
                'Goal' => 1925,
            ],
            [
                'CafeGoalsID' => 196,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 36,
                'Goal' => 1716,
            ],
            [
                'CafeGoalsID' => 197,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 36,
                'Goal' => 2215,
            ],
            [
                'CafeGoalsID' => 198,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 36,
                'Goal' => 2146,
            ],
            [
                'CafeGoalsID' => 199,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 36,
                'Goal' => 2157,
            ],
            [
                'CafeGoalsID' => 200,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 36,
                'Goal' => 2390,
            ],
            [
                'CafeGoalsID' => 201,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 36,
                'Goal' => 2561,
            ],
            [
                'CafeGoalsID' => 202,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 36,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 203,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 36,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 204,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 36,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 205,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 37,
                'Goal' => 1627,
            ],
            [
                'CafeGoalsID' => 206,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 37,
                'Goal' => 1861,
            ],
            [
                'CafeGoalsID' => 207,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 37,
                'Goal' => 1723,
            ],
            [
                'CafeGoalsID' => 208,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 37,
                'Goal' => 1890,
            ],
            [
                'CafeGoalsID' => 209,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 37,
                'Goal' => 1407,
            ],
            [
                'CafeGoalsID' => 210,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 37,
                'Goal' => 1527,
            ],
            [
                'CafeGoalsID' => 211,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 37,
                'Goal' => 1493,
            ],
            [
                'CafeGoalsID' => 212,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 37,
                'Goal' => 1442,
            ],
            [
                'CafeGoalsID' => 213,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 37,
                'Goal' => 1664,
            ],
            [
                'CafeGoalsID' => 214,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 37,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 215,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 37,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 216,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 37,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 217,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 38,
                'Goal' => 1374,
            ],
            [
                'CafeGoalsID' => 218,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 38,
                'Goal' => 2687,
            ],
            [
                'CafeGoalsID' => 219,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 38,
                'Goal' => 1459,
            ],
            [
                'CafeGoalsID' => 220,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 38,
                'Goal' => 1729,
            ],
            [
                'CafeGoalsID' => 221,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 38,
                'Goal' => 1479,
            ],
            [
                'CafeGoalsID' => 222,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 38,
                'Goal' => 2182,
            ],
            [
                'CafeGoalsID' => 223,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 38,
                'Goal' => 1645,
            ],
            [
                'CafeGoalsID' => 224,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 38,
                'Goal' => 2264,
            ],
            [
                'CafeGoalsID' => 225,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 38,
                'Goal' => 2676,
            ],
            [
                'CafeGoalsID' => 226,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 38,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 227,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 38,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 228,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 38,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 229,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 39,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 230,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 39,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 231,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 39,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 232,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 39,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 233,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 39,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 234,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 39,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 235,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 39,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 236,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 39,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 237,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 39,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 238,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 39,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 239,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 39,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 240,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 39,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 241,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 17,
                'Goal' => 1409,
            ],
            [
                'CafeGoalsID' => 242,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 17,
                'Goal' => 1420,
            ],
            [
                'CafeGoalsID' => 243,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 17,
                'Goal' => 1569,
            ],
            [
                'CafeGoalsID' => 244,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 17,
                'Goal' => 1529,
            ],
            [
                'CafeGoalsID' => 245,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 17,
                'Goal' => 1608,
            ],
            [
                'CafeGoalsID' => 246,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 17,
                'Goal' => 2345,
            ],
            [
                'CafeGoalsID' => 247,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 17,
                'Goal' => 1630,
            ],
            [
                'CafeGoalsID' => 248,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 17,
                'Goal' => 1646,
            ],
            [
                'CafeGoalsID' => 249,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 17,
                'Goal' => 1431,
            ],
            [
                'CafeGoalsID' => 250,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 17,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 251,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 17,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 252,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 17,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 253,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 24,
                'Goal' => 3514,
            ],
            [
                'CafeGoalsID' => 254,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 24,
                'Goal' => 3688,
            ],
            [
                'CafeGoalsID' => 255,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 24,
                'Goal' => 3963,
            ],
            [
                'CafeGoalsID' => 256,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 24,
                'Goal' => 4151,
            ],
            [
                'CafeGoalsID' => 257,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 24,
                'Goal' => 4297,
            ],
            [
                'CafeGoalsID' => 258,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 24,
                'Goal' => 3824,
            ],
            [
                'CafeGoalsID' => 259,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 24,
                'Goal' => 2971,
            ],
            [
                'CafeGoalsID' => 260,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 24,
                'Goal' => 4348,
            ],
            [
                'CafeGoalsID' => 261,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 24,
                'Goal' => 4001,
            ],
            [
                'CafeGoalsID' => 262,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 24,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 263,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 24,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 264,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 24,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 265,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 27,
                'Goal' => 1226,
            ],
            [
                'CafeGoalsID' => 266,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 27,
                'Goal' => 1339,
            ],
            [
                'CafeGoalsID' => 267,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 27,
                'Goal' => 1426,
            ],
            [
                'CafeGoalsID' => 268,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 27,
                'Goal' => 1536,
            ],
            [
                'CafeGoalsID' => 269,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 27,
                'Goal' => 1328,
            ],
            [
                'CafeGoalsID' => 270,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 27,
                'Goal' => 1586,
            ],
            [
                'CafeGoalsID' => 271,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 27,
                'Goal' => 1341,
            ],
            [
                'CafeGoalsID' => 272,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 27,
                'Goal' => 1544,
            ],
            [
                'CafeGoalsID' => 273,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 27,
                'Goal' => 1590,
            ],
            [
                'CafeGoalsID' => 274,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 27,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 275,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 27,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 276,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 27,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 277,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 25,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 278,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 25,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 279,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 25,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 280,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 25,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 281,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 25,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 282,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 25,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 283,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 25,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 284,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 25,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 285,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 25,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 286,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 25,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 287,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 25,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 288,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 25,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 289,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 19,
                'Goal' => 1781,
            ],
            [
                'CafeGoalsID' => 290,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 19,
                'Goal' => 1662,
            ],
            [
                'CafeGoalsID' => 291,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 19,
                'Goal' => 1372,
            ],
            [
                'CafeGoalsID' => 292,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 19,
                'Goal' => 1541,
            ],
            [
                'CafeGoalsID' => 293,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 19,
                'Goal' => 1532,
            ],
            [
                'CafeGoalsID' => 294,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 19,
                'Goal' => 2282,
            ],
            [
                'CafeGoalsID' => 295,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 19,
                'Goal' => 2263,
            ],
            [
                'CafeGoalsID' => 296,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 19,
                'Goal' => 991,
            ],
            [
                'CafeGoalsID' => 297,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 19,
                'Goal' => 958,
            ],
            [
                'CafeGoalsID' => 298,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 19,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 299,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 19,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 300,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 19,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 301,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 41,
                'Goal' => 3430,
            ],
            [
                'CafeGoalsID' => 302,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 41,
                'Goal' => 3740,
            ],
            [
                'CafeGoalsID' => 303,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 41,
                'Goal' => 3645,
            ],
            [
                'CafeGoalsID' => 304,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 41,
                'Goal' => 3977,
            ],
            [
                'CafeGoalsID' => 305,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 41,
                'Goal' => 3973,
            ],
            [
                'CafeGoalsID' => 306,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 41,
                'Goal' => 3361,
            ],
            [
                'CafeGoalsID' => 307,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 41,
                'Goal' => 2634,
            ],
            [
                'CafeGoalsID' => 308,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 41,
                'Goal' => 4320,
            ],
            [
                'CafeGoalsID' => 309,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 41,
                'Goal' => 3526,
            ],
            [
                'CafeGoalsID' => 310,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 41,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 311,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 41,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 312,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 41,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 313,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 42,
                'Goal' => 2231,
            ],
            [
                'CafeGoalsID' => 314,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 42,
                'Goal' => 2671,
            ],
            [
                'CafeGoalsID' => 315,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 42,
                'Goal' => 2934,
            ],
            [
                'CafeGoalsID' => 316,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 42,
                'Goal' => 3089,
            ],
            [
                'CafeGoalsID' => 317,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 42,
                'Goal' => 2917,
            ],
            [
                'CafeGoalsID' => 318,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 42,
                'Goal' => 3652,
            ],
            [
                'CafeGoalsID' => 319,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 42,
                'Goal' => 3565,
            ],
            [
                'CafeGoalsID' => 320,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 42,
                'Goal' => 3530,
            ],
            [
                'CafeGoalsID' => 321,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 42,
                'Goal' => 3734,
            ],
            [
                'CafeGoalsID' => 322,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 42,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 323,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 42,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 324,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 42,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 325,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 43,
                'Goal' => 1983,
            ],
            [
                'CafeGoalsID' => 326,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 43,
                'Goal' => 2594,
            ],
            [
                'CafeGoalsID' => 327,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 43,
                'Goal' => 2115,
            ],
            [
                'CafeGoalsID' => 328,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 43,
                'Goal' => 2331,
            ],
            [
                'CafeGoalsID' => 329,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 43,
                'Goal' => 2667,
            ],
            [
                'CafeGoalsID' => 330,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 43,
                'Goal' => 2399,
            ],
            [
                'CafeGoalsID' => 331,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 43,
                'Goal' => 2060,
            ],
            [
                'CafeGoalsID' => 332,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 43,
                'Goal' => 2821,
            ],
            [
                'CafeGoalsID' => 333,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 43,
                'Goal' => 2715,
            ],
            [
                'CafeGoalsID' => 334,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 43,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 335,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 43,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 336,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 43,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 337,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 44,
                'Goal' => 2893,
            ],
            [
                'CafeGoalsID' => 338,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 44,
                'Goal' => 2088,
            ],
            [
                'CafeGoalsID' => 339,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 44,
                'Goal' => 3005,
            ],
            [
                'CafeGoalsID' => 340,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 44,
                'Goal' => 2963,
            ],
            [
                'CafeGoalsID' => 341,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 44,
                'Goal' => 3987,
            ],
            [
                'CafeGoalsID' => 342,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 44,
                'Goal' => 4836,
            ],
            [
                'CafeGoalsID' => 343,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 44,
                'Goal' => 3357,
            ],
            [
                'CafeGoalsID' => 344,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 44,
                'Goal' => 3806,
            ],
            [
                'CafeGoalsID' => 345,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 44,
                'Goal' => 3091,
            ],
            [
                'CafeGoalsID' => 346,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 44,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 347,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 44,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 348,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 44,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 349,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 46,
                'Goal' => 2240,
            ],
            [
                'CafeGoalsID' => 350,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 46,
                'Goal' => 2570,
            ],
            [
                'CafeGoalsID' => 351,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 46,
                'Goal' => 2499,
            ],
            [
                'CafeGoalsID' => 352,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 46,
                'Goal' => 2697,
            ],
            [
                'CafeGoalsID' => 353,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 46,
                'Goal' => 2593,
            ],
            [
                'CafeGoalsID' => 354,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 46,
                'Goal' => 2590,
            ],
            [
                'CafeGoalsID' => 355,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 46,
                'Goal' => 2369,
            ],
            [
                'CafeGoalsID' => 356,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 46,
                'Goal' => 2797,
            ],
            [
                'CafeGoalsID' => 357,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 46,
                'Goal' => 2711,
            ],
            [
                'CafeGoalsID' => 358,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 46,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 359,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 46,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 360,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 46,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 361,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 45,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 362,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 45,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 363,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 45,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 364,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 45,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 365,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 45,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 366,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 45,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 367,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 45,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 368,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 45,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 369,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 45,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 370,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 45,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 371,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 45,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 372,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 45,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 373,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 47,
                'Goal' => 1226,
            ],
            [
                'CafeGoalsID' => 374,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 47,
                'Goal' => 1590,
            ],
            [
                'CafeGoalsID' => 375,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 47,
                'Goal' => 1252,
            ],
            [
                'CafeGoalsID' => 376,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 47,
                'Goal' => 1564,
            ],
            [
                'CafeGoalsID' => 377,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 47,
                'Goal' => 1390,
            ],
            [
                'CafeGoalsID' => 378,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 47,
                'Goal' => 1594,
            ],
            [
                'CafeGoalsID' => 379,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 47,
                'Goal' => 1497,
            ],
            [
                'CafeGoalsID' => 380,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 47,
                'Goal' => 1783,
            ],
            [
                'CafeGoalsID' => 381,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 47,
                'Goal' => 1971,
            ],
            [
                'CafeGoalsID' => 382,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 47,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 383,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 47,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 384,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 47,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 385,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 51,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 386,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 51,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 387,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 51,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 388,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 51,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 389,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 51,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 390,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 51,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 391,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 51,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 392,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 51,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 393,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 51,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 394,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 51,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 395,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 51,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 396,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 51,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 397,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 52,
                'Goal' => 991,
            ],
            [
                'CafeGoalsID' => 398,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 52,
                'Goal' => 1379,
            ],
            [
                'CafeGoalsID' => 399,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 52,
                'Goal' => 1296,
            ],
            [
                'CafeGoalsID' => 400,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 52,
                'Goal' => 1515,
            ],
            [
                'CafeGoalsID' => 401,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 52,
                'Goal' => 1339,
            ],
            [
                'CafeGoalsID' => 402,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 52,
                'Goal' => 1391,
            ],
            [
                'CafeGoalsID' => 403,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 52,
                'Goal' => 1431,
            ],
            [
                'CafeGoalsID' => 404,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 52,
                'Goal' => 1632,
            ],
            [
                'CafeGoalsID' => 405,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 52,
                'Goal' => 1695,
            ],
            [
                'CafeGoalsID' => 406,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 52,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 407,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 52,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 408,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 52,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 409,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 53,
                'Goal' => 1118,
            ],
            [
                'CafeGoalsID' => 410,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 53,
                'Goal' => 996,
            ],
            [
                'CafeGoalsID' => 411,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 53,
                'Goal' => 1219,
            ],
            [
                'CafeGoalsID' => 412,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 53,
                'Goal' => 1967,
            ],
            [
                'CafeGoalsID' => 413,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 53,
                'Goal' => 1249,
            ],
            [
                'CafeGoalsID' => 414,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 53,
                'Goal' => 1845,
            ],
            [
                'CafeGoalsID' => 415,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 53,
                'Goal' => 1535,
            ],
            [
                'CafeGoalsID' => 416,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 53,
                'Goal' => 1508,
            ],
            [
                'CafeGoalsID' => 417,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 53,
                'Goal' => 1582,
            ],
            [
                'CafeGoalsID' => 418,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 53,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 419,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 53,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 420,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 53,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 421,
                'Year' => 2012,
                'Quarter' => 1,
                'DistrictID' => 54,
                'Goal' => 229,
            ],
            [
                'CafeGoalsID' => 422,
                'Year' => 2012,
                'Quarter' => 2,
                'DistrictID' => 54,
                'Goal' => 269,
            ],
            [
                'CafeGoalsID' => 423,
                'Year' => 2012,
                'Quarter' => 3,
                'DistrictID' => 54,
                'Goal' => 1643,
            ],
            [
                'CafeGoalsID' => 424,
                'Year' => 2012,
                'Quarter' => 4,
                'DistrictID' => 54,
                'Goal' => 559,
            ],
            [
                'CafeGoalsID' => 425,
                'Year' => 2012,
                'Quarter' => 5,
                'DistrictID' => 54,
                'Goal' => 703,
            ],
            [
                'CafeGoalsID' => 426,
                'Year' => 2012,
                'Quarter' => 6,
                'DistrictID' => 54,
                'Goal' => 605,
            ],
            [
                'CafeGoalsID' => 427,
                'Year' => 2012,
                'Quarter' => 7,
                'DistrictID' => 54,
                'Goal' => 690,
            ],
            [
                'CafeGoalsID' => 428,
                'Year' => 2012,
                'Quarter' => 8,
                'DistrictID' => 54,
                'Goal' => 1395,
            ],
            [
                'CafeGoalsID' => 429,
                'Year' => 2012,
                'Quarter' => 9,
                'DistrictID' => 54,
                'Goal' => 804,
            ],
            [
                'CafeGoalsID' => 430,
                'Year' => 2012,
                'Quarter' => 10,
                'DistrictID' => 54,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 431,
                'Year' => 2012,
                'Quarter' => 11,
                'DistrictID' => 54,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 432,
                'Year' => 2012,
                'Quarter' => 12,
                'DistrictID' => 54,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 433,
                'Year' => 2011,
                'Quarter' => 1,
                'DistrictID' => 13,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 434,
                'Year' => 2011,
                'Quarter' => 2,
                'DistrictID' => 13,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 435,
                'Year' => 2011,
                'Quarter' => 3,
                'DistrictID' => 13,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 436,
                'Year' => 2011,
                'Quarter' => 4,
                'DistrictID' => 13,
                'Goal' => 1825,
            ],
            [
                'CafeGoalsID' => 437,
                'Year' => 2011,
                'Quarter' => 5,
                'DistrictID' => 13,
                'Goal' => 1932,
            ],
            [
                'CafeGoalsID' => 438,
                'Year' => 2011,
                'Quarter' => 6,
                'DistrictID' => 13,
                'Goal' => 1652,
            ],
            [
                'CafeGoalsID' => 439,
                'Year' => 2011,
                'Quarter' => 7,
                'DistrictID' => 13,
                'Goal' => 1908,
            ],
            [
                'CafeGoalsID' => 440,
                'Year' => 2011,
                'Quarter' => 8,
                'DistrictID' => 13,
                'Goal' => 1615,
            ],
            [
                'CafeGoalsID' => 441,
                'Year' => 2011,
                'Quarter' => 9,
                'DistrictID' => 13,
                'Goal' => 1639,
            ],
            [
                'CafeGoalsID' => 442,
                'Year' => 2011,
                'Quarter' => 10,
                'DistrictID' => 13,
                'Goal' => 2085,
            ],
            [
                'CafeGoalsID' => 443,
                'Year' => 2011,
                'Quarter' => 11,
                'DistrictID' => 13,
                'Goal' => 1732,
            ],
            [
                'CafeGoalsID' => 444,
                'Year' => 2011,
                'Quarter' => 12,
                'DistrictID' => 13,
                'Goal' => 2019,
            ],
            [
                'CafeGoalsID' => 445,
                'Year' => 2011,
                'Quarter' => 1,
                'DistrictID' => 14,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 446,
                'Year' => 2011,
                'Quarter' => 2,
                'DistrictID' => 14,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 447,
                'Year' => 2011,
                'Quarter' => 3,
                'DistrictID' => 14,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 448,
                'Year' => 2011,
                'Quarter' => 4,
                'DistrictID' => 14,
                'Goal' => 2966,
            ],
            [
                'CafeGoalsID' => 449,
                'Year' => 2011,
                'Quarter' => 5,
                'DistrictID' => 14,
                'Goal' => 2607,
            ],
            [
                'CafeGoalsID' => 450,
                'Year' => 2011,
                'Quarter' => 6,
                'DistrictID' => 14,
                'Goal' => 2435,
            ],
            [
                'CafeGoalsID' => 451,
                'Year' => 2011,
                'Quarter' => 7,
                'DistrictID' => 14,
                'Goal' => 2157,
            ],
            [
                'CafeGoalsID' => 452,
                'Year' => 2011,
                'Quarter' => 8,
                'DistrictID' => 14,
                'Goal' => 2060,
            ],
            [
                'CafeGoalsID' => 453,
                'Year' => 2011,
                'Quarter' => 9,
                'DistrictID' => 14,
                'Goal' => 2710,
            ],
            [
                'CafeGoalsID' => 454,
                'Year' => 2011,
                'Quarter' => 10,
                'DistrictID' => 14,
                'Goal' => 2511,
            ],
            [
                'CafeGoalsID' => 455,
                'Year' => 2011,
                'Quarter' => 11,
                'DistrictID' => 14,
                'Goal' => 3582,
            ],
            [
                'CafeGoalsID' => 456,
                'Year' => 2011,
                'Quarter' => 12,
                'DistrictID' => 14,
                'Goal' => 2310,
            ],
            [
                'CafeGoalsID' => 457,
                'Year' => 2011,
                'Quarter' => 1,
                'DistrictID' => 15,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 458,
                'Year' => 2011,
                'Quarter' => 2,
                'DistrictID' => 15,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 459,
                'Year' => 2011,
                'Quarter' => 3,
                'DistrictID' => 15,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 460,
                'Year' => 2011,
                'Quarter' => 4,
                'DistrictID' => 15,
                'Goal' => 2540,
            ],
            [
                'CafeGoalsID' => 461,
                'Year' => 2011,
                'Quarter' => 5,
                'DistrictID' => 15,
                'Goal' => 3078,
            ],
            [
                'CafeGoalsID' => 462,
                'Year' => 2011,
                'Quarter' => 6,
                'DistrictID' => 15,
                'Goal' => 3448,
            ],
            [
                'CafeGoalsID' => 463,
                'Year' => 2011,
                'Quarter' => 7,
                'DistrictID' => 15,
                'Goal' => 3110,
            ],
            [
                'CafeGoalsID' => 464,
                'Year' => 2011,
                'Quarter' => 8,
                'DistrictID' => 15,
                'Goal' => 3248,
            ],
            [
                'CafeGoalsID' => 465,
                'Year' => 2011,
                'Quarter' => 9,
                'DistrictID' => 15,
                'Goal' => 3665,
            ],
            [
                'CafeGoalsID' => 466,
                'Year' => 2011,
                'Quarter' => 10,
                'DistrictID' => 15,
                'Goal' => 3731,
            ],
            [
                'CafeGoalsID' => 467,
                'Year' => 2011,
                'Quarter' => 11,
                'DistrictID' => 15,
                'Goal' => 4342,
            ],
            [
                'CafeGoalsID' => 468,
                'Year' => 2011,
                'Quarter' => 12,
                'DistrictID' => 15,
                'Goal' => 6510,
            ],
            [
                'CafeGoalsID' => 469,
                'Year' => 2011,
                'Quarter' => 1,
                'DistrictID' => 3,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 470,
                'Year' => 2011,
                'Quarter' => 2,
                'DistrictID' => 3,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 471,
                'Year' => 2011,
                'Quarter' => 3,
                'DistrictID' => 3,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 472,
                'Year' => 2011,
                'Quarter' => 4,
                'DistrictID' => 3,
                'Goal' => 3399,
            ],
            [
                'CafeGoalsID' => 473,
                'Year' => 2011,
                'Quarter' => 5,
                'DistrictID' => 3,
                'Goal' => 3297,
            ],
            [
                'CafeGoalsID' => 474,
                'Year' => 2011,
                'Quarter' => 6,
                'DistrictID' => 3,
                'Goal' => 3271,
            ],
            [
                'CafeGoalsID' => 475,
                'Year' => 2011,
                'Quarter' => 7,
                'DistrictID' => 3,
                'Goal' => 2856,
            ],
            [
                'CafeGoalsID' => 476,
                'Year' => 2011,
                'Quarter' => 8,
                'DistrictID' => 3,
                'Goal' => 4061,
            ],
            [
                'CafeGoalsID' => 477,
                'Year' => 2011,
                'Quarter' => 9,
                'DistrictID' => 3,
                'Goal' => 3381,
            ],
            [
                'CafeGoalsID' => 478,
                'Year' => 2011,
                'Quarter' => 10,
                'DistrictID' => 3,
                'Goal' => 3863,
            ],
            [
                'CafeGoalsID' => 479,
                'Year' => 2011,
                'Quarter' => 11,
                'DistrictID' => 3,
                'Goal' => 4060,
            ],
            [
                'CafeGoalsID' => 480,
                'Year' => 2011,
                'Quarter' => 12,
                'DistrictID' => 3,
                'Goal' => 4203,
            ],
            [
                'CafeGoalsID' => 481,
                'Year' => 2011,
                'Quarter' => 1,
                'DistrictID' => 28,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 482,
                'Year' => 2011,
                'Quarter' => 2,
                'DistrictID' => 28,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 483,
                'Year' => 2011,
                'Quarter' => 3,
                'DistrictID' => 28,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 484,
                'Year' => 2011,
                'Quarter' => 4,
                'DistrictID' => 28,
                'Goal' => 1450,
            ],
            [
                'CafeGoalsID' => 485,
                'Year' => 2011,
                'Quarter' => 5,
                'DistrictID' => 28,
                'Goal' => 2043,
            ],
            [
                'CafeGoalsID' => 486,
                'Year' => 2011,
                'Quarter' => 6,
                'DistrictID' => 28,
                'Goal' => 2179,
            ],
            [
                'CafeGoalsID' => 487,
                'Year' => 2011,
                'Quarter' => 7,
                'DistrictID' => 28,
                'Goal' => 2043,
            ],
            [
                'CafeGoalsID' => 488,
                'Year' => 2011,
                'Quarter' => 8,
                'DistrictID' => 28,
                'Goal' => 2068,
            ],
            [
                'CafeGoalsID' => 489,
                'Year' => 2011,
                'Quarter' => 9,
                'DistrictID' => 28,
                'Goal' => 2225,
            ],
            [
                'CafeGoalsID' => 490,
                'Year' => 2011,
                'Quarter' => 10,
                'DistrictID' => 28,
                'Goal' => 2317,
            ],
            [
                'CafeGoalsID' => 491,
                'Year' => 2011,
                'Quarter' => 11,
                'DistrictID' => 28,
                'Goal' => 2748,
            ],
            [
                'CafeGoalsID' => 492,
                'Year' => 2011,
                'Quarter' => 12,
                'DistrictID' => 28,
                'Goal' => 1824,
            ],
            [
                'CafeGoalsID' => 493,
                'Year' => 2011,
                'Quarter' => 1,
                'DistrictID' => 29,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 494,
                'Year' => 2011,
                'Quarter' => 2,
                'DistrictID' => 29,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 495,
                'Year' => 2011,
                'Quarter' => 3,
                'DistrictID' => 29,
                'Goal' => 0,
            ],
            [
                'CafeGoalsID' => 496,
                'Year' => 2011,
                'Quarter' => 4,
                'DistrictID' => 29,
                'Goal' => 512,
            ],
            [
                'CafeGoalsID' => 497,
                'Year' => 2011,
                'Quarter' => 5,
                'DistrictID' => 29,
                'Goal' => 739,
            ],
            [
                'CafeGoalsID' => 498,
                'Year' => 2011,
                'Quarter' => 6,
                'DistrictID' => 29,
                'Goal' => 653,
            ],
            [
                'CafeGoalsID' => 499,
                'Year' => 2011,
                'Quarter' => 7,
                'DistrictID' => 29,
                'Goal' => 642,
            ],
            [
                'CafeGoalsID' => 500,
                'Year' => 2011,
                'Quarter' => 8,
                'DistrictID' => 29,
                'Goal' => 722,
            ],
        ];

        DB::table('cafegoals')->insert($dataTables);
    }
}
