<?php

namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DirectorsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables --limit=500
         */
        $dataTables = [
            [
                'id' => 12,
                'market_id' => 6,
                'title' => 'Catering Director',
                'director' => 'Suzun Edmead',
                'phone' => '312-831-9006',
                'fax' => '312-831-9104',
                'email' => 'sedmead@alonti.com',
                'alonti_user_id' => null,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 19,
                'market_id' => 9,
                'title' => 'Catering Sales Manager',
                'director' => 'Amber Keyser',
                'phone' => '713-878-9784',
                'fax' => '713-960-0949',
                'email' => 'akeyser@alonti.com',
                'alonti_user_id' => 103408,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 33,
                'market_id' => 1,
                'title' => 'Catering Sales Manager',
                'director' => 'Devany Florence',
                'phone' => '682-465-6685',
                'fax' => '817-877-4282',
                'email' => 'dflorence@alonti.com',
                'alonti_user_id' => 46275,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 45,
                'market_id' => 1,
                'title' => 'Catering Sales Manager',
                'director' => 'Linda Nayfa',
                'phone' => '(713] 836-8137',
                'fax' => '(214] 761-6430',
                'email' => 'lnayfa2@alonti.com',
                'alonti_user_id' => 41365,
                'created' => null,
                'modified' => '2020-05-21 06:12:26',
            ],
            [
                'id' => 48,
                'market_id' => 15,
                'title' => 'District Catering Sales Manager',
                'director' => 'Jennifer Gonzalez-',
                'phone' => '(512] 373-0221',
                'fax' => '',
                'email' => 'jgonzalezsa@alonti.com',
                'alonti_user_id' => null,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 49,
                'market_id' => 1,
                'title' => 'Catering Sales Manager',
                'director' => 'Tonya Emery',
                'phone' => '(214] 280-9352',
                'fax' => '(972] 960-9502',
                'email' => 'temery@alonti.com',
                'alonti_user_id' => 18310,
                'created' => null,
                'modified' => '2022-06-07 20:41:48',
            ],
            [
                'id' => 52,
                'market_id' => 9,
                'title' => 'Catering Sales Manager',
                'director' => 'Ashleigh Rapp',
                'phone' => '(832] 703-5712',
                'fax' => '(713] 960-0949',
                'email' => '2asrapp@alonti.com',
                'alonti_user_id' => 82194,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 61,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Sandra Huizenga',
                'phone' => '(714] 881-9379',
                'fax' => '(714] 558-9501',
                'email' => 'shuizenga@alonti.com',
                'alonti_user_id' => 66926,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 62,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Nicolle DiSimone',
                'phone' => '(562] 964-3288',
                'fax' => '(714] 373-2422',
                'email' => 'ndisimone@alonti.com',
                'alonti_user_id' => 139167,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 66,
                'market_id' => 2,
                'title' => 'District Catering Sales Manager',
                'director' => 'Thea Fellencer',
                'phone' => '(713] 878-7489',
                'fax' => '',
                'email' => 'tfellencer@alonti.com',
                'alonti_user_id' => 74831,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 69,
                'market_id' => 15,
                'title' => 'Catering Sles Manager',
                'director' => 'Andria Rodriguez',
                'phone' => '(210] 365-3419',
                'fax' => '(210] 348-6554',
                'email' => 'arodriguez@alonti.com',
                'alonti_user_id' => null,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 70,
                'market_id' => 4,
                'title' => 'Catering Sales Manager',
                'director' => 'Lauren Dessauer',
                'phone' => '(312] 852-7353',
                'fax' => '(312] 786-4666',
                'email' => 'ldessauer@alonti.com',
                'alonti_user_id' => 121329,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 74,
                'market_id' => 4,
                'title' => 'Catering Sales Manager',
                'director' => 'Jori Weissman',
                'phone' => '(312] 852-7354',
                'fax' => '(312] 786-4666',
                'email' => 'jweissman@alonti.com',
                'alonti_user_id' => 108814,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 76,
                'market_id' => 2,
                'title' => 'Catering Sales Manager',
                'director' => 'Megan McGill',
                'phone' => '(832] 703 -5712',
                'fax' => '(713]796-2300',
                'email' => 'mmcgill@alonti.com',
                'alonti_user_id' => 103287,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 79,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Terri Schaeffer',
                'phone' => '(714] 658-7743',
                'fax' => '(313] 221-2106',
                'email' => 'tschaeffer@alonti.com',
                'alonti_user_id' => 138083,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 80,
                'market_id' => 16,
                'title' => 'Assistant Catering Sales Manager',
                'director' => 'Kari Anderson',
                'phone' => '(714] 558-9500',
                'fax' => '(714] 558-9501',
                'email' => 'kanderson@alonti.com',
                'alonti_user_id' => 116711,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 81,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Jaime Cubero',
                'phone' => '(213] 842-7529',
                'fax' => '(313] 221-2106',
                'email' => 'jcubero@alonti.com',
                'alonti_user_id' => 124479,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 82,
                'market_id' => 4,
                'title' => 'Catering Sales Manager',
                'director' => 'Lainey Donash',
                'phone' => '(312] 933-1206',
                'fax' => '(312] 831-9106',
                'email' => 'ldonash@alonti.com',
                'alonti_user_id' => 139166,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 83,
                'market_id' => 2,
                'title' => 'General Manager ',
                'director' => 'Alex Waterhouse ',
                'phone' => '713-654-1856',
                'fax' => '713-654-1840',
                'email' => 'alonti18@alonti.com',
                'alonti_user_id' => 110979,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 84,
                'market_id' => 1,
                'title' => 'Catering Sales Manager',
                'director' => 'Melissa Stack',
                'phone' => '(713] 836-8137',
                'fax' => '',
                'email' => 'mstack@alonti.com',
                'alonti_user_id' => 32700,
                'created' => null,
                'modified' => '2025-06-02 13:28:16',
            ],
            [
                'id' => 89,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Darbi Loy Schennum',
                'phone' => '(310] 403-0697',
                'fax' => '(949] 586-3660',
                'email' => 'dschennum@alonti.com',
                'alonti_user_id' => 103937,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 91,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Lesley Elliott',
                'phone' => '(714] 654-4052',
                'fax' => '(714] 558-9501',
                'email' => 'lelliott@alonti.com',
                'alonti_user_id' => 106765,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 92,
                'market_id' => 2,
                'title' => 'Catering Sales Manager',
                'director' => 'Stephanie Schaefer',
                'phone' => '(281](804-8927',
                'fax' => '(713] 228-8933',
                'email' => 'shaefer@alonti.com',
                'alonti_user_id' => 47472,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 93,
                'market_id' => 9,
                'title' => 'Catering Sales Manager',
                'director' => 'Kristina George',
                'phone' => '(713] 446-6738',
                'fax' => '(713] 960-0949',
                'email' => 'kgeorge@alonti.com',
                'alonti_user_id' => 126284,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 94,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Linda Nayfa1',
                'phone' => '(713] 836-8137',
                'fax' => '(313] 221-2106',
                'email' => 'lnayfa1@alonti.com',
                'alonti_user_id' => 41365,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 97,
                'market_id' => 13,
                'title' => 'Catering Sales Manager',
                'director' => 'Julie Curtis',
                'phone' => '(512] 373-0225',
                'fax' => '(512] 614-2940',
                'email' => 'jcurtis@alonti.com',
                'alonti_user_id' => 111126,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 99,
                'market_id' => 9,
                'title' => 'Catering Sales Manager',
                'director' => 'Christine Binner',
                'phone' => '(281] 883-9325',
                'fax' => '(281] 873-7957',
                'email' => 'cbinner@alonti.com',
                'alonti_user_id' => 116438,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 100,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Danna Elias',
                'phone' => '(310] 709-1032',
                'fax' => '(313] 221-2106',
                'email' => 'delias@alonti.com',
                'alonti_user_id' => 126511,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 107,
                'market_id' => 9,
                'title' => 'Catering Sales Manager',
                'director' => 'Alex Den',
                'phone' => '(713] 757 - 2715',
                'fax' => '(281] 873-7957',
                'email' => 'aden@alonti.com',
                'alonti_user_id' => 117066,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 108,
                'market_id' => 1,
                'title' => 'Catering Sales Manager',
                'director' => 'Dina Benefield',
                'phone' => 'TBD',
                'fax' => 'TBD',
                'email' => 'dbenefield@alonti.com',
                'alonti_user_id' => 126292,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 109,
                'market_id' => 13,
                'title' => 'Catering Sales Manager',
                'director' => 'Jennifer Gonzalez',
                'phone' => '(512] 373-0221',
                'fax' => '(512] 916-8529',
                'email' => 'jgonzalez@alonti.com',
                'alonti_user_id' => 41888,
                'created' => null,
                'modified' => '2020-05-26 16:17:53',
            ],
            [
                'id' => 110,
                'market_id' => 24,
                'title' => 'Catering Sales Manager',
                'director' => 'Alyssia George',
                'phone' => '(832] 741-2598',
                'fax' => '(713] 626-0089',
                'email' => 'ageorge@alonti.com',
                'alonti_user_id' => 157633,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 112,
                'market_id' => 2,
                'title' => 'Catering Sales Manager',
                'director' => 'Beth Saunders',
                'phone' => '(832] 703-5712',
                'fax' => '(713] 654-1840',
                'email' => 'esaunders1@alonti.com',
                'alonti_user_id' => 111124,
                'created' => null,
                'modified' => '2020-05-07 16:27:22',
            ],
            [
                'id' => 113,
                'market_id' => 24,
                'title' => 'Assistant Catering Manager',
                'director' => 'Shannon Ward',
                'phone' => '(832] 754-1521',
                'fax' => '(713] 796-2300',
                'email' => 'sward@alonti.com',
                'alonti_user_id' => null,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 114,
                'market_id' => 24,
                'title' => 'Catering Sales Manager',
                'director' => 'Kristiana George',
                'phone' => '(713] 446-6738',
                'fax' => '(713] 626-0089',
                'email' => 'kgeorge@alonti.com',
                'alonti_user_id' => 126284,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 115,
                'market_id' => 9,
                'title' => 'Catering Sales Manager',
                'director' => 'DeLila Tirey',
                'phone' => '(281] 300-6029',
                'fax' => '(713] 957-3792',
                'email' => 'dtirey@alonti.com',
                'alonti_user_id' => 41702,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 116,
                'market_id' => 1,
                'title' => 'Catering Sales Manager',
                'director' => 'Christa Meroney',
                'phone' => '(817] 723-6196',
                'fax' => '(817] 335-3769',
                'email' => 'cmeroney@alonti.com',
                'alonti_user_id' => 131391,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 119,
                'market_id' => 4,
                'title' => 'Catering Sales Manager',
                'director' => 'Amanda Colver',
                'phone' => '(312] 545-1026',
                'fax' => '(312] 786-4666',
                'email' => 'acolver@alonti.com',
                'alonti_user_id' => 132373,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 120,
                'market_id' => 4,
                'title' => 'Catering Sales Manager',
                'director' => 'Allison Kubek',
                'phone' => '(312] 523-9302',
                'fax' => '(224] 653-8681',
                'email' => 'akubek@alonti.com',
                'alonti_user_id' => 133163,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 121,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Suzanne Ohman',
                'phone' => '(949] 929-5054',
                'fax' => '(949] 586-3660',
                'email' => 'sohman@alonti.com',
                'alonti_user_id' => 134055,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 123,
                'market_id' => 13,
                'title' => 'Catering Sales manager',
                'director' => 'Stacy Acosta',
                'phone' => '(512] 373-0225',
                'fax' => '(512] 916-8529',
                'email' => 'sacosta@alonti.com',
                'alonti_user_id' => 135424,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 125,
                'market_id' => 1,
                'title' => 'Catering Sales Manager',
                'director' => 'Karen Miller',
                'phone' => '(972] 505-8040',
                'fax' => '(972] 960-9502',
                'email' => 'kmiller@alonti.com',
                'alonti_user_id' => 136738,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 126,
                'market_id' => 4,
                'title' => 'Catering Sales Manager',
                'director' => 'Sarah Garcia',
                'phone' => '(312] 933-1206',
                'fax' => '(312] 831-9106',
                'email' => 'sgarcia@alonti.com',
                'alonti_user_id' => 183066,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 127,
                'market_id' => 1,
                'title' => 'Catering Sales Manager',
                'director' => 'Khalilah Waldon',
                'phone' => '(214] 405-0983',
                'fax' => '(972] 807-6464',
                'email' => 'kwaldon@alonti.com',
                'alonti_user_id' => 132288,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 129,
                'market_id' => 2,
                'title' => 'Catering Sales Manager',
                'director' => 'Katherine Easterling',
                'phone' => '(281] 779-0836',
                'fax' => '(713] 796-2300',
                'email' => 'keasterling1@alonti.com',
                'alonti_user_id' => 134915,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 130,
                'market_id' => 4,
                'title' => 'Catering Sales Manager',
                'director' => 'Carly Novoselsky',
                'phone' => '(312] 768-0784',
                'fax' => '(312] 831-9106',
                'email' => 'cnovoselsky@alonti.com',
                'alonti_user_id' => 144285,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 131,
                'market_id' => 13,
                'title' => 'Catering Sales Manager',
                'director' => 'Mary Tudyk',
                'phone' => '(210] 445-8834',
                'fax' => '(210] 826-1292',
                'email' => 'mtudyk@alonti.com',
                'alonti_user_id' => 127081,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 132,
                'market_id' => 13,
                'title' => 'Catering Sales Manager',
                'director' => 'Bianca Flores',
                'phone' => '(210] 365-3419',
                'fax' => '(210] 348-5447',
                'email' => 'bflores@alonti.com',
                'alonti_user_id' => 98738,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 134,
                'market_id' => 4,
                'title' => 'Catering Sales Manager',
                'director' => 'Heather Heagy',
                'phone' => '(312] 545-1026',
                'fax' => '(312] 786-4666',
                'email' => 'hheagy@alonti.com',
                'alonti_user_id' => 43758,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 135,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Alisha Nguyen',
                'phone' => '(714] 881-9379',
                'fax' => '(949] 586-3660',
                'email' => 'anguyen@alonti.com',
                'alonti_user_id' => 145712,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 136,
                'market_id' => 1,
                'title' => 'Catering Sales Manager',
                'director' => 'Kimberly Wright',
                'phone' => '(214] 417-4478',
                'fax' => '(214] 360-7559',
                'email' => 'kwright@alonti.com',
                'alonti_user_id' => 147187,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 137,
                'market_id' => 1,
                'title' => 'Catering Sales Manager',
                'director' => 'Lauren Stevens',
                'phone' => '(817] 723-6196',
                'fax' => '(817] 87-4282',
                'email' => 'lstevens@alonti.com',
                'alonti_user_id' => 149123,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 138,
                'market_id' => 4,
                'title' => 'Catering Sales Manager',
                'director' => 'Angie Matson',
                'phone' => '(312] 285-4383',
                'fax' => '(224] 653-8681',
                'email' => 'amatson@alonti.com',
                'alonti_user_id' => 150460,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 139,
                'market_id' => 9,
                'title' => 'Catering Sales Manager',
                'director' => 'Susan Glass',
                'phone' => '(713] 757-2715',
                'fax' => '(281] 873-7957',
                'email' => 'sglass@alonti.com',
                'alonti_user_id' => 151553,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 141,
                'market_id' => 1,
                'title' => 'Catering Sales Manager',
                'director' => 'Jamie Pritchard',
                'phone' => '(214] 564-4227',
                'fax' => '(214] 441-1021',
                'email' => 'jpritchard@alonti.com',
                'alonti_user_id' => 153015,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 142,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Gina Ivey',
                'phone' => '(323] 898-5291',
                'fax' => '(323] 221-2106',
                'email' => 'givey@alonti.com',
                'alonti_user_id' => 154372,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 143,
                'market_id' => 4,
                'title' => 'Assistant Catering Sales Manager',
                'director' => 'Kara Hoots',
                'phone' => '312-523-9203',
                'fax' => '(630] 684-0870',
                'email' => 'khoots@alonti.com',
                'alonti_user_id' => 155154,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 144,
                'market_id' => 4,
                'title' => 'Catering Sales Manager',
                'director' => 'Chris Reyes',
                'phone' => '(312] 768-0784',
                'fax' => '(312] 831-9106',
                'email' => 'creyes@alonti.com',
                'alonti_user_id' => 157099,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 148,
                'market_id' => 9,
                'title' => 'Catering Sales Manager',
                'director' => 'Stephanie Schaefer',
                'phone' => '(713] 878-7489',
                'fax' => '281-498-3033',
                'email' => 'sschaefer@alonti.com',
                'alonti_user_id' => 47472,
                'created' => null,
                'modified' => '2020-08-21 13:51:40',
            ],
            [
                'id' => 150,
                'market_id' => 1,
                'title' => 'Catering Sales Manager',
                'director' => 'Kaily Ellis',
                'phone' => '(817] 723-6196',
                'fax' => '(817] 877-4282',
                'email' => 'kellis@alonti.com',
                'alonti_user_id' => 160985,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 151,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Stacy Porras',
                'phone' => '(310] 709-1032',
                'fax' => '(313] 221-2106',
                'email' => 'sporras@alonti.com',
                'alonti_user_id' => 163014,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 152,
                'market_id' => 2,
                'title' => 'Catering Sales Manager',
                'director' => 'Kylee Leibold',
                'phone' => '(281] 779 - 0836',
                'fax' => '(713] 796 - 2300',
                'email' => 'kleibold@alonti.com',
                'alonti_user_id' => 152749,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 153,
                'market_id' => 13,
                'title' => 'Assistant Catering Sales Manager',
                'director' => 'Beverly Paulis',
                'phone' => '(512] 779-1304',
                'fax' => '(512] 916-8529',
                'email' => 'bpaulis@alonti.com',
                'alonti_user_id' => 165278,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 154,
                'market_id' => 1,
                'title' => 'Catering Sales Manager',
                'director' => 'Katherine Easterling',
                'phone' => '(972] 505-8040',
                'fax' => '(972] 960-9502',
                'email' => 'keasterling@alonti.com',
                'alonti_user_id' => 134915,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 155,
                'market_id' => 1,
                'title' => 'Assistant Catering Sales Manager',
                'director' => 'Marissa Day',
                'phone' => '(214] 223-5383',
                'fax' => '(214] 761-6430',
                'email' => 'mday@alonti.com',
                'alonti_user_id' => 165896,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 156,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Melissa Miller',
                'phone' => '(714] 881-9379',
                'fax' => '(714] 373-2422',
                'email' => 'mmiller@alonti.com',
                'alonti_user_id' => 163015,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 157,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Katie Baggett',
                'phone' => '(714] 658-7743',
                'fax' => '(323] 231-2429',
                'email' => 'kbaggett@alonti.com',
                'alonti_user_id' => 169718,
                'created' => null,
                'modified' => '2024-07-10 21:53:44',
            ],
            [
                'id' => 158,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Cristina Felix',
                'phone' => '(323] 898-5291',
                'fax' => '',
                'email' => 'cfelix@alonti.com',
                'alonti_user_id' => 169717,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 159,
                'market_id' => 1,
                'title' => 'Assistant Catering Sales Manager',
                'director' => 'Margaret Traster',
                'phone' => '(214] 405-0983',
                'fax' => '(972] 807-6464',
                'email' => 'matraster@alonti.com',
                'alonti_user_id' => 170772,
                'created' => null,
                'modified' => '2021-01-04 17:14:02',
            ],
            [
                'id' => 160,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Jennifer Kelley',
                'phone' => '(714] 658-7443',
                'fax' => '(313] 221-2106',
                'email' => 'jkelley@alonti.com',
                'alonti_user_id' => 120054,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 161,
                'market_id' => 2,
                'title' => 'Catering Sales Manager',
                'director' => 'Trina Cameron-Rothman',
                'phone' => '(281] 779 – 0836',
                'fax' => '(713] 796 – 2300',
                'email' => 'trothman2@alonti.com',
                'alonti_user_id' => 156791,
                'created' => null,
                'modified' => '2020-05-07 16:29:52',
            ],
            [
                'id' => 163,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Kaylee Tran',
                'phone' => '(310] 403-0697',
                'fax' => '(949] 586-3660',
                'email' => 'ktran@alonti.com',
                'alonti_user_id' => 169719,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 164,
                'market_id' => 1,
                'title' => 'Catering Sales Manager',
                'director' => 'Carla Horton',
                'phone' => '(214] 405-0983',
                'fax' => '(972] 807-6464',
                'email' => 'chorton@alonti.com',
                'alonti_user_id' => 175701,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 165,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Mari Nakaura',
                'phone' => '  (714] 658-7743',
                'fax' => '(323] 231-2429',
                'email' => 'mnakaura@alonti.com',
                'alonti_user_id' => 179632,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 166,
                'market_id' => 1,
                'title' => 'Assistant Catering Sales Manager',
                'director' => 'Emilie Bedell',
                'phone' => '(214] 761-3120',
                'fax' => '( 241] 761-6430',
                'email' => 'ebedell@alonti.com',
                'alonti_user_id' => 180276,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 167,
                'market_id' => 4,
                'title' => 'Catering Sales Manager',
                'director' => 'Kaitlynn Tolleson',
                'phone' => '(630] 666-0701',
                'fax' => '(312] 831-9106',
                'email' => 'ktolleson@alonti.com',
                'alonti_user_id' => 175988,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 168,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Adrienne Neumeyer',
                'phone' => '(562] 964-3288',
                'fax' => '(714] 373-2211',
                'email' => 'aneumeyer@alonti.com',
                'alonti_user_id' => 182426,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 169,
                'market_id' => 1,
                'title' => 'Catering Sales Manager',
                'director' => 'Chelsea Selvadurai',
                'phone' => '(817] 723-6196',
                'fax' => '(817] 537-2443',
                'email' => 'cselvadurai@alonti.com',
                'alonti_user_id' => 182526,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 170,
                'market_id' => 1,
                'title' => 'Catering Sales Manager',
                'director' => 'Melissa Perry',
                'phone' => '(972] 505-8040',
                'fax' => '(972] -954-7229',
                'email' => 'mperry@alonti.com',
                'alonti_user_id' => 182067,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 171,
                'market_id' => 9,
                'title' => 'Catering Sales Manager',
                'director' => 'Jillian Jordan',
                'phone' => '(713] 878-9784',
                'fax' => '(713] 585-0698',
                'email' => 'jjordan@alonti.com',
                'alonti_user_id' => 182161,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 172,
                'market_id' => 2,
                'title' => 'Assistant Catering Sales Manager',
                'director' => 'Meagan Kerr',
                'phone' => '(713] 757-2715',
                'fax' => '(713] 422-3347',
                'email' => 'mkerr=@alonti.com',
                'alonti_user_id' => 165903,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 173,
                'market_id' => 16,
                'title' => 'Assistant Catering Sales Manager',
                'director' => 'Claudia Garcia',
                'phone' => '(213] 804-2083',
                'fax' => '',
                'email' => 'cgarcia@alonti.com',
                'alonti_user_id' => 186171,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 174,
                'market_id' => 4,
                'title' => 'Assistant Catering Sales Manager',
                'director' => 'Amy Pride',
                'phone' => '(630] 666-0701',
                'fax' => '(312] 786-4666',
                'email' => 'apride@alonti.com',
                'alonti_user_id' => 186441,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 175,
                'market_id' => 13,
                'title' => 'Assistant Catering Sales Manager',
                'director' => 'Lacey McTyre',
                'phone' => '(512] 779-1304',
                'fax' => '(512] 916-8529',
                'email' => 'lmctyre@alonti.com',
                'alonti_user_id' => 189017,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 176,
                'market_id' => 2,
                'title' => 'Assistant Catering Sales Manager',
                'director' => 'Lori Alfano',
                'phone' => '(281] 995-9069',
                'fax' => '(713] 654-1840',
                'email' => 'lalfano@alonti.com',
                'alonti_user_id' => 186067,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 177,
                'market_id' => 9,
                'title' => 'Catering Sales Manager',
                'director' => 'Krystal Woodward',
                'phone' => '(713] 422-3347',
                'fax' => '(281] 741-8694',
                'email' => 'kwoodward@alonti.com',
                'alonti_user_id' => 186980,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 178,
                'market_id' => 4,
                'title' => 'Catering Sales Manager',
                'director' => 'Lori Knill',
                'phone' => '(312] 852-7353',
                'fax' => '(312] 831-9104',
                'email' => 'lknill@alonti.com',
                'alonti_user_id' => 190143,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 180,
                'market_id' => 9,
                'title' => 'Catering Sales Manager',
                'director' => 'Meagan Kerr',
                'phone' => '(713] 422-3347',
                'fax' => '',
                'email' => 'mkerr@alonti.com',
                'alonti_user_id' => 165903,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 181,
                'market_id' => 1,
                'title' => 'Assistant Catering Sales Manager',
                'director' => 'Lyndell Massengale',
                'phone' => '(214] 417-4478',
                'fax' => '(972] 960-9502',
                'email' => 'lmassengale2@alonti.com',
                'alonti_user_id' => 190275,
                'created' => null,
                'modified' => '2020-11-10 21:02:37',
            ],
            [
                'id' => 182,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Kate Granger',
                'phone' => '(714] 255-8469',
                'fax' => '',
                'email' => 'kgranger@alonti.com',
                'alonti_user_id' => 190665,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 183,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Zenda Iannetti',
                'phone' => '(949] 929-5054',
                'fax' => '(714] 654-2026 ',
                'email' => 'ziannetti@alonti.com',
                'alonti_user_id' => 190857,
                'created' => null,
                'modified' => '2023-03-07 17:56:49',
            ],
            [
                'id' => 184,
                'market_id' => 4,
                'title' => 'Assistant Catering Sales Manager',
                'director' => 'Allison Kubek',
                'phone' => '(312] 890-1017',
                'fax' => '(630] 541-7199',
                'email' => 'htinucci1@alonti.com',
                'alonti_user_id' => 133163,
                'created' => null,
                'modified' => '2024-06-17 18:53:28',
            ],
            [
                'id' => 185,
                'market_id' => 9,
                'title' => 'Catering Sales Manager',
                'director' => 'Melyssa Andrews',
                'phone' => '(713] 757-2715',
                'fax' => '(832] 585-0698',
                'email' => 'mandrews@alonti.com',
                'alonti_user_id' => 58161,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 186,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Linda Nayfa',
                'phone' => '(714] 881-9379',
                'fax' => '(714] 373-2422',
                'email' => 'lnayfa3@alonti.com',
                'alonti_user_id' => 41365,
                'created' => null,
                'modified' => '2020-05-26 16:29:52',
            ],
            [
                'id' => 187,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Kendall Koehler',
                'phone' => '(310] 709-0237',
                'fax' => '(424] 326-9012',
                'email' => 'kkoehler@alonti.com',
                'alonti_user_id' => 193356,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 188,
                'market_id' => 9,
                'title' => 'Assistant Catering Sales Manager',
                'director' => 'Elizabeth Rosinke',
                'phone' => '(832] 741-2598',
                'fax' => '',
                'email' => 'erosinke@alonti.com',
                'alonti_user_id' => 191093,
                'created' => null,
                'modified' => null,
            ],
            [
                'id' => 189,
                'market_id' => 9,
                'title' => 'Catering Sales Manager',
                'director' => 'Beth Saunders',
                'phone' => '(832] 703-5712',
                'fax' => '(713] 796-2300',
                'email' => 'esaunders@alonti.com',
                'alonti_user_id' => 111124,
                'created' => '2020-05-07 16:28:14',
                'modified' => '2020-05-07 16:28:14',
            ],
            [
                'id' => 190,
                'market_id' => 1,
                'title' => 'Catering Sales Manager',
                'director' => 'Linda Nayfa',
                'phone' => '832-936-2254',
                'fax' => '',
                'email' => 'lnayfa@alonti.com',
                'alonti_user_id' => 41365,
                'created' => '2020-05-20 14:08:13',
                'modified' => '2025-06-02 13:27:38',
            ],
            [
                'id' => 192,
                'market_id' => 4,
                'title' => 'Catering Sales Manager',
                'director' => 'Anthony Daccardo',
                'phone' => '312-340-1373',
                'fax' => '',
                'email' => 'adaccardo@alonti.com',
                'alonti_user_id' => 201437,
                'created' => '2021-06-28 00:31:46',
                'modified' => '2021-06-28 00:31:46',
            ],
            [
                'id' => 193,
                'market_id' => 9,
                'title' => 'Catering Sales Manager',
                'director' => 'Lacey Bracken',
                'phone' => '(281] 779-0836',
                'fax' => '',
                'email' => 'lbracken@alonti.com',
                'alonti_user_id' => 155965,
                'created' => '2021-07-23 18:36:47',
                'modified' => '2021-07-23 18:36:47',
            ],
            [
                'id' => 194,
                'market_id' => 9,
                'title' => 'Catering Sales Manager',
                'director' => 'Denise Shaw',
                'phone' => '(713] 757-2715 ',
                'fax' => '',
                'email' => 'dshaw@alonti.com',
                'alonti_user_id' => 203264,
                'created' => '2021-08-30 20:28:31',
                'modified' => '2022-10-17 13:57:57',
            ],
            [
                'id' => 195,
                'market_id' => 4,
                'title' => 'Catering Sales Manager',
                'director' => 'Nycole Stoudt',
                'phone' => '(312] 975-1432',
                'fax' => '',
                'email' => 'nstoudt@alonti.com',
                'alonti_user_id' => 203394,
                'created' => '2022-01-03 14:51:44',
                'modified' => '2022-01-03 14:51:44',
            ],
            [
                'id' => 196,
                'market_id' => 1,
                'title' => 'Catering Sales Manager',
                'director' => 'Erin Woolridge',
                'phone' => '682-465-6685',
                'fax' => '',
                'email' => 'ewoolridge1@alonti.com',
                'alonti_user_id' => 206012,
                'created' => '2022-01-10 16:03:38',
                'modified' => '2022-01-21 22:17:18',
            ],
            [
                'id' => 198,
                'market_id' => 16,
                'title' => 'Assistant Catering Sales Manager',
                'director' => 'Lindsey Collins',
                'phone' => '(323] 231-2427',
                'fax' => '',
                'email' => 'lcollins@alonti.com',
                'alonti_user_id' => 207593,
                'created' => '2022-03-23 16:32:28',
                'modified' => '2022-03-23 16:32:28',
            ],
            [
                'id' => 199,
                'market_id' => 16,
                'title' => 'Assistant General Manager',
                'director' => 'Carlos Quiroz',
                'phone' => '949-586-3600',
                'fax' => '',
                'email' => 'alonti72@alonti.com',
                'alonti_user_id' => 208040,
                'created' => '2022-04-05 13:25:44',
                'modified' => '2022-04-05 13:25:44',
            ],
            [
                'id' => 200,
                'market_id' => 1,
                'title' => 'Catering Sales Manager',
                'director' => 'Sorida Atnip',
                'phone' => '123-123-1234',
                'fax' => '',
                'email' => 'satnip@alonti.com',
                'alonti_user_id' => 209168,
                'created' => '2022-05-09 20:26:12',
                'modified' => '2025-04-07 21:02:53',
            ],
            [
                'id' => 201,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Lawrence Scorca',
                'phone' => '(213] 842-7529',
                'fax' => '',
                'email' => 'lscorca@alonti.com',
                'alonti_user_id' => 212785,
                'created' => '2022-09-21 21:15:56',
                'modified' => '2023-02-24 20:23:27',
            ],
            [
                'id' => 202,
                'market_id' => 9,
                'title' => 'Catering Sales Manager',
                'director' => 'Peter Schnellhardt',
                'phone' => '(713] 422-3347',
                'fax' => '',
                'email' => 'peters@alonti.com',
                'alonti_user_id' => 210473,
                'created' => '2022-10-17 13:56:50',
                'modified' => '2022-10-17 13:56:50',
            ],
            [
                'id' => 203,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Katie Kelton',
                'phone' => '(949] 929-5054',
                'fax' => '',
                'email' => 'kkelton@alonti.com',
                'alonti_user_id' => 215128,
                'created' => '2022-12-14 15:20:42',
                'modified' => '2022-12-14 16:26:57',
            ],
            [
                'id' => 204,
                'market_id' => 13,
                'title' => 'Assistant Catering Sales Manager',
                'director' => 'Karlie Scherff',
                'phone' => '123-123-1234',
                'fax' => '',
                'email' => 'kscherff@alonti.com',
                'alonti_user_id' => 215304,
                'created' => '2023-01-04 16:54:26',
                'modified' => '2023-01-04 16:54:26',
            ],
            [
                'id' => 206,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Kalyn Brown',
                'phone' => '(714] 981-1470',
                'fax' => '',
                'email' => 'kbrown@alonti.com',
                'alonti_user_id' => 216609,
                'created' => '2023-02-21 17:51:06',
                'modified' => '2024-07-01 21:06:01',
            ],
            [
                'id' => 207,
                'market_id' => 4,
                'title' => 'Assistant Catering Sales Manager',
                'director' => 'Kayla Scharboneau',
                'phone' => '123-123-1234',
                'fax' => '',
                'email' => 'kscharboneau@alonti.com',
                'alonti_user_id' => 217713,
                'created' => '2023-03-31 15:50:00',
                'modified' => '2023-03-31 15:50:00',
            ],
            [
                'id' => 208,
                'market_id' => 9,
                'title' => 'Catering Sales Manager',
                'director' => 'Tiffany Gulley',
                'phone' => '281-779-0836',
                'fax' => '',
                'email' => 'tgulley@alonti.com',
                'alonti_user_id' => 218385,
                'created' => '2023-04-24 21:05:23',
                'modified' => '2025-07-09 21:42:29',
            ],
            [
                'id' => 209,
                'market_id' => 9,
                'title' => 'Regional Manager',
                'director' => 'Heath McKinney',
                'phone' => '123-123-1234',
                'fax' => '',
                'email' => 'hmckinney@alonti.com',
                'alonti_user_id' => 111127,
                'created' => '2023-05-10 17:08:04',
                'modified' => '2023-05-10 17:08:04',
            ],
            [
                'id' => 210,
                'market_id' => 13,
                'title' => 'Regional Manager',
                'director' => 'Heath McKinney1',
                'phone' => 123,
                'fax' => '',
                'email' => '123@alonti.com',
                'alonti_user_id' => 44255,
                'created' => '2023-05-10 17:13:23',
                'modified' => '2023-05-10 17:13:23',
            ],
            [
                'id' => 211,
                'market_id' => 4,
                'title' => 'regional manager',
                'director' => 'Eddie OuilleCHI',
                'phone' => '123-123-1234',
                'fax' => '',
                'email' => 'eouillechi@alonti.com',
                'alonti_user_id' => 110085,
                'created' => '2023-05-10 17:15:35',
                'modified' => '2023-05-10 17:15:35',
            ],
            [
                'id' => 212,
                'market_id' => 16,
                'title' => 'district manager',
                'director' => 'John Villarreal1',
                'phone' => '123-123-1234',
                'fax' => '',
                'email' => '1@alonti.com',
                'alonti_user_id' => 57657,
                'created' => '2023-05-10 17:21:30',
                'modified' => '2023-05-10 17:21:30',
            ],
            [
                'id' => 213,
                'market_id' => 16,
                'title' => 'regional manger',
                'director' => 'Eddie OuilleCal',
                'phone' => '123-123-1234',
                'fax' => '',
                'email' => '2@alonti.com',
                'alonti_user_id' => 113175,
                'created' => '2023-05-10 17:22:21',
                'modified' => '2023-05-10 17:22:21',
            ],
            [
                'id' => 214,
                'market_id' => 1,
                'title' => 'D.O.',
                'director' => 'Nick Everitt',
                'phone' => '321-654-6877',
                'fax' => '',
                'email' => '5@alonti.com',
                'alonti_user_id' => 6369,
                'created' => '2023-05-10 17:25:37',
                'modified' => '2023-05-10 17:25:37',
            ],
            [
                'id' => 215,
                'market_id' => 1,
                'title' => 'district manager',
                'director' => 'Chris Malloy',
                'phone' => 521,
                'fax' => '',
                'email' => 'chris@alonti.com',
                'alonti_user_id' => 129339,
                'created' => '2023-05-10 17:26:15',
                'modified' => '2023-05-10 17:26:15',
            ],
            [
                'id' => 216,
                'market_id' => 9,
                'title' => 'regional manager',
                'director' => 'Heath McKinney1',
                'phone' => '321-321-321',
                'fax' => '',
                'email' => '34@alonti.com',
                'alonti_user_id' => 44255,
                'created' => '2023-05-10 17:30:10',
                'modified' => '2023-05-10 17:30:10',
            ],
            [
                'id' => 217,
                'market_id' => 9,
                'title' => 'ads',
                'director' => 'Heath McKinney1',
                'phone' => 'asd',
                'fax' => '',
                'email' => 'asd@alonti.com',
                'alonti_user_id' => 44255,
                'created' => '2023-05-10 17:30:27',
                'modified' => '2023-05-10 17:30:27',
            ],
            [
                'id' => 218,
                'market_id' => 9,
                'title' => 'asd',
                'director' => 'Michael Underwood1',
                'phone' => 'asd',
                'fax' => '',
                'email' => 'fds@alonti.com',
                'alonti_user_id' => 145309,
                'created' => '2023-05-10 17:30:46',
                'modified' => '2023-05-10 17:30:46',
            ],
            [
                'id' => 219,
                'market_id' => 1,
                'title' => 'Assistant Catering Sales Manager',
                'director' => 'Michael Martin',
                'phone' => '214-405-0983 ',
                'fax' => '',
                'email' => 'mmartin@alonti.com',
                'alonti_user_id' => 219525,
                'created' => '2023-06-07 18:42:41',
                'modified' => '2023-06-07 20:02:26',
            ],
            [
                'id' => 220,
                'market_id' => 1,
                'title' => 'Catering Sales Manager',
                'director' => 'Jaylan Evans',
                'phone' => '(469] 223-0498',
                'fax' => '',
                'email' => 'jevans@alonti.com',
                'alonti_user_id' => 219749,
                'created' => '2023-06-20 13:31:45',
                'modified' => '2025-06-03 15:32:05',
            ],
            [
                'id' => 221,
                'market_id' => 1,
                'title' => 'Catering Assistant',
                'director' => 'Sierra Sailer',
                'phone' => '123-123-1234',
                'fax' => '',
                'email' => 'ssailer@alonti.com',
                'alonti_user_id' => 220829,
                'created' => '2023-08-04 19:23:20',
                'modified' => '2023-08-04 19:23:20',
            ],
            [
                'id' => 222,
                'market_id' => 4,
                'title' => 'Catering Sales Manager',
                'director' => 'Kayla Test Test Chicago',
                'phone' => '123-123-1234',
                'fax' => '',
                'email' => 'ktest@alonti.com',
                'alonti_user_id' => 221332,
                'created' => '2023-08-24 20:15:03',
                'modified' => '2023-08-24 20:15:03',
            ],
            [
                'id' => 223,
                'market_id' => 4,
                'title' => 'Assistant Catering Sales Manager',
                'director' => 'Kayla Scharboneau74',
                'phone' => '312-975-1432',
                'fax' => '',
                'email' => 'kscharboneau1@alonti.com',
                'alonti_user_id' => 221332,
                'created' => '2023-09-12 17:43:52',
                'modified' => '2023-09-12 17:43:52',
            ],
            [
                'id' => 224,
                'market_id' => 9,
                'title' => 'Catering Sales Manager',
                'director' => 'Lyndell Massengale',
                'phone' => '(832] 703-5712',
                'fax' => '',
                'email' => 'lmassengale1@alonti.com',
                'alonti_user_id' => 190275,
                'created' => '2023-10-11 21:33:44',
                'modified' => '2023-10-11 21:33:44',
            ],
            [
                'id' => 225,
                'market_id' => 13,
                'title' => 'Assistant Catering Sales Manager',
                'director' => 'Caroline Stanton',
                'phone' => '123-123-1234',
                'fax' => '',
                'email' => 'cstanton@alonti.com',
                'alonti_user_id' => 222829,
                'created' => '2023-10-23 15:32:45',
                'modified' => '2023-10-23 15:32:45',
            ],
            [
                'id' => 226,
                'market_id' => 13,
                'title' => 'Regional Manager',
                'director' => 'Christopher Malloy',
                'phone' => 123123123,
                'fax' => '',
                'email' => 'cmalloy@alonti.com',
                'alonti_user_id' => 221750,
                'created' => '2023-10-24 15:47:10',
                'modified' => '2023-10-24 15:47:10',
            ],
            [
                'id' => 227,
                'market_id' => 16,
                'title' => 'Regional manager',
                'director' => 'Christopher Malloy',
                'phone' => 123123123,
                'fax' => '',
                'email' => 'cmalloy1@alonti.com',
                'alonti_user_id' => 221750,
                'created' => '2023-10-24 15:48:49',
                'modified' => '2023-10-24 15:48:49',
            ],
            [
                'id' => 228,
                'market_id' => 1,
                'title' => 'regional manager',
                'director' => 'Christopher Malloy',
                'phone' => 123123123,
                'fax' => '',
                'email' => 'cmalloy2@alonti.com',
                'alonti_user_id' => 221750,
                'created' => '2023-10-24 15:53:52',
                'modified' => '2023-10-24 15:53:52',
            ],
            [
                'id' => 229,
                'market_id' => 13,
                'title' => 'District Manager',
                'director' => 'Eddie Robledo',
                'phone' => 123123123,
                'fax' => '',
                'email' => 'erobledo@alonti.com',
                'alonti_user_id' => 220726,
                'created' => '2023-10-24 15:56:02',
                'modified' => '2023-10-24 15:56:02',
            ],
            [
                'id' => 231,
                'market_id' => 1,
                'title' => 'General Manager',
                'director' => 'Greg Meyer DFW',
                'phone' => '123-123-1234',
                'fax' => '',
                'email' => 'gmeyer@alonti.com',
                'alonti_user_id' => 222662,
                'created' => '2024-03-18 17:23:15',
                'modified' => '2024-03-18 17:23:15',
            ],
            [
                'id' => 232,
                'market_id' => 4,
                'title' => 'Catering Sales Manager',
                'director' => 'Ella  Gergely',
                'phone' => '(312] 868-3467',
                'fax' => '',
                'email' => 'egergely@alonti.com',
                'alonti_user_id' => 215657,
                'created' => '2024-05-01 13:46:15',
                'modified' => '2025-04-25 12:02:57',
            ],
            [
                'id' => 233,
                'market_id' => 13,
                'title' => 'Sales Assistant',
                'director' => 'Jamie Hernandez',
                'phone' => '123-123-1234',
                'fax' => '',
                'email' => 'jhernandez@alonti.com',
                'alonti_user_id' => 228067,
                'created' => '2024-06-12 15:04:08',
                'modified' => '2024-06-12 15:04:08',
            ],
            [
                'id' => 234,
                'market_id' => 4,
                'title' => 'Catering Sales Manager',
                'director' => 'Hope Tinucci_Old Profile',
                'phone' => '(312] 890-1017',
                'fax' => '',
                'email' => 'htinucci2@alonti.com',
                'alonti_user_id' => 180485,
                'created' => '2024-06-17 19:02:06',
                'modified' => '2024-06-17 19:08:14',
            ],
            [
                'id' => 235,
                'market_id' => 4,
                'title' => 'Catering Sales Manager',
                'director' => 'Hope Tinucci',
                'phone' => '(312] 890-1017',
                'fax' => '',
                'email' => 'htinucci@alonti.com',
                'alonti_user_id' => 228136,
                'created' => '2024-06-17 19:09:52',
                'modified' => '2024-06-17 19:09:52',
            ],
            [
                'id' => 236,
                'market_id' => 1,
                'title' => 'Sales Assistant',
                'director' => 'Sheba Harris',
                'phone' => '(972] 960-9740',
                'fax' => '',
                'email' => 'sharris@alonti.com',
                'alonti_user_id' => 228721,
                'created' => '2024-07-22 20:37:15',
                'modified' => '2024-07-22 20:37:15',
            ],
            [
                'id' => 237,
                'market_id' => 1,
                'title' => 'Sales Assistant',
                'director' => 'Kasey Meyer',
                'phone' => '(214] 564-4227',
                'fax' => '',
                'email' => 'kmeyer@alonti.com',
                'alonti_user_id' => 229091,
                'created' => '2024-08-08 12:28:05',
                'modified' => '2024-08-08 12:28:05',
            ],
            [
                'id' => 239,
                'market_id' => 17,
                'title' => 'Catering Sales Manager',
                'director' => 'Katrina Smith-May',
                'phone' => '(404] 259-0468',
                'fax' => '',
                'email' => 'ksmithmay@alonti.com',
                'alonti_user_id' => 238488,
                'created' => '2024-09-16 13:31:01',
                'modified' => '2025-10-20 13:57:03',
            ],
            [
                'id' => 240,
                'market_id' => 1,
                'title' => 'Sales Assistant',
                'director' => 'Gabby Aguilar',
                'phone' => '123-123-1324',
                'fax' => '',
                'email' => 'gaguilar@alonti.com',
                'alonti_user_id' => 229890,
                'created' => '2024-09-16 19:41:34',
                'modified' => '2024-09-16 19:41:34',
            ],
            [
                'id' => 241,
                'market_id' => 9,
                'title' => 'Catering Sales Manager',
                'director' => 'James  Repperger ',
                'phone' => '832-703-5712',
                'fax' => '',
                'email' => 'jrepperger@alonti.com',
                'alonti_user_id' => 223985,
                'created' => '2024-10-10 15:45:49',
                'modified' => '2025-05-21 20:06:35',
            ],
            [
                'id' => 242,
                'market_id' => 16,
                'title' => 'Sales Assistant',
                'director' => 'Gladys Lopez',
                'phone' => '123-123-1234',
                'fax' => '',
                'email' => 'glopez@alonti.com',
                'alonti_user_id' => 230559,
                'created' => '2024-10-11 19:21:14',
                'modified' => '2024-10-11 19:21:14',
            ],
            [
                'id' => 244,
                'market_id' => 9,
                'title' => 'Catering Sales Manager',
                'director' => 'Jennifer Davis',
                'phone' => '(281] 804-8927',
                'fax' => '',
                'email' => 'jdavis@alonti.com',
                'alonti_user_id' => 231140,
                'created' => '2024-11-04 17:03:57',
                'modified' => '2025-01-23 20:52:10',
            ],
            [
                'id' => 245,
                'market_id' => 17,
                'title' => 'Sales Assistant',
                'director' => 'Paul Gallois',
                'phone' => '123-123-1234',
                'fax' => '',
                'email' => 'pgallois@alonti.com',
                'alonti_user_id' => 230775,
                'created' => '2025-03-27 14:14:24',
                'modified' => '2025-07-01 18:44:02',
            ],
            [
                'id' => 246,
                'market_id' => 16,
                'title' => 'Catering Sales Manager',
                'director' => 'Damien Lee',
                'phone' => '(714] 981-1470',
                'fax' => '',
                'email' => 'dlee@alonti.com',
                'alonti_user_id' => 234444,
                'created' => '2025-04-04 12:27:49',
                'modified' => '2026-01-16 13:34:04',
            ],
            [
                'id' => 247,
                'market_id' => 1,
                'title' => 'Sales Assistant',
                'director' => 'Kira Vickers',
                'phone' => '123-123-1234',
                'fax' => '',
                'email' => 'kvickers@alonti.com',
                'alonti_user_id' => 228721,
                'created' => '2025-08-05 20:29:57',
                'modified' => '2025-08-05 20:29:57',
            ],
            [
                'id' => 248,
                'market_id' => 9,
                'title' => 'Sales Assistant',
                'director' => 'Krystle Valdez',
                'phone' => '123-123-1234',
                'fax' => '',
                'email' => 'kvaldez@alonti.com',
                'alonti_user_id' => 237412,
                'created' => '2025-08-29 20:58:15',
                'modified' => '2025-08-29 20:58:34',
            ],
            [
                'id' => 249,
                'market_id' => 9,
                'title' => 'Sales Assistant',
                'director' => 'Celia  Aguilar',
                'phone' => '123-123-1234',
                'fax' => '',
                'email' => 'cAguilar@alonti.com',
                'alonti_user_id' => 6390,
                'created' => '2025-10-02 00:57:24',
                'modified' => '2025-10-02 00:57:24',
            ],
            [
                'id' => 250,
                'market_id' => 13,
                'title' => 'Catering Sales Manager',
                'director' => 'Richard Valdez',
                'phone' => '(210] 365-3419',
                'fax' => '',
                'email' => 'rvaldez@alonti.com',
                'alonti_user_id' => 238891,
                'created' => '2025-11-04 21:44:03',
                'modified' => '2026-01-06 16:58:19',
            ],
        ];

        DB::table('directors')->insert($dataTables);
    }
}
