<?php

namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistrictsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables --limit=500
         */
        $dataTables = [
            [
                'id' => 1,
                'name' => 'Houston Downtown',
                'sequence' => 1,
                'filtered_dwp' => 38408,
                'market_id' => 9,
                'admin_id' => null,
                'catering_manager' => 241,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2025-05-20 20:20:08',
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'name' => 'Houston East',
                'sequence' => 2,
                'filtered_dwp' => 132304,
                'market_id' => 9,
                'admin_id' => null,
                'catering_manager' => 241,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2025-05-20 20:20:13',
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'name' => 'Houston West',
                'sequence' => 7,
                'filtered_dwp' => 121301,
                'market_id' => 9,
                'admin_id' => null,
                'catering_manager' => 202,
                'assistant_catering_manager' => 248,
                'created_at' => null,
                'updated_at' => '2025-08-29 20:59:08',
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'name' => 'Dallas North',
                'sequence' => 8,
                'filtered_dwp' => 242076,
                'market_id' => 1,
                'admin_id' => null,
                'catering_manager' => 49,
                'assistant_catering_manager' => 84,
                'created_at' => null,
                'updated_at' => '2025-06-02 13:31:38',
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'name' => 'Dallas',
                'sequence' => 9,
                'filtered_dwp' => 152553,
                'market_id' => 1,
                'admin_id' => null,
                'catering_manager' => 84,
                'assistant_catering_manager' => 240,
                'created_at' => null,
                'updated_at' => '2025-05-22 18:16:49',
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'name' => 'Fort Worth',
                'sequence' => 11,
                'filtered_dwp' => 125548,
                'market_id' => 1,
                'admin_id' => null,
                'catering_manager' => 141,
                'assistant_catering_manager' => 220,
                'created_at' => null,
                'updated_at' => '2024-05-30 17:29:27',
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'name' => 'Chicago West Loop',
                'sequence' => 14,
                'filtered_dwp' => 115043,
                'market_id' => 4,
                'admin_id' => null,
                'catering_manager' => 120,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2022-03-16 13:28:46',
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'name' => 'Chicago Downtown',
                'sequence' => 16,
                'filtered_dwp' => 241524,
                'market_id' => 4,
                'admin_id' => null,
                'catering_manager' => 134,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2022-02-09 21:25:04',
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'name' => 'Houston Northwest',
                'sequence' => 17,
                'filtered_dwp' => 173887,
                'market_id' => 9,
                'admin_id' => null,
                'catering_manager' => 107,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2022-11-17 13:17:06',
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'name' => 'Las Colinas',
                'sequence' => 10,
                'filtered_dwp' => 149959,
                'market_id' => 1,
                'admin_id' => null,
                'catering_manager' => 200,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2025-05-22 18:17:19',
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'name' => 'Lisle',
                'sequence' => 18,
                'filtered_dwp' => 217997,
                'market_id' => 4,
                'admin_id' => null,
                'catering_manager' => 184,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2021-12-29 15:53:10',
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'name' => 'Houston Medical Center',
                'sequence' => 4,
                'filtered_dwp' => 143111,
                'market_id' => 9,
                'admin_id' => null,
                'catering_manager' => 208,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2025-09-15 14:06:55',
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'name' => 'Houston North Closed Sales Area',
                'sequence' => 19,
                'filtered_dwp' => 149031,
                'market_id' => 9,
                'admin_id' => null,
                'catering_manager' => 107,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2022-11-17 13:24:04',
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'name' => 'Austin Central',
                'sequence' => 20,
                'filtered_dwp' => 167249,
                'market_id' => 13,
                'admin_id' => null,
                'catering_manager' => 109,
                'assistant_catering_manager' => 225,
                'created_at' => null,
                'updated_at' => '2023-10-23 15:33:11',
                'deleted_at' => null,
            ],
            [
                'id' => 17,
                'name' => 'Austin North',
                'sequence' => 21,
                'filtered_dwp' => 120544,
                'market_id' => 13,
                'admin_id' => null,
                'catering_manager' => 123,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2023-01-04 17:13:15',
                'deleted_at' => null,
            ],
            [
                'id' => 18,
                'name' => 'Chicago North',
                'sequence' => 22,
                'filtered_dwp' => 215913,
                'market_id' => 4,
                'admin_id' => null,
                'catering_manager' => 232,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2025-04-24 20:45:14',
                'deleted_at' => null,
            ],
            [
                'id' => 20,
                'name' => 'San Antonio - East',
                'sequence' => 12,
                'filtered_dwp' => 181823,
                'market_id' => 13,
                'admin_id' => null,
                'catering_manager' => 131,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2021-12-28 21:45:51',
                'deleted_at' => null,
            ],
            [
                'id' => 21,
                'name' => 'Houston North',
                'sequence' => 23,
                'filtered_dwp' => 108338,
                'market_id' => 9,
                'admin_id' => null,
                'catering_manager' => 194,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2022-11-17 13:24:16',
                'deleted_at' => null,
            ],
            [
                'id' => 22,
                'name' => 'Houston Southwest',
                'sequence' => 24,
                'filtered_dwp' => 133562,
                'market_id' => 9,
                'admin_id' => null,
                'catering_manager' => 107,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2022-11-17 13:17:00',
                'deleted_at' => null,
            ],
            [
                'id' => 23,
                'name' => 'Chicago Northwest Suburban',
                'sequence' => 25,
                'filtered_dwp' => 301401,
                'market_id' => 4,
                'admin_id' => null,
                'catering_manager' => 192,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2022-02-09 21:48:13',
                'deleted_at' => null,
            ],
            [
                'id' => 24,
                'name' => 'Houston Downtown - C',
                'sequence' => 3,
                'filtered_dwp' => 38408,
                'market_id' => null,
                'admin_id' => null,
                'catering_manager' => null,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 25,
                'name' => 'Dallas NE',
                'sequence' => 26,
                'filtered_dwp' => 223919,
                'market_id' => 1,
                'admin_id' => null,
                'catering_manager' => 190,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2021-12-29 15:57:46',
                'deleted_at' => null,
            ],
            [
                'id' => 26,
                'name' => 'San Antonio',
                'sequence' => 13,
                'filtered_dwp' => 169277,
                'market_id' => 13,
                'admin_id' => null,
                'catering_manager' => 250,
                'assistant_catering_manager' => 131,
                'created_at' => null,
                'updated_at' => '2025-11-04 21:44:39',
                'deleted_at' => null,
            ],
            [
                'id' => 28,
                'name' => 'Anaheim',
                'sequence' => 28,
                'filtered_dwp' => 261188,
                'market_id' => 16,
                'admin_id' => null,
                'catering_manager' => 206,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2025-01-15 22:08:32',
                'deleted_at' => null,
            ],
            [
                'id' => 29,
                'name' => 'Chicago West',
                'sequence' => 30,
                'filtered_dwp' => 229118,
                'market_id' => 4,
                'admin_id' => null,
                'catering_manager' => 74,
                'assistant_catering_manager' => 207,
                'created_at' => null,
                'updated_at' => '2024-05-22 12:31:56',
                'deleted_at' => null,
            ],
            [
                'id' => 30,
                'name' => 'Chicago South',
                'sequence' => 31,
                'filtered_dwp' => 168531,
                'market_id' => 4,
                'admin_id' => null,
                'catering_manager' => 74,
                'assistant_catering_manager' => 207,
                'created_at' => null,
                'updated_at' => '2023-08-24 20:08:30',
                'deleted_at' => null,
            ],
            [
                'id' => 31,
                'name' => 'Greenway Plaza',
                'sequence' => 29,
                'filtered_dwp' => 144987,
                'market_id' => 9,
                'admin_id' => null,
                'catering_manager' => 148,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2021-12-29 16:11:01',
                'deleted_at' => null,
            ],
            [
                'id' => 33,
                'name' => 'Houston Galleria',
                'sequence' => 3,
                'filtered_dwp' => 191708,
                'market_id' => 9,
                'admin_id' => null,
                'catering_manager' => 244,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2025-01-23 19:29:34',
                'deleted_at' => null,
            ],
            [
                'id' => 35,
                'name' => 'Medical Center South',
                'sequence' => 32,
                'filtered_dwp' => 90759,
                'market_id' => 9,
                'admin_id' => null,
                'catering_manager' => 208,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2025-05-22 19:22:54',
                'deleted_at' => null,
            ],
            [
                'id' => 36,
                'name' => 'Fort Worth East',
                'sequence' => 33,
                'filtered_dwp' => 103107,
                'market_id' => 1,
                'admin_id' => null,
                'catering_manager' => 141,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2021-12-29 15:59:32',
                'deleted_at' => null,
            ],
            [
                'id' => 37,
                'name' => 'Dallas Downtown',
                'sequence' => 34,
                'filtered_dwp' => 178684,
                'market_id' => 1,
                'admin_id' => null,
                'catering_manager' => 190,
                'assistant_catering_manager' => 159,
                'created_at' => null,
                'updated_at' => '2022-01-03 18:20:35',
                'deleted_at' => null,
            ],
            [
                'id' => 38,
                'name' => 'OC',
                'sequence' => 35,
                'filtered_dwp' => 249487,
                'market_id' => 16,
                'admin_id' => null,
                'catering_manager' => 246,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2025-05-21 23:31:32',
                'deleted_at' => null,
            ],
            [
                'id' => 39,
                'name' => 'Laguna Hills',
                'sequence' => 36,
                'filtered_dwp' => 318031,
                'market_id' => 16,
                'admin_id' => null,
                'catering_manager' => 203,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2023-01-31 15:00:42',
                'deleted_at' => null,
            ],
            [
                'id' => 40,
                'name' => 'NE LA',
                'sequence' => 37,
                'filtered_dwp' => 330443,
                'market_id' => 16,
                'admin_id' => null,
                'catering_manager' => 157,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2022-02-10 13:43:42',
                'deleted_at' => null,
            ],
            [
                'id' => 41,
                'name' => 'Central LA',
                'sequence' => 38,
                'filtered_dwp' => 338095,
                'market_id' => 16,
                'admin_id' => null,
                'catering_manager' => 201,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2022-12-01 18:51:53',
                'deleted_at' => null,
            ],
            [
                'id' => 42,
                'name' => 'Burbank',
                'sequence' => 39,
                'filtered_dwp' => 265436,
                'market_id' => 16,
                'admin_id' => null,
                'catering_manager' => 206,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2025-01-15 22:08:46',
                'deleted_at' => null,
            ],
            [
                'id' => 43,
                'name' => 'Orange County 4',
                'sequence' => 40,
                'filtered_dwp' => 1,
                'market_id' => 16,
                'admin_id' => null,
                'catering_manager' => 206,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2025-01-15 22:09:11',
                'deleted_at' => null,
            ],
            [
                'id' => 44,
                'name' => 'Austin South',
                'sequence' => 41,
                'filtered_dwp' => 1,
                'market_id' => 13,
                'admin_id' => null,
                'catering_manager' => 123,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2022-01-03 18:54:00',
                'deleted_at' => null,
            ],
            [
                'id' => 45,
                'name' => 'Dallas Frisco',
                'sequence' => 42,
                'filtered_dwp' => 1,
                'market_id' => 1,
                'admin_id' => null,
                'catering_manager' => 49,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2022-01-03 18:18:27',
                'deleted_at' => null,
            ],
            [
                'id' => 46,
                'name' => 'Grapevine',
                'sequence' => 43,
                'filtered_dwp' => 1,
                'market_id' => 1,
                'admin_id' => null,
                'catering_manager' => 220,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2025-02-07 20:41:38',
                'deleted_at' => null,
            ],
            [
                'id' => 47,
                'name' => 'Barrington',
                'sequence' => 44,
                'filtered_dwp' => 1,
                'market_id' => 4,
                'admin_id' => null,
                'catering_manager' => 192,
                'assistant_catering_manager' => 184,
                'created_at' => null,
                'updated_at' => '2022-01-03 14:53:07',
                'deleted_at' => null,
            ],
            [
                'id' => 48,
                'name' => 'Chicago Southwest Suburban',
                'sequence' => 45,
                'filtered_dwp' => 1,
                'market_id' => 4,
                'admin_id' => null,
                'catering_manager' => 235,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2024-06-17 19:10:22',
                'deleted_at' => null,
            ],
            [
                'id' => 49,
                'name' => 'Long Beach',
                'sequence' => 46,
                'filtered_dwp' => 1,
                'market_id' => 16,
                'admin_id' => null,
                'catering_manager' => 206,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2025-01-15 22:09:01',
                'deleted_at' => null,
            ],
            [
                'id' => 50,
                'name' => 'West LA',
                'sequence' => 47,
                'filtered_dwp' => 1,
                'market_id' => 16,
                'admin_id' => null,
                'catering_manager' => 157,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2024-07-01 21:38:14',
                'deleted_at' => null,
            ],
            [
                'id' => 51,
                'name' => 'Beverly Hills/Century City',
                'sequence' => 48,
                'filtered_dwp' => 1,
                'market_id' => 16,
                'admin_id' => null,
                'catering_manager' => 165,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2022-02-10 13:43:13',
                'deleted_at' => null,
            ],
            [
                'id' => 52,
                'name' => 'Houston West A',
                'sequence' => 49,
                'filtered_dwp' => 1,
                'market_id' => 2,
                'admin_id' => null,
                'catering_manager' => null,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2021-12-28 05:22:30',
                'deleted_at' => null,
            ],
            [
                'id' => 53,
                'name' => 'Houston West B',
                'sequence' => 50,
                'filtered_dwp' => 1,
                'market_id' => 2,
                'admin_id' => null,
                'catering_manager' => null,
                'assistant_catering_manager' => null,
                'created_at' => null,
                'updated_at' => '2021-12-28 05:22:30',
                'deleted_at' => null,
            ],
            [
                'id' => 54,
                'name' => 'East OC',
                'sequence' => null,
                'filtered_dwp' => null,
                'market_id' => 16,
                'admin_id' => null,
                'catering_manager' => 206,
                'assistant_catering_manager' => null,
                'created_at' => '2024-07-01 20:25:59',
                'updated_at' => '2024-07-01 20:25:59',
                'deleted_at' => null,
            ],
            [
                'id' => 55,
                'name' => 'Atlanta',
                'sequence' => null,
                'filtered_dwp' => null,
                'market_id' => 17,
                'admin_id' => null,
                'catering_manager' => 239,
                'assistant_catering_manager' => 245,
                'created_at' => '2024-08-26 01:03:34',
                'updated_at' => '2025-10-07 00:19:32',
                'deleted_at' => null,
            ],
            [
                'id' => 56,
                'name' => 'Atlanta West',
                'sequence' => null,
                'filtered_dwp' => null,
                'market_id' => 17,
                'admin_id' => null,
                'catering_manager' => 239,
                'assistant_catering_manager' => 245,
                'created_at' => '2024-08-26 01:03:46',
                'updated_at' => '2025-08-14 14:33:11',
                'deleted_at' => null,
            ],
            [
                'id' => 57,
                'name' => 'Atlanta North',
                'sequence' => null,
                'filtered_dwp' => null,
                'market_id' => 17,
                'admin_id' => null,
                'catering_manager' => 239,
                'assistant_catering_manager' => 245,
                'created_at' => '2024-08-26 01:03:57',
                'updated_at' => '2025-04-01 15:55:03',
                'deleted_at' => null,
            ],
        ];

        DB::table('districts')->insert($dataTables);
    }
}
