<?php

namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EtPaidoutSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables --limit=500
         */
        $dataTables = [
            [
                'pd_id' => 72989,
                'inp_id' => 78150,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Chalk Markers',
                'amount' => '3.7700',
            ],
            [
                'pd_id' => 72992,
                'inp_id' => 78150,
                'cafe_id' => 68,
                'exp_id' => 9,
                'descr' => 'Ice',
                'amount' => 91,
            ],
            [
                'pd_id' => 72995,
                'inp_id' => 78156,
                'cafe_id' => 68,
                'exp_id' => 23,
                'descr' => '(512] 3 Kegs',
                'amount' => 465,
            ],
            [
                'pd_id' => 72996,
                'inp_id' => 78156,
                'cafe_id' => 68,
                'exp_id' => 16,
                'descr' => 'TABC Zachery Sexton',
                'amount' => 11,
            ],
            [
                'pd_id' => 72999,
                'inp_id' => 78159,
                'cafe_id' => 68,
                'exp_id' => 23,
                'descr' => 'Keg 2 HD',
                'amount' => 54,
            ],
            [
                'pd_id' => 73000,
                'inp_id' => 78159,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Paper Clips, Erasers',
                'amount' => '10.4800',
            ],
            [
                'pd_id' => 73001,
                'inp_id' => 78161,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Arugula ',
                'amount' => '15.9600',
            ],
            [
                'pd_id' => 73002,
                'inp_id' => 78165,
                'cafe_id' => 68,
                'exp_id' => 23,
                'descr' => '2 Kegs HD',
                'amount' => 337,
            ],
            [
                'pd_id' => 73003,
                'inp_id' => 78165,
                'cafe_id' => 68,
                'exp_id' => 11,
                'descr' => 'Soap',
                'amount' => '7.7000',
            ],
            [
                'pd_id' => 73004,
                'inp_id' => 78165,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Stickers',
                'amount' => '7.5700',
            ],
            [
                'pd_id' => 73005,
                'inp_id' => 78166,
                'cafe_id' => 68,
                'exp_id' => 23,
                'descr' => '512 Brewing Company',
                'amount' => 105,
            ],
            [
                'pd_id' => 73006,
                'inp_id' => 78166,
                'cafe_id' => 68,
                'exp_id' => 23,
                'descr' => '512 Brewing Company',
                'amount' => -105,
            ],
            [
                'pd_id' => 73007,
                'inp_id' => 78167,
                'cafe_id' => 68,
                'exp_id' => 10,
                'descr' => 'Napkins',
                'amount' => '22.4000',
            ],
            [
                'pd_id' => 73008,
                'inp_id' => 78167,
                'cafe_id' => 68,
                'exp_id' => 23,
                'descr' => 'Keg from 512 Brewery',
                'amount' => 105,
            ],
            [
                'pd_id' => 73009,
                'inp_id' => 78168,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'French Fries',
                'amount' => '90.5000',
            ],
            [
                'pd_id' => 73010,
                'inp_id' => 78176,
                'cafe_id' => 68,
                'exp_id' => 8,
                'descr' => 'Zachary Sexton',
                'amount' => '534.6600',
            ],
            [
                'pd_id' => 73011,
                'inp_id' => 78176,
                'cafe_id' => 68,
                'exp_id' => 12,
                'descr' => 'Forks',
                'amount' => '9.7200',
            ],
            [
                'pd_id' => 73012,
                'inp_id' => 78182,
                'cafe_id' => 68,
                'exp_id' => 10,
                'descr' => 'Cups',
                'amount' => '178.3600',
            ],
            [
                'pd_id' => 73013,
                'inp_id' => 78188,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Oven Mitts',
                'amount' => '37.2600',
            ],
            [
                'pd_id' => 73014,
                'inp_id' => 78193,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'tomatillos',
                'amount' => '19.6500',
            ],
            [
                'pd_id' => 73015,
                'inp_id' => 78195,
                'cafe_id' => 68,
                'exp_id' => 10,
                'descr' => 'Trifold Napkins',
                'amount' => '20.1000',
            ],
            [
                'pd_id' => 73016,
                'inp_id' => 78196,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'BACON',
                'amount' => '55.9600',
            ],
            [
                'pd_id' => 73017,
                'inp_id' => 78201,
                'cafe_id' => 68,
                'exp_id' => 11,
                'descr' => 'Gloves',
                'amount' => '55.0500',
            ],
            [
                'pd_id' => 73018,
                'inp_id' => 78208,
                'cafe_id' => 68,
                'exp_id' => 43,
                'descr' => 'Kolaches',
                'amount' => '29.7900',
            ],
            [
                'pd_id' => 73019,
                'inp_id' => 78209,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'pablano peppers',
                'amount' => '8.3800',
            ],
            [
                'pd_id' => 73020,
                'inp_id' => 78211,
                'cafe_id' => 68,
                'exp_id' => 12,
                'descr' => 'Knife Sharpner',
                'amount' => '19.6800',
            ],
            [
                'pd_id' => 73021,
                'inp_id' => 78211,
                'cafe_id' => 68,
                'exp_id' => 14,
                'descr' => 'Key, Chair Glides',
                'amount' => '8.5100',
            ],
            [
                'pd_id' => 73022,
                'inp_id' => 78216,
                'cafe_id' => 68,
                'exp_id' => 10,
                'descr' => 'Baking Tray Paper',
                'amount' => '44.9000',
            ],
            [
                'pd_id' => 73023,
                'inp_id' => 78224,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'BACON',
                'amount' => '78.7900',
            ],
            [
                'pd_id' => 73024,
                'inp_id' => 78228,
                'cafe_id' => 68,
                'exp_id' => 12,
                'descr' => 'Divider Bar',
                'amount' => '4.6000',
            ],
            [
                'pd_id' => 73025,
                'inp_id' => 78229,
                'cafe_id' => 68,
                'exp_id' => 11,
                'descr' => 'Magic Eraser',
                'amount' => '15.1100',
            ],
            [
                'pd_id' => 73026,
                'inp_id' => 78235,
                'cafe_id' => 68,
                'exp_id' => 14,
                'descr' => 'Dishwasher Sprayer',
                'amount' => '72.5100',
            ],
            [
                'pd_id' => 73027,
                'inp_id' => 78237,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Honey Mustard, Mozz Cheese',
                'amount' => '38.4000',
            ],
            [
                'pd_id' => 73028,
                'inp_id' => 78238,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Thermal Paper',
                'amount' => '40.0400',
            ],
            [
                'pd_id' => 73029,
                'inp_id' => 78240,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Paper',
                'amount' => 0,
            ],
            [
                'pd_id' => 73032,
                'inp_id' => 78242,
                'cafe_id' => 68,
                'exp_id' => 14,
                'descr' => 'Key',
                'amount' => '1.9300',
            ],
            [
                'pd_id' => 73033,
                'inp_id' => 78243,
                'cafe_id' => 68,
                'exp_id' => 16,
                'descr' => 'TABC',
                'amount' => '10.9900',
            ],
            [
                'pd_id' => 73035,
                'inp_id' => 78240,
                'cafe_id' => 68,
                'exp_id' => 10,
                'descr' => '.',
                'amount' => 0,
            ],
            [
                'pd_id' => 73036,
                'inp_id' => 78240,
                'cafe_id' => 68,
                'exp_id' => 10,
                'descr' => ',',
                'amount' => 0,
            ],
            [
                'pd_id' => 73037,
                'inp_id' => 78240,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => '.',
                'amount' => 0,
            ],
            [
                'pd_id' => 73039,
                'inp_id' => 78248,
                'cafe_id' => 68,
                'exp_id' => 8,
                'descr' => 'Michael Vargas ',
                'amount' => 175,
            ],
            [
                'pd_id' => 73040,
                'inp_id' => 78251,
                'cafe_id' => 68,
                'exp_id' => 11,
                'descr' => 'Gloves',
                'amount' => '26.0600',
            ],
            [
                'pd_id' => 73041,
                'inp_id' => 78252,
                'cafe_id' => 68,
                'exp_id' => 8,
                'descr' => 'Aaron Simmons',
                'amount' => 280,
            ],
            [
                'pd_id' => 73042,
                'inp_id' => 78253,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'Paper Products for Marketing',
                'amount' => '13.8200',
            ],
            [
                'pd_id' => 73043,
                'inp_id' => 78254,
                'cafe_id' => 68,
                'exp_id' => 8,
                'descr' => 'Employee Advance',
                'amount' => 200,
            ],
            [
                'pd_id' => 73044,
                'inp_id' => 78254,
                'cafe_id' => 68,
                'exp_id' => 8,
                'descr' => 'Employee Advance',
                'amount' => 80,
            ],
            [
                'pd_id' => 73045,
                'inp_id' => 78256,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Binders ',
                'amount' => '14.8100',
            ],
            [
                'pd_id' => 73046,
                'inp_id' => 78258,
                'cafe_id' => 68,
                'exp_id' => 10,
                'descr' => 'Napkins',
                'amount' => '19.4500',
            ],
            [
                'pd_id' => 73047,
                'inp_id' => 78265,
                'cafe_id' => 68,
                'exp_id' => 10,
                'descr' => 'Napkins',
                'amount' => '34.5200',
            ],
            [
                'pd_id' => 73048,
                'inp_id' => 78265,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Beef',
                'amount' => '59.8000',
            ],
            [
                'pd_id' => 73051,
                'inp_id' => 78268,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Dill',
                'amount' => '7.5600',
            ],
            [
                'pd_id' => 73052,
                'inp_id' => 78270,
                'cafe_id' => 68,
                'exp_id' => 12,
                'descr' => 'crafts',
                'amount' => '9.0800',
            ],
            [
                'pd_id' => 73059,
                'inp_id' => 78275,
                'cafe_id' => 68,
                'exp_id' => 11,
                'descr' => 'Drill ',
                'amount' => '266.0500',
            ],
            [
                'pd_id' => 73061,
                'inp_id' => 78275,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'Batteries',
                'amount' => '11.7100',
            ],
            [
                'pd_id' => 73064,
                'inp_id' => 78279,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Cheese',
                'amount' => '45.4400',
            ],
            [
                'pd_id' => 73065,
                'inp_id' => 78281,
                'cafe_id' => 68,
                'exp_id' => 14,
                'descr' => 'Grill Brush',
                'amount' => '55.8900',
            ],
            [
                'pd_id' => 73066,
                'inp_id' => 78282,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Tomatoes',
                'amount' => '12.9500',
            ],
            [
                'pd_id' => 73067,
                'inp_id' => 78283,
                'cafe_id' => 68,
                'exp_id' => 50,
                'descr' => 'SnagAJob',
                'amount' => '66.7500',
            ],
            [
                'pd_id' => 73071,
                'inp_id' => 78290,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Card Stock',
                'amount' => '33.8500',
            ],
            [
                'pd_id' => 73073,
                'inp_id' => 78291,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'Print Certificate',
                'amount' => 6,
            ],
            [
                'pd_id' => 73075,
                'inp_id' => 78297,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'Paper for Marketing',
                'amount' => '19.4500',
            ],
            [
                'pd_id' => 73076,
                'inp_id' => 78297,
                'cafe_id' => 68,
                'exp_id' => 50,
                'descr' => 'Craigslist',
                'amount' => 25,
            ],
            [
                'pd_id' => 73078,
                'inp_id' => 78297,
                'cafe_id' => 68,
                'exp_id' => 183,
                'descr' => 'Cy Hope Contribution',
                'amount' => -95,
            ],
            [
                'pd_id' => 73081,
                'inp_id' => 78305,
                'cafe_id' => 68,
                'exp_id' => 12,
                'descr' => 'Opener, False Bottoms, Hangers',
                'amount' => '74.3600',
            ],
            [
                'pd_id' => 73083,
                'inp_id' => 78305,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Markers',
                'amount' => '15.5700',
            ],
            [
                'pd_id' => 73085,
                'inp_id' => 78313,
                'cafe_id' => 68,
                'exp_id' => 50,
                'descr' => 'SnagAJob',
                'amount' => 89,
            ],
            [
                'pd_id' => 73086,
                'inp_id' => 78314,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Cottonseed Oil',
                'amount' => '24.2000',
            ],
            [
                'pd_id' => 73087,
                'inp_id' => 78317,
                'cafe_id' => 68,
                'exp_id' => 50,
                'descr' => 'Craigslist',
                'amount' => 25,
            ],
            [
                'pd_id' => 73089,
                'inp_id' => 78317,
                'cafe_id' => 68,
                'exp_id' => 14,
                'descr' => 'Drill Bit',
                'amount' => '8.2200',
            ],
            [
                'pd_id' => 73090,
                'inp_id' => 78317,
                'cafe_id' => 68,
                'exp_id' => 14,
                'descr' => 'Screws',
                'amount' => '0.6900',
            ],
            [
                'pd_id' => 73091,
                'inp_id' => 78320,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Office Supplies / Phone Case',
                'amount' => '10.8000',
            ],
            [
                'pd_id' => 73092,
                'inp_id' => 78320,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Velcro',
                'amount' => '2.9400',
            ],
            [
                'pd_id' => 73093,
                'inp_id' => 78322,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Mushrooms Cilantro ',
                'amount' => '48.3000',
            ],
            [
                'pd_id' => 73094,
                'inp_id' => 78325,
                'cafe_id' => 68,
                'exp_id' => 8,
                'descr' => 'Aaron Simmons',
                'amount' => 275,
            ],
            [
                'pd_id' => 73095,
                'inp_id' => 78327,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Staples',
                'amount' => '10.0500',
            ],
            [
                'pd_id' => 73096,
                'inp_id' => 78328,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Brown Sugar',
                'amount' => '6.2600',
            ],
            [
                'pd_id' => 73098,
                'inp_id' => 78332,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Ground Turkey',
                'amount' => '25.9000',
            ],
            [
                'pd_id' => 73100,
                'inp_id' => 78335,
                'cafe_id' => 68,
                'exp_id' => 12,
                'descr' => 'Grill Gloves',
                'amount' => '39.9700',
            ],
            [
                'pd_id' => 73102,
                'inp_id' => 78340,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Seasoning',
                'amount' => '4.6800',
            ],
            [
                'pd_id' => 73103,
                'inp_id' => 78340,
                'cafe_id' => 68,
                'exp_id' => 10,
                'descr' => '1# Boats',
                'amount' => '89.5000',
            ],
            [
                'pd_id' => 73104,
                'inp_id' => 78344,
                'cafe_id' => 68,
                'exp_id' => 10,
                'descr' => 'Lids',
                'amount' => '30.5100',
            ],
            [
                'pd_id' => 73105,
                'inp_id' => 78348,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Stamper and Ink (LSM]',
                'amount' => '23.5600',
            ],
            [
                'pd_id' => 73106,
                'inp_id' => 78352,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Note Pads, Lminating (LSM]',
                'amount' => '24.1800',
            ],
            [
                'pd_id' => 73107,
                'inp_id' => 78353,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Office supplies',
                'amount' => '7.5600',
            ],
            [
                'pd_id' => 73108,
                'inp_id' => 78358,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Chalkboard Markers',
                'amount' => '16.1700',
            ],
            [
                'pd_id' => 73109,
                'inp_id' => 78363,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'LSM Supplies',
                'amount' => '37.4300',
            ],
            [
                'pd_id' => 73110,
                'inp_id' => 78365,
                'cafe_id' => 68,
                'exp_id' => 20,
                'descr' => 'LSM Postage',
                'amount' => '33.6000',
            ],
            [
                'pd_id' => 73111,
                'inp_id' => 78370,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Thermal Paper',
                'amount' => '35.7100',
            ],
            [
                'pd_id' => 73112,
                'inp_id' => 78371,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Spinach',
                'amount' => '14.8300',
            ],
            [
                'pd_id' => 73113,
                'inp_id' => 78372,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Pickles',
                'amount' => '17.6400',
            ],
            [
                'pd_id' => 73114,
                'inp_id' => 78376,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => '(No Receipt $2.87] Cilantro/Brown Sugar',
                'amount' => 0,
            ],
            [
                'pd_id' => 73115,
                'inp_id' => 78376,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Jalapeno',
                'amount' => '2.6000',
            ],
            [
                'pd_id' => 73117,
                'inp_id' => 78383,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Flyers - LSM',
                'amount' => '3.7100',
            ],
            [
                'pd_id' => 73118,
                'inp_id' => 78383,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Self -Ink - LSM',
                'amount' => '6.4800',
            ],
            [
                'pd_id' => 73119,
                'inp_id' => 78384,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'peppers',
                'amount' => '6.8200',
            ],
            [
                'pd_id' => 73120,
                'inp_id' => 78384,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'arugula',
                'amount' => '13.1600',
            ],
            [
                'pd_id' => 73121,
                'inp_id' => 78388,
                'cafe_id' => 68,
                'exp_id' => 50,
                'descr' => 'Craigs List Ad',
                'amount' => 25,
            ],
            [
                'pd_id' => 73122,
                'inp_id' => 78388,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Office Supplis',
                'amount' => '9.7300',
            ],
            [
                'pd_id' => 73123,
                'inp_id' => 78392,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Brown Sugar',
                'amount' => '4.1400',
            ],
            [
                'pd_id' => 73124,
                'inp_id' => 78395,
                'cafe_id' => 68,
                'exp_id' => 11,
                'descr' => 'Hose & Glue',
                'amount' => '36.1800',
            ],
            [
                'pd_id' => 73125,
                'inp_id' => 78397,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Mayo/Mustard',
                'amount' => '20.3200',
            ],
            [
                'pd_id' => 73126,
                'inp_id' => 78397,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Food Test',
                'amount' => '12.4600',
            ],
            [
                'pd_id' => 73127,
                'inp_id' => 78399,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'French Fries',
                'amount' => '81.3300',
            ],
            [
                'pd_id' => 73128,
                'inp_id' => 78400,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Chickpeas ',
                'amount' => '4.9200',
            ],
            [
                'pd_id' => 73129,
                'inp_id' => 78402,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Counterfit Pen',
                'amount' => '11.9000',
            ],
            [
                'pd_id' => 73130,
                'inp_id' => 78402,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Gatorade',
                'amount' => '15.0400',
            ],
            [
                'pd_id' => 73131,
                'inp_id' => 78402,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Green Chilies',
                'amount' => '13.8600',
            ],
            [
                'pd_id' => 73132,
                'inp_id' => 78406,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Ibuprofen',
                'amount' => '13.4900',
            ],
            [
                'pd_id' => 73133,
                'inp_id' => 78408,
                'cafe_id' => 68,
                'exp_id' => 12,
                'descr' => 'Can Opener',
                'amount' => '10.7900',
            ],
            [
                'pd_id' => 73134,
                'inp_id' => 78408,
                'cafe_id' => 68,
                'exp_id' => 12,
                'descr' => 'Can Opener',
                'amount' => 0,
            ],
            [
                'pd_id' => 73135,
                'inp_id' => 78408,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'Can Opener',
                'amount' => 0,
            ],
            [
                'pd_id' => 73136,
                'inp_id' => 78409,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Employee Drinks',
                'amount' => 7,
            ],
            [
                'pd_id' => 73138,
                'inp_id' => 78414,
                'cafe_id' => 68,
                'exp_id' => 14,
                'descr' => 'Screws',
                'amount' => '5.1500',
            ],
            [
                'pd_id' => 73139,
                'inp_id' => 78414,
                'cafe_id' => 68,
                'exp_id' => 11,
                'descr' => 'Trash Bag',
                'amount' => '4.8100',
            ],
            [
                'pd_id' => 73140,
                'inp_id' => 78416,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Lemonade',
                'amount' => '17.2800',
            ],
            [
                'pd_id' => 73141,
                'inp_id' => 78421,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Light Bulbs',
                'amount' => '18.2700',
            ],
            [
                'pd_id' => 73142,
                'inp_id' => 78423,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Poblanos',
                'amount' => '18.3900',
            ],
            [
                'pd_id' => 73143,
                'inp_id' => 78423,
                'cafe_id' => 68,
                'exp_id' => 50,
                'descr' => 'Craigslist',
                'amount' => 25,
            ],
            [
                'pd_id' => 73144,
                'inp_id' => 78428,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Oil',
                'amount' => '117.8700',
            ],
            [
                'pd_id' => 73145,
                'inp_id' => 78430,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'Contest Winner Instagram',
                'amount' => 100,
            ],
            [
                'pd_id' => 73146,
                'inp_id' => 78436,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'Coin Medallion',
                'amount' => '4.3200',
            ],
            [
                'pd_id' => 73147,
                'inp_id' => 78437,
                'cafe_id' => 68,
                'exp_id' => 12,
                'descr' => 'Aroma Rice Cooker',
                'amount' => '43.2900',
            ],
            [
                'pd_id' => 73148,
                'inp_id' => 78437,
                'cafe_id' => 68,
                'exp_id' => 12,
                'descr' => 'Rice Cooker',
                'amount' => '60.5100',
            ],
            [
                'pd_id' => 73149,
                'inp_id' => 78437,
                'cafe_id' => 68,
                'exp_id' => 11,
                'descr' => 'Tape',
                'amount' => '15.4500',
            ],
            [
                'pd_id' => 73150,
                'inp_id' => 78438,
                'cafe_id' => 68,
                'exp_id' => 10,
                'descr' => 'Paper Bags',
                'amount' => '13.0800',
            ],
            [
                'pd_id' => 73151,
                'inp_id' => 78439,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'LSM Copies',
                'amount' => '282.4100',
            ],
            [
                'pd_id' => 73152,
                'inp_id' => 78439,
                'cafe_id' => 68,
                'exp_id' => 12,
                'descr' => 'Smallwares',
                'amount' => '24.8500',
            ],
            [
                'pd_id' => 73153,
                'inp_id' => 78441,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Eggs',
                'amount' => '2.1600',
            ],
            [
                'pd_id' => 73154,
                'inp_id' => 78430,
                'cafe_id' => 68,
                'exp_id' => 69,
                'descr' => 'Gift Card Sold',
                'amount' => -100,
            ],
            [
                'pd_id' => 73155,
                'inp_id' => 78423,
                'cafe_id' => 68,
                'exp_id' => 69,
                'descr' => 'Gift Card Redeemed',
                'amount' => 5,
            ],
            [
                'pd_id' => 73156,
                'inp_id' => 78442,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Pineapple',
                'amount' => '3.9900',
            ],
            [
                'pd_id' => 73157,
                'inp_id' => 78443,
                'cafe_id' => 68,
                'exp_id' => 14,
                'descr' => 'Plumbers Putty',
                'amount' => '3.2400',
            ],
            [
                'pd_id' => 73164,
                'inp_id' => 78450,
                'cafe_id' => 68,
                'exp_id' => 11,
                'descr' => 'Pens',
                'amount' => '15.6600',
            ],
            [
                'pd_id' => 73168,
                'inp_id' => 78438,
                'cafe_id' => 68,
                'exp_id' => 69,
                'descr' => 'Gift Card Sold',
                'amount' => -10,
            ],
            [
                'pd_id' => 73169,
                'inp_id' => 78462,
                'cafe_id' => 68,
                'exp_id' => 10,
                'descr' => 'Water Cups',
                'amount' => '6.4700',
            ],
            [
                'pd_id' => 73170,
                'inp_id' => 78464,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Corn Starch',
                'amount' => '2.9700',
            ],
            [
                'pd_id' => 73171,
                'inp_id' => 78464,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Eggs-Flour-Corn Meal-Garlic Powder',
                'amount' => '14.1200',
            ],
            [
                'pd_id' => 73172,
                'inp_id' => 78466,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => '(No Receipt $7.88] Chick Fil\'A Sandwiches / R&D',
                'amount' => 0,
            ],
            [
                'pd_id' => 73173,
                'inp_id' => 78467,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Spinach',
                'amount' => '6.3800',
            ],
            [
                'pd_id' => 73174,
                'inp_id' => 78470,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Brown Sugar',
                'amount' => '3.7800',
            ],
            [
                'pd_id' => 73175,
                'inp_id' => 78471,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Flour',
                'amount' => '5.2900',
            ],
            [
                'pd_id' => 73176,
                'inp_id' => 78472,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Bread Crumbs, Eggs',
                'amount' => '4.7200',
            ],
            [
                'pd_id' => 73177,
                'inp_id' => 78475,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Olive Oil',
                'amount' => '18.7900',
            ],
            [
                'pd_id' => 73179,
                'inp_id' => 78477,
                'cafe_id' => 68,
                'exp_id' => 14,
                'descr' => 'Light Bulbs',
                'amount' => '14.0100',
            ],
            [
                'pd_id' => 73180,
                'inp_id' => 78479,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Rubber Bands',
                'amount' => '4.1100',
            ],
            [
                'pd_id' => 73182,
                'inp_id' => 78494,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Office Supplies',
                'amount' => '3.9500',
            ],
            [
                'pd_id' => 73183,
                'inp_id' => 78498,
                'cafe_id' => 68,
                'exp_id' => 12,
                'descr' => 'Drain Pans, Sanitary Napkin Bags',
                'amount' => '53.5600',
            ],
            [
                'pd_id' => 73184,
                'inp_id' => 78498,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Buttermilk, Eggs, Flour',
                'amount' => '12.4300',
            ],
            [
                'pd_id' => 73185,
                'inp_id' => 78499,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Brown Sugar/Cleaner',
                'amount' => '3.7800',
            ],
            [
                'pd_id' => 73186,
                'inp_id' => 78499,
                'cafe_id' => 68,
                'exp_id' => 11,
                'descr' => 'toilet cleaner',
                'amount' => '6.4700',
            ],
            [
                'pd_id' => 73187,
                'inp_id' => 78507,
                'cafe_id' => 68,
                'exp_id' => 30,
                'descr' => 'Mgr Uniform Shirts',
                'amount' => '96.7600',
            ],
            [
                'pd_id' => 73197,
                'inp_id' => 78566,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'Testing Items',
                'amount' => '9.3800',
            ],
            [
                'pd_id' => 73198,
                'inp_id' => 78575,
                'cafe_id' => 68,
                'exp_id' => 14,
                'descr' => 'CaptiveAire Systems',
                'amount' => 340,
            ],
            [
                'pd_id' => 73199,
                'inp_id' => 78577,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Whipped Cream',
                'amount' => '7.8000',
            ],
            [
                'pd_id' => 73200,
                'inp_id' => 78577,
                'cafe_id' => 68,
                'exp_id' => 12,
                'descr' => 'New Items',
                'amount' => '113.4000',
            ],
            [
                'pd_id' => 73201,
                'inp_id' => 78578,
                'cafe_id' => 68,
                'exp_id' => 43,
                'descr' => 'Coffee ',
                'amount' => '23.8700',
            ],
            [
                'pd_id' => 73202,
                'inp_id' => 78579,
                'cafe_id' => 68,
                'exp_id' => 10,
                'descr' => 'Gloves, Patty Paper',
                'amount' => '20.0500',
            ],
            [
                'pd_id' => 72993,
                'inp_id' => 78150,
                'cafe_id' => 68,
                'exp_id' => 14,
                'descr' => 'Window Cleaning',
                'amount' => 90,
            ],
            [
                'pd_id' => 73068,
                'inp_id' => 78283,
                'cafe_id' => 68,
                'exp_id' => 50,
                'descr' => 'Craigslist',
                'amount' => 25,
            ],
            [
                'pd_id' => 73116,
                'inp_id' => 78378,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Fries',
                'amount' => '39.2800',
            ],
            [
                'pd_id' => 73158,
                'inp_id' => 78444,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Flour/Corn Meal/Butter Milk/Spices',
                'amount' => '20.5300',
            ],
            [
                'pd_id' => 73161,
                'inp_id' => 78447,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Ink',
                'amount' => '31.3800',
            ],
            [
                'pd_id' => 73165,
                'inp_id' => 78453,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Spinach',
                'amount' => '11.9800',
            ],
            [
                'pd_id' => 73166,
                'inp_id' => 78454,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Milk',
                'amount' => '18.4900',
            ],
            [
                'pd_id' => 73167,
                'inp_id' => 78455,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Tomato',
                'amount' => '4.8800',
            ],
            [
                'pd_id' => 73196,
                'inp_id' => 78555,
                'cafe_id' => 68,
                'exp_id' => 11,
                'descr' => 'Trash Bags',
                'amount' => '3.0200',
            ],
            [
                'pd_id' => 73204,
                'inp_id' => 78579,
                'cafe_id' => 68,
                'exp_id' => 10,
                'descr' => 'Patty Paper',
                'amount' => '3.2500',
            ],
            [
                'pd_id' => 73205,
                'inp_id' => 78585,
                'cafe_id' => 68,
                'exp_id' => 8,
                'descr' => 'Loren Berry Vacation Pay',
                'amount' => 240,
            ],
            [
                'pd_id' => 73206,
                'inp_id' => 78587,
                'cafe_id' => 68,
                'exp_id' => 12,
                'descr' => 'Wine Sealer',
                'amount' => '15.8300',
            ],
            [
                'pd_id' => 73207,
                'inp_id' => 78596,
                'cafe_id' => 68,
                'exp_id' => 43,
                'descr' => 'Employee GCs',
                'amount' => '289.5000',
            ],
            [
                'pd_id' => 73208,
                'inp_id' => 78596,
                'cafe_id' => 68,
                'exp_id' => 43,
                'descr' => 'Employee GCs',
                'amount' => '225.7000',
            ],
            [
                'pd_id' => 73209,
                'inp_id' => 78597,
                'cafe_id' => 68,
                'exp_id' => 12,
                'descr' => 'New Menu Items',
                'amount' => '194.6100',
            ],
            [
                'pd_id' => 73210,
                'inp_id' => 78599,
                'cafe_id' => 68,
                'exp_id' => 10,
                'descr' => '1 # Boats',
                'amount' => '65.1800',
            ],
            [
                'pd_id' => 73211,
                'inp_id' => 78599,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'American Cheese',
                'amount' => '9.9900',
            ],
            [
                'pd_id' => 73212,
                'inp_id' => 78599,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Tape',
                'amount' => '10.8100',
            ],
            [
                'pd_id' => 73213,
                'inp_id' => 78602,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Brown Sugar',
                'amount' => '4.0100',
            ],
            [
                'pd_id' => 73214,
                'inp_id' => 78604,
                'cafe_id' => 68,
                'exp_id' => 12,
                'descr' => 'New Items for New Menu',
                'amount' => '133.4000',
            ],
            [
                'pd_id' => 73215,
                'inp_id' => 78606,
                'cafe_id' => 68,
                'exp_id' => 10,
                'descr' => '2 OZ Lids',
                'amount' => '33.4900',
            ],
            [
                'pd_id' => 73216,
                'inp_id' => 78608,
                'cafe_id' => 68,
                'exp_id' => 14,
                'descr' => 'Super Glue, Thread Tape',
                'amount' => '12.6800',
            ],
            [
                'pd_id' => 73217,
                'inp_id' => 78610,
                'cafe_id' => 68,
                'exp_id' => 12,
                'descr' => 'Tea Urn Test',
                'amount' => 78,
            ],
            [
                'pd_id' => 73218,
                'inp_id' => 78611,
                'cafe_id' => 68,
                'exp_id' => 12,
                'descr' => 'Cold Brew For Testing',
                'amount' => '134.7400',
            ],
            [
                'pd_id' => 73219,
                'inp_id' => 78616,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Tomatoes',
                'amount' => '5.6600',
            ],
            [
                'pd_id' => 73220,
                'inp_id' => 78617,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Swiss Cheese',
                'amount' => '14.7800',
            ],
            [
                'pd_id' => 73221,
                'inp_id' => 78617,
                'cafe_id' => 68,
                'exp_id' => 50,
                'descr' => 'Craigslist Ad',
                'amount' => 35,
            ],
            [
                'pd_id' => 73222,
                'inp_id' => 78618,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Brown Sugar',
                'amount' => '3.9800',
            ],
            [
                'pd_id' => 73223,
                'inp_id' => 78619,
                'cafe_id' => 68,
                'exp_id' => 43,
                'descr' => 'Employee GC',
                'amount' => '104.9400',
            ],
            [
                'pd_id' => 73224,
                'inp_id' => 78620,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Red Peppers',
                'amount' => 25,
            ],
            [
                'pd_id' => 73225,
                'inp_id' => 78623,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'Fish Bowl',
                'amount' => '21.6400',
            ],
            [
                'pd_id' => 73226,
                'inp_id' => 78630,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'Fish Bowl Gift Card',
                'amount' => 50,
            ],
            [
                'pd_id' => 73227,
                'inp_id' => 78630,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'Table Tents',
                'amount' => '134.7400',
            ],
            [
                'pd_id' => 73228,
                'inp_id' => 78633,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Spinach',
                'amount' => '13.1800',
            ],
            [
                'pd_id' => 73229,
                'inp_id' => 78636,
                'cafe_id' => 68,
                'exp_id' => 10,
                'descr' => 'Fry Boats',
                'amount' => '65.9900',
            ],
            [
                'pd_id' => 73230,
                'inp_id' => 78638,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Brown Sugar',
                'amount' => '3.6800',
            ],
            [
                'pd_id' => 73231,
                'inp_id' => 78640,
                'cafe_id' => 68,
                'exp_id' => 14,
                'descr' => 'Pvc Pipe Repair ',
                'amount' => '24.0300',
            ],
            [
                'pd_id' => 73232,
                'inp_id' => 78641,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Apple Juice',
                'amount' => '9.9600',
            ],
            [
                'pd_id' => 73233,
                'inp_id' => 78644,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'R. Rea - Fishbowl',
                'amount' => 50,
            ],
            [
                'pd_id' => 73234,
                'inp_id' => 78644,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'R. Rivera - Fishbowl',
                'amount' => 50,
            ],
            [
                'pd_id' => 73235,
                'inp_id' => 78646,
                'cafe_id' => 68,
                'exp_id' => 12,
                'descr' => 'Fry Baskets',
                'amount' => '16.7800',
            ],
            [
                'pd_id' => 73236,
                'inp_id' => 78647,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'GC Donation',
                'amount' => 25,
            ],
            [
                'pd_id' => 73237,
                'inp_id' => 78652,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Tape',
                'amount' => '9.7100',
            ],
            [
                'pd_id' => 73238,
                'inp_id' => 78652,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Dr. Pepper',
                'amount' => '76.9700',
            ],
            [
                'pd_id' => 73239,
                'inp_id' => 78657,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'Fishbowl Gift Card',
                'amount' => 50,
            ],
            [
                'pd_id' => 73240,
                'inp_id' => 78664,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'Fishbowl GC Winner',
                'amount' => 50,
            ],
            [
                'pd_id' => 73241,
                'inp_id' => 78678,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'Fishbowl GC Winner',
                'amount' => 50,
            ],
            [
                'pd_id' => 73242,
                'inp_id' => 78683,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Corn Starch',
                'amount' => '1.9800',
            ],
            [
                'pd_id' => 73243,
                'inp_id' => 78685,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Masking Tape',
                'amount' => '5.2000',
            ],
            [
                'pd_id' => 73244,
                'inp_id' => 78685,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'Fishbowl GC Winner',
                'amount' => 50,
            ],
            [
                'pd_id' => 73245,
                'inp_id' => 78691,
                'cafe_id' => 68,
                'exp_id' => 14,
                'descr' => 'Tools',
                'amount' => '41.6400',
            ],
            [
                'pd_id' => 73246,
                'inp_id' => 78693,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'Fishbowl GC Winner',
                'amount' => 50,
            ],
            [
                'pd_id' => 73247,
                'inp_id' => 78695,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'Gift Card Donation',
                'amount' => 20,
            ],
            [
                'pd_id' => 73248,
                'inp_id' => 78699,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'Fishbowl GC Winner',
                'amount' => 50,
            ],
            [
                'pd_id' => 73250,
                'inp_id' => 78702,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'donation',
                'amount' => 20,
            ],
            [
                'pd_id' => 73251,
                'inp_id' => 78706,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'Fishbowl',
                'amount' => 50,
            ],
            [
                'pd_id' => 73252,
                'inp_id' => 78707,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Tape',
                'amount' => '4.3200',
            ],
            [
                'pd_id' => 73253,
                'inp_id' => 78707,
                'cafe_id' => 68,
                'exp_id' => 33,
                'descr' => 'Parking DC - Travis',
                'amount' => 40,
            ],
            [
                'pd_id' => 73254,
                'inp_id' => 78707,
                'cafe_id' => 68,
                'exp_id' => 33,
                'descr' => 'Parking DC - Greenway',
                'amount' => 2,
            ],
            [
                'pd_id' => 73255,
                'inp_id' => 78707,
                'cafe_id' => 68,
                'exp_id' => 33,
                'descr' => 'Parking DC - Exit 5',
                'amount' => 20,
            ],
            [
                'pd_id' => 73256,
                'inp_id' => 78711,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Thumb Drive',
                'amount' => '10.8100',
            ],
            [
                'pd_id' => 73034,
                'inp_id' => 78244,
                'cafe_id' => 68,
                'exp_id' => 12,
                'descr' => 'Grill Brush',
                'amount' => '61.0400',
            ],
            [
                'pd_id' => 73088,
                'inp_id' => 78317,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'Tent Weights',
                'amount' => '34.6400',
            ],
            [
                'pd_id' => 73162,
                'inp_id' => 78450,
                'cafe_id' => 68,
                'exp_id' => 11,
                'descr' => 'Sharpie/Tape',
                'amount' => '30.7100',
            ],
            [
                'pd_id' => 73188,
                'inp_id' => 78510,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Lids - Plastic Wrap',
                'amount' => '44.8300',
            ],
            [
                'pd_id' => 73189,
                'inp_id' => 78498,
                'cafe_id' => 68,
                'exp_id' => 69,
                'descr' => 'Gift Card Sold',
                'amount' => -15,
            ],
            [
                'pd_id' => 73190,
                'inp_id' => 78522,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Pad Lock',
                'amount' => '13.5200',
            ],
            [
                'pd_id' => 73191,
                'inp_id' => 78537,
                'cafe_id' => 68,
                'exp_id' => 11,
                'descr' => 'Degreaser',
                'amount' => '17.2900',
            ],
            [
                'pd_id' => 73192,
                'inp_id' => 78537,
                'cafe_id' => 68,
                'exp_id' => 12,
                'descr' => 'Squeege, Tongs',
                'amount' => '36.8700',
            ],
            [
                'pd_id' => 73193,
                'inp_id' => 78537,
                'cafe_id' => 68,
                'exp_id' => 12,
                'descr' => 'Sink Parts',
                'amount' => '9.0700',
            ],
            [
                'pd_id' => 73194,
                'inp_id' => 78538,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Brown Sugar - Aluminum Pan',
                'amount' => '11.1100',
            ],
            [
                'pd_id' => 73249,
                'inp_id' => 78700,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'donation',
                'amount' => 20,
            ],
            [
                'pd_id' => 73038,
                'inp_id' => 78247,
                'cafe_id' => 68,
                'exp_id' => 73,
                'descr' => 'Superintendent Fun Run Booth',
                'amount' => 200,
            ],
            [
                'pd_id' => 73049,
                'inp_id' => 78266,
                'cafe_id' => 68,
                'exp_id' => 3,
                'descr' => 'Swiss Cheese',
                'amount' => '27.8600',
            ],
            [
                'pd_id' => 73097,
                'inp_id' => 78329,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Sharpies & Paper Clips',
                'amount' => '18.1600',
            ],
            [
                'pd_id' => 73178,
                'inp_id' => 78477,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Sour Cream',
                'amount' => '1.8300',
            ],
            [
                'pd_id' => 73181,
                'inp_id' => 78483,
                'cafe_id' => 68,
                'exp_id' => 10,
                'descr' => 'Tape',
                'amount' => '22.0500',
            ],
            [
                'pd_id' => 73195,
                'inp_id' => 78555,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Eggs',
                'amount' => '2.6700',
            ],
            [
                'pd_id' => 72994,
                'inp_id' => 78153,
                'cafe_id' => 68,
                'exp_id' => 23,
                'descr' => '(512] Keg',
                'amount' => 165,
            ],
            [
                'pd_id' => 72997,
                'inp_id' => 78157,
                'cafe_id' => 68,
                'exp_id' => 23,
                'descr' => 'HD Kegs 2',
                'amount' => 328,
            ],
            [
                'pd_id' => 72998,
                'inp_id' => 78157,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Cheese, Mustard',
                'amount' => '56.7500',
            ],
            [
                'pd_id' => 73069,
                'inp_id' => 78283,
                'cafe_id' => 68,
                'exp_id' => 14,
                'descr' => 'screws',
                'amount' => '7.5300',
            ],
            [
                'pd_id' => 73070,
                'inp_id' => 78283,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Binder',
                'amount' => '3.7800',
            ],
            [
                'pd_id' => 72990,
                'inp_id' => 78150,
                'cafe_id' => 68,
                'exp_id' => 11,
                'descr' => 'Water Hose',
                'amount' => '43.6600',
            ],
            [
                'pd_id' => 72991,
                'inp_id' => 78150,
                'cafe_id' => 68,
                'exp_id' => 14,
                'descr' => 'Window Cleaning',
                'amount' => 45,
            ],
            [
                'pd_id' => 73030,
                'inp_id' => 78240,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Beef',
                'amount' => '239.3400',
            ],
            [
                'pd_id' => 73031,
                'inp_id' => 78242,
                'cafe_id' => 68,
                'exp_id' => 14,
                'descr' => 'Key',
                'amount' => '2.8400',
            ],
            [
                'pd_id' => 73050,
                'inp_id' => 78267,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Tomatillos',
                'amount' => '11.3400',
            ],
            [
                'pd_id' => 73053,
                'inp_id' => 78271,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Sharpies/pens',
                'amount' => '35.3800',
            ],
            [
                'pd_id' => 73054,
                'inp_id' => 78271,
                'cafe_id' => 68,
                'exp_id' => 10,
                'descr' => 'Lids',
                'amount' => '30.5100',
            ],
            [
                'pd_id' => 73077,
                'inp_id' => 78300,
                'cafe_id' => 68,
                'exp_id' => 14,
                'descr' => 'Dishwasher Parts',
                'amount' => '26.7900',
            ],
            [
                'pd_id' => 73082,
                'inp_id' => 78305,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Red Onions',
                'amount' => '8.3300',
            ],
            [
                'pd_id' => 73137,
                'inp_id' => 78410,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Gatoraide',
                'amount' => '2.1000',
            ],
            [
                'pd_id' => 73163,
                'inp_id' => 78450,
                'cafe_id' => 68,
                'exp_id' => 11,
                'descr' => 'Nozels',
                'amount' => '42.7000',
            ],
            [
                'pd_id' => 73055,
                'inp_id' => 78273,
                'cafe_id' => 68,
                'exp_id' => 10,
                'descr' => 'Daydots',
                'amount' => '33.1100',
            ],
            [
                'pd_id' => 73056,
                'inp_id' => 78273,
                'cafe_id' => 68,
                'exp_id' => 12,
                'descr' => 'Wine Saver',
                'amount' => '32.5100',
            ],
            [
                'pd_id' => 73057,
                'inp_id' => 78274,
                'cafe_id' => 68,
                'exp_id' => 14,
                'descr' => 'Pressure Wash',
                'amount' => '216.5000',
            ],
            [
                'pd_id' => 73058,
                'inp_id' => 78274,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Phones',
                'amount' => '193.0300',
            ],
            [
                'pd_id' => 73060,
                'inp_id' => 78275,
                'cafe_id' => 68,
                'exp_id' => 14,
                'descr' => 'Filters',
                'amount' => '92.8700',
            ],
            [
                'pd_id' => 73062,
                'inp_id' => 78277,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Tomatoes ',
                'amount' => '10.9800',
            ],
            [
                'pd_id' => 73063,
                'inp_id' => 78278,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'cheese',
                'amount' => '31.7400',
            ],
            [
                'pd_id' => 73079,
                'inp_id' => 78303,
                'cafe_id' => 68,
                'exp_id' => 10,
                'descr' => 'Lids',
                'amount' => '29.8900',
            ],
            [
                'pd_id' => 73080,
                'inp_id' => 78303,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'tape',
                'amount' => 7,
            ],
            [
                'pd_id' => 73084,
                'inp_id' => 78305,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Markers',
                'amount' => '12.9700',
            ],
            [
                'pd_id' => 73159,
                'inp_id' => 78446,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'Roll On Ink',
                'amount' => '5.4000',
            ],
            [
                'pd_id' => 73160,
                'inp_id' => 78446,
                'cafe_id' => 68,
                'exp_id' => 11,
                'descr' => 'Nozel ',
                'amount' => '18.3800',
            ],
            [
                'pd_id' => 73072,
                'inp_id' => 78290,
                'cafe_id' => 68,
                'exp_id' => 11,
                'descr' => 'Trash Bags',
                'amount' => '27.4500',
            ],
            [
                'pd_id' => 73074,
                'inp_id' => 78291,
                'cafe_id' => 68,
                'exp_id' => 21,
                'descr' => 'Chairs and Cinder Blocks',
                'amount' => '26.0200',
            ],
            [
                'pd_id' => 73099,
                'inp_id' => 78332,
                'cafe_id' => 68,
                'exp_id' => 13,
                'descr' => 'Masking Tape, Magic Eraser',
                'amount' => '24.9600',
            ],
            [
                'pd_id' => 73101,
                'inp_id' => 78338,
                'cafe_id' => 68,
                'exp_id' => 14,
                'descr' => 'drain covers',
                'amount' => '52.2800',
            ],
            [
                'pd_id' => 73203,
                'inp_id' => 78579,
                'cafe_id' => 68,
                'exp_id' => 5,
                'descr' => 'Brown Sugar',
                'amount' => 3,
            ],
        ];

        DB::table('et_paidout')->insert($dataTables);
    }
}
