<?php

namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExceptionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables --limit=500
         */
        $dataTables = [
            [
                'id' => 1,
                'zipcode' => 110,
                'taxrate' => 0,
                'customermenu_id' => 3,
                'menu_id' => 55,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 2,
                'zipcode' => 770,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 219,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 3,
                'zipcode' => 752,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 219,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 4,
                'zipcode' => 761,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 219,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 5,
                'zipcode' => 750,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 219,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 6,
                'zipcode' => 770,
                'taxrate' => 0,
                'customermenu_id' => 14,
                'menu_id' => 435,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 7,
                'zipcode' => 770,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 707,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 8,
                'zipcode' => 752,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 707,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 9,
                'zipcode' => 761,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 707,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 10,
                'zipcode' => 750,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 707,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 11,
                'zipcode' => 770,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 829,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 12,
                'zipcode' => 770,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 829,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 13,
                'zipcode' => 752,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 829,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 14,
                'zipcode' => 761,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 829,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 15,
                'zipcode' => 750,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 829,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 16,
                'zipcode' => 770,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 17,
                'zipcode' => 752,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 18,
                'zipcode' => 761,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 19,
                'zipcode' => 750,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 20,
                'zipcode' => 770,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 21,
                'zipcode' => 760,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 22,
                'zipcode' => 774,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 23,
                'zipcode' => 775,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 24,
                'zipcode' => 787,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 25,
                'zipcode' => 779,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 26,
                'zipcode' => 773,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 27,
                'zipcode' => 780,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 28,
                'zipcode' => 781,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 29,
                'zipcode' => 782,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 30,
                'zipcode' => 773,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 31,
                'zipcode' => 926,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 32,
                'zipcode' => 927,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 33,
                'zipcode' => 928,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 34,
                'zipcode' => 900,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 35,
                'zipcode' => 910,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 36,
                'zipcode' => 911,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 37,
                'zipcode' => 912,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 38,
                'zipcode' => 913,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 39,
                'zipcode' => 915,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 40,
                'zipcode' => 916,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 41,
                'zipcode' => 918,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 42,
                'zipcode' => 111,
                'taxrate' => 1,
                'customermenu_id' => 16,
                'menu_id' => 626,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 43,
                'zipcode' => 750,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 44,
                'zipcode' => 752,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 45,
                'zipcode' => 760,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 46,
                'zipcode' => 761,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 47,
                'zipcode' => 770,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 48,
                'zipcode' => 773,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 49,
                'zipcode' => 774,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 50,
                'zipcode' => 775,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 51,
                'zipcode' => 779,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 52,
                'zipcode' => 780,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 53,
                'zipcode' => 781,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 54,
                'zipcode' => 782,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 55,
                'zipcode' => 787,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 56,
                'zipcode' => 751,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 57,
                'zipcode' => 753,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 58,
                'zipcode' => 762,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 59,
                'zipcode' => 786,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1099,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 60,
                'zipcode' => 751,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 61,
                'zipcode' => 753,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 62,
                'zipcode' => 762,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 63,
                'zipcode' => 772,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 64,
                'zipcode' => 786,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 65,
                'zipcode' => 900,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 66,
                'zipcode' => 910,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 67,
                'zipcode' => 911,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 68,
                'zipcode' => 912,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 69,
                'zipcode' => 913,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 70,
                'zipcode' => 915,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 71,
                'zipcode' => 916,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 72,
                'zipcode' => 918,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 73,
                'zipcode' => 926,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 74,
                'zipcode' => 927,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 75,
                'zipcode' => 928,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 76,
                'zipcode' => 77019,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1541,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 77,
                'zipcode' => 770,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 78,
                'zipcode' => 750,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1541,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 79,
                'zipcode' => 752,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1482,
                'product_variant_id' => null,
                'flag' => 1,
            ],
            [
                'id' => 80,
                'zipcode' => 753,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1541,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 81,
                'zipcode' => 760,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1541,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 82,
                'zipcode' => 761,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1541,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 83,
                'zipcode' => 762,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1541,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 84,
                'zipcode' => 770,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1541,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 85,
                'zipcode' => 772,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1541,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 86,
                'zipcode' => 773,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1541,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 87,
                'zipcode' => 774,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1541,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 88,
                'zipcode' => 775,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1541,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 89,
                'zipcode' => 780,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1541,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 90,
                'zipcode' => 781,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1541,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 91,
                'zipcode' => 782,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1541,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 92,
                'zipcode' => 786,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1541,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 93,
                'zipcode' => 787,
                'taxrate' => 0,
                'customermenu_id' => 1,
                'menu_id' => 1541,
                'product_variant_id' => null,
                'flag' => 0,
            ],
            [
                'id' => 94,
                'zipcode' => 770,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 1,
            ],
            [
                'id' => 95,
                'zipcode' => 752,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 1,
            ],
            [
                'id' => 96,
                'zipcode' => 761,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 1,
            ],
            [
                'id' => 97,
                'zipcode' => 750,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 1,
            ],
            [
                'id' => 98,
                'zipcode' => 770,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 1,
            ],
            [
                'id' => 99,
                'zipcode' => 760,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 1,
            ],
            [
                'id' => 100,
                'zipcode' => 774,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 1,
            ],
            [
                'id' => 101,
                'zipcode' => 775,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 1,
            ],
            [
                'id' => 102,
                'zipcode' => 787,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 1,
            ],
            [
                'id' => 103,
                'zipcode' => 779,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 1,
            ],
            [
                'id' => 104,
                'zipcode' => 773,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 1,
            ],
            [
                'id' => 105,
                'zipcode' => 780,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 1,
            ],
            [
                'id' => 106,
                'zipcode' => 781,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 1,
            ],
            [
                'id' => 107,
                'zipcode' => 782,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 1,
            ],
            [
                'id' => 108,
                'zipcode' => 773,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 1,
            ],
            [
                'id' => 109,
                'zipcode' => 751,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 1,
            ],
            [
                'id' => 110,
                'zipcode' => 753,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 1,
            ],
            [
                'id' => 111,
                'zipcode' => 762,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 1,
            ],
            [
                'id' => 112,
                'zipcode' => 786,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 1,
            ],
            [
                'id' => 113,
                'zipcode' => 926,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 0,
            ],
            [
                'id' => 114,
                'zipcode' => 927,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 0,
            ],
            [
                'id' => 115,
                'zipcode' => 928,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 0,
            ],
            [
                'id' => 116,
                'zipcode' => 900,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 0,
            ],
            [
                'id' => 117,
                'zipcode' => 910,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 0,
            ],
            [
                'id' => 118,
                'zipcode' => 911,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 0,
            ],
            [
                'id' => 119,
                'zipcode' => 912,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 0,
            ],
            [
                'id' => 120,
                'zipcode' => 913,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 0,
            ],
            [
                'id' => 121,
                'zipcode' => 915,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 0,
            ],
            [
                'id' => 122,
                'zipcode' => 916,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 0,
            ],
            [
                'id' => 123,
                'zipcode' => 918,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 119,
                'flag' => 0,
            ],
            [
                'id' => 124,
                'zipcode' => 750,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 1,
            ],
            [
                'id' => 125,
                'zipcode' => 752,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 1,
            ],
            [
                'id' => 126,
                'zipcode' => 760,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 1,
            ],
            [
                'id' => 127,
                'zipcode' => 761,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 1,
            ],
            [
                'id' => 128,
                'zipcode' => 770,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 1,
            ],
            [
                'id' => 129,
                'zipcode' => 773,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 1,
            ],
            [
                'id' => 130,
                'zipcode' => 774,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 1,
            ],
            [
                'id' => 131,
                'zipcode' => 775,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 1,
            ],
            [
                'id' => 132,
                'zipcode' => 779,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 1,
            ],
            [
                'id' => 133,
                'zipcode' => 780,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 1,
            ],
            [
                'id' => 134,
                'zipcode' => 781,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 1,
            ],
            [
                'id' => 135,
                'zipcode' => 782,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 1,
            ],
            [
                'id' => 136,
                'zipcode' => 787,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 1,
            ],
            [
                'id' => 137,
                'zipcode' => 751,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 1,
            ],
            [
                'id' => 138,
                'zipcode' => 753,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 1,
            ],
            [
                'id' => 139,
                'zipcode' => 762,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 1,
            ],
            [
                'id' => 140,
                'zipcode' => 772,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 1,
            ],
            [
                'id' => 141,
                'zipcode' => 786,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 1,
            ],
            [
                'id' => 142,
                'zipcode' => 900,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 0,
            ],
            [
                'id' => 143,
                'zipcode' => 910,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 0,
            ],
            [
                'id' => 144,
                'zipcode' => 911,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 0,
            ],
            [
                'id' => 145,
                'zipcode' => 912,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 0,
            ],
            [
                'id' => 146,
                'zipcode' => 913,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 0,
            ],
            [
                'id' => 147,
                'zipcode' => 915,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 0,
            ],
            [
                'id' => 148,
                'zipcode' => 916,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 0,
            ],
            [
                'id' => 149,
                'zipcode' => 918,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 0,
            ],
            [
                'id' => 150,
                'zipcode' => 926,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 0,
            ],
            [
                'id' => 151,
                'zipcode' => 927,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 0,
            ],
            [
                'id' => 152,
                'zipcode' => 928,
                'taxrate' => 0,
                'customermenu_id' => null,
                'menu_id' => null,
                'product_variant_id' => 160,
                'flag' => 0,
            ],
        ];

        DB::table('exceptions')->insert($dataTables);
    }
}
