<?php

namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuExtraItemsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables --limit=500
         */
        $dataTables = [
            [
                'id' => 1,
                'menu_id' => 1142,
                'items' => null,
                'menu_item' => '1092, 1094, 1138',
            ],
            [
                'id' => 2,
                'menu_id' => 445,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 3,
                'menu_id' => 446,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 4,
                'menu_id' => 432,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 5,
                'menu_id' => 428,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 6,
                'menu_id' => 1108,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 7,
                'menu_id' => 1151,
                'items' => null,
                'menu_item' => '1092, 1094, 1105',
            ],
            [
                'id' => 8,
                'menu_id' => 1220,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 9,
                'menu_id' => 1145,
                'items' => null,
                'menu_item' => '1092, 1094',
            ],
            [
                'id' => 10,
                'menu_id' => 1144,
                'items' => null,
                'menu_item' => '1092, 1094',
            ],
            [
                'id' => 11,
                'menu_id' => 1143,
                'items' => null,
                'menu_item' => '1092, 1094, 1138',
            ],
            [
                'id' => 12,
                'menu_id' => 1141,
                'items' => null,
                'menu_item' => '1092, 1094, 1138',
            ],
            [
                'id' => 13,
                'menu_id' => 1140,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 14,
                'menu_id' => 1139,
                'items' => null,
                'menu_item' => '1092, 1094, 1138',
            ],
            [
                'id' => 15,
                'menu_id' => 1138,
                'items' => null,
                'menu_item' => '1092, 1094, 1142',
            ],
            [
                'id' => 16,
                'menu_id' => 1137,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1104',
            ],
            [
                'id' => 17,
                'menu_id' => 1135,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1104',
            ],
            [
                'id' => 18,
                'menu_id' => 1136,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1104',
            ],
            [
                'id' => 19,
                'menu_id' => 1122,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 20,
                'menu_id' => 1125,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 21,
                'menu_id' => 1124,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 22,
                'menu_id' => 1123,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 23,
                'menu_id' => 1127,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 24,
                'menu_id' => 1126,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 25,
                'menu_id' => 1130,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 26,
                'menu_id' => 1146,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 27,
                'menu_id' => 1129,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 28,
                'menu_id' => 1147,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 29,
                'menu_id' => 1128,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 30,
                'menu_id' => 1148,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 31,
                'menu_id' => 1133,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 32,
                'menu_id' => 1131,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 33,
                'menu_id' => 1134,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 34,
                'menu_id' => 1132,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 35,
                'menu_id' => 1121,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1103, 1101, 1100, 1102',
            ],
            [
                'id' => 36,
                'menu_id' => 1120,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1103, 1101, 1100, 1102',
            ],
            [
                'id' => 37,
                'menu_id' => 1119,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1103, 1101, 1100, 1102',
            ],
            [
                'id' => 38,
                'menu_id' => 1118,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1103, 1101, 1100, 1102',
            ],
            [
                'id' => 39,
                'menu_id' => 1117,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1103, 1101, 1100, 1102',
            ],
            [
                'id' => 40,
                'menu_id' => 1216,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1103, 1101, 1100, 1102',
            ],
            [
                'id' => 41,
                'menu_id' => 1116,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1103, 1101, 1100, 1102',
            ],
            [
                'id' => 42,
                'menu_id' => 1115,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1103, 1101, 1100, 1102',
            ],
            [
                'id' => 43,
                'menu_id' => 1187,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1103, 1101, 1100, 1102',
            ],
            [
                'id' => 44,
                'menu_id' => 1113,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1103, 1101, 1100, 1102',
            ],
            [
                'id' => 45,
                'menu_id' => 1214,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1103, 1101, 1100, 1102',
            ],
            [
                'id' => 46,
                'menu_id' => 1107,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 47,
                'menu_id' => 1106,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 48,
                'menu_id' => 1105,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 49,
                'menu_id' => 1104,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 50,
                'menu_id' => 1103,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1094',
            ],
            [
                'id' => 51,
                'menu_id' => 1101,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1094',
            ],
            [
                'id' => 52,
                'menu_id' => 1100,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1094',
            ],
            [
                'id' => 53,
                'menu_id' => 1102,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1094',
            ],
            [
                'id' => 54,
                'menu_id' => 1249,
                'items' => null,
                'menu_item' => '1094, 1138',
            ],
            [
                'id' => 55,
                'menu_id' => 1250,
                'items' => null,
                'menu_item' => 1094,
            ],
            [
                'id' => 56,
                'menu_id' => 1253,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1103, 1101, 1100, 1102',
            ],
            [
                'id' => 57,
                'menu_id' => 1150,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 58,
                'menu_id' => 1252,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 59,
                'menu_id' => 1112,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 60,
                'menu_id' => 1099,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 61,
                'menu_id' => 1093,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 62,
                'menu_id' => 1255,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1104',
            ],
            [
                'id' => 63,
                'menu_id' => 1256,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 64,
                'menu_id' => 1257,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 65,
                'menu_id' => 1258,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 66,
                'menu_id' => 1094,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 67,
                'menu_id' => 1262,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1103, 1101, 1100, 1102',
            ],
            [
                'id' => 68,
                'menu_id' => 1263,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1103, 1101, 1100, 1102',
            ],
            [
                'id' => 69,
                'menu_id' => 1264,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1103, 1101, 1100, 1102',
            ],
            [
                'id' => 70,
                'menu_id' => 1269,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1103, 1101, 1100, 1102',
            ],
            [
                'id' => 71,
                'menu_id' => 1265,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1103, 1101, 1100, 1102',
            ],
            [
                'id' => 72,
                'menu_id' => 1267,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1103, 1101, 1100, 1102',
            ],
            [
                'id' => 73,
                'menu_id' => 1270,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1103, 1101, 1100, 1102',
            ],
            [
                'id' => 74,
                'menu_id' => 1271,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1103, 1101, 1100, 1102',
            ],
            [
                'id' => 75,
                'menu_id' => 1266,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1103, 1101, 1100, 1102',
            ],
            [
                'id' => 76,
                'menu_id' => 1268,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1103, 1101, 1100, 1102',
            ],
            [
                'id' => 77,
                'menu_id' => 1259,
                'items' => null,
                'menu_item' => '1092, 1094',
            ],
            [
                'id' => 78,
                'menu_id' => 1052,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 79,
                'menu_id' => 1085,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 80,
                'menu_id' => 1226,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 81,
                'menu_id' => 1273,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1104',
            ],
            [
                'id' => 82,
                'menu_id' => 1274,
                'items' => null,
                'menu_item' => '1093, 1099, 1095, 1104',
            ],
            [
                'id' => 83,
                'menu_id' => 1260,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 84,
                'menu_id' => 1244,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 85,
                'menu_id' => 307,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 86,
                'menu_id' => 213,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 87,
                'menu_id' => 1076,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 88,
                'menu_id' => 1057,
                'items' => null,
                'menu_item' => '1539, 1541, 1538, 1540',
            ],
            [
                'id' => 89,
                'menu_id' => 943,
                'items' => null,
                'menu_item' => '',
            ],
            [
                'id' => 90,
                'menu_id' => 4,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 91,
                'menu_id' => 1051,
                'items' => null,
                'menu_item' => '1501, 1503, 1500, 1502, 1504',
            ],
            [
                'id' => 92,
                'menu_id' => 1053,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 93,
                'menu_id' => 1054,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 94,
                'menu_id' => 1055,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 95,
                'menu_id' => 1050,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 96,
                'menu_id' => 1056,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 97,
                'menu_id' => 1217,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 98,
                'menu_id' => 1283,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 99,
                'menu_id' => 538,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 100,
                'menu_id' => 1344,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 101,
                'menu_id' => 1061,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 102,
                'menu_id' => 438,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 103,
                'menu_id' => 1074,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 104,
                'menu_id' => 1345,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 105,
                'menu_id' => 1254,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 106,
                'menu_id' => 1062,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 107,
                'menu_id' => 1063,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 108,
                'menu_id' => 1064,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 109,
                'menu_id' => 1065,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 110,
                'menu_id' => 384,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 111,
                'menu_id' => 61,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 112,
                'menu_id' => 62,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 113,
                'menu_id' => 1275,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 114,
                'menu_id' => 1021,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 115,
                'menu_id' => 1360,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 116,
                'menu_id' => 201,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 117,
                'menu_id' => 626,
                'items' => null,
                'menu_item' => null,
            ],
            [
                'id' => 118,
                'menu_id' => 1468,
                'items' => null,
                'menu_item' => '1478, 1480, 1482, 1479, 1481',
            ],
            [
                'id' => 119,
                'menu_id' => 1469,
                'items' => null,
                'menu_item' => '1478, 1480, 1482, 1479, 1481',
            ],
            [
                'id' => 120,
                'menu_id' => 1470,
                'items' => null,
                'menu_item' => '1478, 1480, 1482, 1479, 1481',
            ],
            [
                'id' => 121,
                'menu_id' => 1471,
                'items' => null,
                'menu_item' => '1478, 1480, 1482, 1479, 1481',
            ],
            [
                'id' => 122,
                'menu_id' => 1472,
                'items' => null,
                'menu_item' => '1478, 1480, 1482, 1479, 1481',
            ],
            [
                'id' => 123,
                'menu_id' => 1473,
                'items' => null,
                'menu_item' => '1478, 1480, 1482, 1479, 1481',
            ],
            [
                'id' => 124,
                'menu_id' => 1373,
                'items' => null,
                'menu_item' => '1542, 1544, 1543, 1545',
            ],
            [
                'id' => 125,
                'menu_id' => 1490,
                'items' => null,
                'menu_item' => '1542, 1544, 1541, 1543, 1545',
            ],
            [
                'id' => 126,
                'menu_id' => 1491,
                'items' => null,
                'menu_item' => '1542, 1544, 1541, 1543, 1545',
            ],
            [
                'id' => 127,
                'menu_id' => 1492,
                'items' => null,
                'menu_item' => '1542, 1544, 1541, 1543, 1545',
            ],
            [
                'id' => 128,
                'menu_id' => 1493,
                'items' => null,
                'menu_item' => '1542, 1544, 1541, 1543, 1545',
            ],
            [
                'id' => 129,
                'menu_id' => 1494,
                'items' => null,
                'menu_item' => '1542, 1544, 1541, 1543, 1545',
            ],
            [
                'id' => 130,
                'menu_id' => 1495,
                'items' => null,
                'menu_item' => '1542, 1544, 1541, 1543, 1545',
            ],
            [
                'id' => 131,
                'menu_id' => 1464,
                'items' => null,
                'menu_item' => '1506, 1505, 1507, 1504',
            ],
            [
                'id' => 132,
                'menu_id' => 1508,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 133,
                'menu_id' => 1516,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 134,
                'menu_id' => 1509,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 135,
                'menu_id' => 1510,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 136,
                'menu_id' => 1517,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 137,
                'menu_id' => 1521,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 138,
                'menu_id' => 1520,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 139,
                'menu_id' => 1449,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 140,
                'menu_id' => 1439,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 141,
                'menu_id' => 1419,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 142,
                'menu_id' => 1420,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 143,
                'menu_id' => 1440,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 144,
                'menu_id' => 1421,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 145,
                'menu_id' => 1441,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 146,
                'menu_id' => 1511,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 147,
                'menu_id' => 1512,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 148,
                'menu_id' => 1513,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 149,
                'menu_id' => 1518,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 150,
                'menu_id' => 1519,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
            [
                'id' => 151,
                'menu_id' => 1422,
                'items' => null,
                'menu_item' => '1093, 1099, 1095',
            ],
        ];

        DB::table('menu_extra_items')->insert($dataTables);
    }
}
