<?php

namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OffmenusSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables --limit=500
         */
        $dataTables = [
            [
                'id' => 1572423,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 15,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 297361,
            ],
            [
                'id' => 1572632,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 8,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 296821,
            ],
            [
                'id' => 1575145,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 12,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 297891,
            ],
            [
                'id' => 1575254,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 25,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 301540,
            ],
            [
                'id' => 1576953,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 40,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 296229,
            ],
            [
                'id' => 1579082,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 52,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 304587,
            ],
            [
                'id' => 1580200,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 45,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 296237,
            ],
            [
                'id' => 1582062,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 180,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 307263,
            ],
            [
                'id' => 1582066,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 200,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 307463,
            ],
            [
                'id' => 1582557,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 18,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 305226,
            ],
            [
                'id' => 1584979,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 20,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 310496,
            ],
            [
                'id' => 1585401,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 60,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 310260,
            ],
            [
                'id' => 1587014,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 20,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 313497,
            ],
            [
                'id' => 1589690,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 38,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 296358,
            ],
            [
                'id' => 1592361,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 38,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 296344,
            ],
            [
                'id' => 1592875,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 10,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 319319,
            ],
            [
                'id' => 1595386,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 9,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 321785,
            ],
            [
                'id' => 1595387,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 4,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 321787,
            ],
            [
                'id' => 1595388,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 7,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 321788,
            ],
            [
                'id' => 1596552,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 15,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 322975,
            ],
            [
                'id' => 1603713,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 12,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 329995,
            ],
            [
                'id' => 1603720,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 20,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 330720,
            ],
            [
                'id' => 1603905,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 21,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 296366,
            ],
            [
                'id' => 1605157,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 10,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => null,
            ],
            [
                'id' => 1605233,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 12,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 332316,
            ],
            [
                'id' => 1605349,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 8,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 332586,
            ],
            [
                'id' => 1611205,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 32,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 296352,
            ],
            [
                'id' => 1611215,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 22,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 296375,
            ],
            [
                'id' => 1611221,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 22,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 306650,
            ],
            [
                'id' => 1612332,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 40,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 337439,
            ],
            [
                'id' => 1618348,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 20,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 344965,
            ],
            [
                'id' => 1621446,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 14,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 348703,
            ],
            [
                'id' => 1622890,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 11,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 349399,
            ],
            [
                'id' => 1625012,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 40,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 351797,
            ],
            [
                'id' => 1626589,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 55,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 351483,
            ],
            [
                'id' => 1629875,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 8,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 356825,
            ],
            [
                'id' => 1638458,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 30,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 296414,
            ],
            [
                'id' => 1640078,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 10,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 366874,
            ],
            [
                'id' => 1640090,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 40,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 362180,
            ],
            [
                'id' => 1644829,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 21,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 371451,
            ],
            [
                'id' => 1645742,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 7,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 372046,
            ],
            [
                'id' => 1663527,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 40,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 388795,
            ],
            [
                'id' => 1664813,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 5,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 390170,
            ],
            [
                'id' => 1674154,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 25,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 397813,
            ],
            [
                'id' => 1676200,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 14,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 400565,
            ],
            [
                'id' => 1677701,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 25,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 400550,
            ],
            [
                'id' => 1688315,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 10,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 411580,
            ],
            [
                'id' => 1690830,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 15,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 413301,
            ],
            [
                'id' => 1705251,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 15,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 427143,
            ],
            [
                'id' => 1705255,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 15,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 427173,
            ],
            [
                'id' => 1706399,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 10,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 428457,
            ],
            [
                'id' => 1711370,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 10,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 432044,
            ],
            [
                'id' => 1716835,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 30,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 434781,
            ],
            [
                'id' => 1737026,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 10,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 454944,
            ],
            [
                'id' => 1747486,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 44,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 464746,
            ],
            [
                'id' => 1749081,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 15,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 466052,
            ],
            [
                'id' => 1749084,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 15,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 466167,
            ],
            [
                'id' => 1752316,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 20,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 463862,
            ],
            [
                'id' => 1757495,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 40,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 473262,
            ],
            [
                'id' => 1760059,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 10,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 473431,
            ],
            [
                'id' => 1764940,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 75,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 468262,
            ],
            [
                'id' => 1766025,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 18,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 474460,
            ],
            [
                'id' => 1766916,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 15,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 481876,
            ],
            [
                'id' => 1766924,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 18,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 481458,
            ],
            [
                'id' => 1769223,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 15,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 480231,
            ],
            [
                'id' => 1785158,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 22,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 473276,
            ],
            [
                'id' => 1793249,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 15,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 504216,
            ],
            [
                'id' => 1793268,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 25,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 504275,
            ],
            [
                'id' => 1793469,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 10,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 504465,
            ],
            [
                'id' => 1793555,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 10,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 504534,
            ],
            [
                'id' => 1793793,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 16,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 504697,
            ],
            [
                'id' => 1793810,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 20,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 504714,
            ],
            [
                'id' => 1794758,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 10,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 505416,
            ],
            [
                'id' => 1795357,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 25,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 505884,
            ],
            [
                'id' => 1796447,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 20,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 506773,
            ],
            [
                'id' => 1798813,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 20,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 508414,
            ],
            [
                'id' => 1801537,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 30,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 511098,
            ],
            [
                'id' => 1801579,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 50,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 511145,
            ],
            [
                'id' => 1801981,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 11,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 511469,
            ],
            [
                'id' => 1802018,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 20,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 511499,
            ],
            [
                'id' => 1802256,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 20,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 511691,
            ],
            [
                'id' => 1802456,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 50,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 511819,
            ],
            [
                'id' => 1802853,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 100,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 512029,
            ],
            [
                'id' => 1802876,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 12,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 512214,
            ],
            [
                'id' => 1802911,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 60,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 511984,
            ],
            [
                'id' => 1802948,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 75,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 512273,
            ],
            [
                'id' => 1803164,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 50,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 512460,
            ],
            [
                'id' => 1803231,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 20,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 512526,
            ],
            [
                'id' => 1803730,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 7,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 512328,
            ],
            [
                'id' => 1803802,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 5,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 512977,
            ],
            [
                'id' => 1803898,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 7,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 513070,
            ],
            [
                'id' => 1804208,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 30,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 513306,
            ],
            [
                'id' => 1804385,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 10,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 513439,
            ],
            [
                'id' => 1804431,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 10,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 513489,
            ],
            [
                'id' => 1804552,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 5,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 513585,
            ],
            [
                'id' => 1804793,
                'order_id' => null,
                'comments' => null,
                'price' => 0,
                'qty' => 19,
                'txbl' => 1,
                'flag' => 6,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => 1,
                'cart_id' => 513776,
            ],
            [
                'id' => 1805086,
                'order_id' => 2150210,
                'comments' => 'Tableware - Plates/Bowls (8], Napkins (8], Utensils (8]',
                'price' => 0,
                'qty' => 1,
                'txbl' => 1,
                'flag' => 1,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => null,
                'cart_id' => 514055,
            ],
            [
                'id' => 1805087,
                'order_id' => 2150210,
                'comments' => 'ezRewards promo applied via ezCater automation',
                'price' => '-66.4700',
                'qty' => 1,
                'txbl' => 1,
                'flag' => 2,
                'offmenu_credit_id' => 10,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => null,
                'cart_id' => null,
            ],
            [
                'id' => 1805088,
                'order_id' => 2150211,
                'comments' => 'A photo of all items including catering, dinnerware, and packaging must be emailed at leas',
                'price' => 0,
                'qty' => 1,
                'txbl' => 1,
                'flag' => 1,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => null,
                'cart_id' => null,
            ],
            [
                'id' => 1805089,
                'order_id' => 2150211,
                'comments' => ' packaging must be emailed at least 1 hour prior to delivery to: ChloeSuhr@oneflight.net',
                'price' => 0,
                'qty' => 1,
                'txbl' => 1,
                'flag' => 1,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => null,
                'cart_id' => null,
            ],
            [
                'id' => 1805090,
                'order_id' => 2150214,
                'comments' => '',
                'price' => '514.2000',
                'qty' => 1,
                'txbl' => 1,
                'flag' => 1,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => null,
                'cart_id' => null,
            ],
            [
                'id' => 1805091,
                'order_id' => 2150214,
                'comments' => '',
                'price' => '-148.6300',
                'qty' => 1,
                'txbl' => 1,
                'flag' => 2,
                'offmenu_credit_id' => 10,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => null,
                'cart_id' => null,
            ],
            [
                'id' => 1805092,
                'order_id' => 2150211,
                'comments' => 'add sm cup hummus(5oz] & carrots/celery(VEGAN] keep separate',
                'price' => 0,
                'qty' => 1,
                'txbl' => 1,
                'flag' => 1,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => null,
                'cart_id' => null,
            ],
            [
                'id' => 1805093,
                'order_id' => 2150218,
                'comments' => 'Tableware - Napkins (2], Utensils (2], Plates/Bowls (2]',
                'price' => 0,
                'qty' => 1,
                'txbl' => 1,
                'flag' => 1,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => null,
                'cart_id' => 514064,
            ],
            [
                'id' => 1805094,
                'order_id' => 2150218,
                'comments' => 'ezRewards promo applied via ezCater automation',
                'price' => '-35.7900',
                'qty' => 1,
                'txbl' => 1,
                'flag' => 2,
                'offmenu_credit_id' => 10,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => null,
                'cart_id' => null,
            ],
            [
                'id' => 1805095,
                'order_id' => 2150219,
                'comments' => 'Tableware - Plates/Bowls (2], Napkins (2], Utensils (2]',
                'price' => 0,
                'qty' => 1,
                'txbl' => 1,
                'flag' => 1,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => null,
                'cart_id' => 514065,
            ],
            [
                'id' => 1805096,
                'order_id' => 2150219,
                'comments' => 'ezRewards promo applied via ezCater automation',
                'price' => '-65.1500',
                'qty' => 1,
                'txbl' => 1,
                'flag' => 2,
                'offmenu_credit_id' => 10,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => null,
                'cart_id' => null,
            ],
            [
                'id' => 1805097,
                'order_id' => 2150217,
                'comments' => '',
                'price' => 616,
                'qty' => 1,
                'txbl' => 1,
                'flag' => 1,
                'offmenu_credit_id' => null,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => null,
                'cart_id' => null,
            ],
            [
                'id' => 1805098,
                'order_id' => 2150217,
                'comments' => '',
                'price' => '-178.0555',
                'qty' => 1,
                'txbl' => 1,
                'flag' => 2,
                'offmenu_credit_id' => 10,
                'coupon_id' => null,
                'vendor' => null,
                'discount' => null,
                'free_delivery' => 0,
                'serving_option_id' => null,
                'cart_id' => null,
            ],
        ];

        DB::table('offmenus')->insert($dataTables);
    }
}
