<?php

namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OjCategoriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables --limit=500
         */
        $dataTables = [
            [
                'id' => 1,
                'parent_id' => 54,
                'name' => 'Breakfast',
                'description' => 'Start your day off right by taking the stress out of early mornings with our healthy and delicious breakfast deals. ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 2,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 1,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2024-12-06 21:31:35',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 2,
                'parent_id' => 63,
                'name' => 'Pastry Packages',
                'description' => ' ',
                'visible_to_invitee' => 0,
                'type' => 1,
                'display_order' => 2,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2024-10-17 13:31:47',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2"]',
            ],
            [
                'id' => 3,
                'parent_id' => 64,
                'name' => 'Breakfast Boxes',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 1,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 1,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2024-10-17 13:30:01',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 4,
                'parent_id' => 1,
                'name' => 'Warm Selections',
                'description' => ' ',
                'visible_to_invitee' => 0,
                'type' => 1,
                'display_order' => 10,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2024-12-06 21:32:05',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2","3"]',
            ],
            [
                'id' => 5,
                'parent_id' => 1,
                'name' => 'Fresh Pastries and More',
                'description' => '  ',
                'visible_to_invitee' => 0,
                'type' => 1,
                'display_order' => 11,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2024-12-06 21:32:08',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2"]',
            ],
            [
                'id' => 6,
                'parent_id' => null,
                'name' => 'Lunch',
                'description' => 'Power up your workday with the right fuel, from premium sandwiches, powerbowls, wraps to hot plates – we’ve got you covered.',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 2,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 1,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2023-12-28 16:59:40',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 7,
                'parent_id' => null,
                'name' => 'Sandwiches, Pressatas and Wraps Buffet Packages',
                'description' => ' ',
                'visible_to_invitee' => 0,
                'type' => 1,
                'display_order' => 4,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2025-09-06 19:27:35',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2"]',
            ],
            [
                'id' => 8,
                'parent_id' => 7,
                'name' => 'Sandwich packages',
                'description' => ' ',
                'visible_to_invitee' => 0,
                'type' => 1,
                'display_order' => 1,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2024-09-15 19:22:48',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2"]',
            ],
            [
                'id' => 9,
                'parent_id' => 7,
                'name' => 'Pressata Sandwich Packages',
                'description' => ' ',
                'visible_to_invitee' => 0,
                'type' => 1,
                'display_order' => 2,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2024-09-15 19:22:53',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2"]',
            ],
            [
                'id' => 10,
                'parent_id' => 7,
                'name' => 'Wrap Packages',
                'description' => ' ',
                'visible_to_invitee' => 0,
                'type' => 1,
                'display_order' => 3,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2024-09-15 19:22:58',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2"]',
            ],
            [
                'id' => 11,
                'parent_id' => 54,
                'name' => 'Sandwiches, Pressatas and Wraps',
                'description' => ' ',
                'visible_to_invitee' => 0,
                'type' => 1,
                'display_order' => 5,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2024-10-17 13:33:03',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2"]',
            ],
            [
                'id' => 12,
                'parent_id' => 67,
                'name' => 'Sandwiches',
                'description' => '  ',
                'visible_to_invitee' => 0,
                'type' => 1,
                'display_order' => 1,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2024-10-17 13:29:45',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2"]',
            ],
            [
                'id' => 13,
                'parent_id' => 67,
                'name' => 'Pressata Sandwiches',
                'description' => ' ',
                'visible_to_invitee' => 0,
                'type' => 1,
                'display_order' => 2,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2024-10-17 13:30:50',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2"]',
            ],
            [
                'id' => 14,
                'parent_id' => 67,
                'name' => 'Wraps',
                'description' => ' ',
                'visible_to_invitee' => 0,
                'type' => 1,
                'display_order' => 3,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2024-10-17 13:32:28',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2"]',
            ],
            [
                'id' => 15,
                'parent_id' => 68,
                'name' => 'Powerbowls',
                'description' => 'These healthy superfoods in a bowl pack all of the high-protein and low-calorie macronutrients you need to fuel your day.',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 1,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 1,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2026-01-30 19:56:35',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 16,
                'parent_id' => 68,
                'name' => 'Box Meals',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 2,
                'display_order' => 2,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 1,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2025-11-10 20:29:27',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 17,
                'parent_id' => 54,
                'name' => 'Salad Bowls',
                'description' => ' ',
                'visible_to_invitee' => 0,
                'type' => 1,
                'display_order' => 6,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2024-11-11 13:40:05',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2"]',
            ],
            [
                'id' => 18,
                'parent_id' => 6,
                'name' => 'Hot Plates & Sides',
                'description' => ' ',
                'visible_to_invitee' => 0,
                'type' => 1,
                'display_order' => 3,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2023-12-28 16:54:04',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2","3"]',
            ],
            [
                'id' => 19,
                'parent_id' => 65,
                'name' => 'Italian Flavors',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 1,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2024-10-17 13:30:08',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2","3"]',
            ],
            [
                'id' => 20,
                'parent_id' => 65,
                'name' => 'Comfort Food',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 2,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2024-10-17 13:31:41',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2","3"]',
            ],
            [
                'id' => 21,
                'parent_id' => 65,
                'name' => 'Cantina Menu',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 3,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2024-10-17 13:32:37',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2","3"]',
            ],
            [
                'id' => 22,
                'parent_id' => 54,
                'name' => 'Scratch-Made Sides',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 4,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2024-10-17 13:32:41',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2","3"]',
            ],
            [
                'id' => 23,
                'parent_id' => 57,
                'name' => 'Desserts',
                'description' => 'Brownies, cheesecake,  oh my! Cap off a delicious meal with a sweet treat, because you deserve it. ',
                'visible_to_invitee' => 0,
                'type' => 1,
                'display_order' => 10,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2025-09-06 19:30:29',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2"]',
            ],
            [
                'id' => 24,
                'parent_id' => 69,
                'name' => 'Beverages',
                'description' => ' ',
                'visible_to_invitee' => 0,
                'type' => 1,
                'display_order' => 4,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2024-10-17 13:32:44',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 25,
                'parent_id' => null,
                'name' => 'Warm Cookies',
                'description' => 'Warm cookies are perfect for any occasion!',
                'visible_to_invitee' => 0,
                'type' => 1,
                'display_order' => 5,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2020-07-17 20:02:05',
                'deleted_at' => null,
                'delivery_exception' => 1,
                'serving_options' => '',
            ],
            [
                'id' => 26,
                'parent_id' => null,
                'name' => 'Cookies',
                'description' => 'Warm, fresh cookies delivered just for you!',
                'visible_to_invitee' => 0,
                'type' => 1,
                'display_order' => 1,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2020-07-17 20:11:42',
                'deleted_at' => null,
                'delivery_exception' => 1,
                'serving_options' => '',
            ],
            [
                'id' => 27,
                'parent_id' => null,
                'name' => 'Special Occasion Packaging',
                'description' => 'Want to make it extra special? Customize your order with our special occasion packaging!',
                'visible_to_invitee' => 0,
                'type' => 1,
                'display_order' => 2,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2020-07-17 20:11:26',
                'deleted_at' => null,
                'delivery_exception' => 1,
                'serving_options' => '',
            ],
            [
                'id' => 28,
                'parent_id' => null,
                'name' => 'Snacks and Hors D\'Oeuvres',
                'description' => ' ',
                'visible_to_invitee' => 0,
                'type' => 1,
                'display_order' => 6,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2025-09-06 19:29:08',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 29,
                'parent_id' => null,
                'name' => 'Value-Added Package Deal Extras',
                'description' => 'Value-Added Package Deal Extras',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 7,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 2,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2019-11-20 13:36:49',
                'updated_at' => '2024-10-17 13:33:19',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 30,
                'parent_id' => 65,
                'name' => 'Soups',
                'description' => 'Your choice of creamy Italian wedding or tomato basil ',
                'visible_to_invitee' => 0,
                'type' => 1,
                'display_order' => 7,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 0,
                'invitee_default_meal' => 0,
                'created_at' => '2019-12-20 19:02:25',
                'updated_at' => '2025-05-14 20:11:41',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2"]',
            ],
            [
                'id' => 31,
                'parent_id' => 6,
                'name' => 'Soups  (DO NOT USE]',
                'description' => 'Your choice of hearty beef chili or delicious broccoli cheddar cheese soup.',
                'visible_to_invitee' => 0,
                'type' => 1,
                'display_order' => 10,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2019-12-20 19:05:53',
                'updated_at' => '2023-04-29 18:10:19',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '',
            ],
            [
                'id' => 32,
                'parent_id' => 6,
                'name' => 'Soba Noodles',
                'description' => '    ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 0,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2020-09-01 20:38:03',
                'updated_at' => '2025-12-07 07:43:07',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 33,
                'parent_id' => null,
                'name' => 'Holiday Menu',
                'description' => 'Our holiday classics are back! ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 0,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 2,
                'available_all_store' => 1,
                'invitee_default_meal' => 1,
                'created_at' => '2020-09-27 13:57:04',
                'updated_at' => '2026-01-06 17:13:36',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 34,
                'parent_id' => null,
                'name' => 'Holiday Box Lunches',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 1,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 2,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2020-09-27 14:16:09',
                'updated_at' => '2024-01-02 20:12:07',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 35,
                'parent_id' => null,
                'name' => 'Holiday Breakfast Boxes',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 7,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 1,
                'created_at' => '2020-09-27 14:17:08',
                'updated_at' => '2024-12-27 21:26:56',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 36,
                'parent_id' => null,
                'name' => 'Holiday Hot Plates',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 2,
                'display_order' => 20,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 2,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2020-09-27 14:19:48',
                'updated_at' => '2024-01-02 20:13:29',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 37,
                'parent_id' => null,
                'name' => 'Heat and Serve at Home',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 4,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2020-09-27 14:21:27',
                'updated_at' => '2021-09-06 22:16:57',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '',
            ],
            [
                'id' => 38,
                'parent_id' => 33,
                'name' => 'Potluck Entrées ',
                'description' => 'A la carte slection of our favorites.',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 10,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2020-09-27 14:27:47',
                'updated_at' => '2025-12-10 18:36:42',
                'deleted_at' => '2020-09-27 16:58:06',
                'delivery_exception' => 0,
                'serving_options' => '',
            ],
            [
                'id' => 39,
                'parent_id' => null,
                'name' => 'Holiday Snacks',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 9,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2020-09-27 14:51:27',
                'updated_at' => '2024-01-02 20:13:18',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 40,
                'parent_id' => null,
                'name' => 'Holiday Sweets',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 10,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 1,
                'created_at' => '2020-09-27 14:52:27',
                'updated_at' => '2026-01-08 13:13:52',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2"]',
            ],
            [
                'id' => 41,
                'parent_id' => null,
                'name' => 'Holiday Favorites',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 1,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2020-09-27 17:05:48',
                'updated_at' => '2026-01-08 13:13:40',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2","3"]',
            ],
            [
                'id' => 42,
                'parent_id' => null,
                'name' => 'Potluck Sides',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 2,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2020-09-27 17:06:19',
                'updated_at' => '2026-01-08 13:13:44',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2","3"]',
            ],
            [
                'id' => 43,
                'parent_id' => null,
                'name' => 'Potluck Entrées',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 2,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2020-09-27 21:28:03',
                'updated_at' => '2026-01-08 13:13:49',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2","3"]',
            ],
            [
                'id' => 44,
                'parent_id' => 68,
                'name' => 'Steak Salads',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 2,
                'display_order' => 0,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2021-02-10 13:15:19',
                'updated_at' => '2024-10-31 14:31:33',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 45,
                'parent_id' => null,
                'name' => 'Steak Salads',
                'description' => 'New and just for Austin, try Alonti\'s steak salads!',
                'visible_to_invitee' => 0,
                'type' => 2,
                'display_order' => 0,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 0,
                'invitee_default_meal' => 0,
                'created_at' => '2021-03-17 05:03:21',
                'updated_at' => '2023-01-06 19:53:49',
                'deleted_at' => '2023-01-06 19:53:49',
                'delivery_exception' => 0,
                'serving_options' => '',
            ],
            [
                'id' => 46,
                'parent_id' => null,
                'name' => 'Holiday Beverages',
                'description' => 'Delicious and refreshing beverages sure to bring holiday cheer!',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 8,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2021-09-06 22:48:53',
                'updated_at' => '2024-12-27 21:27:00',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 47,
                'parent_id' => null,
                'name' => 'Holiday Breakfast Packages',
                'description' => 'Breakfast packages that will excite during the holidays!',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 2,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2021-09-06 23:03:20',
                'updated_at' => '2024-12-27 21:26:52',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2","3"]',
            ],
            [
                'id' => 48,
                'parent_id' => null,
                'name' => 'Holiday Party Snacks & Hors d\'Oeuvres',
                'description' => 'The perfect start to any event!',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 10,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2021-09-06 23:13:18',
                'updated_at' => '2026-01-08 13:13:56',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2","3"]',
            ],
            [
                'id' => 49,
                'parent_id' => 64,
                'name' => 'Breakfast Bowls',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 0,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2022-04-01 20:21:47',
                'updated_at' => '2024-07-26 17:12:17',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 50,
                'parent_id' => 6,
                'name' => 'Steak Salads',
                'description' => 'Our two delicious and premium steak salads are lunch, elevated.',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 1,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 2,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2023-01-06 19:52:14',
                'updated_at' => '2023-01-06 19:53:07',
                'deleted_at' => '2023-01-06 19:53:07',
                'delivery_exception' => 0,
                'serving_options' => '',
            ],
            [
                'id' => 51,
                'parent_id' => 24,
                'name' => 'Iced Coffee',
                'description' => 'Our new Iced Coffees, Lattes, and Cold Brew are the best way to start your morning, or perk up the afternoon meeting!',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 2,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 0,
                'invitee_default_meal' => 0,
                'created_at' => '2023-01-06 21:35:49',
                'updated_at' => '2023-01-06 21:36:45',
                'deleted_at' => '2023-01-06 21:36:45',
                'delivery_exception' => 0,
                'serving_options' => '',
            ],
            [
                'id' => 52,
                'parent_id' => null,
                'name' => 'Summer Picnic Menu',
                'description' => 'Indulge in our summer picnic menu: fresh, vibrant flavors expertly crafted, perfect for any Summer Day!',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 8,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2023-04-24 15:47:50',
                'updated_at' => '2025-09-01 18:07:09',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 53,
                'parent_id' => 52,
                'name' => 'Summer Classic Meal Deal',
                'description' => 'Timeless classics ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 1,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2023-04-24 15:54:44',
                'updated_at' => '2025-04-16 13:06:05',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 54,
                'parent_id' => null,
                'name' => 'A la Carte ',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 10,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2023-04-24 17:26:50',
                'updated_at' => '2025-09-06 19:30:52',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2","3"]',
            ],
            [
                'id' => 55,
                'parent_id' => 52,
                'name' => 'Accompaniments',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 2,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2023-04-24 17:35:17',
                'updated_at' => '2024-04-12 20:20:53',
                'deleted_at' => '2024-04-12 20:20:53',
                'delivery_exception' => 0,
                'serving_options' => '["1","2","3"]',
            ],
            [
                'id' => 56,
                'parent_id' => 52,
                'name' => 'Summer Picnic A La Carte',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 3,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 0,
                'invitee_default_meal' => 0,
                'created_at' => '2023-04-24 17:52:47',
                'updated_at' => '2025-04-16 13:44:44',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2","3"]',
            ],
            [
                'id' => 57,
                'parent_id' => null,
                'name' => 'Desserts',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 9,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2023-04-24 18:04:35',
                'updated_at' => '2024-10-17 13:33:33',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2"]',
            ],
            [
                'id' => 58,
                'parent_id' => null,
                'name' => 'Summer Picnic Beverages',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 5,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 0,
                'invitee_default_meal' => 0,
                'created_at' => '2023-04-24 18:13:39',
                'updated_at' => '2024-10-17 12:16:42',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 59,
                'parent_id' => 6,
                'name' => 'Italian Classics Sandwiches',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 3,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 0,
                'invitee_default_meal' => 0,
                'created_at' => '2023-07-31 01:01:49',
                'updated_at' => '2023-07-31 01:14:06',
                'deleted_at' => '2023-07-31 01:14:06',
                'delivery_exception' => 0,
                'serving_options' => '',
            ],
            [
                'id' => 60,
                'parent_id' => 33,
                'name' => 'Feliz Navidad',
                'description' => 'Indulge in our "Feliz Navidad" Holiday Menu! Choose from sizzling Fajitas, a customizable Taco Bar, Chicken Verde Casserole, or classic Enchiladas. Complete your meal with two sides and a dessert for a festive fusion of Mexican flavors and Holiday spirit.',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 2,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2023-09-07 18:46:20',
                'updated_at' => '2025-12-10 18:36:42',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2","3"]',
            ],
            [
                'id' => 61,
                'parent_id' => 63,
                'name' => 'Hot Breakfast Packages',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 4,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2023-09-29 20:24:08',
                'updated_at' => '2024-10-17 13:32:48',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2","3"]',
            ],
            [
                'id' => 62,
                'parent_id' => 63,
                'name' => 'Sandwich & Taco Packages',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 5,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2023-09-29 20:41:23',
                'updated_at' => '2024-10-17 13:33:07',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2"]',
            ],
            [
                'id' => 63,
                'parent_id' => null,
                'name' => 'Breakfast Buffet Packages',
                'description' => '  ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 1,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2023-12-27 18:52:50',
                'updated_at' => '2025-09-23 12:35:36',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2","3"]',
            ],
            [
                'id' => 64,
                'parent_id' => null,
                'name' => 'Individual Breakfast Boxed Meals',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 2,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2023-12-27 18:53:42',
                'updated_at' => '2025-09-06 19:26:09',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 65,
                'parent_id' => null,
                'name' => 'Hot Buffet Packages ',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 3,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2023-12-27 18:54:06',
                'updated_at' => '2025-09-06 19:26:57',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 66,
                'parent_id' => null,
                'name' => 'A La Carte1',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 7,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2023-12-27 20:02:22',
                'updated_at' => '2023-12-27 20:10:49',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 67,
                'parent_id' => 54,
                'name' => 'Premium Sandwich Trays',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 3,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2023-12-27 21:36:42',
                'updated_at' => '2024-10-17 13:32:23',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 68,
                'parent_id' => null,
                'name' => 'Individual Boxed Meals',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 5,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2023-12-28 18:31:17',
                'updated_at' => '2025-09-06 19:28:10',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 69,
                'parent_id' => null,
                'name' => 'Beverages',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 12,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2024-01-05 21:43:37',
                'updated_at' => '2025-09-06 19:31:25',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 70,
                'parent_id' => null,
                'name' => 'Summer Fajitas Meal Deal',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 2,
                'status' => 0,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2024-04-12 20:19:21',
                'updated_at' => '2024-10-17 12:16:26',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2","3"]',
            ],
            [
                'id' => 71,
                'parent_id' => 52,
                'name' => 'Summer Picnic Desserts',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 4,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 0,
                'invitee_default_meal' => 0,
                'created_at' => '2024-04-12 20:24:38',
                'updated_at' => '2025-04-16 14:08:20',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 72,
                'parent_id' => null,
                'name' => 'Vegetarian, Vegan, Keto, Gluten-Free Individual Meals',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 5,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2024-04-16 17:29:03',
                'updated_at' => '2025-09-06 19:28:32',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 73,
                'parent_id' => 72,
                'name' => 'Vegetarian',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 1,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2024-04-16 17:30:53',
                'updated_at' => '2026-02-09 06:42:42',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 74,
                'parent_id' => 72,
                'name' => 'Vegan',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 2,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2024-04-16 17:31:19',
                'updated_at' => '2024-10-17 13:32:00',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 75,
                'parent_id' => 72,
                'name' => 'Gluten-Friendly',
                'description' => '  ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 3,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2024-04-16 17:31:52',
                'updated_at' => '2024-10-17 13:32:33',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 76,
                'parent_id' => 33,
                'name' => 'Buon Natale',
                'description' => 'An Italian Christmas from Alonti!',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 2,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2024-09-14 19:02:20',
                'updated_at' => '2025-12-10 18:36:42',
                'deleted_at' => '2024-09-14 19:07:13',
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 77,
                'parent_id' => 7,
                'name' => 'Packages',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 1,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2024-09-15 14:11:56',
                'updated_at' => '2024-10-16 20:43:00',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '["1","2"]',
            ],
            [
                'id' => 78,
                'parent_id' => 52,
                'name' => 'Summer Individual Boxed Meal',
                'description' => ' ',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 10,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2025-04-16 14:27:48',
                'updated_at' => '2025-04-16 14:27:48',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 79,
                'parent_id' => null,
                'name' => 'Screaming Hot Deals!',
                'description' => 'Six of our best-selling menu items, crafted with premium ingredients, now available at special reduced pricing while supplies last!',
                'visible_to_invitee' => 1,
                'type' => 1,
                'display_order' => 1,
                'status' => 1,
                'is_discount_free' => 1,
                'display_status' => 1,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2025-12-29 20:07:26',
                'updated_at' => '2026-01-05 16:18:06',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
            [
                'id' => 80,
                'parent_id' => null,
                'name' => 'Screaming Hot Deals - Full Price for Cookie Comps',
                'description' => ' ',
                'visible_to_invitee' => 0,
                'type' => 1,
                'display_order' => 1000,
                'status' => 1,
                'is_discount_free' => 0,
                'display_status' => 2,
                'available_all_store' => 1,
                'invitee_default_meal' => 0,
                'created_at' => '2026-01-06 18:39:26',
                'updated_at' => '2026-01-06 19:45:37',
                'deleted_at' => null,
                'delivery_exception' => 0,
                'serving_options' => '[""]',
            ],
        ];

        DB::table('oj_categories')->insert($dataTables);
    }
}
