<?php

namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OjCartItemsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables --limit=500
         */
        $dataTables = [
            [
                'id' => 2131433,
                'cart_id' => 510945,
                'category_id' => 74,
                'product_id' => 372,
                'product_variant_id' => 397,
                'product_package_id' => null,
                'package_price' => null,
                'package_size' => null,
                'product_dietary_id' => null,
                'quantity' => 2,
                'serve' => null,
                'unit_price' => '15.50',
                'discount' => null,
                'total' => 38,
                'product_description' => '<p>Roasted kale, red quinoa, roasted sweet potatoes, black beans, avocado, green onions, cilantro, roasted red peppers, and roasted tortilla strips served with a roasted tomato and jalape&ntilde;o vinaigrette.</p>
',
                'who_is_this_for' => '',
                'special_instruction' => null,
                'box_lunch_type' => 0,
                'product_name' => 'VEGAN POWERBOWL',
                'state_price_id' => 28061,
                'invitee_id' => null,
                'is_invitee_default_meal' => 0,
                'package_state_price_id' => null,
                'created_at' => '2026-01-20 05:36:24',
                'updated_at' => '2026-01-20 05:51:38',
                'deleted_at' => null,
                'free_delivery' => 0,
                'free_item_id' => null,
                'addon_cartitem_id' => null,
                'is_free_item' => 0,
            ],
            [
                'id' => 2131434,
                'cart_id' => 510945,
                'category_id' => 77,
                'product_id' => 398,
                'product_variant_id' => 423,
                'product_package_id' => null,
                'package_price' => null,
                'package_size' => null,
                'product_dietary_id' => null,
                'quantity' => 45,
                'serve' => null,
                'unit_price' => '17.73',
                'discount' => null,
                'total' => '797.85',
                'product_description' => '<p>Our Platinum package deal is our <strong>Premier </strong>offering and the best way to make your event memorable.&nbsp; Starting with your choice of 12 half Sandwiches, Wraps, or Pressatas, any of two of our exceptional sides, and the best part is your choice of any of our fantastic dessert options. You can easily add in increments of 5.</p>
',
                'who_is_this_for' => '',
                'special_instruction' => null,
                'box_lunch_type' => 0,
                'product_name' => 'Platinum: 2 sides & 1 dessert choice',
                'state_price_id' => 27737,
                'invitee_id' => null,
                'is_invitee_default_meal' => 0,
                'package_state_price_id' => null,
                'created_at' => '2026-01-20 05:47:35',
                'updated_at' => '2026-01-20 05:53:15',
                'deleted_at' => null,
                'free_delivery' => 0,
                'free_item_id' => null,
                'addon_cartitem_id' => null,
                'is_free_item' => 0,
            ],
            [
                'id' => 2131435,
                'cart_id' => 510945,
                'category_id' => 28,
                'product_id' => 137,
                'product_variant_id' => 153,
                'product_package_id' => null,
                'package_price' => null,
                'package_size' => null,
                'product_dietary_id' => null,
                'quantity' => 1,
                'serve' => null,
                'unit_price' => '73.90',
                'discount' => null,
                'total' => '73.90',
                'product_description' => '<p>Fresh, hand-sliced pineapple, cantaloupe, honeydew, watermelon, grapes, strawberries and blackberries.</p>
',
                'who_is_this_for' => '',
                'special_instruction' => null,
                'box_lunch_type' => 0,
                'product_name' => 'Premium Sliced Fruit Tray',
                'state_price_id' => 26817,
                'invitee_id' => null,
                'is_invitee_default_meal' => 0,
                'package_state_price_id' => null,
                'created_at' => '2026-01-20 05:50:15',
                'updated_at' => '2026-01-20 05:50:15',
                'deleted_at' => null,
                'free_delivery' => 0,
                'free_item_id' => null,
                'addon_cartitem_id' => null,
                'is_free_item' => 0,
            ],
            [
                'id' => 2131436,
                'cart_id' => 510945,
                'category_id' => 28,
                'product_id' => 150,
                'product_variant_id' => 166,
                'product_package_id' => null,
                'package_price' => null,
                'package_size' => null,
                'product_dietary_id' => null,
                'quantity' => 1,
                'serve' => null,
                'unit_price' => '83.20',
                'discount' => null,
                'total' => '83.20',
                'product_description' => '<p>An assortment of crisp, fresh vegetables with ranch dip.</p>
',
                'who_is_this_for' => '',
                'special_instruction' => null,
                'box_lunch_type' => 0,
                'product_name' => 'Vegetable Crudite',
                'state_price_id' => 26867,
                'invitee_id' => null,
                'is_invitee_default_meal' => 0,
                'package_state_price_id' => null,
                'created_at' => '2026-01-20 06:01:06',
                'updated_at' => '2026-01-20 06:01:06',
                'deleted_at' => null,
                'free_delivery' => 0,
                'free_item_id' => null,
                'addon_cartitem_id' => null,
                'is_free_item' => 0,
            ],
            [
                'id' => 2143166,
                'cart_id' => 514383,
                'category_id' => 3,
                'product_id' => 10,
                'product_variant_id' => 10,
                'product_package_id' => null,
                'package_price' => null,
                'package_size' => null,
                'product_dietary_id' => null,
                'quantity' => 1,
                'serve' => null,
                'unit_price' => '13.90',
                'discount' => null,
                'total' => '13.90',
                'product_description' => '<p>Your choice of bacon, honey ham, sausage or vegetarian, with scrambled eggs and cheddar cheese on a ciabatta roll. Includes fresh fruit.</p>
',
                'who_is_this_for' => '',
                'special_instruction' => null,
                'box_lunch_type' => 0,
                'product_name' => 'Ciabatta Breakfast Sandwich Box',
                'state_price_id' => 26386,
                'invitee_id' => null,
                'is_invitee_default_meal' => 0,
                'package_state_price_id' => null,
                'created_at' => '2026-02-13 03:15:02',
                'updated_at' => '2026-02-13 03:15:54',
                'deleted_at' => null,
                'free_delivery' => 0,
                'free_item_id' => null,
                'addon_cartitem_id' => null,
                'is_free_item' => 0,
            ],
        ];

        DB::table('oj_cart_items')->insert($dataTables);
    }
}
