<?php

namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PrepStationsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables --limit=500
         */
        $dataTables = [
            [
                'id' => 5,
                'prep_category_id' => 2,
                'name' => 'Tacos',
                'status' => 'active',
                'bgcolor' => '#b7d1f4',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-03-27 15:32:35',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 5,
            ],
            [
                'id' => 6,
                'prep_category_id' => 2,
                'name' => 'Ciabattas',
                'status' => 'active',
                'bgcolor' => '#d2d2e0',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-03-27 15:42:55',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 6,
            ],
            [
                'id' => 7,
                'prep_category_id' => 2,
                'name' => 'Croissants',
                'status' => 'active',
                'bgcolor' => '#b7d1f4',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-03-27 15:43:08',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 7,
            ],
            [
                'id' => 8,
                'prep_category_id' => 2,
                'name' => 'Burritos',
                'status' => 'active',
                'bgcolor' => '#d2d2e0',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-03-27 15:43:29',
                'updated_at' => '2025-01-29 21:50:09',
                'deleted_by' => 175889,
                'deleted_at' => '2025-01-29 21:50:09',
                'display_order' => 8,
            ],
            [
                'id' => 9,
                'prep_category_id' => 10,
                'name' => 'Box Lunches',
                'status' => 'active',
                'bgcolor' => '#bcccf1',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-04-10 17:19:30',
                'updated_at' => '2023-05-19 14:22:01',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 1,
            ],
            [
                'id' => 10,
                'prep_category_id' => 10,
                'name' => 'Box Lunch Sides',
                'status' => 'active',
                'bgcolor' => '#bcddf4',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-04-10 17:19:45',
                'updated_at' => '2023-07-17 15:06:32',
                'deleted_by' => 175889,
                'deleted_at' => '2023-07-17 15:06:32',
                'display_order' => 2,
            ],
            [
                'id' => 11,
                'prep_category_id' => 10,
                'name' => 'Power Bowls',
                'status' => 'active',
                'bgcolor' => '#a2acdb',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-04-10 17:20:05',
                'updated_at' => '2023-05-19 14:22:21',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 3,
            ],
            [
                'id' => 12,
                'prep_category_id' => 10,
                'name' => 'Other',
                'status' => 'active',
                'bgcolor' => '#e3d6f9',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-04-10 17:20:19',
                'updated_at' => '2023-07-17 15:06:27',
                'deleted_by' => 175889,
                'deleted_at' => '2023-07-17 15:06:27',
                'display_order' => 4,
            ],
            [
                'id' => 13,
                'prep_category_id' => 3,
                'name' => 'Pastries',
                'status' => 'active',
                'bgcolor' => '#52ff7f',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-04-10 17:22:04',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 1,
            ],
            [
                'id' => 14,
                'prep_category_id' => 3,
                'name' => 'Sides',
                'status' => 'active',
                'bgcolor' => '#c8a0fe',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-04-10 17:22:25',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 2,
            ],
            [
                'id' => 15,
                'prep_category_id' => 3,
                'name' => 'Hors d&#039;Oeuvres',
                'status' => 'active',
                'bgcolor' => '#4afe4e',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-04-10 17:22:51',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 3,
            ],
            [
                'id' => 16,
                'prep_category_id' => 3,
                'name' => 'Desserts',
                'status' => 'active',
                'bgcolor' => '#c8a0fe',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-04-10 17:23:05',
                'updated_at' => '2023-05-19 14:26:14',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 4,
            ],
            [
                'id' => 17,
                'prep_category_id' => 3,
                'name' => 'Drinks',
                'status' => 'active',
                'bgcolor' => '#2eff7e',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-04-10 17:23:18',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 5,
            ],
            [
                'id' => 18,
                'prep_category_id' => 4,
                'name' => 'Breakfast',
                'status' => 'active',
                'bgcolor' => '#e4fc35',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-04-10 17:23:45',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 1,
            ],
            [
                'id' => 19,
                'prep_category_id' => 4,
                'name' => 'Lunch',
                'status' => 'active',
                'bgcolor' => '#1cef13',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-04-10 17:24:02',
                'updated_at' => '2023-05-19 14:28:14',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 2,
            ],
            [
                'id' => 20,
                'prep_category_id' => 5,
                'name' => 'Breakfast',
                'status' => 'inactive',
                'bgcolor' => '#e0ff00',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-04-10 17:24:37',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 1,
            ],
            [
                'id' => 21,
                'prep_category_id' => 5,
                'name' => 'Sides',
                'status' => 'active',
                'bgcolor' => '#00f740',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-04-10 17:29:13',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 2,
            ],
            [
                'id' => 22,
                'prep_category_id' => 5,
                'name' => 'Miscellaneous',
                'status' => 'active',
                'bgcolor' => '#fc8a6a',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-04-10 17:29:37',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 3,
            ],
            [
                'id' => 23,
                'prep_category_id' => 5,
                'name' => 'Bread',
                'status' => 'active',
                'bgcolor' => '#fbffc7',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-04-10 17:29:55',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 4,
            ],
            [
                'id' => 24,
                'prep_category_id' => 6,
                'name' => 'Breakfast',
                'status' => 'active',
                'bgcolor' => '#ffc2ca',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-04-10 17:30:21',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 1,
            ],
            [
                'id' => 25,
                'prep_category_id' => 6,
                'name' => 'Lunch',
                'status' => 'active',
                'bgcolor' => '#f9b337',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-04-10 17:30:34',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 2,
            ],
            [
                'id' => 26,
                'prep_category_id' => 6,
                'name' => 'Bread',
                'status' => 'active',
                'bgcolor' => '#fa80ff',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-04-10 17:30:46',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 3,
            ],
            [
                'id' => 27,
                'prep_category_id' => 7,
                'name' => 'Traditional',
                'status' => 'active',
                'bgcolor' => '#b8c8fc',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-04-10 17:40:19',
                'updated_at' => '2023-05-19 14:34:06',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 1,
            ],
            [
                'id' => 28,
                'prep_category_id' => 7,
                'name' => 'Milano Premium',
                'status' => 'active',
                'bgcolor' => '#91edff',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-04-10 17:40:42',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 2,
            ],
            [
                'id' => 29,
                'prep_category_id' => 7,
                'name' => 'Venetian Premium',
                'status' => 'active',
                'bgcolor' => '#ffc357',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-04-10 17:40:59',
                'updated_at' => '2023-05-19 14:34:39',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 3,
            ],
            [
                'id' => 30,
                'prep_category_id' => 7,
                'name' => 'Miscellaneous',
                'status' => 'active',
                'bgcolor' => '#85ceff',
                'created_by' => 175889,
                'updated_by' => null,
                'created_at' => '2023-04-10 17:41:15',
                'updated_at' => '2023-04-10 17:41:15',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 4,
            ],
            [
                'id' => 31,
                'prep_category_id' => 8,
                'name' => 'Milano Pressatas',
                'status' => 'active',
                'bgcolor' => '#f7c95e',
                'created_by' => 175889,
                'updated_by' => null,
                'created_at' => '2023-04-10 17:47:00',
                'updated_at' => '2023-04-10 17:47:00',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 1,
            ],
            [
                'id' => 32,
                'prep_category_id' => 8,
                'name' => 'Venetian Pressatas',
                'status' => 'active',
                'bgcolor' => '#f7e3c0',
                'created_by' => 175889,
                'updated_by' => null,
                'created_at' => '2023-04-10 17:47:21',
                'updated_at' => '2023-04-10 17:47:21',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 2,
            ],
            [
                'id' => 33,
                'prep_category_id' => 8,
                'name' => 'Milano Wrap',
                'status' => 'active',
                'bgcolor' => '#ffd654',
                'created_by' => 175889,
                'updated_by' => null,
                'created_at' => '2023-04-10 17:53:19',
                'updated_at' => '2023-04-10 17:53:19',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 3,
            ],
            [
                'id' => 34,
                'prep_category_id' => 8,
                'name' => 'Venetian Wraps',
                'status' => 'active',
                'bgcolor' => '#fff1e6',
                'created_by' => 175889,
                'updated_by' => null,
                'created_at' => '2023-04-10 17:54:58',
                'updated_at' => '2023-04-10 17:54:58',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 4,
            ],
            [
                'id' => 35,
                'prep_category_id' => 8,
                'name' => 'Miscellaneous',
                'status' => 'active',
                'bgcolor' => '#fef782',
                'created_by' => 175889,
                'updated_by' => null,
                'created_at' => '2023-04-10 17:55:16',
                'updated_at' => '2023-04-10 17:55:16',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 5,
            ],
            [
                'id' => 36,
                'prep_category_id' => 9,
                'name' => 'Leafy Salads',
                'status' => 'active',
                'bgcolor' => '#91fe9a',
                'created_by' => 175889,
                'updated_by' => null,
                'created_at' => '2023-04-10 17:55:44',
                'updated_at' => '2023-04-10 17:55:44',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 1,
            ],
            [
                'id' => 37,
                'prep_category_id' => 9,
                'name' => 'Salad Bowls',
                'status' => 'active',
                'bgcolor' => '#ffae3d',
                'created_by' => 175889,
                'updated_by' => null,
                'created_at' => '2023-04-10 17:56:00',
                'updated_at' => '2023-04-10 17:56:00',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 2,
            ],
            [
                'id' => 38,
                'prep_category_id' => 11,
                'name' => 'Gluten Free Breakfast Box',
                'status' => 'active',
                'bgcolor' => '#cb6666',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-05-19 14:53:45',
                'updated_at' => '2023-05-26 19:48:58',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 1,
            ],
            [
                'id' => 39,
                'prep_category_id' => 12,
                'name' => 'Gluten Free Traditional',
                'status' => 'active',
                'bgcolor' => '#7484fc',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-05-19 14:56:09',
                'updated_at' => '2023-05-26 19:49:16',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 1,
            ],
            [
                'id' => 40,
                'prep_category_id' => 12,
                'name' => 'Gluten Free Premium',
                'status' => 'active',
                'bgcolor' => '#e7e745',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-05-19 14:56:44',
                'updated_at' => '2023-05-26 19:49:23',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 2,
            ],
            [
                'id' => 41,
                'prep_category_id' => 12,
                'name' => 'Gluten Free Venetian ',
                'status' => 'active',
                'bgcolor' => '#24fe50',
                'created_by' => 175889,
                'updated_by' => null,
                'created_at' => '2023-05-19 14:57:07',
                'updated_at' => '2023-05-26 17:53:58',
                'deleted_by' => 175889,
                'deleted_at' => '2023-05-26 17:53:58',
                'display_order' => 3,
            ],
            [
                'id' => 42,
                'prep_category_id' => 3,
                'name' => 'Individual Muffin',
                'status' => 'active',
                'bgcolor' => '#edabff',
                'created_by' => 175889,
                'updated_by' => null,
                'created_at' => '2023-05-19 18:04:20',
                'updated_at' => '2023-05-19 18:04:20',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 6,
            ],
            [
                'id' => 43,
                'prep_category_id' => 4,
                'name' => 'Enchilada Topping',
                'status' => 'active',
                'bgcolor' => '#ff8282',
                'created_by' => 175889,
                'updated_by' => null,
                'created_at' => '2023-05-31 22:31:51',
                'updated_at' => '2023-06-01 02:29:35',
                'deleted_by' => 175889,
                'deleted_at' => '2023-06-01 02:29:35',
                'display_order' => 3,
            ],
            [
                'id' => 44,
                'prep_category_id' => 13,
                'name' => 'South of the Border',
                'status' => 'active',
                'bgcolor' => '#8cfd7d',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-06-01 02:10:42',
                'updated_at' => '2023-06-01 02:57:15',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => '',
            ],
            [
                'id' => 45,
                'prep_category_id' => 14,
                'name' => 'Box Lunch Sides',
                'status' => 'active',
                'bgcolor' => '#86e27c',
                'created_by' => 175889,
                'updated_by' => null,
                'created_at' => '2023-07-17 14:53:23',
                'updated_at' => '2023-07-17 14:53:23',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 1,
            ],
            [
                'id' => 46,
                'prep_category_id' => 14,
                'name' => 'Accompaniments',
                'status' => 'active',
                'bgcolor' => '#78ffe4',
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-07-17 14:53:53',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 2,
            ],
            [
                'id' => 47,
                'prep_category_id' => 16,
                'name' => 'Package',
                'status' => 'active',
                'bgcolor' => '#bd49e6',
                'created_by' => 175889,
                'updated_by' => null,
                'created_at' => '2025-01-24 02:57:45',
                'updated_at' => '2025-01-24 02:57:45',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 1,
            ],
        ];

        DB::table('prep_stations')->insert($dataTables);
    }
}
