<?php

namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PrepProductOptionSelectionPrioritiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables --limit=500
         */
        $dataTables = [
            [
                'id' => 6,
                'product_option_id' => 14,
                'selection_id' => 242,
                'priority' => 1,
            ],
            [
                'id' => 7,
                'product_option_id' => 14,
                'selection_id' => 244,
                'priority' => 2,
            ],
            [
                'id' => 8,
                'product_option_id' => 14,
                'selection_id' => 317,
                'priority' => 3,
            ],
            [
                'id' => 9,
                'product_option_id' => 14,
                'selection_id' => 242,
                'priority' => 4,
            ],
            [
                'id' => 46,
                'product_option_id' => 169,
                'selection_id' => 352,
                'priority' => 1,
            ],
            [
                'id' => 47,
                'product_option_id' => 169,
                'selection_id' => 354,
                'priority' => 2,
            ],
            [
                'id' => 48,
                'product_option_id' => 169,
                'selection_id' => 353,
                'priority' => 3,
            ],
            [
                'id' => 49,
                'product_option_id' => 169,
                'selection_id' => 352,
                'priority' => 4,
            ],
            [
                'id' => 50,
                'product_option_id' => 177,
                'selection_id' => 263,
                'priority' => 1,
            ],
            [
                'id' => 51,
                'product_option_id' => 177,
                'selection_id' => 264,
                'priority' => 2,
            ],
            [
                'id' => 52,
                'product_option_id' => 177,
                'selection_id' => 265,
                'priority' => 3,
            ],
            [
                'id' => 53,
                'product_option_id' => 177,
                'selection_id' => 263,
                'priority' => 4,
            ],
            [
                'id' => 107,
                'product_option_id' => 39,
                'selection_id' => 68,
                'priority' => 1,
            ],
            [
                'id' => 108,
                'product_option_id' => 39,
                'selection_id' => 66,
                'priority' => 2,
            ],
            [
                'id' => 109,
                'product_option_id' => 39,
                'selection_id' => 69,
                'priority' => 3,
            ],
            [
                'id' => 110,
                'product_option_id' => 39,
                'selection_id' => 67,
                'priority' => 4,
            ],
            [
                'id' => 111,
                'product_option_id' => 39,
                'selection_id' => 68,
                'priority' => 5,
            ],
            [
                'id' => 112,
                'product_option_id' => 39,
                'selection_id' => 66,
                'priority' => 6,
            ],
            [
                'id' => 113,
                'product_option_id' => 39,
                'selection_id' => 69,
                'priority' => 7,
            ],
            [
                'id' => 114,
                'product_option_id' => 39,
                'selection_id' => 67,
                'priority' => 8,
            ],
            [
                'id' => 115,
                'product_option_id' => 39,
                'selection_id' => 70,
                'priority' => 8,
            ],
            [
                'id' => 116,
                'product_option_id' => 39,
                'selection_id' => 71,
                'priority' => 9,
            ],
            [
                'id' => 117,
                'product_option_id' => 39,
                'selection_id' => 68,
                'priority' => 10,
            ],
            [
                'id' => 118,
                'product_option_id' => 39,
                'selection_id' => 66,
                'priority' => 11,
            ],
            [
                'id' => 119,
                'product_option_id' => 39,
                'selection_id' => 69,
                'priority' => 12,
            ],
            [
                'id' => 120,
                'product_option_id' => 39,
                'selection_id' => 67,
                'priority' => 13,
            ],
            [
                'id' => 121,
                'product_option_id' => 39,
                'selection_id' => 70,
                'priority' => 14,
            ],
            [
                'id' => 122,
                'product_option_id' => 39,
                'selection_id' => 71,
                'priority' => 15,
            ],
            [
                'id' => 123,
                'product_option_id' => 39,
                'selection_id' => 68,
                'priority' => 16,
            ],
            [
                'id' => 124,
                'product_option_id' => 39,
                'selection_id' => 66,
                'priority' => 17,
            ],
            [
                'id' => 125,
                'product_option_id' => 39,
                'selection_id' => 69,
                'priority' => 17,
            ],
            [
                'id' => 126,
                'product_option_id' => 39,
                'selection_id' => 67,
                'priority' => 18,
            ],
            [
                'id' => 129,
                'product_option_id' => 36,
                'selection_id' => 201,
                'priority' => 5,
            ],
            [
                'id' => 130,
                'product_option_id' => 36,
                'selection_id' => 28,
                'priority' => 16,
            ],
            [
                'id' => 131,
                'product_option_id' => 36,
                'selection_id' => 27,
                'priority' => 17,
            ],
            [
                'id' => 132,
                'product_option_id' => 36,
                'selection_id' => 24,
                'priority' => 4,
            ],
            [
                'id' => 133,
                'product_option_id' => 36,
                'selection_id' => 201,
                'priority' => 15,
            ],
            [
                'id' => 134,
                'product_option_id' => 36,
                'selection_id' => 28,
                'priority' => 6,
            ],
            [
                'id' => 135,
                'product_option_id' => 36,
                'selection_id' => 27,
                'priority' => 7,
            ],
            [
                'id' => 137,
                'product_option_id' => 36,
                'selection_id' => 202,
                'priority' => 9,
            ],
            [
                'id' => 138,
                'product_option_id' => 36,
                'selection_id' => 35,
                'priority' => 10,
            ],
            [
                'id' => 139,
                'product_option_id' => 36,
                'selection_id' => 34,
                'priority' => 11,
            ],
            [
                'id' => 140,
                'product_option_id' => 36,
                'selection_id' => 36,
                'priority' => 12,
            ],
            [
                'id' => 141,
                'product_option_id' => 36,
                'selection_id' => 37,
                'priority' => 13,
            ],
            [
                'id' => 142,
                'product_option_id' => 36,
                'selection_id' => 32,
                'priority' => 14,
            ],
            [
                'id' => 143,
                'product_option_id' => 36,
                'selection_id' => 201,
                'priority' => 1,
            ],
            [
                'id' => 144,
                'product_option_id' => 36,
                'selection_id' => 28,
                'priority' => 2,
            ],
            [
                'id' => 145,
                'product_option_id' => 36,
                'selection_id' => 27,
                'priority' => 3,
            ],
            [
                'id' => 146,
                'product_option_id' => 36,
                'selection_id' => 24,
                'priority' => 8,
            ],
            [
                'id' => 147,
                'product_option_id' => 36,
                'selection_id' => 24,
                'priority' => 17,
            ],
            [
                'id' => 148,
                'product_option_id' => 36,
                'selection_id' => 202,
                'priority' => 17,
            ],
            [
                'id' => 149,
                'product_option_id' => 36,
                'selection_id' => 35,
                'priority' => 17,
            ],
            [
                'id' => 150,
                'product_option_id' => 41,
                'selection_id' => 76,
                'priority' => 1,
            ],
            [
                'id' => 151,
                'product_option_id' => 41,
                'selection_id' => 75,
                'priority' => 2,
            ],
            [
                'id' => 152,
                'product_option_id' => 41,
                'selection_id' => 78,
                'priority' => 3,
            ],
            [
                'id' => 153,
                'product_option_id' => 41,
                'selection_id' => 76,
                'priority' => 4,
            ],
            [
                'id' => 154,
                'product_option_id' => 41,
                'selection_id' => 75,
                'priority' => 5,
            ],
            [
                'id' => 155,
                'product_option_id' => 41,
                'selection_id' => 78,
                'priority' => 6,
            ],
            [
                'id' => 156,
                'product_option_id' => 41,
                'selection_id' => 79,
                'priority' => 7,
            ],
            [
                'id' => 157,
                'product_option_id' => 41,
                'selection_id' => 77,
                'priority' => 8,
            ],
            [
                'id' => 158,
                'product_option_id' => 41,
                'selection_id' => 76,
                'priority' => 9,
            ],
            [
                'id' => 159,
                'product_option_id' => 41,
                'selection_id' => 75,
                'priority' => 10,
            ],
            [
                'id' => 160,
                'product_option_id' => 41,
                'selection_id' => 78,
                'priority' => 10,
            ],
            [
                'id' => 161,
                'product_option_id' => 41,
                'selection_id' => 79,
                'priority' => 11,
            ],
            [
                'id' => 162,
                'product_option_id' => 41,
                'selection_id' => 77,
                'priority' => 12,
            ],
            [
                'id' => 163,
                'product_option_id' => 41,
                'selection_id' => 76,
                'priority' => 13,
            ],
            [
                'id' => 164,
                'product_option_id' => 41,
                'selection_id' => 76,
                'priority' => 14,
            ],
            [
                'id' => 165,
                'product_option_id' => 41,
                'selection_id' => 75,
                'priority' => 15,
            ],
            [
                'id' => 166,
                'product_option_id' => 41,
                'selection_id' => 78,
                'priority' => 16,
            ],
            [
                'id' => 167,
                'product_option_id' => 41,
                'selection_id' => 79,
                'priority' => 17,
            ],
            [
                'id' => 168,
                'product_option_id' => 41,
                'selection_id' => 77,
                'priority' => 18,
            ],
            [
                'id' => 169,
                'product_option_id' => 41,
                'selection_id' => 76,
                'priority' => 19,
            ],
            [
                'id' => 170,
                'product_option_id' => 47,
                'selection_id' => 97,
                'priority' => 1,
            ],
            [
                'id' => 171,
                'product_option_id' => 47,
                'selection_id' => 96,
                'priority' => 2,
            ],
            [
                'id' => 172,
                'product_option_id' => 47,
                'selection_id' => 94,
                'priority' => 3,
            ],
            [
                'id' => 173,
                'product_option_id' => 47,
                'selection_id' => 97,
                'priority' => 4,
            ],
            [
                'id' => 174,
                'product_option_id' => 47,
                'selection_id' => 96,
                'priority' => 5,
            ],
            [
                'id' => 175,
                'product_option_id' => 47,
                'selection_id' => 94,
                'priority' => 6,
            ],
            [
                'id' => 176,
                'product_option_id' => 47,
                'selection_id' => 98,
                'priority' => 7,
            ],
            [
                'id' => 177,
                'product_option_id' => 47,
                'selection_id' => 93,
                'priority' => 8,
            ],
            [
                'id' => 178,
                'product_option_id' => 47,
                'selection_id' => 97,
                'priority' => 9,
            ],
            [
                'id' => 179,
                'product_option_id' => 47,
                'selection_id' => 96,
                'priority' => 10,
            ],
            [
                'id' => 180,
                'product_option_id' => 47,
                'selection_id' => 94,
                'priority' => 10,
            ],
            [
                'id' => 181,
                'product_option_id' => 47,
                'selection_id' => 98,
                'priority' => 11,
            ],
            [
                'id' => 182,
                'product_option_id' => 47,
                'selection_id' => 93,
                'priority' => 12,
            ],
            [
                'id' => 183,
                'product_option_id' => 47,
                'selection_id' => 97,
                'priority' => 13,
            ],
            [
                'id' => 184,
                'product_option_id' => 47,
                'selection_id' => 96,
                'priority' => 14,
            ],
            [
                'id' => 185,
                'product_option_id' => 47,
                'selection_id' => 94,
                'priority' => 15,
            ],
            [
                'id' => 186,
                'product_option_id' => 47,
                'selection_id' => 98,
                'priority' => 16,
            ],
            [
                'id' => 187,
                'product_option_id' => 47,
                'selection_id' => 97,
                'priority' => 17,
            ],
            [
                'id' => 188,
                'product_option_id' => 47,
                'selection_id' => 96,
                'priority' => 18,
            ],
            [
                'id' => 189,
                'product_option_id' => 47,
                'selection_id' => 94,
                'priority' => 19,
            ],
            [
                'id' => 190,
                'product_option_id' => 51,
                'selection_id' => 218,
                'priority' => 1,
            ],
            [
                'id' => 191,
                'product_option_id' => 51,
                'selection_id' => 111,
                'priority' => 2,
            ],
            [
                'id' => 192,
                'product_option_id' => 51,
                'selection_id' => 109,
                'priority' => 3,
            ],
            [
                'id' => 193,
                'product_option_id' => 51,
                'selection_id' => 256,
                'priority' => 4,
            ],
            [
                'id' => 194,
                'product_option_id' => 51,
                'selection_id' => 46,
                'priority' => 5,
            ],
            [
                'id' => 195,
                'product_option_id' => 51,
                'selection_id' => 218,
                'priority' => 6,
            ],
            [
                'id' => 196,
                'product_option_id' => 51,
                'selection_id' => 111,
                'priority' => 7,
            ],
            [
                'id' => 197,
                'product_option_id' => 51,
                'selection_id' => 109,
                'priority' => 8,
            ],
            [
                'id' => 198,
                'product_option_id' => 51,
                'selection_id' => 256,
                'priority' => 9,
            ],
            [
                'id' => 199,
                'product_option_id' => 51,
                'selection_id' => 46,
                'priority' => 11,
            ],
            [
                'id' => 200,
                'product_option_id' => 51,
                'selection_id' => 47,
                'priority' => 10,
            ],
            [
                'id' => 201,
                'product_option_id' => 51,
                'selection_id' => 45,
                'priority' => 12,
            ],
            [
                'id' => 202,
                'product_option_id' => 51,
                'selection_id' => 217,
                'priority' => 13,
            ],
            [
                'id' => 203,
                'product_option_id' => 51,
                'selection_id' => 53,
                'priority' => 14,
            ],
            [
                'id' => 204,
                'product_option_id' => 51,
                'selection_id' => 218,
                'priority' => 15,
            ],
            [
                'id' => 205,
                'product_option_id' => 51,
                'selection_id' => 111,
                'priority' => 16,
            ],
            [
                'id' => 206,
                'product_option_id' => 51,
                'selection_id' => 109,
                'priority' => 17,
            ],
            [
                'id' => 207,
                'product_option_id' => 51,
                'selection_id' => 256,
                'priority' => 18,
            ],
            [
                'id' => 208,
                'product_option_id' => 51,
                'selection_id' => 46,
                'priority' => 19,
            ],
            [
                'id' => 209,
                'product_option_id' => 51,
                'selection_id' => 47,
                'priority' => 20,
            ],
            [
                'id' => 210,
                'product_option_id' => 14,
                'selection_id' => 242,
                'priority' => 4,
            ],
            [
                'id' => 211,
                'product_option_id' => 14,
                'selection_id' => 244,
                'priority' => 5,
            ],
            [
                'id' => 212,
                'product_option_id' => 14,
                'selection_id' => 317,
                'priority' => 6,
            ],
            [
                'id' => 213,
                'product_option_id' => 14,
                'selection_id' => 242,
                'priority' => 7,
            ],
            [
                'id' => 214,
                'product_option_id' => 14,
                'selection_id' => 242,
                'priority' => 8,
            ],
            [
                'id' => 215,
                'product_option_id' => 14,
                'selection_id' => 244,
                'priority' => 9,
            ],
            [
                'id' => 216,
                'product_option_id' => 14,
                'selection_id' => 317,
                'priority' => 10,
            ],
            [
                'id' => 217,
                'product_option_id' => 14,
                'selection_id' => 242,
                'priority' => 11,
            ],
            [
                'id' => 218,
                'product_option_id' => 14,
                'selection_id' => 242,
                'priority' => 11,
            ],
            [
                'id' => 219,
                'product_option_id' => 14,
                'selection_id' => 244,
                'priority' => 12,
            ],
            [
                'id' => 220,
                'product_option_id' => 14,
                'selection_id' => 242,
                'priority' => 13,
            ],
            [
                'id' => 221,
                'product_option_id' => 14,
                'selection_id' => 244,
                'priority' => 14,
            ],
            [
                'id' => 222,
                'product_option_id' => 14,
                'selection_id' => 242,
                'priority' => 15,
            ],
            [
                'id' => 223,
                'product_option_id' => 14,
                'selection_id' => 244,
                'priority' => 16,
            ],
            [
                'id' => 224,
                'product_option_id' => 14,
                'selection_id' => 317,
                'priority' => 17,
            ],
            [
                'id' => 225,
                'product_option_id' => 14,
                'selection_id' => 242,
                'priority' => 18,
            ],
            [
                'id' => 246,
                'product_option_id' => 177,
                'selection_id' => 263,
                'priority' => 4,
            ],
            [
                'id' => 247,
                'product_option_id' => 177,
                'selection_id' => 264,
                'priority' => 5,
            ],
            [
                'id' => 248,
                'product_option_id' => 177,
                'selection_id' => 265,
                'priority' => 6,
            ],
            [
                'id' => 249,
                'product_option_id' => 177,
                'selection_id' => 263,
                'priority' => 7,
            ],
            [
                'id' => 250,
                'product_option_id' => 177,
                'selection_id' => 264,
                'priority' => 8,
            ],
            [
                'id' => 251,
                'product_option_id' => 177,
                'selection_id' => 265,
                'priority' => 9,
            ],
            [
                'id' => 252,
                'product_option_id' => 177,
                'selection_id' => 263,
                'priority' => 10,
            ],
            [
                'id' => 253,
                'product_option_id' => 177,
                'selection_id' => 263,
                'priority' => 11,
            ],
            [
                'id' => 254,
                'product_option_id' => 177,
                'selection_id' => 264,
                'priority' => 11,
            ],
            [
                'id' => 255,
                'product_option_id' => 177,
                'selection_id' => 265,
                'priority' => 12,
            ],
            [
                'id' => 256,
                'product_option_id' => 177,
                'selection_id' => 263,
                'priority' => 13,
            ],
            [
                'id' => 257,
                'product_option_id' => 177,
                'selection_id' => 264,
                'priority' => 14,
            ],
            [
                'id' => 258,
                'product_option_id' => 177,
                'selection_id' => 265,
                'priority' => 15,
            ],
            [
                'id' => 259,
                'product_option_id' => 177,
                'selection_id' => 263,
                'priority' => 16,
            ],
            [
                'id' => 260,
                'product_option_id' => 177,
                'selection_id' => 264,
                'priority' => 17,
            ],
            [
                'id' => 261,
                'product_option_id' => 177,
                'selection_id' => 265,
                'priority' => 18,
            ],
            [
                'id' => 262,
                'product_option_id' => 169,
                'selection_id' => 352,
                'priority' => 4,
            ],
            [
                'id' => 263,
                'product_option_id' => 169,
                'selection_id' => 354,
                'priority' => 5,
            ],
            [
                'id' => 264,
                'product_option_id' => 169,
                'selection_id' => 353,
                'priority' => 6,
            ],
            [
                'id' => 265,
                'product_option_id' => 169,
                'selection_id' => 352,
                'priority' => 7,
            ],
            [
                'id' => 266,
                'product_option_id' => 169,
                'selection_id' => 352,
                'priority' => 8,
            ],
            [
                'id' => 267,
                'product_option_id' => 169,
                'selection_id' => 354,
                'priority' => 9,
            ],
            [
                'id' => 268,
                'product_option_id' => 169,
                'selection_id' => 353,
                'priority' => 9,
            ],
            [
                'id' => 269,
                'product_option_id' => 169,
                'selection_id' => 352,
                'priority' => 10,
            ],
            [
                'id' => 270,
                'product_option_id' => 169,
                'selection_id' => 352,
                'priority' => 11,
            ],
            [
                'id' => 271,
                'product_option_id' => 169,
                'selection_id' => 354,
                'priority' => 12,
            ],
            [
                'id' => 272,
                'product_option_id' => 169,
                'selection_id' => 352,
                'priority' => 13,
            ],
            [
                'id' => 273,
                'product_option_id' => 169,
                'selection_id' => 354,
                'priority' => 14,
            ],
            [
                'id' => 274,
                'product_option_id' => 169,
                'selection_id' => 352,
                'priority' => 15,
            ],
            [
                'id' => 275,
                'product_option_id' => 169,
                'selection_id' => 354,
                'priority' => 16,
            ],
            [
                'id' => 276,
                'product_option_id' => 169,
                'selection_id' => 353,
                'priority' => 17,
            ],
            [
                'id' => 277,
                'product_option_id' => 169,
                'selection_id' => 352,
                'priority' => 18,
            ],
            [
                'id' => 278,
                'product_option_id' => 15,
                'selection_id' => 250,
                'priority' => 1,
            ],
            [
                'id' => 279,
                'product_option_id' => 15,
                'selection_id' => 251,
                'priority' => 2,
            ],
            [
                'id' => 280,
                'product_option_id' => 15,
                'selection_id' => 252,
                'priority' => 3,
            ],
            [
                'id' => 281,
                'product_option_id' => 15,
                'selection_id' => 253,
                'priority' => 4,
            ],
            [
                'id' => 282,
                'product_option_id' => 38,
                'selection_id' => 61,
                'priority' => 1,
            ],
            [
                'id' => 283,
                'product_option_id' => 38,
                'selection_id' => 63,
                'priority' => 2,
            ],
            [
                'id' => 284,
                'product_option_id' => 38,
                'selection_id' => 60,
                'priority' => 3,
            ],
            [
                'id' => 285,
                'product_option_id' => 38,
                'selection_id' => 64,
                'priority' => 4,
            ],
            [
                'id' => 286,
                'product_option_id' => 38,
                'selection_id' => 63,
                'priority' => 5,
            ],
            [
                'id' => 287,
                'product_option_id' => 38,
                'selection_id' => 60,
                'priority' => 6,
            ],
            [
                'id' => 288,
                'product_option_id' => 38,
                'selection_id' => 64,
                'priority' => 7,
            ],
            [
                'id' => 289,
                'product_option_id' => 38,
                'selection_id' => 241,
                'priority' => 8,
            ],
            [
                'id' => 290,
                'product_option_id' => 38,
                'selection_id' => 62,
                'priority' => 9,
            ],
            [
                'id' => 291,
                'product_option_id' => 38,
                'selection_id' => 55,
                'priority' => 10,
            ],
            [
                'id' => 292,
                'product_option_id' => 38,
                'selection_id' => 55,
                'priority' => 10,
            ],
            [
                'id' => 293,
                'product_option_id' => 43,
                'selection_id' => 83,
                'priority' => 1,
            ],
            [
                'id' => 294,
                'product_option_id' => 43,
                'selection_id' => 84,
                'priority' => 2,
            ],
            [
                'id' => 295,
                'product_option_id' => 43,
                'selection_id' => 85,
                'priority' => 3,
            ],
            [
                'id' => 296,
                'product_option_id' => 43,
                'selection_id' => 86,
                'priority' => 4,
            ],
            [
                'id' => 300,
                'product_option_id' => 40,
                'selection_id' => 13,
                'priority' => 1,
            ],
            [
                'id' => 301,
                'product_option_id' => 40,
                'selection_id' => 23,
                'priority' => 2,
            ],
            [
                'id' => 302,
                'product_option_id' => 40,
                'selection_id' => 92,
                'priority' => 3,
            ],
            [
                'id' => 303,
                'product_option_id' => 40,
                'selection_id' => 114,
                'priority' => 4,
            ],
            [
                'id' => 304,
                'product_option_id' => 40,
                'selection_id' => 117,
                'priority' => 5,
            ],
            [
                'id' => 305,
                'product_option_id' => 40,
                'selection_id' => 23,
                'priority' => 6,
            ],
            [
                'id' => 306,
                'product_option_id' => 40,
                'selection_id' => 13,
                'priority' => 7,
            ],
            [
                'id' => 312,
                'product_option_id' => 37,
                'selection_id' => 13,
                'priority' => 1,
            ],
            [
                'id' => 313,
                'product_option_id' => 37,
                'selection_id' => 23,
                'priority' => 2,
            ],
            [
                'id' => 314,
                'product_option_id' => 37,
                'selection_id' => 114,
                'priority' => 3,
            ],
            [
                'id' => 315,
                'product_option_id' => 37,
                'selection_id' => 23,
                'priority' => 4,
            ],
            [
                'id' => 316,
                'product_option_id' => 37,
                'selection_id' => 92,
                'priority' => 5,
            ],
            [
                'id' => 317,
                'product_option_id' => 48,
                'selection_id' => 13,
                'priority' => 1,
            ],
            [
                'id' => 318,
                'product_option_id' => 48,
                'selection_id' => 23,
                'priority' => 2,
            ],
            [
                'id' => 319,
                'product_option_id' => 48,
                'selection_id' => 92,
                'priority' => 3,
            ],
            [
                'id' => 320,
                'product_option_id' => 48,
                'selection_id' => 114,
                'priority' => 4,
            ],
            [
                'id' => 321,
                'product_option_id' => 123,
                'selection_id' => 13,
                'priority' => 1,
            ],
            [
                'id' => 322,
                'product_option_id' => 123,
                'selection_id' => 23,
                'priority' => 2,
            ],
            [
                'id' => 323,
                'product_option_id' => 123,
                'selection_id' => 92,
                'priority' => 3,
            ],
            [
                'id' => 324,
                'product_option_id' => 123,
                'selection_id' => 114,
                'priority' => 4,
            ],
            [
                'id' => 325,
                'product_option_id' => 123,
                'selection_id' => 23,
                'priority' => 5,
            ],
            [
                'id' => 326,
                'product_option_id' => 50,
                'selection_id' => 13,
                'priority' => 1,
            ],
            [
                'id' => 327,
                'product_option_id' => 50,
                'selection_id' => 23,
                'priority' => 2,
            ],
            [
                'id' => 328,
                'product_option_id' => 50,
                'selection_id' => 92,
                'priority' => 3,
            ],
            [
                'id' => 329,
                'product_option_id' => 50,
                'selection_id' => 114,
                'priority' => 4,
            ],
            [
                'id' => 330,
                'product_option_id' => 50,
                'selection_id' => 23,
                'priority' => 5,
            ],
            [
                'id' => 331,
                'product_option_id' => 52,
                'selection_id' => 13,
                'priority' => 1,
            ],
            [
                'id' => 332,
                'product_option_id' => 52,
                'selection_id' => 23,
                'priority' => 2,
            ],
            [
                'id' => 333,
                'product_option_id' => 52,
                'selection_id' => 92,
                'priority' => 3,
            ],
            [
                'id' => 334,
                'product_option_id' => 52,
                'selection_id' => 23,
                'priority' => 4,
            ],
            [
                'id' => 335,
                'product_option_id' => 46,
                'selection_id' => 13,
                'priority' => 1,
            ],
            [
                'id' => 336,
                'product_option_id' => 46,
                'selection_id' => 23,
                'priority' => 2,
            ],
            [
                'id' => 337,
                'product_option_id' => 46,
                'selection_id' => 54,
                'priority' => 3,
            ],
            [
                'id' => 338,
                'product_option_id' => 46,
                'selection_id' => 117,
                'priority' => 4,
            ],
            [
                'id' => 344,
                'product_option_id' => 55,
                'selection_id' => 124,
                'priority' => 1,
            ],
            [
                'id' => 345,
                'product_option_id' => 55,
                'selection_id' => 255,
                'priority' => 2,
            ],
            [
                'id' => 346,
                'product_option_id' => 55,
                'selection_id' => 383,
                'priority' => 3,
            ],
            [
                'id' => 347,
                'product_option_id' => 55,
                'selection_id' => 286,
                'priority' => 4,
            ],
            [
                'id' => 348,
                'product_option_id' => 42,
                'selection_id' => 13,
                'priority' => 1,
            ],
            [
                'id' => 349,
                'product_option_id' => 42,
                'selection_id' => 13,
                'priority' => 1,
            ],
            [
                'id' => 350,
                'product_option_id' => 42,
                'selection_id' => 92,
                'priority' => 1,
            ],
            [
                'id' => 351,
                'product_option_id' => 42,
                'selection_id' => 54,
                'priority' => 2,
            ],
            [
                'id' => 352,
                'product_option_id' => 42,
                'selection_id' => 105,
                'priority' => 3,
            ],
            [
                'id' => 353,
                'product_option_id' => 42,
                'selection_id' => 114,
                'priority' => 4,
            ],
            [
                'id' => 354,
                'product_option_id' => 15,
                'selection_id' => 250,
                'priority' => 4,
            ],
            [
                'id' => 355,
                'product_option_id' => 15,
                'selection_id' => 251,
                'priority' => 5,
            ],
            [
                'id' => 356,
                'product_option_id' => 15,
                'selection_id' => 252,
                'priority' => 6,
            ],
            [
                'id' => 357,
                'product_option_id' => 15,
                'selection_id' => 253,
                'priority' => 7,
            ],
            [
                'id' => 367,
                'product_option_id' => 13,
                'selection_id' => 246,
                'priority' => 4,
            ],
        ];

        DB::table('prep_product_option_selection_priorities')->insert($dataTables);
    }
}
