<?php

namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PrepCategoriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables --limit=500
         */
        $dataTables = [
            [
                'id' => 2,
                'name' => 'Breakfast',
                'status' => 'active',
                'has_sizes' => 'no',
                'no_of_rows' => 9,
                'created_by' => 175889,
                'updated_by' => 120277,
                'created_at' => '2023-03-27 15:29:16',
                'updated_at' => '2023-07-11 10:32:24',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 1,
                'tally_sheet' => 'no',
            ],
            [
                'id' => 3,
                'name' => 'Miscellaneous',
                'status' => 'active',
                'has_sizes' => 'no',
                'no_of_rows' => 9,
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-03-27 15:41:11',
                'updated_at' => '2025-01-29 17:27:42',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 2,
                'tally_sheet' => 'no',
            ],
            [
                'id' => 4,
                'name' => 'Hot Plates Page 1',
                'status' => 'active',
                'has_sizes' => 'no',
                'no_of_rows' => 6,
                'created_by' => 175889,
                'updated_by' => 120277,
                'created_at' => '2023-03-27 15:41:18',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 3,
                'tally_sheet' => 'no',
            ],
            [
                'id' => 5,
                'name' => 'Hot Sides',
                'status' => 'active',
                'has_sizes' => 'no',
                'no_of_rows' => 8,
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-03-27 15:41:24',
                'updated_at' => '2023-06-01 02:09:33',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 5,
                'tally_sheet' => 'no',
            ],
            [
                'id' => 6,
                'name' => 'Hot Boxes',
                'status' => 'active',
                'has_sizes' => 'no',
                'no_of_rows' => 7,
                'created_by' => 175889,
                'updated_by' => 120277,
                'created_at' => '2023-03-27 15:41:35',
                'updated_at' => '2023-06-14 10:57:11',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 6,
                'tally_sheet' => 'no',
            ],
            [
                'id' => 7,
                'name' => 'Sandwiches',
                'status' => 'active',
                'has_sizes' => 'no',
                'no_of_rows' => 7,
                'created_by' => 175889,
                'updated_by' => 120277,
                'created_at' => '2023-03-27 15:41:42',
                'updated_at' => '2023-06-14 10:52:18',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 8,
                'tally_sheet' => 'no',
            ],
            [
                'id' => 8,
                'name' => 'Pressattas & Wraps',
                'status' => 'active',
                'has_sizes' => 'no',
                'no_of_rows' => 8,
                'created_by' => 175889,
                'updated_by' => null,
                'created_at' => '2023-03-27 15:41:53',
                'updated_at' => '2023-04-07 19:08:15',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 7,
                'tally_sheet' => 'no',
            ],
            [
                'id' => 9,
                'name' => 'Salad Bulk',
                'status' => 'active',
                'has_sizes' => 'no',
                'no_of_rows' => 7,
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-03-27 15:42:04',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 9,
                'tally_sheet' => 'no',
            ],
            [
                'id' => 10,
                'name' => 'Salad Boxes',
                'status' => 'active',
                'has_sizes' => 'no',
                'no_of_rows' => 6,
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-03-27 15:42:16',
                'updated_at' => '2023-08-03 01:37:25',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 10,
                'tally_sheet' => 'no',
            ],
            [
                'id' => 11,
                'name' => 'GF Breakfast',
                'status' => 'active',
                'has_sizes' => 'no',
                'no_of_rows' => 9,
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-05-19 14:50:07',
                'updated_at' => '2023-07-17 14:52:48',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 12,
                'tally_sheet' => 'no',
            ],
            [
                'id' => 12,
                'name' => 'GF Lunch',
                'status' => 'active',
                'has_sizes' => 'no',
                'no_of_rows' => 7,
                'created_by' => 175889,
                'updated_by' => 120277,
                'created_at' => '2023-05-19 14:50:47',
                'updated_at' => '2023-07-17 14:52:41',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 13,
                'tally_sheet' => 'no',
            ],
            [
                'id' => 13,
                'name' => 'Hot Plates Page 2',
                'status' => 'active',
                'has_sizes' => 'no',
                'no_of_rows' => 7,
                'created_by' => 175889,
                'updated_by' => 120277,
                'created_at' => '2023-06-01 02:08:50',
                'updated_at' => '2023-06-14 05:34:15',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 4,
                'tally_sheet' => 'no',
            ],
            [
                'id' => 14,
                'name' => 'Salad Sides and Other',
                'status' => 'active',
                'has_sizes' => 'no',
                'no_of_rows' => 6,
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-07-17 14:52:28',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 11,
                'tally_sheet' => 'no',
            ],
            [
                'id' => 15,
                'name' => 'sample category edited',
                'status' => 'active',
                'has_sizes' => 'no',
                'no_of_rows' => 1,
                'created_by' => 120277,
                'updated_by' => 120277,
                'created_at' => '2023-08-17 09:24:28',
                'updated_at' => '2023-08-17 09:24:51',
                'deleted_by' => 120277,
                'deleted_at' => '2023-08-17 09:24:51',
                'display_order' => null,
                'tally_sheet' => 'no',
            ],
            [
                'id' => 16,
                'name' => 'Sandwich Packages',
                'status' => 'active',
                'has_sizes' => 'no',
                'no_of_rows' => 5,
                'created_by' => 175889,
                'updated_by' => null,
                'created_at' => '2025-01-24 02:55:58',
                'updated_at' => '2025-01-24 02:56:16',
                'deleted_by' => null,
                'deleted_at' => null,
                'display_order' => 14,
                'tally_sheet' => 'no',
            ],
        ];

        DB::table('prep_categories')->insert($dataTables);
    }
}
