<?php

namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PrepItemStationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables --limit=500
         */
        $dataTables = [
            [
                'id' => 16,
                'prep_category_id' => 2,
                'prep_item_id' => 16,
                'prep_station_id' => 5,
                'has_sizes' => 'no',
                'display_order' => 1,
            ],
            [
                'id' => 17,
                'prep_category_id' => 2,
                'prep_item_id' => 17,
                'prep_station_id' => 5,
                'has_sizes' => 'no',
                'display_order' => 2,
            ],
            [
                'id' => 18,
                'prep_category_id' => 2,
                'prep_item_id' => 18,
                'prep_station_id' => 5,
                'has_sizes' => 'no',
                'display_order' => 3,
            ],
            [
                'id' => 19,
                'prep_category_id' => 2,
                'prep_item_id' => 19,
                'prep_station_id' => 5,
                'has_sizes' => 'no',
                'display_order' => 4,
            ],
            [
                'id' => 20,
                'prep_category_id' => 2,
                'prep_item_id' => 16,
                'prep_station_id' => 6,
                'has_sizes' => 'no',
                'display_order' => 1,
            ],
            [
                'id' => 21,
                'prep_category_id' => 2,
                'prep_item_id' => 17,
                'prep_station_id' => 6,
                'has_sizes' => 'no',
                'display_order' => 2,
            ],
            [
                'id' => 22,
                'prep_category_id' => 2,
                'prep_item_id' => 19,
                'prep_station_id' => 6,
                'has_sizes' => 'no',
                'display_order' => 3,
            ],
            [
                'id' => 23,
                'prep_category_id' => 2,
                'prep_item_id' => 20,
                'prep_station_id' => 6,
                'has_sizes' => 'no',
                'display_order' => 4,
            ],
            [
                'id' => 24,
                'prep_category_id' => 2,
                'prep_item_id' => 16,
                'prep_station_id' => 7,
                'has_sizes' => 'no',
                'display_order' => 1,
            ],
            [
                'id' => 25,
                'prep_category_id' => 2,
                'prep_item_id' => 17,
                'prep_station_id' => 7,
                'has_sizes' => 'no',
                'display_order' => 2,
            ],
            [
                'id' => 26,
                'prep_category_id' => 2,
                'prep_item_id' => 19,
                'prep_station_id' => 7,
                'has_sizes' => 'no',
                'display_order' => 3,
            ],
            [
                'id' => 27,
                'prep_category_id' => 2,
                'prep_item_id' => 20,
                'prep_station_id' => 7,
                'has_sizes' => 'no',
                'display_order' => 4,
            ],
            [
                'id' => 28,
                'prep_category_id' => 2,
                'prep_item_id' => 19,
                'prep_station_id' => 8,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 29,
                'prep_category_id' => 2,
                'prep_item_id' => 20,
                'prep_station_id' => 8,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 30,
                'prep_category_id' => 2,
                'prep_item_id' => 21,
                'prep_station_id' => 8,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 31,
                'prep_category_id' => 10,
                'prep_item_id' => 143,
                'prep_station_id' => 9,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 32,
                'prep_category_id' => 10,
                'prep_item_id' => 144,
                'prep_station_id' => 9,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 33,
                'prep_category_id' => 10,
                'prep_item_id' => 145,
                'prep_station_id' => 9,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 34,
                'prep_category_id' => 10,
                'prep_item_id' => 146,
                'prep_station_id' => 9,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 35,
                'prep_category_id' => 10,
                'prep_item_id' => 147,
                'prep_station_id' => 9,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 36,
                'prep_category_id' => 10,
                'prep_item_id' => 148,
                'prep_station_id' => 9,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 37,
                'prep_category_id' => 10,
                'prep_item_id' => 149,
                'prep_station_id' => 9,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 39,
                'prep_category_id' => 10,
                'prep_item_id' => 151,
                'prep_station_id' => 9,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 40,
                'prep_category_id' => 10,
                'prep_item_id' => 152,
                'prep_station_id' => 9,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 41,
                'prep_category_id' => 10,
                'prep_item_id' => 153,
                'prep_station_id' => 9,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 42,
                'prep_category_id' => 10,
                'prep_item_id' => 154,
                'prep_station_id' => 9,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 43,
                'prep_category_id' => 10,
                'prep_item_id' => 155,
                'prep_station_id' => 10,
                'has_sizes' => 'no',
                'display_order' => 1,
            ],
            [
                'id' => 44,
                'prep_category_id' => 10,
                'prep_item_id' => 156,
                'prep_station_id' => 10,
                'has_sizes' => 'no',
                'display_order' => 2,
            ],
            [
                'id' => 45,
                'prep_category_id' => 10,
                'prep_item_id' => 157,
                'prep_station_id' => 10,
                'has_sizes' => 'no',
                'display_order' => 3,
            ],
            [
                'id' => 46,
                'prep_category_id' => 10,
                'prep_item_id' => 158,
                'prep_station_id' => 10,
                'has_sizes' => 'no',
                'display_order' => 4,
            ],
            [
                'id' => 47,
                'prep_category_id' => 10,
                'prep_item_id' => 159,
                'prep_station_id' => 10,
                'has_sizes' => 'no',
                'display_order' => 5,
            ],
            [
                'id' => 48,
                'prep_category_id' => 10,
                'prep_item_id' => 160,
                'prep_station_id' => 10,
                'has_sizes' => 'no',
                'display_order' => 6,
            ],
            [
                'id' => 49,
                'prep_category_id' => 10,
                'prep_item_id' => 161,
                'prep_station_id' => 10,
                'has_sizes' => 'no',
                'display_order' => 7,
            ],
            [
                'id' => 50,
                'prep_category_id' => 10,
                'prep_item_id' => 162,
                'prep_station_id' => 10,
                'has_sizes' => 'no',
                'display_order' => 8,
            ],
            [
                'id' => 51,
                'prep_category_id' => 10,
                'prep_item_id' => 163,
                'prep_station_id' => 11,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 52,
                'prep_category_id' => 10,
                'prep_item_id' => 164,
                'prep_station_id' => 11,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 53,
                'prep_category_id' => 10,
                'prep_item_id' => 165,
                'prep_station_id' => 11,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 54,
                'prep_category_id' => 10,
                'prep_item_id' => 166,
                'prep_station_id' => 11,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 55,
                'prep_category_id' => 10,
                'prep_item_id' => 167,
                'prep_station_id' => 11,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 56,
                'prep_category_id' => 10,
                'prep_item_id' => 168,
                'prep_station_id' => 11,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 58,
                'prep_category_id' => 10,
                'prep_item_id' => 169,
                'prep_station_id' => 12,
                'has_sizes' => 'no',
                'display_order' => 1,
            ],
            [
                'id' => 59,
                'prep_category_id' => 9,
                'prep_item_id' => 132,
                'prep_station_id' => 36,
                'has_sizes' => 'yes',
                'display_order' => null,
            ],
            [
                'id' => 60,
                'prep_category_id' => 9,
                'prep_item_id' => 133,
                'prep_station_id' => 36,
                'has_sizes' => 'yes',
                'display_order' => null,
            ],
            [
                'id' => 61,
                'prep_category_id' => 9,
                'prep_item_id' => 134,
                'prep_station_id' => 36,
                'has_sizes' => 'yes',
                'display_order' => null,
            ],
            [
                'id' => 62,
                'prep_category_id' => 9,
                'prep_item_id' => 135,
                'prep_station_id' => 36,
                'has_sizes' => 'yes',
                'display_order' => null,
            ],
            [
                'id' => 63,
                'prep_category_id' => 9,
                'prep_item_id' => 136,
                'prep_station_id' => 36,
                'has_sizes' => 'yes',
                'display_order' => null,
            ],
            [
                'id' => 64,
                'prep_category_id' => 9,
                'prep_item_id' => 137,
                'prep_station_id' => 36,
                'has_sizes' => 'yes',
                'display_order' => null,
            ],
            [
                'id' => 65,
                'prep_category_id' => 9,
                'prep_item_id' => 138,
                'prep_station_id' => 36,
                'has_sizes' => 'yes',
                'display_order' => null,
            ],
            [
                'id' => 66,
                'prep_category_id' => 9,
                'prep_item_id' => 139,
                'prep_station_id' => 37,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 67,
                'prep_category_id' => 9,
                'prep_item_id' => 140,
                'prep_station_id' => 37,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 68,
                'prep_category_id' => 9,
                'prep_item_id' => 141,
                'prep_station_id' => 37,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 69,
                'prep_category_id' => 9,
                'prep_item_id' => 142,
                'prep_station_id' => 37,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 70,
                'prep_category_id' => 8,
                'prep_item_id' => 116,
                'prep_station_id' => 31,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 71,
                'prep_category_id' => 8,
                'prep_item_id' => 117,
                'prep_station_id' => 31,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 72,
                'prep_category_id' => 8,
                'prep_item_id' => 118,
                'prep_station_id' => 31,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 73,
                'prep_category_id' => 8,
                'prep_item_id' => 119,
                'prep_station_id' => 31,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 74,
                'prep_category_id' => 8,
                'prep_item_id' => 120,
                'prep_station_id' => 32,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 75,
                'prep_category_id' => 8,
                'prep_item_id' => 121,
                'prep_station_id' => 32,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 76,
                'prep_category_id' => 8,
                'prep_item_id' => 122,
                'prep_station_id' => 32,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 77,
                'prep_category_id' => 8,
                'prep_item_id' => 123,
                'prep_station_id' => 33,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 78,
                'prep_category_id' => 8,
                'prep_item_id' => 124,
                'prep_station_id' => 33,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 79,
                'prep_category_id' => 8,
                'prep_item_id' => 125,
                'prep_station_id' => 33,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 80,
                'prep_category_id' => 8,
                'prep_item_id' => 126,
                'prep_station_id' => 34,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 81,
                'prep_category_id' => 8,
                'prep_item_id' => 127,
                'prep_station_id' => 34,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 82,
                'prep_category_id' => 8,
                'prep_item_id' => 128,
                'prep_station_id' => 34,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 83,
                'prep_category_id' => 8,
                'prep_item_id' => 129,
                'prep_station_id' => 35,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 84,
                'prep_category_id' => 8,
                'prep_item_id' => 130,
                'prep_station_id' => 35,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 85,
                'prep_category_id' => 8,
                'prep_item_id' => 131,
                'prep_station_id' => 35,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 86,
                'prep_category_id' => 7,
                'prep_item_id' => 96,
                'prep_station_id' => 27,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 87,
                'prep_category_id' => 7,
                'prep_item_id' => 97,
                'prep_station_id' => 27,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 88,
                'prep_category_id' => 7,
                'prep_item_id' => 98,
                'prep_station_id' => 27,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 89,
                'prep_category_id' => 7,
                'prep_item_id' => 99,
                'prep_station_id' => 27,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 90,
                'prep_category_id' => 7,
                'prep_item_id' => 100,
                'prep_station_id' => 27,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 91,
                'prep_category_id' => 7,
                'prep_item_id' => 101,
                'prep_station_id' => 27,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 92,
                'prep_category_id' => 7,
                'prep_item_id' => 102,
                'prep_station_id' => 28,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 93,
                'prep_category_id' => 7,
                'prep_item_id' => 103,
                'prep_station_id' => 28,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 94,
                'prep_category_id' => 7,
                'prep_item_id' => 104,
                'prep_station_id' => 28,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 95,
                'prep_category_id' => 7,
                'prep_item_id' => 105,
                'prep_station_id' => 28,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 96,
                'prep_category_id' => 7,
                'prep_item_id' => 106,
                'prep_station_id' => 28,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 97,
                'prep_category_id' => 7,
                'prep_item_id' => 107,
                'prep_station_id' => 28,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 98,
                'prep_category_id' => 7,
                'prep_item_id' => 108,
                'prep_station_id' => 29,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 99,
                'prep_category_id' => 7,
                'prep_item_id' => 109,
                'prep_station_id' => 29,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 100,
                'prep_category_id' => 7,
                'prep_item_id' => 110,
                'prep_station_id' => 29,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 101,
                'prep_category_id' => 7,
                'prep_item_id' => 111,
                'prep_station_id' => 29,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 102,
                'prep_category_id' => 7,
                'prep_item_id' => 112,
                'prep_station_id' => 29,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 103,
                'prep_category_id' => 7,
                'prep_item_id' => 113,
                'prep_station_id' => 29,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 104,
                'prep_category_id' => 7,
                'prep_item_id' => 114,
                'prep_station_id' => 30,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 105,
                'prep_category_id' => 7,
                'prep_item_id' => 115,
                'prep_station_id' => 30,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 106,
                'prep_category_id' => 6,
                'prep_item_id' => 82,
                'prep_station_id' => 24,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 107,
                'prep_category_id' => 6,
                'prep_item_id' => 83,
                'prep_station_id' => 24,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 108,
                'prep_category_id' => 6,
                'prep_item_id' => 84,
                'prep_station_id' => 24,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 109,
                'prep_category_id' => 6,
                'prep_item_id' => 85,
                'prep_station_id' => 25,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 110,
                'prep_category_id' => 6,
                'prep_item_id' => 86,
                'prep_station_id' => 25,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 111,
                'prep_category_id' => 6,
                'prep_item_id' => 87,
                'prep_station_id' => 25,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 112,
                'prep_category_id' => 6,
                'prep_item_id' => 88,
                'prep_station_id' => 25,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 113,
                'prep_category_id' => 6,
                'prep_item_id' => 89,
                'prep_station_id' => 25,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 114,
                'prep_category_id' => 6,
                'prep_item_id' => 90,
                'prep_station_id' => 25,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 115,
                'prep_category_id' => 6,
                'prep_item_id' => 91,
                'prep_station_id' => 25,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 116,
                'prep_category_id' => 6,
                'prep_item_id' => 92,
                'prep_station_id' => 25,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 117,
                'prep_category_id' => 6,
                'prep_item_id' => 93,
                'prep_station_id' => 25,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 119,
                'prep_category_id' => 6,
                'prep_item_id' => 95,
                'prep_station_id' => 26,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 120,
                'prep_category_id' => 5,
                'prep_item_id' => 66,
                'prep_station_id' => 20,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 121,
                'prep_category_id' => 5,
                'prep_item_id' => 67,
                'prep_station_id' => 20,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 122,
                'prep_category_id' => 5,
                'prep_item_id' => 68,
                'prep_station_id' => 21,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 123,
                'prep_category_id' => 5,
                'prep_item_id' => 69,
                'prep_station_id' => 21,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 124,
                'prep_category_id' => 5,
                'prep_item_id' => 70,
                'prep_station_id' => 21,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 125,
                'prep_category_id' => 5,
                'prep_item_id' => 71,
                'prep_station_id' => 21,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 126,
                'prep_category_id' => 5,
                'prep_item_id' => 72,
                'prep_station_id' => 21,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 128,
                'prep_category_id' => 5,
                'prep_item_id' => 74,
                'prep_station_id' => 21,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 129,
                'prep_category_id' => 5,
                'prep_item_id' => 75,
                'prep_station_id' => 21,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 130,
                'prep_category_id' => 5,
                'prep_item_id' => 76,
                'prep_station_id' => 21,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 131,
                'prep_category_id' => 5,
                'prep_item_id' => 77,
                'prep_station_id' => 21,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 133,
                'prep_category_id' => 5,
                'prep_item_id' => 79,
                'prep_station_id' => 22,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 134,
                'prep_category_id' => 5,
                'prep_item_id' => 80,
                'prep_station_id' => 23,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 136,
                'prep_category_id' => 4,
                'prep_item_id' => 46,
                'prep_station_id' => 18,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 137,
                'prep_category_id' => 4,
                'prep_item_id' => 47,
                'prep_station_id' => 18,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 138,
                'prep_category_id' => 4,
                'prep_item_id' => 48,
                'prep_station_id' => 18,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 139,
                'prep_category_id' => 4,
                'prep_item_id' => 49,
                'prep_station_id' => 19,
                'has_sizes' => 'no',
                'display_order' => 1,
            ],
            [
                'id' => 140,
                'prep_category_id' => 4,
                'prep_item_id' => 50,
                'prep_station_id' => 19,
                'has_sizes' => 'no',
                'display_order' => 7,
            ],
            [
                'id' => 142,
                'prep_category_id' => 4,
                'prep_item_id' => 52,
                'prep_station_id' => 19,
                'has_sizes' => 'no',
                'display_order' => 4,
            ],
            [
                'id' => 143,
                'prep_category_id' => 4,
                'prep_item_id' => 53,
                'prep_station_id' => 19,
                'has_sizes' => 'no',
                'display_order' => 7,
            ],
            [
                'id' => 144,
                'prep_category_id' => 4,
                'prep_item_id' => 54,
                'prep_station_id' => 19,
                'has_sizes' => 'no',
                'display_order' => 9,
            ],
            [
                'id' => 146,
                'prep_category_id' => 4,
                'prep_item_id' => 56,
                'prep_station_id' => 19,
                'has_sizes' => 'no',
                'display_order' => 8,
            ],
            [
                'id' => 148,
                'prep_category_id' => 4,
                'prep_item_id' => 58,
                'prep_station_id' => 19,
                'has_sizes' => 'no',
                'display_order' => 2,
            ],
            [
                'id' => 149,
                'prep_category_id' => 4,
                'prep_item_id' => 59,
                'prep_station_id' => 19,
                'has_sizes' => 'no',
                'display_order' => 3,
            ],
            [
                'id' => 156,
                'prep_category_id' => 3,
                'prep_item_id' => 22,
                'prep_station_id' => 13,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 157,
                'prep_category_id' => 3,
                'prep_item_id' => 23,
                'prep_station_id' => 13,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 158,
                'prep_category_id' => 3,
                'prep_item_id' => 24,
                'prep_station_id' => 13,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 160,
                'prep_category_id' => 3,
                'prep_item_id' => 26,
                'prep_station_id' => 14,
                'has_sizes' => 'no',
                'display_order' => 1,
            ],
            [
                'id' => 161,
                'prep_category_id' => 3,
                'prep_item_id' => 27,
                'prep_station_id' => 14,
                'has_sizes' => 'yes',
                'display_order' => 2,
            ],
            [
                'id' => 162,
                'prep_category_id' => 3,
                'prep_item_id' => 28,
                'prep_station_id' => 14,
                'has_sizes' => 'no',
                'display_order' => 3,
            ],
            [
                'id' => 163,
                'prep_category_id' => 3,
                'prep_item_id' => 29,
                'prep_station_id' => 14,
                'has_sizes' => 'no',
                'display_order' => 4,
            ],
            [
                'id' => 164,
                'prep_category_id' => 3,
                'prep_item_id' => 30,
                'prep_station_id' => 15,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 165,
                'prep_category_id' => 3,
                'prep_item_id' => 31,
                'prep_station_id' => 15,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 166,
                'prep_category_id' => 3,
                'prep_item_id' => 32,
                'prep_station_id' => 15,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 167,
                'prep_category_id' => 3,
                'prep_item_id' => 33,
                'prep_station_id' => 15,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 168,
                'prep_category_id' => 3,
                'prep_item_id' => 34,
                'prep_station_id' => 16,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 169,
                'prep_category_id' => 3,
                'prep_item_id' => 35,
                'prep_station_id' => 16,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 170,
                'prep_category_id' => 3,
                'prep_item_id' => 36,
                'prep_station_id' => 16,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 171,
                'prep_category_id' => 3,
                'prep_item_id' => 38,
                'prep_station_id' => 16,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 172,
                'prep_category_id' => 3,
                'prep_item_id' => 39,
                'prep_station_id' => 16,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 173,
                'prep_category_id' => 3,
                'prep_item_id' => 40,
                'prep_station_id' => 17,
                'has_sizes' => 'no',
                'display_order' => 1,
            ],
            [
                'id' => 174,
                'prep_category_id' => 3,
                'prep_item_id' => 41,
                'prep_station_id' => 17,
                'has_sizes' => 'no',
                'display_order' => 2,
            ],
            [
                'id' => 175,
                'prep_category_id' => 3,
                'prep_item_id' => 42,
                'prep_station_id' => 17,
                'has_sizes' => 'no',
                'display_order' => 3,
            ],
            [
                'id' => 177,
                'prep_category_id' => 3,
                'prep_item_id' => 44,
                'prep_station_id' => 17,
                'has_sizes' => 'no',
                'display_order' => 5,
            ],
            [
                'id' => 179,
                'prep_category_id' => 3,
                'prep_item_id' => 171,
                'prep_station_id' => 17,
                'has_sizes' => 'no',
                'display_order' => 7,
            ],
            [
                'id' => 180,
                'prep_category_id' => 2,
                'prep_item_id' => 172,
                'prep_station_id' => 5,
                'has_sizes' => 'no',
                'display_order' => 5,
            ],
            [
                'id' => 181,
                'prep_category_id' => 10,
                'prep_item_id' => 170,
                'prep_station_id' => 12,
                'has_sizes' => 'no',
                'display_order' => 2,
            ],
            [
                'id' => 182,
                'prep_category_id' => 3,
                'prep_item_id' => 173,
                'prep_station_id' => 17,
                'has_sizes' => 'no',
                'display_order' => 8,
            ],
            [
                'id' => 183,
                'prep_category_id' => 10,
                'prep_item_id' => 174,
                'prep_station_id' => 9,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 184,
                'prep_category_id' => 10,
                'prep_item_id' => 175,
                'prep_station_id' => 9,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 185,
                'prep_category_id' => 10,
                'prep_item_id' => 176,
                'prep_station_id' => 11,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 186,
                'prep_category_id' => 10,
                'prep_item_id' => 177,
                'prep_station_id' => 11,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 187,
                'prep_category_id' => 10,
                'prep_item_id' => 178,
                'prep_station_id' => 11,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 193,
                'prep_category_id' => 3,
                'prep_item_id' => 183,
                'prep_station_id' => 42,
                'has_sizes' => 'no',
                'display_order' => 2,
            ],
            [
                'id' => 194,
                'prep_category_id' => 3,
                'prep_item_id' => 184,
                'prep_station_id' => 42,
                'has_sizes' => 'no',
                'display_order' => 3,
            ],
            [
                'id' => 195,
                'prep_category_id' => 3,
                'prep_item_id' => 185,
                'prep_station_id' => 42,
                'has_sizes' => 'no',
                'display_order' => 4,
            ],
            [
                'id' => 196,
                'prep_category_id' => 3,
                'prep_item_id' => 186,
                'prep_station_id' => 42,
                'has_sizes' => 'no',
                'display_order' => 5,
            ],
            [
                'id' => 197,
                'prep_category_id' => 3,
                'prep_item_id' => 187,
                'prep_station_id' => 42,
                'has_sizes' => 'no',
                'display_order' => 6,
            ],
            [
                'id' => 198,
                'prep_category_id' => 4,
                'prep_item_id' => 188,
                'prep_station_id' => 19,
                'has_sizes' => 'no',
                'display_order' => 5,
            ],
            [
                'id' => 199,
                'prep_category_id' => 4,
                'prep_item_id' => 189,
                'prep_station_id' => 19,
                'has_sizes' => 'no',
                'display_order' => 8,
            ],
            [
                'id' => 200,
                'prep_category_id' => 4,
                'prep_item_id' => 190,
                'prep_station_id' => 19,
                'has_sizes' => 'no',
                'display_order' => 8,
            ],
            [
                'id' => 202,
                'prep_category_id' => 4,
                'prep_item_id' => 192,
                'prep_station_id' => 19,
                'has_sizes' => 'no',
                'display_order' => 9,
            ],
            [
                'id' => 204,
                'prep_category_id' => 5,
                'prep_item_id' => 200,
                'prep_station_id' => 21,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 205,
                'prep_category_id' => 3,
                'prep_item_id' => 202,
                'prep_station_id' => 15,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 206,
                'prep_category_id' => 3,
                'prep_item_id' => 201,
                'prep_station_id' => 14,
                'has_sizes' => 'no',
                'display_order' => 7,
            ],
            [
                'id' => 209,
                'prep_category_id' => 3,
                'prep_item_id' => 199,
                'prep_station_id' => 16,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 210,
                'prep_category_id' => 5,
                'prep_item_id' => 195,
                'prep_station_id' => 21,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 211,
                'prep_category_id' => 11,
                'prep_item_id' => 205,
                'prep_station_id' => 38,
                'has_sizes' => 'no',
                'display_order' => 1,
            ],
            [
                'id' => 212,
                'prep_category_id' => 11,
                'prep_item_id' => 206,
                'prep_station_id' => 38,
                'has_sizes' => 'no',
                'display_order' => 2,
            ],
            [
                'id' => 213,
                'prep_category_id' => 11,
                'prep_item_id' => 207,
                'prep_station_id' => 38,
                'has_sizes' => 'no',
                'display_order' => 3,
            ],
            [
                'id' => 214,
                'prep_category_id' => 11,
                'prep_item_id' => 208,
                'prep_station_id' => 38,
                'has_sizes' => 'no',
                'display_order' => 4,
            ],
            [
                'id' => 215,
                'prep_category_id' => 12,
                'prep_item_id' => 209,
                'prep_station_id' => 39,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 216,
                'prep_category_id' => 12,
                'prep_item_id' => 210,
                'prep_station_id' => 39,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 217,
                'prep_category_id' => 12,
                'prep_item_id' => 211,
                'prep_station_id' => 39,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 218,
                'prep_category_id' => 12,
                'prep_item_id' => 212,
                'prep_station_id' => 39,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 219,
                'prep_category_id' => 12,
                'prep_item_id' => 213,
                'prep_station_id' => 40,
                'has_sizes' => 'no',
                'display_order' => 1,
            ],
            [
                'id' => 220,
                'prep_category_id' => 12,
                'prep_item_id' => 214,
                'prep_station_id' => 40,
                'has_sizes' => 'no',
                'display_order' => 2,
            ],
            [
                'id' => 221,
                'prep_category_id' => 12,
                'prep_item_id' => 215,
                'prep_station_id' => 40,
                'has_sizes' => 'no',
                'display_order' => 3,
            ],
            [
                'id' => 222,
                'prep_category_id' => 12,
                'prep_item_id' => 216,
                'prep_station_id' => 40,
                'has_sizes' => 'no',
                'display_order' => 4,
            ],
            [
                'id' => 223,
                'prep_category_id' => 12,
                'prep_item_id' => 217,
                'prep_station_id' => 40,
                'has_sizes' => 'no',
                'display_order' => 5,
            ],
            [
                'id' => 224,
                'prep_category_id' => 12,
                'prep_item_id' => 218,
                'prep_station_id' => 40,
                'has_sizes' => 'no',
                'display_order' => 6,
            ],
            [
                'id' => 225,
                'prep_category_id' => 12,
                'prep_item_id' => 219,
                'prep_station_id' => 40,
                'has_sizes' => 'no',
                'display_order' => 7,
            ],
            [
                'id' => 226,
                'prep_category_id' => 12,
                'prep_item_id' => 221,
                'prep_station_id' => 40,
                'has_sizes' => 'no',
                'display_order' => 8,
            ],
            [
                'id' => 227,
                'prep_category_id' => 10,
                'prep_item_id' => 223,
                'prep_station_id' => 12,
                'has_sizes' => 'no',
                'display_order' => 3,
            ],
            [
                'id' => 228,
                'prep_category_id' => 10,
                'prep_item_id' => 224,
                'prep_station_id' => 12,
                'has_sizes' => 'no',
                'display_order' => 4,
            ],
            [
                'id' => 230,
                'prep_category_id' => 10,
                'prep_item_id' => 226,
                'prep_station_id' => 12,
                'has_sizes' => 'no',
                'display_order' => 5,
            ],
            [
                'id' => 232,
                'prep_category_id' => 3,
                'prep_item_id' => 228,
                'prep_station_id' => 42,
                'has_sizes' => 'no',
                'display_order' => 7,
            ],
            [
                'id' => 233,
                'prep_category_id' => 12,
                'prep_item_id' => 222,
                'prep_station_id' => 40,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 234,
                'prep_category_id' => 12,
                'prep_item_id' => 220,
                'prep_station_id' => 40,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 235,
                'prep_category_id' => 6,
                'prep_item_id' => 229,
                'prep_station_id' => 25,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 236,
                'prep_category_id' => 6,
                'prep_item_id' => 230,
                'prep_station_id' => 25,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 237,
                'prep_category_id' => 6,
                'prep_item_id' => 231,
                'prep_station_id' => 25,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 238,
                'prep_category_id' => 6,
                'prep_item_id' => 193,
                'prep_station_id' => 25,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 239,
                'prep_category_id' => 10,
                'prep_item_id' => 233,
                'prep_station_id' => 12,
                'has_sizes' => 'no',
                'display_order' => 6,
            ],
            [
                'id' => 240,
                'prep_category_id' => 4,
                'prep_item_id' => 234,
                'prep_station_id' => 43,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 241,
                'prep_category_id' => 4,
                'prep_item_id' => 235,
                'prep_station_id' => 43,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 242,
                'prep_category_id' => 4,
                'prep_item_id' => 236,
                'prep_station_id' => 43,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 243,
                'prep_category_id' => 13,
                'prep_item_id' => 64,
                'prep_station_id' => 44,
                'has_sizes' => 'no',
                'display_order' => 1,
            ],
            [
                'id' => 244,
                'prep_category_id' => 13,
                'prep_item_id' => 65,
                'prep_station_id' => 44,
                'has_sizes' => 'no',
                'display_order' => 2,
            ],
            [
                'id' => 245,
                'prep_category_id' => 13,
                'prep_item_id' => 179,
                'prep_station_id' => 44,
                'has_sizes' => 'no',
                'display_order' => 3,
            ],
            [
                'id' => 246,
                'prep_category_id' => 13,
                'prep_item_id' => 180,
                'prep_station_id' => 44,
                'has_sizes' => 'no',
                'display_order' => 4,
            ],
            [
                'id' => 247,
                'prep_category_id' => 13,
                'prep_item_id' => 181,
                'prep_station_id' => 44,
                'has_sizes' => 'no',
                'display_order' => 5,
            ],
            [
                'id' => 248,
                'prep_category_id' => 13,
                'prep_item_id' => 63,
                'prep_station_id' => 44,
                'has_sizes' => 'no',
                'display_order' => 6,
            ],
            [
                'id' => 249,
                'prep_category_id' => 13,
                'prep_item_id' => 60,
                'prep_station_id' => 44,
                'has_sizes' => 'no',
                'display_order' => 7,
            ],
            [
                'id' => 250,
                'prep_category_id' => 13,
                'prep_item_id' => 61,
                'prep_station_id' => 44,
                'has_sizes' => 'no',
                'display_order' => 11,
            ],
            [
                'id' => 251,
                'prep_category_id' => 13,
                'prep_item_id' => 237,
                'prep_station_id' => 44,
                'has_sizes' => 'no',
                'display_order' => 8,
            ],
            [
                'id' => 252,
                'prep_category_id' => 13,
                'prep_item_id' => 238,
                'prep_station_id' => 44,
                'has_sizes' => 'no',
                'display_order' => 10,
            ],
            [
                'id' => 253,
                'prep_category_id' => 13,
                'prep_item_id' => 239,
                'prep_station_id' => 44,
                'has_sizes' => 'no',
                'display_order' => 14,
            ],
            [
                'id' => 254,
                'prep_category_id' => 13,
                'prep_item_id' => 240,
                'prep_station_id' => 44,
                'has_sizes' => 'no',
                'display_order' => 9,
            ],
            [
                'id' => 255,
                'prep_category_id' => 13,
                'prep_item_id' => 241,
                'prep_station_id' => 44,
                'has_sizes' => 'no',
                'display_order' => 11,
            ],
            [
                'id' => 258,
                'prep_category_id' => 6,
                'prep_item_id' => 244,
                'prep_station_id' => 24,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 259,
                'prep_category_id' => 3,
                'prep_item_id' => 245,
                'prep_station_id' => 17,
                'has_sizes' => 'no',
                'display_order' => 9,
            ],
            [
                'id' => 260,
                'prep_category_id' => 3,
                'prep_item_id' => 246,
                'prep_station_id' => 17,
                'has_sizes' => 'no',
                'display_order' => 10,
            ],
            [
                'id' => 261,
                'prep_category_id' => 9,
                'prep_item_id' => 197,
                'prep_station_id' => 37,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 262,
                'prep_category_id' => 9,
                'prep_item_id' => 196,
                'prep_station_id' => 36,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 263,
                'prep_category_id' => 5,
                'prep_item_id' => 198,
                'prep_station_id' => 22,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 264,
                'prep_category_id' => 4,
                'prep_item_id' => 247,
                'prep_station_id' => 19,
                'has_sizes' => 'no',
                'display_order' => 6,
            ],
            [
                'id' => 265,
                'prep_category_id' => 2,
                'prep_item_id' => 248,
                'prep_station_id' => 5,
                'has_sizes' => 'no',
                'display_order' => 6,
            ],
            [
                'id' => 266,
                'prep_category_id' => 10,
                'prep_item_id' => 249,
                'prep_station_id' => 10,
                'has_sizes' => 'no',
                'display_order' => 9,
            ],
            [
                'id' => 267,
                'prep_category_id' => 10,
                'prep_item_id' => 250,
                'prep_station_id' => 10,
                'has_sizes' => 'no',
                'display_order' => 10,
            ],
            [
                'id' => 268,
                'prep_category_id' => 14,
                'prep_item_id' => 155,
                'prep_station_id' => 45,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 269,
                'prep_category_id' => 14,
                'prep_item_id' => 156,
                'prep_station_id' => 45,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 270,
                'prep_category_id' => 14,
                'prep_item_id' => 157,
                'prep_station_id' => 45,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 271,
                'prep_category_id' => 14,
                'prep_item_id' => 158,
                'prep_station_id' => 45,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 272,
                'prep_category_id' => 14,
                'prep_item_id' => 159,
                'prep_station_id' => 45,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 273,
                'prep_category_id' => 14,
                'prep_item_id' => 160,
                'prep_station_id' => 45,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 274,
                'prep_category_id' => 14,
                'prep_item_id' => 161,
                'prep_station_id' => 45,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 275,
                'prep_category_id' => 14,
                'prep_item_id' => 249,
                'prep_station_id' => 45,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 276,
                'prep_category_id' => 14,
                'prep_item_id' => 250,
                'prep_station_id' => 45,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 277,
                'prep_category_id' => 14,
                'prep_item_id' => 169,
                'prep_station_id' => 46,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 278,
                'prep_category_id' => 14,
                'prep_item_id' => 170,
                'prep_station_id' => 46,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 279,
                'prep_category_id' => 14,
                'prep_item_id' => 223,
                'prep_station_id' => 46,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 280,
                'prep_category_id' => 14,
                'prep_item_id' => 224,
                'prep_station_id' => 46,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 281,
                'prep_category_id' => 14,
                'prep_item_id' => 226,
                'prep_station_id' => 46,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 282,
                'prep_category_id' => 14,
                'prep_item_id' => 233,
                'prep_station_id' => 46,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 283,
                'prep_category_id' => 14,
                'prep_item_id' => 162,
                'prep_station_id' => 45,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 284,
                'prep_category_id' => 16,
                'prep_item_id' => 251,
                'prep_station_id' => 47,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 285,
                'prep_category_id' => 16,
                'prep_item_id' => 252,
                'prep_station_id' => 47,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 286,
                'prep_category_id' => 16,
                'prep_item_id' => 253,
                'prep_station_id' => 47,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 287,
                'prep_category_id' => 16,
                'prep_item_id' => 254,
                'prep_station_id' => 47,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 288,
                'prep_category_id' => 16,
                'prep_item_id' => 255,
                'prep_station_id' => 47,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 289,
                'prep_category_id' => 16,
                'prep_item_id' => 256,
                'prep_station_id' => 47,
                'has_sizes' => 'no',
                'display_order' => null,
            ],
            [
                'id' => 290,
                'prep_category_id' => 3,
                'prep_item_id' => 258,
                'prep_station_id' => 42,
                'has_sizes' => 'no',
                'display_order' => 1,
            ],
            [
                'id' => 291,
                'prep_category_id' => 2,
                'prep_item_id' => 261,
                'prep_station_id' => 5,
                'has_sizes' => 'no',
                'display_order' => 7,
            ],
            [
                'id' => 292,
                'prep_category_id' => 2,
                'prep_item_id' => 260,
                'prep_station_id' => 6,
                'has_sizes' => 'no',
                'display_order' => 5,
            ],
            [
                'id' => 294,
                'prep_category_id' => 2,
                'prep_item_id' => 259,
                'prep_station_id' => 7,
                'has_sizes' => 'no',
                'display_order' => 5,
            ],
            [
                'id' => 295,
                'prep_category_id' => 11,
                'prep_item_id' => 263,
                'prep_station_id' => 38,
                'has_sizes' => 'no',
                'display_order' => 5,
            ],
            [
                'id' => 296,
                'prep_category_id' => 4,
                'prep_item_id' => 264,
                'prep_station_id' => 19,
                'has_sizes' => 'no',
                'display_order' => 9,
            ],
        ];

        DB::table('prep_item_station')->insert($dataTables);
    }
}
