<?php

namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PrepPackageDealIndexesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables --limit=500
         */
        $dataTables = [
            [
                'id' => 1,
                'quantity' => 1,
                'feed' => 6,
                'leafy_salad' => '["0","1","0"]',
                'leafy_salad_alacart' => '["0","1","0"]',
                'pasta_salad' => '["1","0","0"]',
                'pasta_salad_alacart' => '["1","0","0"]',
                'fruit_bowl' => '["1","0","0"]',
                'fruit_bowl_alacart' => '["1","0","0"]',
                'fruit_tray' => 1,
                'fruit_tray_alacart' => 1,
                'sweet_tray_cookie_brownie' => 1,
                'sweet_tray_cookie_brownie_alacart' => 1,
                'created_by' => 120277,
                'updated_by' => 175889,
                'created_at' => '2023-03-27 13:11:49',
                'updated_at' => '2023-07-11 13:25:22',
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'quantity' => 2,
                'feed' => 12,
                'leafy_salad' => '["0","0","1"]',
                'leafy_salad_alacart' => '["0","0","1"]',
                'pasta_salad' => '["0","1","0"]',
                'pasta_salad_alacart' => '["0","1","0"]',
                'fruit_bowl' => '["1","0","0"]',
                'fruit_bowl_alacart' => '["0","1","0"]',
                'fruit_tray' => 1,
                'fruit_tray_alacart' => 2,
                'sweet_tray_cookie_brownie' => 1,
                'sweet_tray_cookie_brownie_alacart' => 2,
                'created_by' => 120277,
                'updated_by' => 175889,
                'created_at' => '2023-03-27 13:23:58',
                'updated_at' => '2023-08-04 20:45:40',
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'quantity' => 3,
                'feed' => 18,
                'leafy_salad' => '["0","0","1"]',
                'leafy_salad_alacart' => '["0","1","1"]',
                'pasta_salad' => '["0","1","0"]',
                'pasta_salad_alacart' => '["1","1","0"]',
                'fruit_bowl' => '["0","1","0"]',
                'fruit_bowl_alacart' => '["1","1","0"]',
                'fruit_tray' => 2,
                'fruit_tray_alacart' => 3,
                'sweet_tray_cookie_brownie' => 2,
                'sweet_tray_cookie_brownie_alacart' => 3,
                'created_by' => 120277,
                'updated_by' => 175889,
                'created_at' => '2023-03-27 13:24:38',
                'updated_at' => '2023-07-11 13:29:07',
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'quantity' => 4,
                'feed' => 24,
                'leafy_salad' => '["0","0","1"]',
                'leafy_salad_alacart' => '["0","0","2"]',
                'pasta_salad' => '["0","1","0"]',
                'pasta_salad_alacart' => '["0","2","0"]',
                'fruit_bowl' => '["0","1","0"]',
                'fruit_bowl_alacart' => '["0","2","0"]',
                'fruit_tray' => 2,
                'fruit_tray_alacart' => 4,
                'sweet_tray_cookie_brownie' => 2,
                'sweet_tray_cookie_brownie_alacart' => 4,
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-03-27 17:37:21',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'quantity' => 5,
                'feed' => 30,
                'leafy_salad' => '["0","1","1"]',
                'leafy_salad_alacart' => '["0","1","2"]',
                'pasta_salad' => '["1","1","0"]',
                'pasta_salad_alacart' => '["1","2","0"]',
                'fruit_bowl' => '["1","1","0"]',
                'fruit_bowl_alacart' => '["1","2","0"]',
                'fruit_tray' => 3,
                'fruit_tray_alacart' => 5,
                'sweet_tray_cookie_brownie' => 3,
                'sweet_tray_cookie_brownie_alacart' => 5,
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-05-19 13:46:38',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'quantity' => 6,
                'feed' => 36,
                'leafy_salad' => '["0","1","1"]',
                'leafy_salad_alacart' => '["0","0","3"]',
                'pasta_salad' => '["1","1","0"]',
                'pasta_salad_alacart' => '["0","3","0"]',
                'fruit_bowl' => '["1","1","0"]',
                'fruit_bowl_alacart' => '["0","3","0"]',
                'fruit_tray' => 3,
                'fruit_tray_alacart' => 6,
                'sweet_tray_cookie_brownie' => 3,
                'sweet_tray_cookie_brownie_alacart' => 6,
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-05-19 13:47:29',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'quantity' => 7,
                'feed' => 42,
                'leafy_salad' => '["0","0","2"]',
                'leafy_salad_alacart' => '["0","1","3"]',
                'pasta_salad' => '["0","2","0"]',
                'pasta_salad_alacart' => '["1","3","0"]',
                'fruit_bowl' => '["0","2","0"]',
                'fruit_bowl_alacart' => '["1","3","0"]',
                'fruit_tray' => 4,
                'fruit_tray_alacart' => 7,
                'sweet_tray_cookie_brownie' => 4,
                'sweet_tray_cookie_brownie_alacart' => 7,
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-05-19 13:48:00',
                'updated_at' => '2023-07-11 14:42:01',
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'quantity' => 8,
                'feed' => 48,
                'leafy_salad' => '["0","0","2"]',
                'leafy_salad_alacart' => '["0","0","4"]',
                'pasta_salad' => '["0","2","0"]',
                'pasta_salad_alacart' => '["0","4","0"]',
                'fruit_bowl' => '["0","2","0"]',
                'fruit_bowl_alacart' => '["0","4","0"]',
                'fruit_tray' => 4,
                'fruit_tray_alacart' => 8,
                'sweet_tray_cookie_brownie' => 4,
                'sweet_tray_cookie_brownie_alacart' => 8,
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-05-19 13:48:58',
                'updated_at' => '2023-07-11 14:42:29',
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'quantity' => 9,
                'feed' => 54,
                'leafy_salad' => '["0","0","2"]',
                'leafy_salad_alacart' => '["0","1","4"]',
                'pasta_salad' => '["0","2","0"]',
                'pasta_salad_alacart' => '["1","4","0"]',
                'fruit_bowl' => '["0","2","0"]',
                'fruit_bowl_alacart' => '["1","4","0"]',
                'fruit_tray' => 4,
                'fruit_tray_alacart' => 9,
                'sweet_tray_cookie_brownie' => 4,
                'sweet_tray_cookie_brownie_alacart' => 9,
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-05-19 14:16:27',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'quantity' => 10,
                'feed' => 60,
                'leafy_salad' => '["0","1","2"]',
                'leafy_salad_alacart' => '["0","0","5"]',
                'pasta_salad' => '["1","2","0"]',
                'pasta_salad_alacart' => '["0","5","0"]',
                'fruit_bowl' => '["1","2","0"]',
                'fruit_bowl_alacart' => '["0","5","0"]',
                'fruit_tray' => 5,
                'fruit_tray_alacart' => 10,
                'sweet_tray_cookie_brownie' => 5,
                'sweet_tray_cookie_brownie_alacart' => 10,
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-05-19 14:17:07',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'quantity' => 11,
                'feed' => 66,
                'leafy_salad' => '["0","0","3"]',
                'leafy_salad_alacart' => '["0","1","5"]',
                'pasta_salad' => '["0","3","0"]',
                'pasta_salad_alacart' => '["1","5","0"]',
                'fruit_bowl' => '["0","3","0"]',
                'fruit_bowl_alacart' => '["1","5","0"]',
                'fruit_tray' => 6,
                'fruit_tray_alacart' => 11,
                'sweet_tray_cookie_brownie' => 6,
                'sweet_tray_cookie_brownie_alacart' => 11,
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-05-19 14:17:45',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'quantity' => 12,
                'feed' => 72,
                'leafy_salad' => '["0","0","3"]',
                'leafy_salad_alacart' => '["0","0","6"]',
                'pasta_salad' => '["0","3","0"]',
                'pasta_salad_alacart' => '["0","6","0"]',
                'fruit_bowl' => '["0","3","0"]',
                'fruit_bowl_alacart' => '["0","6","0"]',
                'fruit_tray' => 6,
                'fruit_tray_alacart' => 12,
                'sweet_tray_cookie_brownie' => 6,
                'sweet_tray_cookie_brownie_alacart' => 12,
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-05-19 14:18:15',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'quantity' => 13,
                'feed' => 78,
                'leafy_salad' => '["0","1","3"]',
                'leafy_salad_alacart' => '["0","1","6"]',
                'pasta_salad' => '["1","3","0"]',
                'pasta_salad_alacart' => '["1","6","0"]',
                'fruit_bowl' => '["1","3","0"]',
                'fruit_bowl_alacart' => '["1","6","0"]',
                'fruit_tray' => 7,
                'fruit_tray_alacart' => 13,
                'sweet_tray_cookie_brownie' => 7,
                'sweet_tray_cookie_brownie_alacart' => 13,
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-05-19 14:18:57',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'quantity' => 14,
                'feed' => 84,
                'leafy_salad' => '["0","1","3"]',
                'leafy_salad_alacart' => '["0","0","7"]',
                'pasta_salad' => '["1","3","0"]',
                'pasta_salad_alacart' => '["0","7","0"]',
                'fruit_bowl' => '["1","3","0"]',
                'fruit_bowl_alacart' => '["0","7","0"]',
                'fruit_tray' => 7,
                'fruit_tray_alacart' => 14,
                'sweet_tray_cookie_brownie' => 7,
                'sweet_tray_cookie_brownie_alacart' => 14,
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-05-19 14:19:29',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'quantity' => 15,
                'feed' => 90,
                'leafy_salad' => '["0","0","4"]',
                'leafy_salad_alacart' => '["0","1","7"]',
                'pasta_salad' => '["0","4","0"]',
                'pasta_salad_alacart' => '["1","7","0"]',
                'fruit_bowl' => '["0","4","0"]',
                'fruit_bowl_alacart' => '["1","7","0"]',
                'fruit_tray' => 8,
                'fruit_tray_alacart' => 15,
                'sweet_tray_cookie_brownie' => 8,
                'sweet_tray_cookie_brownie_alacart' => 15,
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-05-19 14:19:56',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'quantity' => 16,
                'feed' => 96,
                'leafy_salad' => '["0","0","4"]',
                'leafy_salad_alacart' => '["0","0","8"]',
                'pasta_salad' => '["0","4","0"]',
                'pasta_salad_alacart' => '["0","8","0"]',
                'fruit_bowl' => '["0","4","0"]',
                'fruit_bowl_alacart' => '["0","8","0"]',
                'fruit_tray' => 8,
                'fruit_tray_alacart' => 16,
                'sweet_tray_cookie_brownie' => 8,
                'sweet_tray_cookie_brownie_alacart' => 16,
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-05-19 14:20:24',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 17,
                'quantity' => 17,
                'feed' => 102,
                'leafy_salad' => '["0","0","4"]',
                'leafy_salad_alacart' => '["0","1","8"]',
                'pasta_salad' => '["0","4","0"]',
                'pasta_salad_alacart' => '["1","8","0"]',
                'fruit_bowl' => '["0","4","0"]',
                'fruit_bowl_alacart' => '["1","8","0"]',
                'fruit_tray' => 9,
                'fruit_tray_alacart' => 17,
                'sweet_tray_cookie_brownie' => 9,
                'sweet_tray_cookie_brownie_alacart' => 17,
                'created_by' => 175889,
                'updated_by' => 175889,
                'created_at' => '2023-05-19 14:20:48',
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
        ];

        DB::table('prep_package_deal_indexes')->insert($dataTables);
    }
}
