<?php

namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PromotionTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables --limit=500
         */
        $dataTables = [
            [
                'id' => 1,
                'name' => '25% off orders for next Monday',
                'discount_type' => 1,
                'discount_value' => 25,
                'day_value' => 'Monday',
                'day_type' => 1,
                'all_orders' => 1,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 2,
                'name' => '20% off orders for next Monday',
                'discount_type' => 1,
                'discount_value' => 20,
                'day_value' => 'Monday',
                'day_type' => 1,
                'all_orders' => 1,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 3,
                'name' => '15% off orders for next Monday',
                'discount_type' => 1,
                'discount_value' => 15,
                'day_value' => 'Monday',
                'day_type' => 1,
                'all_orders' => 1,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 4,
                'name' => '10% off orders for next Monday',
                'discount_type' => 1,
                'discount_value' => 10,
                'day_value' => 'Monday',
                'day_type' => 1,
                'all_orders' => 1,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 5,
                'name' => '25% off orders for next Friday',
                'discount_type' => 1,
                'discount_value' => 25,
                'day_value' => 'Friday',
                'day_type' => 1,
                'all_orders' => 1,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 6,
                'name' => '20% off orders for next Friday',
                'discount_type' => 1,
                'discount_value' => 20,
                'day_value' => 'Friday',
                'day_type' => 1,
                'all_orders' => 1,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 7,
                'name' => '15% off orders for next Friday',
                'discount_type' => 1,
                'discount_value' => 15,
                'day_value' => 'Friday',
                'day_type' => 1,
                'all_orders' => 1,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 8,
                'name' => '10% off orders for next Friday',
                'discount_type' => 1,
                'discount_value' => 10,
                'day_value' => 'Friday',
                'day_type' => 1,
                'all_orders' => 1,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 9,
                'name' => '25% off Platinum package deals for next week',
                'discount_type' => 1,
                'discount_value' => 25,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 10,
                'name' => '20% off Platinum package deals for next week',
                'discount_type' => 1,
                'discount_value' => 20,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 11,
                'name' => '15% off Platinum package deals for next week',
                'discount_type' => 1,
                'discount_value' => 15,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 12,
                'name' => '10% off Platinum package deals for next week',
                'discount_type' => 1,
                'discount_value' => 10,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 13,
                'name' => '25% off All orders for next week',
                'discount_type' => 1,
                'discount_value' => 25,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 1,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 14,
                'name' => '20% off All orders for next week',
                'discount_type' => 1,
                'discount_value' => 20,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 1,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 15,
                'name' => '15% off All orders for next week',
                'discount_type' => 1,
                'discount_value' => 15,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 1,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 16,
                'name' => '10% off All orders for next week',
                'discount_type' => 1,
                'discount_value' => 10,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 1,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 17,
                'name' => '25% off Flash sale for all orders next (Select one - day]',
                'discount_type' => 1,
                'discount_value' => 25,
                'day_value' => '',
                'day_type' => 3,
                'all_orders' => 1,
                'special' => 1,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 0,
            ],
            [
                'id' => 18,
                'name' => 'Free Delivery for all lunch orders next week ',
                'discount_type' => 3,
                'discount_value' => 0,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 0,
            ],
            [
                'id' => 19,
                'name' => 'Free Delivery for all breakfast orders next week',
                'discount_type' => 3,
                'discount_value' => 0,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 0,
            ],
            [
                'id' => 20,
                'name' => '25% off Hot Plate Orders for next week (excludes box lunch hot plates]',
                'discount_type' => 1,
                'discount_value' => 25,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 21,
                'name' => '20% off Hot Plate Orders for next week (excludes box lunch hot plates]',
                'discount_type' => 1,
                'discount_value' => 20,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 22,
                'name' => '15% off Hot Plate Orders for next week (excludes box lunch hot plates]',
                'discount_type' => 1,
                'discount_value' => 15,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 23,
                'name' => '10% off Hot Plate Orders for next week (excludes box lunch hot plates]',
                'discount_type' => 1,
                'discount_value' => 10,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 24,
                'name' => '$8 - $9 -$10 (Traditional - Premium - Salad] Box lunch special all next week',
                'discount_type' => 2,
                'discount_value' => 0,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 1,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 0,
            ],
            [
                'id' => 25,
                'name' => '20% off All breakfast orders next week',
                'discount_type' => 1,
                'discount_value' => 20,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 26,
                'name' => '15% off All breakfast orders next week',
                'discount_type' => 1,
                'discount_value' => 15,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 27,
                'name' => '10% off All breakfast orders next week',
                'discount_type' => 1,
                'discount_value' => 10,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 28,
                'name' => 'Free dessert with hot plate orders next week',
                'discount_type' => 3,
                'discount_value' => 0,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 29,
                'name' => 'Free Discount equal to Tax plus Delivery fee for all orders next week',
                'discount_type' => 3,
                'discount_value' => 0,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 1,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 0,
            ],
            [
                'id' => 30,
                'name' => '$8.99 box lunch special for premium sandwiches, Pressatas, wraps and salad box lunches next week',
                'discount_type' => 2,
                'discount_value' => 0,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 1,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 0,
            ],
            [
                'id' => 31,
                'name' => 'Free Coffee or OJ for all breakfast orders next week',
                'discount_type' => 3,
                'discount_value' => 0,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 32,
                'name' => '$2 off any box lunch next week',
                'discount_type' => 2,
                'discount_value' => 0,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 1,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 33,
                'name' => '$7.50 traditional box lunch next week',
                'discount_type' => 2,
                'discount_value' => 0,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 1,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 34,
                'name' => '15% all items in the Soup and More category.',
                'discount_type' => 1,
                'discount_value' => 15,
                'day_value' => 'week',
                'day_type' => 3,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 35,
                'name' => 'Free box lunch (100%  discount] ',
                'discount_type' => 3,
                'discount_value' => 0,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 1,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 36,
                'name' => 'Free Box of assorted cookies',
                'discount_type' => 3,
                'discount_value' => 0,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 1,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2019-02-01 05:38:04',
                'modified' => '2019-02-01 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 42,
                'name' => 'Free fruit cup with box lunch',
                'discount_type' => 3,
                'discount_value' => 0,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'selection',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-15 04:53:47',
                'modified' => '2020-06-15 04:53:47',
                'status' => 1,
            ],
            [
                'id' => 43,
                'name' => '15% Off Orders over $100',
                'discount_type' => 1,
                'discount_value' => 15,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 1,
                'special' => 1,
                'price_multiple' => 0,
                'min_order_value' => 100,
                'applies_to' => 'order',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-15 04:53:47',
                'modified' => '2020-06-15 04:53:47',
                'status' => 1,
            ],
            [
                'id' => 44,
                'name' => '$1 off for ciabatta breakfast sandwich box',
                'discount_type' => 2,
                'discount_value' => 1,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 1',
                'product_type' => 'single',
                'notes' => 'Ciabatta Breakfast Sandwich Box',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 45,
                'name' => '$2 off for ciabatta breakfast sandwich box',
                'discount_type' => 2,
                'discount_value' => 2,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 2',
                'product_type' => 'single',
                'notes' => 'Ciabatta Breakfast Sandwich Box',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 46,
                'name' => '$1 off for breakfast taco box',
                'discount_type' => 2,
                'discount_value' => 1,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 1',
                'product_type' => 'single',
                'notes' => 'Breakfast Taco Box',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 47,
                'name' => '$2 off for breakfast taco box',
                'discount_type' => 2,
                'discount_value' => 2,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 2',
                'product_type' => 'single',
                'notes' => 'Breakfast Taco Box',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 48,
                'name' => '$1 off for gluten-free breakfast sandwich box',
                'discount_type' => 2,
                'discount_value' => 1,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 1',
                'product_type' => 'single',
                'notes' => 'Gluten-Free Breakfast Sandwich Box',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 49,
                'name' => '$2 off for gluten-free breakfast sandwich box',
                'discount_type' => 2,
                'discount_value' => 2,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 2',
                'product_type' => 'single',
                'notes' => 'Gluten-Free Breakfast Sandwich Box',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 50,
                'name' => '$1 off for hot plate box lunch',
                'discount_type' => 2,
                'discount_value' => 1,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 1',
                'product_type' => 'single',
                'notes' => 'Hot Plate Box Lunch',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 51,
                'name' => '$2 off for hot plate box lunch',
                'discount_type' => 2,
                'discount_value' => 2,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 2',
                'product_type' => 'single',
                'notes' => 'Hot Plate Box Lunch',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 52,
                'name' => '$1 off for pressata box lunch',
                'discount_type' => 2,
                'discount_value' => 1,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 1',
                'product_type' => 'single',
                'notes' => 'Pressata Box lunch',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 53,
                'name' => '$2 off for pressata box lunch',
                'discount_type' => 2,
                'discount_value' => 2,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 2',
                'product_type' => 'single',
                'notes' => 'Pressata Box lunch',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 54,
                'name' => '$1 off for premium sandwich box lunch',
                'discount_type' => 2,
                'discount_value' => 1,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 1',
                'product_type' => 'single',
                'notes' => 'Premium Sandwich Box Lunch',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 55,
                'name' => '$2 off for premium sandwich box lunch',
                'discount_type' => 2,
                'discount_value' => 2,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 2',
                'product_type' => 'single',
                'notes' => 'Premium Sandwich Box Lunch',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 56,
                'name' => '$1 off for traditional sandwich box lunch',
                'discount_type' => 2,
                'discount_value' => 1,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 1',
                'product_type' => 'single',
                'notes' => 'Traditional Sandwich Box Lunch',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 57,
                'name' => '$2 off for traditional sandwich box lunch',
                'discount_type' => 2,
                'discount_value' => 2,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 2',
                'product_type' => 'single',
                'notes' => 'Traditional Sandwich Box Lunch',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 58,
                'name' => '$1 off for wrap box lunch',
                'discount_type' => 2,
                'discount_value' => 1,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 1',
                'product_type' => 'single',
                'notes' => 'Wrap Box Lunch',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 59,
                'name' => '$2 off for wrap box lunch',
                'discount_type' => 2,
                'discount_value' => 2,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 2',
                'product_type' => 'single',
                'notes' => 'Wrap Box Lunch',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 60,
                'name' => '$1 off for tinga chicken pita box lunch',
                'discount_type' => 2,
                'discount_value' => 1,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 1',
                'product_type' => 'single',
                'notes' => 'Tinga Chicken Pita Box Lunch',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 61,
                'name' => '$2 off for tinga chicken pita box lunch',
                'discount_type' => 2,
                'discount_value' => 2,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 2',
                'product_type' => 'single',
                'notes' => 'Tinga Chicken Pita Box Lunch',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 62,
                'name' => '$1 off for shawarma chicken pita box lunch',
                'discount_type' => 2,
                'discount_value' => 1,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 1',
                'product_type' => 'single',
                'notes' => 'Shawarma Chicken Pita Box Lunch',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 63,
                'name' => '$2 off for shawarma chicken pita box lunch',
                'discount_type' => 2,
                'discount_value' => 2,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 2',
                'product_type' => 'single',
                'notes' => 'Shawarma Chicken Pita Box Lunch',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 64,
                'name' => '$1 off for salad box lunch',
                'discount_type' => 2,
                'discount_value' => 1,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 1',
                'product_type' => 'single',
                'notes' => 'Salad Box Lunch',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 65,
                'name' => '$2 off for salad box lunch',
                'discount_type' => 2,
                'discount_value' => 2,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 2',
                'product_type' => 'single',
                'notes' => 'Salad Box Lunch',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 66,
                'name' => '$1 off for gluten-free premium sandwich box lunch',
                'discount_type' => 2,
                'discount_value' => 1,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 1',
                'product_type' => 'single',
                'notes' => 'Gluten-Free Premium Sandwich Box Lunch',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 67,
                'name' => '$2 off for gluten-free premium sandwich box lunch',
                'discount_type' => 2,
                'discount_value' => 2,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 2',
                'product_type' => 'single',
                'notes' => 'Gluten-Free Premium Sandwich Box Lunch',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 68,
                'name' => '$1 off for gluten-free traditional sandwich box lunch',
                'discount_type' => 2,
                'discount_value' => 1,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 1',
                'product_type' => 'single',
                'notes' => 'Gluten-Free Traditional Sandwich Box Lunch',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 69,
                'name' => '$2 off for gluten-free traditional sandwich box lunch',
                'discount_type' => 2,
                'discount_value' => 2,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 2',
                'product_type' => 'single',
                'notes' => 'Gluten-Free Traditional Sandwich Box Lunch',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 70,
                'name' => '$1 off for any powerbowls',
                'discount_type' => 2,
                'discount_value' => 1,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 1',
                'product_type' => 'multiple',
                'notes' => 'Powerbowls',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 71,
                'name' => '$2 off for any powerbowls',
                'discount_type' => 2,
                'discount_value' => 2,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 2',
                'product_type' => 'multiple',
                'notes' => 'Powerbowls',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 72,
                'name' => '$1 off for any breakfast boxes',
                'discount_type' => 2,
                'discount_value' => 1,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 1',
                'product_type' => 'multiple',
                'notes' => 'Breakfast Boxes',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 73,
                'name' => '$2 off for any breakfast boxes',
                'discount_type' => 2,
                'discount_value' => 2,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 2',
                'product_type' => 'multiple',
                'notes' => 'Breakfast Boxes',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:26:10',
                'modified' => '2020-06-19 04:26:10',
                'status' => 1,
            ],
            [
                'id' => 74,
                'name' => '20% off orders over $100',
                'discount_type' => 1,
                'discount_value' => 20,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 1,
                'special' => 1,
                'price_multiple' => 0,
                'min_order_value' => 100,
                'applies_to' => 'order',
                'spl_condition' => '',
                'product_type' => '',
                'notes' => '',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:31:51',
                'modified' => '2020-06-19 04:31:51',
                'status' => 1,
            ],
            [
                'id' => 75,
                'name' => '25% off orders over $100',
                'discount_type' => 1,
                'discount_value' => 25,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 1,
                'special' => 1,
                'price_multiple' => 0,
                'min_order_value' => 100,
                'applies_to' => 'order',
                'spl_condition' => '',
                'product_type' => '',
                'notes' => '',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:31:51',
                'modified' => '2020-06-19 04:31:51',
                'status' => 1,
            ],
            [
                'id' => 76,
                'name' => '15% off orders over $200',
                'discount_type' => 1,
                'discount_value' => 15,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 1,
                'special' => 1,
                'price_multiple' => 0,
                'min_order_value' => 200,
                'applies_to' => 'order',
                'spl_condition' => '',
                'product_type' => '',
                'notes' => '',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:31:51',
                'modified' => '2020-06-19 04:31:51',
                'status' => 1,
            ],
            [
                'id' => 77,
                'name' => '20% off orders over $200',
                'discount_type' => 1,
                'discount_value' => 20,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 1,
                'special' => 1,
                'price_multiple' => 0,
                'min_order_value' => 200,
                'applies_to' => 'order',
                'spl_condition' => '',
                'product_type' => '',
                'notes' => '',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:31:51',
                'modified' => '2020-06-19 04:31:51',
                'status' => 1,
            ],
            [
                'id' => 78,
                'name' => '25% off orders over $200',
                'discount_type' => 1,
                'discount_value' => 25,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 1,
                'special' => 1,
                'price_multiple' => 0,
                'min_order_value' => 200,
                'applies_to' => 'order',
                'spl_condition' => '',
                'product_type' => '',
                'notes' => '',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:31:51',
                'modified' => '2020-06-19 04:31:51',
                'status' => 1,
            ],
            [
                'id' => 79,
                'name' => '15% off orders over $300',
                'discount_type' => 1,
                'discount_value' => 15,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 1,
                'special' => 1,
                'price_multiple' => 0,
                'min_order_value' => 300,
                'applies_to' => 'order',
                'spl_condition' => '',
                'product_type' => '',
                'notes' => '',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:31:51',
                'modified' => '2020-06-19 04:31:51',
                'status' => 1,
            ],
            [
                'id' => 80,
                'name' => '20% off orders over $300',
                'discount_type' => 1,
                'discount_value' => 20,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 1,
                'special' => 1,
                'price_multiple' => 0,
                'min_order_value' => 300,
                'applies_to' => 'order',
                'spl_condition' => '',
                'product_type' => '',
                'notes' => '',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:31:51',
                'modified' => '2020-06-19 04:31:51',
                'status' => 1,
            ],
            [
                'id' => 81,
                'name' => '25% off orders over $300',
                'discount_type' => 1,
                'discount_value' => 25,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 1,
                'special' => 1,
                'price_multiple' => 0,
                'min_order_value' => 300,
                'applies_to' => 'order',
                'spl_condition' => '',
                'product_type' => '',
                'notes' => '',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:31:51',
                'modified' => '2020-06-19 04:31:51',
                'status' => 1,
            ],
            [
                'id' => 82,
                'name' => 'Free quinoa & kale salad side with purchase of power bowl or box lunch',
                'discount_type' => 3,
                'discount_value' => 0,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'selection',
                'spl_condition' => 'Quinoa & Kale Salad Side',
                'product_type' => '',
                'notes' => 'specific selection is free',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:31:51',
                'modified' => '2020-06-19 04:31:51',
                'status' => 1,
            ],
            [
                'id' => 83,
                'name' => 'Free tomato basil pasta salad side with purchase of power bowl or box lunch',
                'discount_type' => 3,
                'discount_value' => 0,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'selection',
                'spl_condition' => 'Tomato Basil Pasta Salad Side',
                'product_type' => '',
                'notes' => 'specific selection is free',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:31:52',
                'modified' => '2020-06-19 04:31:52',
                'status' => 1,
            ],
            [
                'id' => 84,
                'name' => 'Free fresh fruit cup side with purchase of power bowl or box lunch',
                'discount_type' => 3,
                'discount_value' => 0,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'selection',
                'spl_condition' => 'Fresh Fruit Cup Side',
                'product_type' => '',
                'notes' => 'specific selection is free',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:31:52',
                'modified' => '2020-06-19 04:31:52',
                'status' => 1,
            ],
            [
                'id' => 85,
                'name' => 'Free hummus & veggies side with purchase of power bowl or box lunch',
                'discount_type' => 3,
                'discount_value' => 0,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'selection',
                'spl_condition' => 'Hummus & Veggies Side',
                'product_type' => '',
                'notes' => 'specific selection is free',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:31:52',
                'modified' => '2020-06-19 04:31:52',
                'status' => 1,
            ],
            [
                'id' => 86,
                'name' => 'Free mediterranean pasta salad side with purchase of power bowl or box lunch',
                'discount_type' => 3,
                'discount_value' => 0,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'selection',
                'spl_condition' => 'Mediterranean Pasta Salad Side',
                'product_type' => '',
                'notes' => 'specific selection is free',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:31:52',
                'modified' => '2020-06-19 04:31:52',
                'status' => 1,
            ],
            [
                'id' => 87,
                'name' => 'Free mixed green salad side with purchase of power bowl or box lunch',
                'discount_type' => 3,
                'discount_value' => 0,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'selection',
                'spl_condition' => 'Mixed Green Salad Side',
                'product_type' => '',
                'notes' => 'specific selection is free',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:31:52',
                'modified' => '2020-06-19 04:31:52',
                'status' => 1,
            ],
            [
                'id' => 88,
                'name' => 'Free pesto pasta salad side with purchase of power bowl or box lunch',
                'discount_type' => 3,
                'discount_value' => 0,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'selection',
                'spl_condition' => 'Pesto Pasta Salad Side',
                'product_type' => '',
                'notes' => 'specific selection is free',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:31:52',
                'modified' => '2020-06-19 04:31:52',
                'status' => 1,
            ],
            [
                'id' => 89,
                'name' => 'Free assorted side with purchase of power bowl or box lunch',
                'discount_type' => 3,
                'discount_value' => 0,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'selection',
                'spl_condition' => 'Assorted Side',
                'product_type' => '',
                'notes' => 'specific selection is free',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-19 04:31:52',
                'modified' => '2020-06-19 04:31:52',
                'status' => 1,
            ],
            [
                'id' => 90,
                'name' => '$1 off for vegetarian box lunch',
                'discount_type' => 2,
                'discount_value' => 1,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 1',
                'product_type' => 'single',
                'notes' => 'Vegetarian Box Lunch',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-22 06:22:30',
                'modified' => '2020-06-22 06:22:30',
                'status' => 1,
            ],
            [
                'id' => 91,
                'name' => '$2 off for vegetarian box lunch',
                'discount_type' => 2,
                'discount_value' => 2,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 2',
                'product_type' => 'single',
                'notes' => 'Vegetarian Box Lunch',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-22 06:22:30',
                'modified' => '2020-06-22 06:22:30',
                'status' => 1,
            ],
            [
                'id' => 92,
                'name' => '$1 off for gluten-free salad box lunch',
                'discount_type' => 2,
                'discount_value' => 1,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 1',
                'product_type' => 'single',
                'notes' => 'Gluten-Free Salad Box Lunch',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-22 06:22:30',
                'modified' => '2020-06-22 06:22:30',
                'status' => 1,
            ],
            [
                'id' => 93,
                'name' => '$2 off for gluten-free salad box lunch',
                'discount_type' => 2,
                'discount_value' => 2,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 2',
                'product_type' => 'single',
                'notes' => 'Gluten-Free Salad Box Lunch',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-22 06:22:30',
                'modified' => '2020-06-22 06:22:30',
                'status' => 1,
            ],
            [
                'id' => 94,
                'name' => '$1 off  for any box lunches',
                'discount_type' => 2,
                'discount_value' => 1,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 1',
                'product_type' => 'multiple',
                'notes' => 'Box Lunches',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-22 06:22:30',
                'modified' => '2020-06-22 06:22:30',
                'status' => 1,
            ],
            [
                'id' => 95,
                'name' => '$2 off  for any box lunches',
                'discount_type' => 2,
                'discount_value' => 2,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 2',
                'product_type' => 'multiple',
                'notes' => 'Box Lunches',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-22 06:22:30',
                'modified' => '2020-06-22 06:22:30',
                'status' => 1,
            ],
            [
                'id' => 96,
                'name' => '1990\'s price off for any hot plates & sides',
                'discount_type' => 2,
                'discount_value' => 21,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 21',
                'product_type' => 'multiple',
                'notes' => 'Hot Plates & Sides',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-23 04:56:10',
                'modified' => '2020-06-23 04:56:10',
                'status' => 0,
            ],
            [
                'id' => 97,
                'name' => '1990\'s price off for any hot plates & sides',
                'discount_type' => 2,
                'discount_value' => 21,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 0,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'product',
                'spl_condition' => 'product_discount is 21',
                'product_type' => 'multiple',
                'notes' => 'Hot Plates & Sides',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2020-06-29 07:25:18',
                'modified' => '2020-06-29 07:25:18',
                'status' => 1,
            ],
            [
                'id' => 98,
                'name' => '21% off orders for next Friday',
                'discount_type' => 1,
                'discount_value' => 21,
                'day_value' => 'Friday',
                'day_type' => 1,
                'all_orders' => 1,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2021-01-04 05:38:04',
                'modified' => '2021-01-04 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 99,
                'name' => '21% off orders for next Monday',
                'discount_type' => 1,
                'discount_value' => 21,
                'day_value' => 'Monday',
                'day_type' => 1,
                'all_orders' => 1,
                'special' => 0,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => '',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => null,
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2021-01-04 05:38:04',
                'modified' => '2021-01-04 05:38:04',
                'status' => 1,
            ],
            [
                'id' => 100,
                'name' => '21% off 1st order of the year',
                'discount_type' => 4,
                'discount_value' => 21,
                'day_value' => 'Year',
                'day_type' => 3,
                'all_orders' => 1,
                'special' => 1,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'order',
                'spl_condition' => 'product_discount is 21',
                'product_type' => null,
                'notes' => 'one time use for the year',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2021-01-11 04:35:45',
                'modified' => '2021-01-11 04:35:45',
                'status' => 1,
            ],
            [
                'id' => 101,
                'name' => 'Free Delivery after $100 food spending',
                'discount_type' => 3,
                'discount_value' => 0,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 1,
                'special' => 1,
                'price_multiple' => 0,
                'min_order_value' => 100,
                'applies_to' => 'order',
                'spl_condition' => null,
                'product_type' => null,
                'notes' => 'Free Delivery after $100 food spending',
                'free_delivery' => 1,
                'free_tax' => 0,
                'created' => '2021-01-27 02:44:54',
                'modified' => '2021-01-27 02:44:54',
                'status' => 1,
            ],
            [
                'id' => 102,
                'name' => '100% off for Coffee for 10 or Orange Juice for 10 purchase with breakfast package deal',
                'discount_type' => 1,
                'discount_value' => 100,
                'day_value' => 'week',
                'day_type' => 2,
                'all_orders' => 1,
                'special' => 1,
                'price_multiple' => 0,
                'min_order_value' => null,
                'applies_to' => 'category',
                'spl_condition' => 'Breakfast-Packages',
                'product_type' => null,
                'notes' => 'Get 100% discount for beverage coffee for 10 or orange juice for 10 of purchasing with breakfast packages',
                'free_delivery' => 0,
                'free_tax' => 0,
                'created' => '2021-07-09 14:32:46',
                'modified' => '2021-07-09 14:32:46',
                'status' => 1,
            ],
        ];

        DB::table('promotion_type')->insert($dataTables);
    }
}
