<?php

namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SpecialOffersTestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables --limit=500
         */
        $dataTables = [
            [
                'id' => 1,
                'active' => 1,
                'firstname' => 'rupam',
                'lastname' => 'boruah',
                'company' => 'test',
                'email' => 'rupam.jyoti@softway.com',
                'deliveryzipcode' => 77479,
                'email_bounce' => 'no',
            ],
            [
                'id' => 2,
                'active' => 1,
                'firstname' => 'Jayasimha',
                'lastname' => 'softway',
                'company' => 'test',
                'email' => 'jayasimha@softway.com',
                'deliveryzipcode' => 77479,
                'email_bounce' => 'yes',
            ],
            [
                'id' => 3,
                'active' => 1,
                'firstname' => 'Mohammed',
                'lastname' => 'Khadeer',
                'company' => 'test',
                'email' => 'mohammed.khadeer@softwaysolutions.com',
                'deliveryzipcode' => 77479,
                'email_bounce' => 'no',
            ],
            [
                'id' => 4,
                'active' => 1,
                'firstname' => 'avneesh',
                'lastname' => 'gupta',
                'company' => 'Test',
                'email' => 'vipin@softwaysolutions.com',
                'deliveryzipcode' => 77479,
                'email_bounce' => 'no',
            ],
            [
                'id' => 6,
                'active' => 1,
                'firstname' => 'Anthony',
                'lastname' => 'Caudle',
                'company' => 'Utility Concrete Products',
                'email' => 'acaudle@stormtrap.com',
                'deliveryzipcode' => 60450,
                'email_bounce' => 'no',
            ],
            [
                'id' => 7,
                'active' => 1,
                'firstname' => 'Brenda',
                'lastname' => 'Sitton',
                'company' => 'Nokia',
                'email' => 'brenda.sitton@nokia.com',
                'deliveryzipcode' => 75075,
                'email_bounce' => 'no',
            ],
            [
                'id' => 8,
                'active' => 1,
                'firstname' => 'Gail',
                'lastname' => 'Garcia',
                'company' => 'N/A',
                'email' => 'gail.garcia@mastec.com',
                'deliveryzipcode' => 78238,
                'email_bounce' => 'no',
            ],
            [
                'id' => 9,
                'active' => 1,
                'firstname' => 'Alice',
                'lastname' => 'Yum',
                'company' => 'HDR Inc',
                'email' => 'alice.yum@hdrinc.com',
                'deliveryzipcode' => 91101,
                'email_bounce' => 'no',
            ],
            [
                'id' => 10,
                'active' => 1,
                'firstname' => 'Mariann',
                'lastname' => 'Rapp',
                'company' => 'Federal Reserve Bank of Chicago',
                'email' => 'mariann.rapp@chi.frb.org',
                'deliveryzipcode' => 60148,
                'email_bounce' => 'no',
            ],
            [
                'id' => 11,
                'active' => 1,
                'firstname' => 'Carrie',
                'lastname' => 'Brownlee',
                'company' => 'Macmillan Learning',
                'email' => 'carrie.brownlee@macmillan.com',
                'deliveryzipcode' => 77044,
                'email_bounce' => 'no',
            ],
            [
                'id' => 12,
                'active' => 1,
                'firstname' => 'Karen',
                'lastname' => 'Miller',
                'company' => 'Austin Board of Realtors',
                'email' => 'kmiller@abor.com',
                'deliveryzipcode' => 78759,
                'email_bounce' => 'no',
            ],
            [
                'id' => 13,
                'active' => 1,
                'firstname' => 'Cameron',
                'lastname' => 'Gafford',
                'company' => 'TDIndustries',
                'email' => 'cameron.gafford@tdindustries.com',
                'deliveryzipcode' => 77002,
                'email_bounce' => 'no',
            ],
            [
                'id' => 14,
                'active' => 1,
                'firstname' => 'Annissa',
                'lastname' => 'Mendoza ',
                'company' => 'Sysco',
                'email' => 'Mendoza.Annissa@corp.sysco.com',
                'deliveryzipcode' => 77077,
                'email_bounce' => 'no',
            ],
            [
                'id' => 15,
                'active' => 1,
                'firstname' => 'Paul',
                'lastname' => 'Pinon',
                'company' => 'Waste Management',
                'email' => 'tchipley@aprecovery.com',
                'deliveryzipcode' => 77002,
                'email_bounce' => 'no',
            ],
            [
                'id' => 16,
                'active' => 1,
                'firstname' => 'Darlene',
                'lastname' => 'Allison',
                'company' => 'N/A',
                'email' => 'dallison@farouk.com',
                'deliveryzipcode' => 77073,
                'email_bounce' => 'no',
            ],
            [
                'id' => 17,
                'active' => 1,
                'firstname' => 'Amy',
                'lastname' => 'Wright',
                'company' => 'Chicago Booth',
                'email' => 'sawright@chicagobooth.edu',
                'deliveryzipcode' => 60637,
                'email_bounce' => 'no',
            ],
            [
                'id' => 18,
                'active' => 1,
                'firstname' => 'Rachel',
                'lastname' => 'Johnson',
                'company' => 'The Catherine',
                'email' => 'propertymanager@thecatherineaustin.com',
                'deliveryzipcode' => 78704,
                'email_bounce' => 'no',
            ],
            [
                'id' => 19,
                'active' => 1,
                'firstname' => 'Laura',
                'lastname' => 'Ramos',
                'company' => 'BCFS',
                'email' => 'LR0614@bcfs.net',
                'deliveryzipcode' => 78232,
                'email_bounce' => 'no',
            ],
            [
                'id' => 20,
                'active' => 1,
                'firstname' => 'Kristen ',
                'lastname' => 'Donaldson',
                'company' => 'Echo Global Logistics',
                'email' => 'Kristen.Donaldson@echo.com',
                'deliveryzipcode' => 60654,
                'email_bounce' => 'no',
            ],
            [
                'id' => 21,
                'active' => 1,
                'firstname' => 'Jeff',
                'lastname' => 'Weisman',
                'company' => 'BMO Transportation Finance',
                'email' => 'jeff.weisman@bmotf.com',
                'deliveryzipcode' => 75062,
                'email_bounce' => 'no',
            ],
            [
                'id' => 22,
                'active' => 1,
                'firstname' => 'Rocelyn',
                'lastname' => 'Carrasco',
                'company' => 'Hilti North America',
                'email' => 'Rocelyn.Carrasco@hilti.com',
                'deliveryzipcode' => 74146,
                'email_bounce' => 'no',
            ],
            [
                'id' => 23,
                'active' => 1,
                'firstname' => 'Carol ',
                'lastname' => 'Perales',
                'company' => 'N/A',
                'email' => 'cperales@utexas.edu',
                'deliveryzipcode' => 78712,
                'email_bounce' => 'no',
            ],
            [
                'id' => 24,
                'active' => 1,
                'firstname' => 'Lauren',
                'lastname' => 'Combest',
                'company' => 'Goodway Group ',
                'email' => 'lcombest@goodwaygroup.com',
                'deliveryzipcode' => 75219,
                'email_bounce' => 'no',
            ],
            [
                'id' => 25,
                'active' => 1,
                'firstname' => 'Brennan',
                'lastname' => 'Kraut',
                'company' => 'Colonial Oaks',
                'email' => 'brennan@colonialoaks.org',
                'deliveryzipcode' => 77082,
                'email_bounce' => 'no',
            ],
            [
                'id' => 26,
                'active' => 1,
                'firstname' => 'Laura',
                'lastname' => 'Cole',
                'company' => 'Harris Finley Bogle',
                'email' => 'lcole@hfblaw.com',
                'deliveryzipcode' => 'Fort Worth',
                'email_bounce' => 'no',
            ],
            [
                'id' => 27,
                'active' => 1,
                'firstname' => 'Julieta',
                'lastname' => 'Manzo',
                'company' => 'ACD Inc ',
                'email' => 'manzo.julieta84@gmail.com',
                'deliveryzipcode' => 92705,
                'email_bounce' => 'no',
            ],
            [
                'id' => 28,
                'active' => 1,
                'firstname' => 'Vaike',
                'lastname' => 'OGrady',
                'company' => 'Metrostudy',
                'email' => 'vogrady@metrostudy.com',
                'deliveryzipcode' => 78759,
                'email_bounce' => 'no',
            ],
        ];

        DB::table('special_offers_test')->insert($dataTables);
    }
}
