<?php

namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StatesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables --limit=500
         */
        $dataTables = [
            [
                'id' => 1,
                'country_id' => 1,
                'name' => 'Alabama',
                'code' => 'AL',
                'status' => 0,
            ],
            [
                'id' => 2,
                'country_id' => 1,
                'name' => 'Alaska',
                'code' => 'AK',
                'status' => 0,
            ],
            [
                'id' => 3,
                'country_id' => 1,
                'name' => 'American Samoa',
                'code' => 'AS',
                'status' => 0,
            ],
            [
                'id' => 4,
                'country_id' => 1,
                'name' => 'Arizona',
                'code' => 'AZ',
                'status' => 0,
            ],
            [
                'id' => 5,
                'country_id' => 1,
                'name' => 'Arkansas',
                'code' => 'AR',
                'status' => 0,
            ],
            [
                'id' => 6,
                'country_id' => 1,
                'name' => 'California',
                'code' => 'CA',
                'status' => 1,
            ],
            [
                'id' => 7,
                'country_id' => 1,
                'name' => 'Colorado',
                'code' => 'CO',
                'status' => 0,
            ],
            [
                'id' => 8,
                'country_id' => 1,
                'name' => 'Connecticut',
                'code' => 'CT',
                'status' => 0,
            ],
            [
                'id' => 9,
                'country_id' => 1,
                'name' => 'Delaware',
                'code' => 'DE',
                'status' => 0,
            ],
            [
                'id' => 10,
                'country_id' => 1,
                'name' => 'District Of Columbia',
                'code' => 'DC',
                'status' => 0,
            ],
            [
                'id' => 11,
                'country_id' => 1,
                'name' => 'Federated States Of Micronesia',
                'code' => 'FM',
                'status' => 0,
            ],
            [
                'id' => 12,
                'country_id' => 1,
                'name' => 'Florida',
                'code' => 'FL',
                'status' => 0,
            ],
            [
                'id' => 13,
                'country_id' => 1,
                'name' => 'Georgia',
                'code' => 'GA',
                'status' => 1,
            ],
            [
                'id' => 14,
                'country_id' => 1,
                'name' => 'Guam',
                'code' => 'GU',
                'status' => 0,
            ],
            [
                'id' => 15,
                'country_id' => 1,
                'name' => 'Hawaii',
                'code' => 'HI',
                'status' => 0,
            ],
            [
                'id' => 16,
                'country_id' => 1,
                'name' => 'Idaho',
                'code' => 'ID',
                'status' => 0,
            ],
            [
                'id' => 17,
                'country_id' => 1,
                'name' => 'Illinois',
                'code' => 'IL',
                'status' => 1,
            ],
            [
                'id' => 18,
                'country_id' => 1,
                'name' => 'Indiana',
                'code' => 'IN',
                'status' => 0,
            ],
            [
                'id' => 19,
                'country_id' => 1,
                'name' => 'Iowa',
                'code' => 'IA',
                'status' => 0,
            ],
            [
                'id' => 20,
                'country_id' => 1,
                'name' => 'Kansas',
                'code' => 'KS',
                'status' => 0,
            ],
            [
                'id' => 21,
                'country_id' => 1,
                'name' => 'Kentucky',
                'code' => 'KY',
                'status' => 0,
            ],
            [
                'id' => 22,
                'country_id' => 1,
                'name' => 'Louisiana',
                'code' => 'LA',
                'status' => 0,
            ],
            [
                'id' => 23,
                'country_id' => 1,
                'name' => 'Maine',
                'code' => 'ME',
                'status' => 0,
            ],
            [
                'id' => 24,
                'country_id' => 1,
                'name' => 'Marshall Islands',
                'code' => 'MH',
                'status' => 0,
            ],
            [
                'id' => 25,
                'country_id' => 1,
                'name' => 'Maryland',
                'code' => 'MD',
                'status' => 0,
            ],
            [
                'id' => 26,
                'country_id' => 1,
                'name' => 'Massachusetts',
                'code' => 'MA',
                'status' => 0,
            ],
            [
                'id' => 27,
                'country_id' => 1,
                'name' => 'Michigan',
                'code' => 'MI',
                'status' => 0,
            ],
            [
                'id' => 28,
                'country_id' => 1,
                'name' => 'Minnesota',
                'code' => 'MN',
                'status' => 0,
            ],
            [
                'id' => 29,
                'country_id' => 1,
                'name' => 'Mississippi',
                'code' => 'MS',
                'status' => 0,
            ],
            [
                'id' => 30,
                'country_id' => 1,
                'name' => 'Missouri',
                'code' => 'MO',
                'status' => 0,
            ],
            [
                'id' => 31,
                'country_id' => 1,
                'name' => 'Montana',
                'code' => 'MT',
                'status' => 0,
            ],
            [
                'id' => 32,
                'country_id' => 1,
                'name' => 'Nebraska',
                'code' => 'NE',
                'status' => 0,
            ],
            [
                'id' => 33,
                'country_id' => 1,
                'name' => 'Nevada',
                'code' => 'NV',
                'status' => 0,
            ],
            [
                'id' => 34,
                'country_id' => 1,
                'name' => 'New Hampshire',
                'code' => 'NH',
                'status' => 0,
            ],
            [
                'id' => 35,
                'country_id' => 1,
                'name' => 'New Jersey',
                'code' => 'NJ',
                'status' => 0,
            ],
            [
                'id' => 36,
                'country_id' => 1,
                'name' => 'New Mexico',
                'code' => 'NM',
                'status' => 0,
            ],
            [
                'id' => 37,
                'country_id' => 1,
                'name' => 'New York',
                'code' => 'NY',
                'status' => 0,
            ],
            [
                'id' => 38,
                'country_id' => 1,
                'name' => 'North Carolina',
                'code' => 'NC',
                'status' => 0,
            ],
            [
                'id' => 39,
                'country_id' => 1,
                'name' => 'North Dakota',
                'code' => 'ND',
                'status' => 0,
            ],
            [
                'id' => 40,
                'country_id' => 1,
                'name' => 'Northern Mariana Islands',
                'code' => 'MP',
                'status' => 0,
            ],
            [
                'id' => 41,
                'country_id' => 1,
                'name' => 'Ohio',
                'code' => 'OH',
                'status' => 0,
            ],
            [
                'id' => 42,
                'country_id' => 1,
                'name' => 'Oklahoma',
                'code' => 'OK',
                'status' => 0,
            ],
            [
                'id' => 43,
                'country_id' => 1,
                'name' => 'Oregon',
                'code' => 'OR',
                'status' => 0,
            ],
            [
                'id' => 44,
                'country_id' => 1,
                'name' => 'Palau',
                'code' => 'PW',
                'status' => 0,
            ],
            [
                'id' => 45,
                'country_id' => 1,
                'name' => 'Pennsylvania',
                'code' => 'PA',
                'status' => 0,
            ],
            [
                'id' => 46,
                'country_id' => 1,
                'name' => 'Puerto Rico',
                'code' => 'PR',
                'status' => 0,
            ],
            [
                'id' => 47,
                'country_id' => 1,
                'name' => 'Rhode Island',
                'code' => 'RI',
                'status' => 0,
            ],
            [
                'id' => 48,
                'country_id' => 1,
                'name' => 'South Carolina',
                'code' => 'SC',
                'status' => 0,
            ],
            [
                'id' => 49,
                'country_id' => 1,
                'name' => 'South Dakota',
                'code' => 'SD',
                'status' => 0,
            ],
            [
                'id' => 50,
                'country_id' => 1,
                'name' => 'Tennessee',
                'code' => 'TN',
                'status' => 0,
            ],
            [
                'id' => 51,
                'country_id' => 1,
                'name' => 'Texas',
                'code' => 'TX',
                'status' => 1,
            ],
            [
                'id' => 52,
                'country_id' => 1,
                'name' => 'Utah',
                'code' => 'UT',
                'status' => 0,
            ],
            [
                'id' => 53,
                'country_id' => 1,
                'name' => 'Vermont',
                'code' => 'VT',
                'status' => 0,
            ],
            [
                'id' => 54,
                'country_id' => 1,
                'name' => 'Virgin Islands',
                'code' => 'VI',
                'status' => 0,
            ],
            [
                'id' => 55,
                'country_id' => 1,
                'name' => 'Virginia',
                'code' => 'VA',
                'status' => 0,
            ],
            [
                'id' => 56,
                'country_id' => 1,
                'name' => 'Washington',
                'code' => 'WA',
                'status' => 0,
            ],
            [
                'id' => 57,
                'country_id' => 1,
                'name' => 'West Virginia',
                'code' => 'WV',
                'status' => 0,
            ],
            [
                'id' => 58,
                'country_id' => 1,
                'name' => 'Wisconsin',
                'code' => 'WI',
                'status' => 0,
            ],
            [
                'id' => 59,
                'country_id' => 1,
                'name' => 'Wyoming',
                'code' => 'WY',
                'status' => 0,
            ],
        ];

        DB::table('states')->insert($dataTables);
    }
}
