<?php

namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubcategoriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables --limit=500
         */
        $dataTables = [
            [
                'id' => 3,
                'alonti_library_id' => 3,
                'scat' => 'BREAKFAST ',
                'permission' => 'Yes',
                'sort' => 100,
                'hidden' => 'YES',
            ],
            [
                'id' => 6,
                'alonti_library_id' => 6,
                'scat' => 'ORDERS',
                'permission' => 'Yes',
                'sort' => 20,
                'hidden' => '',
            ],
            [
                'id' => 9,
                'alonti_library_id' => 6,
                'scat' => 'REPORTING',
                'permission' => 'Yes',
                'sort' => 50,
                'hidden' => '',
            ],
            [
                'id' => 10,
                'alonti_library_id' => 2,
                'scat' => 'STORE OPENING',
                'permission' => 'Yes',
                'sort' => 990,
                'hidden' => '',
            ],
            [
                'id' => 11,
                'alonti_library_id' => 6,
                'scat' => 'OVERVIEW',
                'permission' => 'Yes',
                'sort' => 0,
                'hidden' => '',
            ],
            [
                'id' => 13,
                'alonti_library_id' => 7,
                'scat' => 'NEW HIRE PAPERWORK ',
                'permission' => 'Yes',
                'sort' => 100,
                'hidden' => 'YES',
            ],
            [
                'id' => 17,
                'alonti_library_id' => 3,
                'scat' => 'SANDWICHES',
                'permission' => 'Yes',
                'sort' => 950,
                'hidden' => '',
            ],
            [
                'id' => 18,
                'alonti_library_id' => 3,
                'scat' => 'SALADS',
                'permission' => 'Yes',
                'sort' => 900,
                'hidden' => '',
            ],
            [
                'id' => 21,
                'alonti_library_id' => 3,
                'scat' => 'RETAIL - HOT PLATE',
                'permission' => 'Yes',
                'sort' => 800,
                'hidden' => '',
            ],
            [
                'id' => 22,
                'alonti_library_id' => 3,
                'scat' => 'GRAB & GO SANDWICHES',
                'permission' => 'Yes',
                'sort' => 600,
                'hidden' => '',
            ],
            [
                'id' => 23,
                'alonti_library_id' => 3,
                'scat' => 'GRAB & GO SALADS',
                'permission' => 'Yes',
                'sort' => 640,
                'hidden' => '',
            ],
            [
                'id' => 25,
                'alonti_library_id' => 3,
                'scat' => 'FRUIT & PARFAITS',
                'permission' => 'Yes',
                'sort' => 350,
                'hidden' => '',
            ],
            [
                'id' => 26,
                'alonti_library_id' => 3,
                'scat' => 'COOKIES & BAKERY',
                'permission' => 'Yes',
                'sort' => 290,
                'hidden' => '',
            ],
            [
                'id' => 29,
                'alonti_library_id' => 3,
                'scat' => 'BULK & BATCH',
                'permission' => 'Yes',
                'sort' => 150,
                'hidden' => 'YES',
            ],
            [
                'id' => 30,
                'alonti_library_id' => 3,
                'scat' => 'CATERING',
                'permission' => 'Yes',
                'sort' => 200,
                'hidden' => 'YES',
            ],
            [
                'id' => 31,
                'alonti_library_id' => 3,
                'scat' => 'HOLIDAY CATERING',
                'permission' => 'Yes',
                'sort' => 999,
                'hidden' => '',
            ],
            [
                'id' => 34,
                'alonti_library_id' => 2,
                'scat' => 'SPEED OF SERVICE',
                'permission' => 'Yes',
                'sort' => 300,
                'hidden' => '',
            ],
            [
                'id' => 35,
                'alonti_library_id' => 2,
                'scat' => 'COST CONTROL',
                'permission' => 'Yes',
                'sort' => 400,
                'hidden' => '',
            ],
            [
                'id' => 36,
                'alonti_library_id' => 2,
                'scat' => 'VENDOR CONTACTS',
                'permission' => 'Yes',
                'sort' => 500,
                'hidden' => '',
            ],
            [
                'id' => 37,
                'alonti_library_id' => 2,
                'scat' => 'CATERING EXECUTION',
                'permission' => 'Yes',
                'sort' => 600,
                'hidden' => '',
            ],
            [
                'id' => 38,
                'alonti_library_id' => 4,
                'scat' => 'CAFE',
                'permission' => 'Yes',
                'sort' => 100,
                'hidden' => '',
            ],
            [
                'id' => 39,
                'alonti_library_id' => 4,
                'scat' => 'CATERING',
                'permission' => 'Yes',
                'sort' => 200,
                'hidden' => '',
            ],
            [
                'id' => 41,
                'alonti_library_id' => 10,
                'scat' => 'INVENTORY & ORDER GUIDE',
                'permission' => 'Yes',
                'sort' => 200,
                'hidden' => '',
            ],
            [
                'id' => 44,
                'alonti_library_id' => 7,
                'scat' => 'VACATION AND FAMILY MEDICAL LEAVE',
                'permission' => 'Yes',
                'sort' => 300,
                'hidden' => '',
            ],
            [
                'id' => 45,
                'alonti_library_id' => 7,
                'scat' => 'PERFORMANCE RELATED FORMS',
                'permission' => 'Yes',
                'sort' => 200,
                'hidden' => '',
            ],
            [
                'id' => 48,
                'alonti_library_id' => 7,
                'scat' => 'PAYROLL ADVANCE',
                'permission' => 'Yes',
                'sort' => 400,
                'hidden' => '',
            ],
            [
                'id' => 51,
                'alonti_library_id' => 7,
                'scat' => 'INJURY FORMS',
                'permission' => 'Yes',
                'sort' => 600,
                'hidden' => '',
            ],
            [
                'id' => 58,
                'alonti_library_id' => 9,
                'scat' => 'FORM W-9 (ALONTI]',
                'permission' => 'Yes',
                'sort' => 500,
                'hidden' => '',
            ],
            [
                'id' => 61,
                'alonti_library_id' => 8,
                'scat' => 'MANAGER MANUAL',
                'permission' => 'Yes',
                'sort' => 300,
                'hidden' => '',
            ],
            [
                'id' => 63,
                'alonti_library_id' => 2,
                'scat' => 'REPAIR & MAINTENANCE',
                'permission' => 'Yes',
                'sort' => 700,
                'hidden' => '',
            ],
            [
                'id' => 64,
                'alonti_library_id' => 2,
                'scat' => 'TRAINING',
                'permission' => 'Yes',
                'sort' => 800,
                'hidden' => '',
            ],
            [
                'id' => 68,
                'alonti_library_id' => 7,
                'scat' => 'BACKGROUND CHECK',
                'permission' => 'Yes',
                'sort' => 175,
                'hidden' => '',
            ],
            [
                'id' => 69,
                'alonti_library_id' => 8,
                'scat' => 'MICROS FUNCTION SCREEN SNAP SHOT',
                'permission' => 'Yes',
                'sort' => 400,
                'hidden' => '',
            ],
            [
                'id' => 70,
                'alonti_library_id' => 8,
                'scat' => 'MICROS MENU SCREEN SNAP SHOT',
                'permission' => 'Yes',
                'sort' => 500,
                'hidden' => '',
            ],
            [
                'id' => 71,
                'alonti_library_id' => 8,
                'scat' => 'ASSIGNING MANAGER\'S CARD',
                'permission' => 'No',
                'sort' => 200,
                'hidden' => '',
            ],
            [
                'id' => 72,
                'alonti_library_id' => 8,
                'scat' => 'HOW TO PRINT PAYROLL REPORT',
                'permission' => 'Yes',
                'sort' => 600,
                'hidden' => '',
            ],
            [
                'id' => 73,
                'alonti_library_id' => 11,
                'scat' => '2007 CSM GOAL',
                'permission' => 'Yes',
                'sort' => 10,
                'hidden' => '',
            ],
            [
                'id' => 74,
                'alonti_library_id' => 3,
                'scat' => 'CATERING - HOT PLATE - SIDES',
                'permission' => 'Yes',
                'sort' => 250,
                'hidden' => '',
            ],
            [
                'id' => 75,
                'alonti_library_id' => 3,
                'scat' => 'CATERING - BEVERAGE',
                'permission' => 'Yes',
                'sort' => 210,
                'hidden' => '',
            ],
            [
                'id' => 76,
                'alonti_library_id' => 3,
                'scat' => 'CATERING - BREAKFAST',
                'permission' => 'Yes',
                'sort' => 220,
                'hidden' => '',
            ],
            [
                'id' => 77,
                'alonti_library_id' => 12,
                'scat' => 'DOCUMENTS',
                'permission' => 'Yes',
                'sort' => 10,
                'hidden' => '',
            ],
            [
                'id' => 79,
                'alonti_library_id' => 8,
                'scat' => 'GHOST CHECKS - HOW TO CLEAR',
                'permission' => 'Yes',
                'sort' => 250,
                'hidden' => '',
            ],
            [
                'id' => 84,
                'alonti_library_id' => 9,
                'scat' => 'HOUSE ACCOUNT APPLICATION',
                'permission' => 'Yes',
                'sort' => 100,
                'hidden' => '',
            ],
            [
                'id' => 86,
                'alonti_library_id' => 7,
                'scat' => 'TEXAS WORKERS COMPENSATION',
                'permission' => 'Yes',
                'sort' => 650,
                'hidden' => '',
            ],
            [
                'id' => 87,
                'alonti_library_id' => 9,
                'scat' => 'CATERING TEMPORARY EMPLOYEE',
                'permission' => 'Yes',
                'sort' => 700,
                'hidden' => '',
            ],
            [
                'id' => 88,
                'alonti_library_id' => 9,
                'scat' => 'CATERING EVENT CONTRACT',
                'permission' => 'Yes',
                'sort' => 650,
                'hidden' => '',
            ],
            [
                'id' => 89,
                'alonti_library_id' => 3,
                'scat' => 'CATERING - SALAD BOWL',
                'permission' => 'Yes',
                'sort' => 230,
                'hidden' => '',
            ],
            [
                'id' => 90,
                'alonti_library_id' => 3,
                'scat' => 'CATERING - HOT PLATE',
                'permission' => 'Yes',
                'sort' => 240,
                'hidden' => '',
            ],
            [
                'id' => 91,
                'alonti_library_id' => 3,
                'scat' => 'RETAIL - HOT PLATE - SIDES',
                'permission' => 'Yes',
                'sort' => 820,
                'hidden' => '',
            ],
            [
                'id' => 92,
                'alonti_library_id' => 3,
                'scat' => 'SALADS - RETAIL AND CATERING SALAD BOX LUNCH',
                'permission' => 'Yes',
                'sort' => 920,
                'hidden' => '',
            ],
            [
                'id' => 94,
                'alonti_library_id' => 7,
                'scat' => 'EMPLOYEE CASH PAY OUT',
                'permission' => 'Yes',
                'sort' => 160,
                'hidden' => '',
            ],
            [
                'id' => 95,
                'alonti_library_id' => 9,
                'scat' => 'EXPENSE REPORT',
                'permission' => 'Yes',
                'sort' => 300,
                'hidden' => '',
            ],
            [
                'id' => 96,
                'alonti_library_id' => 3,
                'scat' => 'CATERING - PREMIUM ENTREES',
                'permission' => 'Yes',
                'sort' => 260,
                'hidden' => '',
            ],
            [
                'id' => 98,
                'alonti_library_id' => 9,
                'scat' => 'CREDIT CARD REPLACEMENT REQUEST',
                'permission' => 'Yes',
                'sort' => 200,
                'hidden' => '',
            ],
            [
                'id' => 101,
                'alonti_library_id' => 13,
                'scat' => 'COMPANY DIRECTORY',
                'permission' => 'Yes',
                'sort' => 0,
                'hidden' => 'YES',
            ],
            [
                'id' => 103,
                'alonti_library_id' => 7,
                'scat' => 'CA Worker\'s Comp Employee Notice',
                'permission' => 'Yes',
                'sort' => 750,
                'hidden' => '',
            ],
            [
                'id' => 104,
                'alonti_library_id' => 3,
                'scat' => 'Wraps',
                'permission' => 'Yes',
                'sort' => 975,
                'hidden' => '',
            ],
            [
                'id' => 105,
                'alonti_library_id' => 15,
                'scat' => 'Charts',
                'permission' => 'Yes',
                'sort' => 100,
                'hidden' => '',
            ],
            [
                'id' => 109,
                'alonti_library_id' => 3,
                'scat' => 'INDIVIDUAL ENTREES',
                'permission' => 'Yes',
                'sort' => 675,
                'hidden' => '',
            ],
            [
                'id' => 110,
                'alonti_library_id' => 7,
                'scat' => 'CA Meal and Break Policy',
                'permission' => 'Yes',
                'sort' => 725,
                'hidden' => '',
            ],
            [
                'id' => 111,
                'alonti_library_id' => 13,
                'scat' => 'RECIPES',
                'permission' => 'Yes',
                'sort' => 1,
                'hidden' => 'YES',
            ],
            [
                'id' => 112,
                'alonti_library_id' => 18,
                'scat' => 'BREAKFAST',
                'permission' => 'Yes',
                'sort' => 100,
                'hidden' => '',
            ],
            [
                'id' => 113,
                'alonti_library_id' => 18,
                'scat' => 'BULK & BATCH',
                'permission' => 'Yes',
                'sort' => 150,
                'hidden' => '',
            ],
            [
                'id' => 114,
                'alonti_library_id' => 18,
                'scat' => 'CATERING',
                'permission' => 'Yes',
                'sort' => 200,
                'hidden' => '',
            ],
            [
                'id' => 115,
                'alonti_library_id' => 18,
                'scat' => 'CATERING - BEVERAGE',
                'permission' => 'Yes',
                'sort' => 210,
                'hidden' => '',
            ],
            [
                'id' => 116,
                'alonti_library_id' => 18,
                'scat' => 'CATERING - BREAKFAST',
                'permission' => 'Yes',
                'sort' => 220,
                'hidden' => '',
            ],
            [
                'id' => 117,
                'alonti_library_id' => 18,
                'scat' => 'CATERING - SALAD BOWL',
                'permission' => 'Yes',
                'sort' => 230,
                'hidden' => '',
            ],
            [
                'id' => 118,
                'alonti_library_id' => 18,
                'scat' => 'CATERING - HOT PLATE',
                'permission' => 'Yes',
                'sort' => 240,
                'hidden' => '',
            ],
            [
                'id' => 119,
                'alonti_library_id' => 18,
                'scat' => 'CATERING - HOT PLATE - SIDES',
                'permission' => 'Yes',
                'sort' => 250,
                'hidden' => '',
            ],
            [
                'id' => 120,
                'alonti_library_id' => 18,
                'scat' => 'CATERING - PREMIUM ENTREES',
                'permission' => 'Yes',
                'sort' => 260,
                'hidden' => '',
            ],
            [
                'id' => 121,
                'alonti_library_id' => 18,
                'scat' => 'COOKIES & BAKERY',
                'permission' => 'Yes',
                'sort' => 290,
                'hidden' => '',
            ],
            [
                'id' => 122,
                'alonti_library_id' => 18,
                'scat' => 'FRUIT & PARFAITS',
                'permission' => 'Yes',
                'sort' => 350,
                'hidden' => '',
            ],
            [
                'id' => 123,
                'alonti_library_id' => 18,
                'scat' => 'GRAB & GO SANDWICHES',
                'permission' => 'Yes',
                'sort' => 600,
                'hidden' => '',
            ],
            [
                'id' => 124,
                'alonti_library_id' => 18,
                'scat' => 'GRAB & GO SALADS',
                'permission' => 'Yes',
                'sort' => 640,
                'hidden' => '',
            ],
            [
                'id' => 125,
                'alonti_library_id' => 18,
                'scat' => 'INDIVIDUAL ENTREES',
                'permission' => 'Yes',
                'sort' => 675,
                'hidden' => '',
            ],
            [
                'id' => 126,
                'alonti_library_id' => 18,
                'scat' => 'RETAIL - HOT PLATE',
                'permission' => 'Yes',
                'sort' => 800,
                'hidden' => '',
            ],
            [
                'id' => 127,
                'alonti_library_id' => 18,
                'scat' => 'RETAIL - HOT PLATE - SIDES',
                'permission' => 'Yes',
                'sort' => 820,
                'hidden' => '',
            ],
            [
                'id' => 128,
                'alonti_library_id' => 18,
                'scat' => 'SALADS',
                'permission' => 'Yes',
                'sort' => 900,
                'hidden' => '',
            ],
            [
                'id' => 129,
                'alonti_library_id' => 18,
                'scat' => 'SALADS - RETAIL AND CATERING SALAD BOX LUNCH',
                'permission' => 'Yes',
                'sort' => 920,
                'hidden' => '',
            ],
            [
                'id' => 130,
                'alonti_library_id' => 18,
                'scat' => 'SANDWICHES',
                'permission' => 'Yes',
                'sort' => 950,
                'hidden' => '',
            ],
            [
                'id' => 131,
                'alonti_library_id' => 18,
                'scat' => 'Wraps',
                'permission' => 'Yes',
                'sort' => 975,
                'hidden' => '',
            ],
            [
                'id' => 132,
                'alonti_library_id' => 18,
                'scat' => 'HOLIDAY MENU',
                'permission' => 'Yes',
                'sort' => 999,
                'hidden' => '',
            ],
            [
                'id' => 133,
                'alonti_library_id' => 19,
                'scat' => 'Charts',
                'permission' => 'Yes',
                'sort' => 100,
                'hidden' => 'YES',
            ],
            [
                'id' => 134,
                'alonti_library_id' => 20,
                'scat' => 'NEW HIRE PAPERWORK',
                'permission' => 'Yes',
                'sort' => 100,
                'hidden' => 'YES',
            ],
            [
                'id' => 135,
                'alonti_library_id' => 20,
                'scat' => 'eT NEW HIRE PAPERWORK',
                'permission' => 'Yes',
                'sort' => 125,
                'hidden' => 'YES',
            ],
            [
                'id' => 136,
                'alonti_library_id' => 20,
                'scat' => 'EMPLOYEE HANDBOOK',
                'permission' => 'Yes',
                'sort' => 540,
                'hidden' => '',
            ],
            [
                'id' => 137,
                'alonti_library_id' => 20,
                'scat' => 'EMPLOYEE CASH PAY OUT',
                'permission' => 'Yes',
                'sort' => 525,
                'hidden' => '',
            ],
            [
                'id' => 138,
                'alonti_library_id' => 20,
                'scat' => 'BACKGROUND CHECK',
                'permission' => 'Yes',
                'sort' => 175,
                'hidden' => '',
            ],
            [
                'id' => 139,
                'alonti_library_id' => 20,
                'scat' => 'BACKGROUND CHECK',
                'permission' => 'Yes',
                'sort' => 200,
                'hidden' => 'YES',
            ],
            [
                'id' => 140,
                'alonti_library_id' => 20,
                'scat' => 'VACATION ',
                'permission' => 'Yes',
                'sort' => 700,
                'hidden' => '',
            ],
            [
                'id' => 141,
                'alonti_library_id' => 20,
                'scat' => 'PAYROLL ADVANCE',
                'permission' => 'Yes',
                'sort' => 675,
                'hidden' => '',
            ],
            [
                'id' => 142,
                'alonti_library_id' => 20,
                'scat' => 'EMPLOYEE BENEFITS',
                'permission' => 'Yes',
                'sort' => 500,
                'hidden' => '',
            ],
            [
                'id' => 143,
                'alonti_library_id' => 20,
                'scat' => 'INJURY FORMS',
                'permission' => 'Yes',
                'sort' => 600,
                'hidden' => '',
            ],
            [
                'id' => 144,
                'alonti_library_id' => 20,
                'scat' => 'TEXAS WORKERS COMPENSATION',
                'permission' => 'Yes',
                'sort' => 710,
                'hidden' => '',
            ],
            [
                'id' => 145,
                'alonti_library_id' => 20,
                'scat' => 'CA Meal and Break Policy',
                'permission' => 'Yes',
                'sort' => 725,
                'hidden' => '',
            ],
            [
                'id' => 146,
                'alonti_library_id' => 20,
                'scat' => 'CA Worker\'s Comp Employee Notice',
                'permission' => 'Yes',
                'sort' => 750,
                'hidden' => '',
            ],
            [
                'id' => 147,
                'alonti_library_id' => 20,
                'scat' => 'CA TERMINATION INFORMATION',
                'permission' => 'Yes',
                'sort' => 850,
                'hidden' => '',
            ],
            [
                'id' => 148,
                'alonti_library_id' => 21,
                'scat' => 'HOUSE ACCOUNT APPLICATION',
                'permission' => 'Yes',
                'sort' => 100,
                'hidden' => '',
            ],
            [
                'id' => 149,
                'alonti_library_id' => 21,
                'scat' => 'CREDIT CARD REPLACEMENT REQUEST',
                'permission' => 'Yes',
                'sort' => 200,
                'hidden' => '',
            ],
            [
                'id' => 150,
                'alonti_library_id' => 21,
                'scat' => 'EXPENSE REPORT',
                'permission' => 'Yes',
                'sort' => 300,
                'hidden' => '',
            ],
            [
                'id' => 151,
                'alonti_library_id' => 21,
                'scat' => 'FORM W-9 (ALONTI]',
                'permission' => 'Yes',
                'sort' => 500,
                'hidden' => '',
            ],
            [
                'id' => 152,
                'alonti_library_id' => 21,
                'scat' => 'CATERING EVENT CONTRACT',
                'permission' => 'Yes',
                'sort' => 650,
                'hidden' => 'YES',
            ],
            [
                'id' => 153,
                'alonti_library_id' => 21,
                'scat' => 'CATERING TEMPORARY EMPLOYEE',
                'permission' => 'Yes',
                'sort' => 700,
                'hidden' => '',
            ],
            [
                'id' => 154,
                'alonti_library_id' => 22,
                'scat' => 'OVERVIEW',
                'permission' => 'Yes',
                'sort' => 1,
                'hidden' => '',
            ],
            [
                'id' => 155,
                'alonti_library_id' => 22,
                'scat' => 'ORDERS',
                'permission' => 'Yes',
                'sort' => 20,
                'hidden' => '',
            ],
            [
                'id' => 156,
                'alonti_library_id' => 22,
                'scat' => 'REPORTING',
                'permission' => 'Yes',
                'sort' => 50,
                'hidden' => '',
            ],
            [
                'id' => 157,
                'alonti_library_id' => 24,
                'scat' => 'ASSIGNING MANAGER\'S CARD',
                'permission' => 'No',
                'sort' => 200,
                'hidden' => '',
            ],
            [
                'id' => 158,
                'alonti_library_id' => 24,
                'scat' => 'GHOST CHECKS - HOW TO CLEAR',
                'permission' => 'Yes',
                'sort' => 250,
                'hidden' => '',
            ],
            [
                'id' => 159,
                'alonti_library_id' => 24,
                'scat' => 'MANAGER MANUAL',
                'permission' => 'Yes',
                'sort' => 300,
                'hidden' => '',
            ],
            [
                'id' => 160,
                'alonti_library_id' => 24,
                'scat' => 'MICROS FUNCTION SCREEN SNAP SHOT',
                'permission' => 'Yes',
                'sort' => 400,
                'hidden' => '',
            ],
            [
                'id' => 161,
                'alonti_library_id' => 24,
                'scat' => 'MICROS MENU SCREEN SNAP SHOT',
                'permission' => 'Yes',
                'sort' => 500,
                'hidden' => '',
            ],
            [
                'id' => 162,
                'alonti_library_id' => 24,
                'scat' => 'HOW TO PRINT PAYROLL REPORT',
                'permission' => 'Yes',
                'sort' => 600,
                'hidden' => 'YES',
            ],
            [
                'id' => 163,
                'alonti_library_id' => 20,
                'scat' => 'PERFORMANCE RELATED FORMS',
                'permission' => 'Yes',
                'sort' => 680,
                'hidden' => '',
            ],
            [
                'id' => 164,
                'alonti_library_id' => 18,
                'scat' => 'C ATERING - HORS D\'OEUVRE & SNACKS',
                'permission' => 'Yes',
                'sort' => 235,
                'hidden' => '',
            ],
            [
                'id' => 165,
                'alonti_library_id' => 20,
                'scat' => 'FMLA',
                'permission' => 'Yes',
                'sort' => 550,
                'hidden' => '',
            ],
            [
                'id' => 166,
                'alonti_library_id' => 21,
                'scat' => 'CATERING EVENT CONTRACT',
                'permission' => 'Yes',
                'sort' => 800,
                'hidden' => '',
            ],
            [
                'id' => 167,
                'alonti_library_id' => 21,
                'scat' => 'ADMINISTRATIVE TRAINING GUIDES',
                'permission' => 'Yes',
                'sort' => 900,
                'hidden' => 'YES',
            ],
            [
                'id' => 168,
                'alonti_library_id' => 26,
                'scat' => 'TRAINING GUIDES',
                'permission' => 'Yes',
                'sort' => 100,
                'hidden' => '',
            ],
            [
                'id' => 169,
                'alonti_library_id' => 20,
                'scat' => 'MISCELLANEOUS FORMS',
                'permission' => 'Yes',
                'sort' => 650,
                'hidden' => '',
            ],
            [
                'id' => 170,
                'alonti_library_id' => 13,
                'scat' => 'COMPANY DIRECTORY',
                'permission' => 'Yes',
                'sort' => 101,
                'hidden' => 'YES',
            ],
            [
                'id' => 171,
                'alonti_library_id' => 27,
                'scat' => 'Archived Recipes',
                'permission' => 'Yes',
                'sort' => 1000,
                'hidden' => '',
            ],
            [
                'id' => 172,
                'alonti_library_id' => 27,
                'scat' => 'Beverages',
                'permission' => 'Yes',
                'sort' => 50,
                'hidden' => '',
            ],
            [
                'id' => 173,
                'alonti_library_id' => 27,
                'scat' => 'Boxed Lunches',
                'permission' => 'Yes',
                'sort' => 100,
                'hidden' => '',
            ],
            [
                'id' => 174,
                'alonti_library_id' => 27,
                'scat' => 'Breakfast',
                'permission' => 'Yes',
                'sort' => 150,
                'hidden' => '',
            ],
            [
                'id' => 175,
                'alonti_library_id' => 27,
                'scat' => 'Bulk and Batch',
                'permission' => 'Yes',
                'sort' => 200,
                'hidden' => '',
            ],
            [
                'id' => 176,
                'alonti_library_id' => 27,
                'scat' => 'Desserts',
                'permission' => 'Yes',
                'sort' => 250,
                'hidden' => '',
            ],
            [
                'id' => 177,
                'alonti_library_id' => 27,
                'scat' => 'Holiday',
                'permission' => 'Yes',
                'sort' => 300,
                'hidden' => '',
            ],
            [
                'id' => 178,
                'alonti_library_id' => 27,
                'scat' => 'Hors D\'Oeuvres',
                'permission' => 'Yes',
                'sort' => 350,
                'hidden' => '',
            ],
            [
                'id' => 179,
                'alonti_library_id' => 27,
                'scat' => 'Hot Plate Sides',
                'permission' => 'Yes',
                'sort' => 400,
                'hidden' => '',
            ],
            [
                'id' => 180,
                'alonti_library_id' => 27,
                'scat' => 'Hot Plates',
                'permission' => 'Yes',
                'sort' => 450,
                'hidden' => '',
            ],
            [
                'id' => 181,
                'alonti_library_id' => 27,
                'scat' => 'Pressatas',
                'permission' => 'Yes',
                'sort' => 500,
                'hidden' => '',
            ],
            [
                'id' => 182,
                'alonti_library_id' => 27,
                'scat' => 'Retail',
                'permission' => 'Yes',
                'sort' => 550,
                'hidden' => '',
            ],
            [
                'id' => 183,
                'alonti_library_id' => 27,
                'scat' => 'Salad Bowls - Group',
                'permission' => 'Yes',
                'sort' => 600,
                'hidden' => '',
            ],
            [
                'id' => 184,
                'alonti_library_id' => 27,
                'scat' => 'Sandwiches',
                'permission' => 'Yes',
                'sort' => 650,
                'hidden' => '',
            ],
            [
                'id' => 185,
                'alonti_library_id' => 27,
                'scat' => 'Wraps',
                'permission' => 'Yes',
                'sort' => 700,
                'hidden' => '',
            ],
            [
                'id' => 186,
                'alonti_library_id' => 13,
                'scat' => 'COMPANY DIRECTORY',
                'permission' => 'Yes',
                'sort' => 201,
                'hidden' => 'YES',
            ],
            [
                'id' => 187,
                'alonti_library_id' => 27,
                'scat' => 'Recipe Books',
                'permission' => 'Yes',
                'sort' => 800,
                'hidden' => 'YES',
            ],
            [
                'id' => 188,
                'alonti_library_id' => 27,
                'scat' => 'Build Sheets & Paper Charts',
                'permission' => 'Yes',
                'sort' => 175,
                'hidden' => '',
            ],
            [
                'id' => 189,
                'alonti_library_id' => 20,
                'scat' => 'SICK LEAVE REQUEST',
                'permission' => 'Yes',
                'sort' => 705,
                'hidden' => '',
            ],
            [
                'id' => 190,
                'alonti_library_id' => 29,
                'scat' => 'GM ALL STAR TRACKER',
                'permission' => 'Yes',
                'sort' => 100,
                'hidden' => 'YES',
            ],
            [
                'id' => 191,
                'alonti_library_id' => 29,
                'scat' => 'CSM ALL STAR TRACKER',
                'permission' => 'Yes',
                'sort' => 200,
                'hidden' => '',
            ],
            [
                'id' => 192,
                'alonti_library_id' => 29,
                'scat' => 'GM ALL STAR TRACKER',
                'permission' => 'Yes',
                'sort' => 300,
                'hidden' => '',
            ],
            [
                'id' => 193,
                'alonti_library_id' => 30,
                'scat' => 'Safety Manual',
                'permission' => 'Yes',
                'sort' => 100,
                'hidden' => '',
            ],
            [
                'id' => 194,
                'alonti_library_id' => 13,
                'scat' => 'COMPANY DIRECTORY',
                'permission' => 'Yes',
                'sort' => 301,
                'hidden' => 'YES',
            ],
            [
                'id' => 195,
                'alonti_library_id' => 20,
                'scat' => 'California Workers Comp',
                'permission' => 'Yes',
                'sort' => 751,
                'hidden' => 'YES',
            ],
            [
                'id' => 196,
                'alonti_library_id' => 13,
                'scat' => 'COMPANY DIRECTORY',
                'permission' => 'Yes',
                'sort' => 401,
                'hidden' => 'YES',
            ],
            [
                'id' => 197,
                'alonti_library_id' => 13,
                'scat' => 'COMPANY DIRECTORY',
                'permission' => 'Yes',
                'sort' => 501,
                'hidden' => 'YES',
            ],
            [
                'id' => 198,
                'alonti_library_id' => 13,
                'scat' => 'COMPANY DIRECTORY',
                'permission' => 'Yes',
                'sort' => 100,
                'hidden' => '',
            ],
            [
                'id' => 199,
                'alonti_library_id' => 27,
                'scat' => 'Summer Picnic',
                'permission' => 'Yes',
                'sort' => 305,
                'hidden' => 'YES',
            ],
            [
                'id' => 200,
                'alonti_library_id' => 27,
                'scat' => 'Summer Picnic',
                'permission' => 'Yes',
                'sort' => 655,
                'hidden' => '',
            ],
            [
                'id' => 201,
                'alonti_library_id' => 31,
                'scat' => 'California Forms',
                'permission' => 'Yes',
                'sort' => 100,
                'hidden' => '',
            ],
            [
                'id' => 202,
                'alonti_library_id' => 31,
                'scat' => 'Illinois Forms',
                'permission' => 'Yes',
                'sort' => 200,
                'hidden' => '',
            ],
            [
                'id' => 203,
                'alonti_library_id' => 31,
                'scat' => 'Texas Forms',
                'permission' => 'Yes',
                'sort' => 300,
                'hidden' => '',
            ],
            [
                'id' => 204,
                'alonti_library_id' => 31,
                'scat' => 'Miscellaneous Forms',
                'permission' => 'Yes',
                'sort' => 400,
                'hidden' => '',
            ],
            [
                'id' => 205,
                'alonti_library_id' => 13,
                'scat' => 'Company Directory',
                'permission' => 'Yes',
                'sort' => 601,
                'hidden' => 'YES',
            ],
            [
                'id' => 206,
                'alonti_library_id' => 13,
                'scat' => 'Company Directory',
                'permission' => 'Yes',
                'sort' => 701,
                'hidden' => 'YES',
            ],
            [
                'id' => 208,
                'alonti_library_id' => 31,
                'scat' => 'Job Descriptions',
                'permission' => 'Yes',
                'sort' => 500,
                'hidden' => '',
            ],
            [
                'id' => 209,
                'alonti_library_id' => 27,
                'scat' => 'Vegan Items',
                'permission' => 'Yes',
                'sort' => 1100,
                'hidden' => '',
            ],
            [
                'id' => 210,
                'alonti_library_id' => 13,
                'scat' => 'Company Directory',
                'permission' => 'Yes',
                'sort' => 801,
                'hidden' => 'YES',
            ],
            [
                'id' => 211,
                'alonti_library_id' => 13,
                'scat' => 'Company Directory',
                'permission' => 'Yes',
                'sort' => 901,
                'hidden' => 'YES',
            ],
            [
                'id' => 212,
                'alonti_library_id' => 32,
                'scat' => 'May Sales',
                'permission' => 'Yes',
                'sort' => 500,
                'hidden' => 'YES',
            ],
            [
                'id' => 213,
                'alonti_library_id' => 32,
                'scat' => 'Apr Sales',
                'permission' => 'Yes',
                'sort' => 200,
                'hidden' => 'YES',
            ],
            [
                'id' => 214,
                'alonti_library_id' => 32,
                'scat' => 'Apr Sales',
                'permission' => 'Yes',
                'sort' => 400,
                'hidden' => 'YES',
            ],
            [
                'id' => 215,
                'alonti_library_id' => 32,
                'scat' => 'Mar Sales',
                'permission' => 'Yes',
                'sort' => 300,
                'hidden' => 'YES',
            ],
            [
                'id' => 216,
                'alonti_library_id' => 32,
                'scat' => 'Feb Sales',
                'permission' => 'Yes',
                'sort' => 200,
                'hidden' => 'YES',
            ],
            [
                'id' => 217,
                'alonti_library_id' => 32,
                'scat' => 'Jan Sales',
                'permission' => 'Yes',
                'sort' => 50,
                'hidden' => 'YES',
            ],
            [
                'id' => 218,
                'alonti_library_id' => 32,
                'scat' => 'June Sales',
                'permission' => 'Yes',
                'sort' => 600,
                'hidden' => 'YES',
            ],
            [
                'id' => 219,
                'alonti_library_id' => 32,
                'scat' => 'July Sales',
                'permission' => 'Yes',
                'sort' => 700,
                'hidden' => 'YES',
            ],
            [
                'id' => 220,
                'alonti_library_id' => 32,
                'scat' => 'August Sales',
                'permission' => 'Yes',
                'sort' => 800,
                'hidden' => 'YES',
            ],
            [
                'id' => 221,
                'alonti_library_id' => 32,
                'scat' => 'Sept Sales ',
                'permission' => 'Yes',
                'sort' => 900,
                'hidden' => 'YES',
            ],
            [
                'id' => 222,
                'alonti_library_id' => 32,
                'scat' => 'Oct Sales',
                'permission' => 'Yes',
                'sort' => 1000,
                'hidden' => 'YES',
            ],
            [
                'id' => 223,
                'alonti_library_id' => 32,
                'scat' => 'Nov Sales',
                'permission' => 'Yes',
                'sort' => 1100,
                'hidden' => 'YES',
            ],
            [
                'id' => 224,
                'alonti_library_id' => 32,
                'scat' => 'Dec Sales',
                'permission' => 'Yes',
                'sort' => 1200,
                'hidden' => 'YES',
            ],
            [
                'id' => 225,
                'alonti_library_id' => 32,
                'scat' => '2024 Daily Sales Report',
                'permission' => 'Yes',
                'sort' => 2000,
                'hidden' => 'YES',
            ],
            [
                'id' => 226,
                'alonti_library_id' => 31,
                'scat' => 'Georgia Forms',
                'permission' => 'Yes',
                'sort' => 600,
                'hidden' => '',
            ],
            [
                'id' => 227,
                'alonti_library_id' => 32,
                'scat' => 'Consolidated Reports',
                'permission' => 'Yes',
                'sort' => 1,
                'hidden' => '',
            ],
            [
                'id' => 228,
                'alonti_library_id' => 32,
                'scat' => 'Dec Sales',
                'permission' => 'Yes',
                'sort' => 1400,
                'hidden' => 'YES',
            ],
            [
                'id' => 229,
                'alonti_library_id' => 32,
                'scat' => 2026,
                'permission' => 'Yes',
                'sort' => 2100,
                'hidden' => '',
            ],
            [
                'id' => 230,
                'alonti_library_id' => 32,
                'scat' => 2025,
                'permission' => 'Yes',
                'sort' => 3000,
                'hidden' => '',
            ],
            [
                'id' => 231,
                'alonti_library_id' => 32,
                'scat' => 2024,
                'permission' => 'Yes',
                'sort' => 4000,
                'hidden' => '',
            ],
        ];

        DB::table('subcategories')->insert($dataTables);
    }
}
