<?php

namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VendorsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables --limit=500
         */
        $dataTables = [
            [
                'id' => 1,
                'name' => 'SYSCO HOUSTON',
                'address' => 1221,
                'city' => 'Houston',
                'state' => 'TX',
                'zip' => 77056,
                'phone' => '713-555-5555',
                'vendor_number' => '01-SYSCOH',
            ],
            [
                'id' => 3,
                'name' => 'AMERICAN BOTTLING CO',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '',
            ],
            [
                'id' => 4,
                'name' => 'CENTRAL BEVERAGE CO',
                'address' => ' ',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 5,
                'name' => 'CENTRAL CONTINENTAL',
                'address' => null,
                'city' => null,
                'state' => null,
                'zip' => null,
                'phone' => null,
                'vendor_number' => null,
            ],
            [
                'id' => 6,
                'name' => 'DALMARES PRODUCE',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '',
            ],
            [
                'id' => 7,
                'name' => 'D\'AMATO\'S WHOLESALE',
                'address' => null,
                'city' => null,
                'state' => null,
                'zip' => null,
                'phone' => null,
                'vendor_number' => null,
            ],
            [
                'id' => 8,
                'name' => 'GONNELLA BAKING CO',
                'address' => null,
                'city' => null,
                'state' => null,
                'zip' => null,
                'phone' => null,
                'vendor_number' => null,
            ],
            [
                'id' => 9,
                'name' => 'HIGHLAND BAKING CO',
                'address' => null,
                'city' => null,
                'state' => null,
                'zip' => null,
                'phone' => null,
                'vendor_number' => null,
            ],
            [
                'id' => 10,
                'name' => 'PASTRIES BY KAY',
                'address' => null,
                'city' => null,
                'state' => null,
                'zip' => null,
                'phone' => null,
                'vendor_number' => null,
            ],
            [
                'id' => 11,
                'name' => 'RIVER NORTH SALES SE',
                'address' => null,
                'city' => null,
                'state' => null,
                'zip' => null,
                'phone' => null,
                'vendor_number' => null,
            ],
            [
                'id' => 12,
                'name' => 'WINDY APPLE PROVISION',
                'address' => 'vendors',
                'city' => null,
                'state' => null,
                'zip' => null,
                'phone' => null,
                'vendor_number' => null,
            ],
            [
                'id' => 13,
                'name' => 'AMY\'S DONUT HOUSE',
                'address' => null,
                'city' => null,
                'state' => null,
                'zip' => null,
                'phone' => null,
                'vendor_number' => null,
            ],
            [
                'id' => 14,
                'name' => 'CHEFS\' PRODUCE',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 15,
                'name' => 'Dr Pepper Snapple Group',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '01-DRPEP  ',
            ],
            [
                'id' => 16,
                'name' => 'MASSIMOS',
                'address' => null,
                'city' => null,
                'state' => null,
                'zip' => null,
                'phone' => null,
                'vendor_number' => null,
            ],
            [
                'id' => 17,
                'name' => 'SCHEPPS DAIRY',
                'address' => null,
                'city' => null,
                'state' => null,
                'zip' => null,
                'phone' => null,
                'vendor_number' => null,
            ],
            [
                'id' => 18,
                'name' => 'WILLIAMS BAKING COMP',
                'address' => null,
                'city' => null,
                'state' => null,
                'zip' => null,
                'phone' => null,
                'vendor_number' => null,
            ],
            [
                'id' => 19,
                'name' => 'PAIN DU JOUR',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 20,
                'name' => 'TRIMARK MARLINN, INC.',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '03-MARLINN',
            ],
            [
                'id' => 21,
                'name' => 'PAID-OUT',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 22,
                'name' => 'GREAT AMERICAN BAGEL',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 23,
                'name' => 'PREFERRED FOOD GROUP',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 24,
                'name' => '06-ALONTI',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 25,
                'name' => '12-ALONTI',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 26,
                'name' => '32-ALONTI',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 27,
                'name' => '52-ALONTI',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 28,
                'name' => '53-ALONTI',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 29,
                'name' => '54-ALONTI',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 30,
                'name' => 'A BARR SALES',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 31,
                'name' => 'ARAMARK',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 32,
                'name' => 'COCA-COLA',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 33,
                'name' => 'TREE FRESH',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 34,
                'name' => 'ANY OCCASION PARTY RENTAL',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 35,
                'name' => 'RT BEVERAGE',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 36,
                'name' => '01-PLEASE SELECT A VENDOR',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 37,
                'name' => 'STARBUCKS',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 38,
                'name' => 'ECOLAB  PEST EL IM DIV',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '01-ECOLAB ',
            ],
            [
                'id' => 39,
                'name' => '57-ALONTI',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 40,
                'name' => 'BREADSMITH',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 41,
                'name' => 'Alpha Bread',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 42,
                'name' => 'ATHENAS',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 44,
                'name' => 'FRESH POINT',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 45,
                'name' => 'GET FRESH PRODUCE',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '03-GETFRES',
            ],
            [
                'id' => 46,
                'name' => '60-ALONTI',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 47,
                'name' => 'BROTHERS - HOUSTON',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '01-BROTHER',
            ],
            [
                'id' => 48,
                'name' => '62-ALONTI',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 49,
                'name' => '64-ALONTI',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 50,
                'name' => '65 - ALONTI ',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '',
            ],
            [
                'id' => 51,
                'name' => '01 - Alonit 01',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 52,
                'name' => '02 - Alonti 02',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 53,
                'name' => '04 - Alonti 04',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 54,
                'name' => '07 - Alonti 07',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 55,
                'name' => '08 - Alonti 08',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 56,
                'name' => '14 - Alonti 14',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 57,
                'name' => '18 - Alonti 18',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 58,
                'name' => '31 - Alonti 31',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 59,
                'name' => '33 - Alonti 33',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 60,
                'name' => '36 - Alonti 36',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 61,
                'name' => '47 - Alonti 47',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 62,
                'name' => '48 - Alonti 48',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 63,
                'name' => '49 - Alonti 49',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 64,
                'name' => '56 - Alontio 56',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 65,
                'name' => '58 - Alonti 58',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 66,
                'name' => 'TEX MEX CUTLERY LLC',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '01-TEXMEX ',
            ],
            [
                'id' => 67,
                'name' => '70 - Alonti 70',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '',
            ],
            [
                'id' => 68,
                'name' => 'FRESH BREW',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 69,
                'name' => '69 - Alonti 69',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 70,
                'name' => '68 - Alonti 68',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 71,
                'name' => 'WORLDWIDE PRODUCE',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '15-WORLD  ',
            ],
            [
                'id' => 72,
                'name' => '61 - eT',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 73,
                'name' => 'Hardies Produce',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 74,
                'name' => '04 - Alonti 04',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '',
            ],
            [
                'id' => 75,
                'name' => 'Diamond Sharp',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 76,
                'name' => '71- Alonti 71',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '',
            ],
            [
                'id' => 77,
                'name' => 'Favorite Brands',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 78,
                'name' => 'Silver Eagle',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 79,
                'name' => '8th Wonder Brewery',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 80,
                'name' => 'Buffalo Bayou Brewing',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 81,
                'name' => 'Fish Window Cleaning',
                'address' => '8524 Highway 6 North, 206',
                'city' => 'Houston',
                'state' => 'TX',
                'zip' => 77095,
                'phone' => '281-550-9444',
                'vendor_number' => null,
            ],
            [
                'id' => 82,
                'name' => 'LBX Lighting Inc',
                'address' => '3211 Fondren Road',
                'city' => 'Houston',
                'state' => 'TX',
                'zip' => 77063,
                'phone' => '713-529-0250',
                'vendor_number' => null,
            ],
            [
                'id' => 83,
                'name' => '512 Brewery',
                'address' => '407 Radam Lane F200',
                'city' => 'Austin',
                'state' => 'Texas',
                'zip' => 78745,
                'phone' => '512-921-1545',
                'vendor_number' => null,
            ],
            [
                'id' => 84,
                'name' => 'Houston Distributing',
                'address' => '7100 High Life Drive',
                'city' => 'Houston',
                'state' => 'Texas',
                'zip' => '',
                'phone' => '281-583-4800',
                'vendor_number' => null,
            ],
            [
                'id' => 85,
                'name' => 'Ben E Keith',
                'address' => '6720 Commerce Creek Dr',
                'city' => 'Houston',
                'state' => 'Texas',
                'zip' => 77040,
                'phone' => '713-849-9195',
                'vendor_number' => '',
            ],
            [
                'id' => 86,
                'name' => 'Fllood Distribution',
                'address' => '2324 Ridgepoint Dr. Ste. C',
                'city' => 'Austin',
                'state' => 'Texas',
                'zip' => 78754,
                'phone' => '512-763-7631',
                'vendor_number' => null,
            ],
            [
                'id' => 87,
                'name' => 'Raymark',
                'address' => 'PO Box 168',
                'city' => 'Porter',
                'state' => 'Texas',
                'zip' => 77365,
                'phone' => '281-354-7018',
                'vendor_number' => null,
            ],
            [
                'id' => 88,
                'name' => 'Bluebonnet Distributing',
                'address' => '1291 N Post Oak Suite 120',
                'city' => 'Houston',
                'state' => 'Texas',
                'zip' => 77055,
                'phone' => '832-968-4095',
                'vendor_number' => null,
            ],
            [
                'id' => 89,
                'name' => '11 Below Brewery',
                'address' => '6820 Bourgeois rd',
                'city' => 'Houston',
                'state' => 'Texas',
                'zip' => 77066,
                'phone' => '281-444-2337',
                'vendor_number' => null,
            ],
            [
                'id' => 90,
                'name' => 'NuCO',
                'address' => 'PO Box 417902',
                'city' => 'Boston',
                'state' => 'Mass',
                'zip' => 2241,
                'phone' => '1-800-472-2855',
                'vendor_number' => null,
            ],
            [
                'id' => 91,
                'name' => 'Belknap Plumbing',
                'address' => '9030 Solon Road',
                'city' => 'Houston',
                'state' => 'Texas',
                'zip' => 77064,
                'phone' => '832-912-6733',
                'vendor_number' => null,
            ],
            [
                'id' => 92,
                'name' => 'Kanela',
                'address' => '306 W Sam Houston Pkwy Notrth',
                'city' => 'Houston',
                'state' => 'Texas',
                'zip' => 77024,
                'phone' => '832-206-5694',
                'vendor_number' => null,
            ],
            [
                'id' => 93,
                'name' => 'Guardian',
                'address' => '20831 White Hyacinth Dr',
                'city' => 'Cypress ',
                'state' => 'Texas',
                'zip' => 77433,
                'phone' => '281-463-7073',
                'vendor_number' => null,
            ],
            [
                'id' => 94,
                'name' => 'Liquid Waste Solutions',
                'address' => '650 West Bough Lane suite 150-204',
                'city' => 'Houston',
                'state' => 'Texas',
                'zip' => 77024,
                'phone' => '713-868-1171',
                'vendor_number' => null,
            ],
            [
                'id' => 95,
                'name' => 'Huff Brewing',
                'address' => '9805 Koehn Rd',
                'city' => 'Bellville',
                'state' => 'Texas',
                'zip' => 77418,
                'phone' => '(979] 885-8624',
                'vendor_number' => null,
            ],
            [
                'id' => 96,
                'name' => 'ISI',
                'address' => '640 West 6th St',
                'city' => 'Houston',
                'state' => 'Texas',
                'zip' => 77001,
                'phone' => '713-861-4455',
                'vendor_number' => null,
            ],
            [
                'id' => 97,
                'name' => 'ARC',
                'address' => 'po box 1770',
                'city' => 'Bellaire',
                'state' => 'Texas',
                'zip' => 77402,
                'phone' => '713-666-7100',
                'vendor_number' => null,
            ],
            [
                'id' => 98,
                'name' => 'Jack Nadel',
                'address' => '8701 Bellanca Ave',
                'city' => 'Los Angeles',
                'state' => 'California',
                'zip' => 90045,
                'phone' => '310-815-5454',
                'vendor_number' => null,
            ],
            [
                'id' => 99,
                'name' => 'Halco',
                'address' => '5420 Acron',
                'city' => 'Houston',
                'state' => 'Texas',
                'zip' => 77092,
                'phone' => 77092,
                'vendor_number' => null,
            ],
            [
                'id' => 100,
                'name' => 'Great Texas Electric',
                'address' => 'PO Box 96274',
                'city' => 'Houston',
                'state' => 'Texas',
                'zip' => 77213,
                'phone' => 2814580634,
                'vendor_number' => null,
            ],
            [
                'id' => 101,
                'name' => 'Spectra Printing',
                'address' => '6103 E. Admiral Blvd',
                'city' => 'Tulsa',
                'state' => 'Oklahoma',
                'zip' => 74115,
                'phone' => '918-835-0172',
                'vendor_number' => null,
            ],
            [
                'id' => 102,
                'name' => 'Displays2Go',
                'address' => '55 Broadcommon Rd.',
                'city' => 'Bristol',
                'state' => 'RI',
                'zip' => 2809,
                'phone' => '1-800-572-2194',
                'vendor_number' => '',
            ],
            [
                'id' => 103,
                'name' => 'Town In City Brewing',
                'address' => '1125 West Cavalcade',
                'city' => 'Houston',
                'state' => 'Texas',
                'zip' => 77009,
                'phone' => '832-834-7151',
                'vendor_number' => null,
            ],
            [
                'id' => 104,
                'name' => '',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 105,
                'name' => '',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 106,
                'name' => '',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 107,
                'name' => '',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 108,
                'name' => '',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 109,
                'name' => '',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => 0,
                'phone' => '',
                'vendor_number' => null,
            ],
            [
                'id' => 110,
                'name' => 'Alvarez Refrigeration',
                'address' => '201 S Heights Blvd, Ste 1415',
                'city' => 'Houston',
                'state' => 'TX ',
                'zip' => 77007,
                'phone' => '832.523.2121',
                'vendor_number' => '',
            ],
            [
                'id' => 111,
                'name' => 'Corporate ',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '00 Corp',
            ],
            [
                'id' => 112,
                'name' => 'Factory Decasa, Inc',
                'address' => '13315 Veterans Memorial Dr. Ste. #108',
                'city' => 'Houston',
                'state' => 'TX',
                'zip' => 77014,
                'phone' => '281-440-9240',
                'vendor_number' => '11-FDECASA',
            ],
            [
                'id' => 113,
                'name' => 'El Milagro',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '',
            ],
            [
                'id' => 114,
                'name' => 'Katz Coffee',
                'address' => '2450 Louisiana St. 400-221',
                'city' => 'Houston',
                'state' => 'Texas',
                'zip' => 77006,
                'phone' => '',
                'vendor_number' => '12-KATZCOF',
            ],
            [
                'id' => 115,
                'name' => '72-ALONTI',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '',
            ],
            [
                'id' => 116,
                'name' => 'BROTHERS - DALLAS',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '02-BROTHER',
            ],
            [
                'id' => 117,
                'name' => 'BROTHERS PRODUCE - AUSTIN',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '12-BROTHER',
            ],
            [
                'id' => 118,
                'name' => 'SYSCO DALLAS',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '02-SYSCOD ',
            ],
            [
                'id' => 119,
                'name' => 'SYSCO CHICAGO',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '03-SYSCOC ',
            ],
            [
                'id' => 120,
                'name' => 'SYSCO LOS ANGELES INC',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '15-SYSCO  ',
            ],
            [
                'id' => 121,
                'name' => 'COZZINI BROS., INC.',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '03-COZZINI',
            ],
            [
                'id' => 122,
                'name' => 'MARQUIS DISTRIBUTORS LLC',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '00-MDISTRI',
            ],
            [
                'id' => 124,
                'name' => 'SYSCO CENTRAL TEXAS',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '01-SYSCOCT',
            ],
            [
                'id' => 125,
                'name' => 'MYR WHOLESALE INC.',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '02-MYRWHOL',
            ],
            [
                'id' => 126,
                'name' => 'IMPERIAL DADE',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '',
            ],
            [
                'id' => 127,
                'name' => 'SYSCO ATLANTA',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '17-SYSCOAT',
            ],
            [
                'id' => 128,
                'name' => 'WHAT CHEFS WANT',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '17-WHATCHE',
            ],
            [
                'id' => 129,
                'name' => 'GRUBMARKET – HOUSTON',
                'address' => '',
                'city' => '',
                'state' => '',
                'zip' => '',
                'phone' => '',
                'vendor_number' => '',
            ],
        ];

        DB::table('vendors')->insert($dataTables);
    }
}
